-- =====================================================================
-- AI LAB HUB — міграція: EN-написи дошки оголошень Marketplace (етап 4) + EN-назви категорій розділу 'board'
--
--   Ключі t() mpb_* з app/translations.php. Готовий людський переклад одразу в ui_translations,
--   source='manual' — Google Translate API для них не витрачається.
--   Українські тексти живуть у app/translations.php (мова оригіналу).
--
--   Безпечно повторювати: INSERT IGNORE (унікальний ключ (key_name, lang)) і INSERT ... WHERE NOT EXISTS.
--   Потребує таблиць ui_translations (migration-2026-09-17-translation-tables.sql) і категорій 'board'
--   (migration-2026-09-21-marketplace-classifieds.sql). Тільки INSERT: жодних DROP/DELETE/TRUNCATE/ALTER.
-- =====================================================================

SET NAMES utf8mb4;

INSERT IGNORE INTO ui_translations (key_name, lang, translated_text, source) VALUES
('mpb_subtitle', 'en', 'Listings from users: services, templates, tutoring, jobs. The platform only publishes the listings.', 'manual'),
('mpb_empty', 'en', 'There are no active listings yet. Be the first — post yours!', 'manual'),
('mpb_post_btn', 'en', 'Post a listing', 'manual'),
('mpb_my_link', 'en', 'My listings', 'manual'),
('mpb_solutions_link', 'en', 'Free solutions from the platform', 'manual'),
('mpb_solutions_title', 'en', 'Ready-made solutions', 'manual'),
('mpb_found', 'en', 'Listings found: %d', 'manual'),
('mpb_pages', 'en', 'Pages', 'manual'),
('mpb_disclaimer', 'en', 'The platform is not a party to any deal between the parties: it does not guarantee quality, payment or fulfilment of agreements. Arrange things directly and verify your counterparty yourself.', 'manual'),
('mpb_f_search', 'en', 'Search by title', 'manual'),
('mpb_f_category', 'en', 'Category', 'manual'),
('mpb_f_price_type', 'en', 'Price type', 'manual'),
('mpb_f_price_range', 'en', 'Price', 'manual'),
('mpb_from', 'en', 'from', 'manual'),
('mpb_to', 'en', 'to', 'manual'),
('mpb_f_sort', 'en', 'Sort by', 'manual'),
('mpb_sort_new', 'en', 'Newest first', 'manual'),
('mpb_sort_cheap', 'en', 'Cheapest first', 'manual'),
('mpb_sort_expensive', 'en', 'Most expensive first', 'manual'),
('mpb_pt_free', 'en', 'Free', 'manual'),
('mpb_pt_fixed', 'en', 'Fixed price', 'manual'),
('mpb_pt_negotiable', 'en', 'Negotiable', 'manual'),
('mpb_pt_exchange', 'en', 'Exchange', 'manual'),
('mpb_price_negotiable', 'en', 'Negotiable', 'manual'),
('mpb_price_exchange', 'en', 'Exchange', 'manual'),
('mpb_remote', 'en', 'remote', 'manual'),
('mpb_views', 'en', 'Views', 'manual'),
('mpb_photo_n', 'en', 'Photo %d', 'manual'),
('mpb_preview_banner', 'en', 'This is a preview: the listing is not published. Status:', 'manual'),
('mpb_own_note', 'en', 'This is your listing.', 'manual'),
('mpb_seller_other', 'en', 'More from this seller', 'manual'),
('mpb_contact_btn', 'en', 'Show contact', 'manual'),
('mpb_contact_title', 'en', 'Seller contacts', 'manual'),
('mpb_contact_name', 'en', 'Name', 'manual'),
('mpb_contact_phone', 'en', 'Phone', 'manual'),
('mpb_contact_login', 'en', 'Sign in or register to see the contacts.', 'manual'),
('mpb_contact_limit', 'en', 'You have reached the daily limit of revealed contacts (%d per day). Try again tomorrow.', 'manual'),
('mpb_contact_notfound', 'en', 'The listing is not available.', 'manual'),
('mpb_contact_error', 'en', 'Could not get the contacts. Please try again.', 'manual'),
('mpb_fav_add', 'en', 'Add to favorites', 'manual'),
('mpb_fav_remove', 'en', 'Remove from favorites', 'manual'),
('mpb_fav_login', 'en', 'Add to favorites (sign in)', 'manual'),
('mpb_fav_title', 'en', 'Favorites', 'manual'),
('mpb_fav_empty', 'en', 'Your favorites are empty.', 'manual'),
('mpb_fav_added', 'en', 'Added to favorites.', 'manual'),
('mpb_fav_removed', 'en', 'Removed from favorites.', 'manual'),
('mpb_fav_unavailable', 'en', 'This listing cannot be added to favorites.', 'manual'),
('mpb_report_btn', 'en', 'Report', 'manual'),
('mpb_report_reason', 'en', 'Reason', 'manual'),
('mpb_report_note', 'en', 'Comment (optional)', 'manual'),
('mpb_report_send', 'en', 'Send report', 'manual'),
('mpb_report_login', 'en', 'Sign in to report a listing.', 'manual'),
('mpb_report_ok', 'en', 'Thank you, your report was received. Moderators will review it.', 'manual'),
('mpb_report_duplicate', 'en', 'You have already reported this listing.', 'manual'),
('mpb_report_own', 'en', 'You cannot report your own listing.', 'manual'),
('mpb_report_invalid', 'en', 'Please choose a reason.', 'manual'),
('mpb_report_notfound', 'en', 'The listing is not available.', 'manual'),
('mpb_reason_fraud', 'en', 'Fraud', 'manual'),
('mpb_reason_prohibited', 'en', 'Prohibited item or service', 'manual'),
('mpb_reason_spam', 'en', 'Spam', 'manual'),
('mpb_reason_wrong_category', 'en', 'Wrong category', 'manual'),
('mpb_reason_other', 'en', 'Other', 'manual'),
('mpb_login_title', 'en', 'Sign in required', 'manual'),
('mpb_login_text', 'en', 'This action is available to registered users only. Sign in or create an account.', 'manual'),
('mpb_post_title', 'en', 'New listing', 'manual'),
('mpb_edit_title', 'en', 'Edit listing', 'manual'),
('mpb_post_note', 'en', 'After saving, your listing goes to moderation and appears on the board once approved. It is shown for 30 days.', 'manual'),
('mpb_post_note_staff', 'en', 'You are posting as staff — the listing appears on the board immediately, without moderation.', 'manual'),
('mpb_f_title', 'en', 'Title', 'manual'),
('mpb_f_short', 'en', 'Short description', 'manual'),
('mpb_f_short_hint', 'en', '10–500 characters. Shown in the list.', 'manual'),
('mpb_f_full', 'en', 'Full description', 'manual'),
('mpb_f_full_hint', 'en', 'Up to 5000 characters. At most %d links in all descriptions combined.', 'manual'),
('mpb_f_categories', 'en', 'Categories', 'manual'),
('mpb_f_categories_hint', 'en', 'Choose 1 to 3.', 'manual'),
('mpb_f_price_amount', 'en', 'Amount', 'manual'),
('mpb_f_currency', 'en', 'Currency', 'manual'),
('mpb_f_price_hint', 'en', 'This is the price between you and the buyer. The platform takes no money.', 'manual'),
('mpb_f_city', 'en', 'City', 'manual'),
('mpb_f_remote', 'en', 'Remote', 'manual'),
('mpb_f_contacts', 'en', 'Contacts', 'manual'),
('mpb_f_contacts_hint', 'en', 'At least one is required: phone, Telegram or email. Shown only after a registered user clicks “Show contact”.', 'manual'),
('mpb_f_photos', 'en', 'Photos (up to %d)', 'manual'),
('mpb_f_photos_hint', 'en', 'JPG, PNG or WEBP, up to %d MB each. The first photo is the cover.', 'manual'),
('mpb_photo_order', 'en', 'Order', 'manual'),
('mpb_photo_cover', 'en', 'Make cover', 'manual'),
('mpb_photo_delete', 'en', 'Delete', 'manual'),
('mpb_f_rules_link', 'en', 'Listing rules', 'manual'),
('mpb_submit_new', 'en', 'Submit for moderation', 'manual'),
('mpb_submit_save', 'en', 'Save changes', 'manual'),
('mpb_cancel', 'en', 'Cancel', 'manual'),
('mpb_saved_pending', 'en', 'The listing was saved and sent for moderation.', 'manual'),
('mpb_saved_published', 'en', 'The listing was saved and published.', 'manual'),
('mpb_err_csrf_title', 'en', 'Session expired', 'manual'),
('mpb_err_csrf', 'en', 'Your session expired or the request is invalid. Reload the page and try again.', 'manual'),
('mpb_err_generic_title', 'en', 'Error', 'manual'),
('mpb_err_spam', 'en', 'The request looks automated. If this is a mistake, please try again.', 'manual'),
('mpb_err_post_too_big', 'en', 'The files are too large for one request. Reduce the size or number of photos.', 'manual'),
('mpb_err_title', 'en', 'Title: 3 to 200 characters.', 'manual'),
('mpb_err_short', 'en', 'Short description: 10 to 500 characters.', 'manual'),
('mpb_err_full', 'en', 'Full description: at most 5000 characters.', 'manual'),
('mpb_err_categories', 'en', 'Choose 1 to 3 categories.', 'manual'),
('mpb_err_price_type', 'en', 'Choose a price type.', 'manual'),
('mpb_err_price_amount', 'en', 'Enter an amount greater than zero (a number with up to two decimals).', 'manual'),
('mpb_err_location', 'en', 'Enter a city or tick “Remote”.', 'manual'),
('mpb_err_city_long', 'en', 'City: at most 120 characters.', 'manual'),
('mpb_err_contact_required', 'en', 'Provide at least one contact: phone, Telegram or email.', 'manual'),
('mpb_err_phone', 'en', 'The phone number is invalid.', 'manual'),
('mpb_err_telegram', 'en', 'Telegram: 5–32 characters (letters, digits, underscore), e.g. @username.', 'manual'),
('mpb_err_email', 'en', 'The email is invalid.', 'manual'),
('mpb_err_rules', 'en', 'You must agree to the listing rules.', 'manual'),
('mpb_err_links', 'en', 'Descriptions may contain at most %d links.', 'manual'),
('mpb_err_stopword', 'en', 'The text contains forbidden words. Please edit it.', 'manual'),
('mpb_err_photo_count', 'en', 'At most %d photos are allowed.', 'manual'),
('mpb_err_photo_size', 'en', 'One of the photos is too large.', 'manual'),
('mpb_err_photo_type', 'en', 'Only genuine JPG, PNG or WEBP images are allowed.', 'manual'),
('mpb_err_photo_upload', 'en', 'One of the photos failed to upload. Please try again.', 'manual'),
('mpb_err_photo_process', 'en', 'One of the photos could not be processed. Try another file.', 'manual'),
('mpb_err_limit_active', 'en', 'Active listings limit (pending + published): %d. Archive some first.', 'manual'),
('mpb_err_limit_day', 'en', 'New listings limit: %d per day. Try again tomorrow.', 'manual'),
('mpb_err_duplicate', 'en', 'You already have a listing with this title.', 'manual'),
('mpb_err_save', 'en', 'Could not save the listing. Please try again later.', 'manual'),
('mpb_my_title', 'en', 'My listings', 'manual'),
('mpb_my_empty', 'en', 'There are no listings in this tab.', 'manual'),
('mpb_tab_pending', 'en', 'Pending', 'manual'),
('mpb_tab_active', 'en', 'Active', 'manual'),
('mpb_tab_finished', 'en', 'Finished', 'manual'),
('mpb_tab_rejected', 'en', 'Rejected', 'manual'),
('mpb_st_pending', 'en', 'Pending review', 'manual'),
('mpb_st_published', 'en', 'Published', 'manual'),
('mpb_st_rejected', 'en', 'Rejected', 'manual'),
('mpb_st_archived', 'en', 'Archived', 'manual'),
('mpb_st_expired', 'en', 'Expired', 'manual'),
('mpb_until', 'en', 'valid until', 'manual'),
('mpb_ended', 'en', 'ended on', 'manual'),
('mpb_reject_reason', 'en', 'Rejection reason', 'manual'),
('mpb_edit_btn', 'en', 'Edit', 'manual'),
('mpb_extend_btn', 'en', 'Extend (+30 days)', 'manual'),
('mpb_archive_btn', 'en', 'Archive', 'manual'),
('mpb_extended', 'en', 'The listing was extended.', 'manual'),
('mpb_archived', 'en', 'The listing was archived.', 'manual'),
('mpb_err_archive', 'en', 'Could not archive the listing.', 'manual'),
('mpb_err_extend_early', 'en', 'You can extend when 30 days or less remain.', 'manual'),
('mpb_err_extend_status', 'en', 'This listing cannot be extended.', 'manual'),
('mpb_rules_placeholder', 'en', 'The listing rules text will be published soon.', 'manual');

INSERT INTO mp_category_translations (category_id, lang, name)
SELECT c.id, 'en', t.name FROM mp_categories c
JOIN (
  SELECT 'ai-services' AS slug, 'AI services and consulting' AS name UNION ALL
  SELECT 'automation-setup',    'Automation and setup' UNION ALL
  SELECT 'prompts-templates',   'Prompts and templates' UNION ALL
  SELECT 'training-lessons',    'Training and lessons' UNION ALL
  SELECT 'content-design',      'Content and design' UNION ALL
  SELECT 'development',         'Development and bots' UNION ALL
  SELECT 'jobs-gigs',           'Jobs and gigs' UNION ALL
  SELECT 'hardware',            'Hardware and equipment' UNION ALL
  SELECT 'other',               'Other'
) t ON t.slug = c.slug
WHERE c.section = 'board'
  AND NOT EXISTS (
    SELECT 1 FROM mp_category_translations x
    WHERE x.category_id = c.id AND x.lang = 'en'
  );
