SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Продуктивність» → нова підкатегорія «AI-асистенти» — 6 нових продуктів, 4 прив'язок наявних
--   Microsoft Copilot — AI-асистенти
--   Google Gemini — AI-асистенти
--   Monica — AI-асистенти
--   Sider — AI-асистенти
--   Merlin — AI-асистенти
--   MaxAI — AI-асистенти
--   (наявний) ChatGPT → AI-асистенти
--   (наявний) Claude → AI-асистенти
--   (наявний) Raycast → AI-асистенти
--   (наявний) Saner.AI → AI-асистенти
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'AI-асистенти', 'AI Assistants', 'ai-assistants' FROM `categories` c WHERE c.`slug` = 'productivity' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Microsoft Copilot — AI-асистенти
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'copilot.microsoft.com' OR LOWER(`name`) = LOWER('Microsoft Copilot'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Microsoft Copilot', NULL, 'https://copilot.microsoft.com', NULL, NULL, 'AI-асистент Microsoft: безкоштовний чат у вебі й застосунках, а з підпискою Microsoft 365 — допомога прямо у Word, Excel, PowerPoint, Outlook і Teams.', 'Microsoft''s AI assistant: a free chat on the web and in apps, and with a Microsoft 365 subscription, help right inside Word, Excel, PowerPoint, Outlook and Teams.', 'Microsoft Copilot — AI-асистент, вбудований в екосистему Microsoft. Безкоштовний Copilot Chat доступний у вебі, на Windows і в мобільних застосунках: він відповідає на запитання, пише й редагує тексти, працює з файлами та зображеннями. З підпискою Microsoft 365 Personal чи Family Copilot з''являється всередині Word, Excel, PowerPoint і Outlook — готує чернетки, підсумовує документи й листи, будує формули та слайди. Для бізнесу є Microsoft 365 Copilot з доступом до корпоративних даних і агентів: окремий модуль Copilot Business коштує $21 за користувача на місяць при річній оплаті (до грудня 2026 діє акційна ціна $18), а пакети Business Standard і Business Premium з Copilot — $23,50 і $32 за користувача на місяць.', 'Microsoft Copilot is an AI assistant built into the Microsoft ecosystem. The free Copilot Chat is available on the web, in Windows and in mobile apps: it answers questions, writes and edits text, and works with files and images. With a Microsoft 365 Personal or Family subscription, Copilot appears inside Word, Excel, PowerPoint and Outlook — drafting, summarising documents and emails, building formulas and slides. For businesses there is Microsoft 365 Copilot with access to company data and agents: the Copilot Business add-on costs $21 per user a month billed annually (a $18 promo price runs until December 2026), and the Business Standard and Business Premium bundles with Copilot cost $23.50 and $32 per user a month.', 'Безкоштовний AI-чат у вебі, Windows і мобільних застосунках
Copilot у Word, Excel, PowerPoint, Outlook і Teams
Підсумки документів, листів і зустрічей
Агенти та доступ до корпоративних даних у бізнес-версії', 'Free AI chat on the web, in Windows and mobile apps
Copilot in Word, Excel, PowerPoint, Outlook and Teams
Summaries of documents, emails and meetings
Agents and company data access in the business version', 'Користувачі Windows і Microsoft 365 — від домашніх користувачів до компаній, які працюють в Office.', 'Windows and Microsoft 365 users — from home users to companies that work in Office.', 'web,mobile,desktop', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'copilot.microsoft.com' OR LOWER(`name`) = LOWER('Microsoft Copilot')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'ai-assistants' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Microsoft''s AI assistant: a free chat on the web and in apps, and with a Microsoft 365 subscription, help right inside Word, Excel, PowerPoint, Outlook and Teams.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Microsoft Copilot is an AI assistant built into the Microsoft ecosystem. The free Copilot Chat is available on the web, in Windows and in mobile apps: it answers questions, writes and edits text, and works with files and images. With a Microsoft 365 Personal or Family subscription, Copilot appears inside Word, Excel, PowerPoint and Outlook — drafting, summarising documents and emails, building formulas and slides. For businesses there is Microsoft 365 Copilot with access to company data and agents: the Copilot Business add-on costs $21 per user a month billed annually (a $18 promo price runs until December 2026), and the Business Standard and Business Premium bundles with Copilot cost $23.50 and $32 per user a month.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Free AI chat on the web, in Windows and mobile apps
Copilot in Word, Excel, PowerPoint, Outlook and Teams
Summaries of documents, emails and meetings
Agents and company data access in the business version', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Windows and Microsoft 365 users — from home users to companies that work in Office.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Copilot Chat', 'Copilot Chat', 0.00, 'free', 'Безкоштовний AI-чат у вебі, Windows і мобільних застосунках', 'Free AI chat on the web, in Windows and mobile apps' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Copilot Chat' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Copilot Chat', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Free AI chat on the web, in Windows and mobile apps', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Microsoft 365 Copilot Business', 'Microsoft 365 Copilot Business', 21.00, 'month', 'За користувача при річній оплаті (акція $18 до грудня 2026); помісячно $25,20', 'Per user billed annually ($18 promo until December 2026); $25.20 billed monthly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Microsoft 365 Copilot Business' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Microsoft 365 Copilot Business', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per user billed annually ($18 promo until December 2026); $25.20 billed monthly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Google Gemini — AI-асистенти
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'gemini.google.com' OR LOWER(`name`) = LOWER('Google Gemini'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Google Gemini', NULL, 'https://gemini.google.com', NULL, NULL, 'AI-асистент Google: чат, глибоке дослідження, генерація зображень і відео, голосовий режим Gemini Live та інтеграція з Gmail, Документами й іншими сервісами Google.', 'Google''s AI assistant: chat, Deep Research, image and video generation, the Gemini Live voice mode and integration with Gmail, Docs and other Google services.', 'Google Gemini — AI-асистент від Google, доступний у вебі та в мобільних застосунках. Він веде діалог, пише й редагує тексти, аналізує файли, проводить глибоке дослідження з джерелами (Deep Research), генерує зображення, а в платних тарифах — і відео. Режим Gemini Live дає змогу говорити з асистентом голосом, а Canvas і Gems допомагають працювати з документами та власними налаштованими ботами. Gemini інтегрований у Gmail, Документи, Диск та інші сервіси Google. Безкоштовний тариф включає 15 ГБ сховища; платні Google AI Plus, AI Pro і AI Ultra розширюють ліміти, дають доступ до найпотужніших моделей і більше сховища. В Україні ціни такі: AI Plus — ₴224,99, AI Pro — ₴909,99, AI Ultra — від ₴4 599 на місяць.', 'Google Gemini is Google''s AI assistant, available on the web and in mobile apps. It holds conversations, writes and edits text, analyses files, runs in-depth research with sources (Deep Research), generates images and, on paid plans, video. Gemini Live lets you talk to the assistant by voice, while Canvas and Gems help you work on documents and with your own custom bots. Gemini is integrated into Gmail, Docs, Drive and other Google services. The free plan includes 15 GB of storage; the paid Google AI Plus, AI Pro and AI Ultra plans raise limits, unlock the most capable models and add more storage. In Ukraine the prices are ₴224.99 for AI Plus, ₴909.99 for AI Pro and from ₴4,599 a month for AI Ultra.', 'Чат, Deep Research і Canvas
Генерація зображень і відео
Голосовий режим Gemini Live
Інтеграція з Gmail, Документами й Диском
Власні боти Gems', 'Chat, Deep Research and Canvas
Image and video generation
Gemini Live voice mode
Integration with Gmail, Docs and Drive
Custom Gems bots', 'Усі, хто користується сервісами Google і хоче AI-асистента для навчання, роботи й повсякденних задач.', 'Anyone who uses Google services and wants an AI assistant for study, work and everyday tasks.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'gemini.google.com' OR LOWER(`name`) = LOWER('Google Gemini')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'ai-assistants' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Google''s AI assistant: chat, Deep Research, image and video generation, the Gemini Live voice mode and integration with Gmail, Docs and other Google services.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Google Gemini is Google''s AI assistant, available on the web and in mobile apps. It holds conversations, writes and edits text, analyses files, runs in-depth research with sources (Deep Research), generates images and, on paid plans, video. Gemini Live lets you talk to the assistant by voice, while Canvas and Gems help you work on documents and with your own custom bots. Gemini is integrated into Gmail, Docs, Drive and other Google services. The free plan includes 15 GB of storage; the paid Google AI Plus, AI Pro and AI Ultra plans raise limits, unlock the most capable models and add more storage. In Ukraine the prices are ₴224.99 for AI Plus, ₴909.99 for AI Pro and from ₴4,599 a month for AI Ultra.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Chat, Deep Research and Canvas
Image and video generation
Gemini Live voice mode
Integration with Gmail, Docs and Drive
Custom Gems bots', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Anyone who uses Google services and wants an AI assistant for study, work and everyday tasks.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовно', 'Free', 0.00, 'free', 'Чат, Deep Research, генерація зображень, Gemini Live, 15 ГБ сховища', 'Chat, Deep Research, image generation, Gemini Live, 15 GB storage' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Безкоштовно' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Chat, Deep Research, image generation, Gemini Live, 15 GB storage', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Google AI Plus', 'Google AI Plus', NULL, 'month', '₴224,99 на місяць в Україні: удвічі вищі ліміти, генерація відео, 400 ГБ сховища', '₴224.99 a month in Ukraine: 2× higher limits, video generation, 400 GB storage' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Google AI Plus' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Google AI Plus', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '₴224.99 a month in Ukraine: 2× higher limits, video generation, 400 GB storage', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Google AI Pro', 'Google AI Pro', NULL, 'month', '₴909,99 на місяць в Україні: розширений доступ до найпотужніших моделей, 5 ТБ сховища', '₴909.99 a month in Ukraine: extended access to the most capable models, 5 TB storage' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Google AI Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Google AI Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '₴909.99 a month in Ukraine: extended access to the most capable models, 5 TB storage', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Google AI Ultra', 'Google AI Ultra', NULL, 'month', 'Від ₴4 599 на місяць в Україні: найвищі ліміти, 20+ ТБ сховища, YouTube Premium', 'From ₴4,599 a month in Ukraine: highest limits, 20+ TB storage, YouTube Premium' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Google AI Ultra' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Google AI Ultra', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'From ₴4,599 a month in Ukraine: highest limits, 20+ TB storage, YouTube Premium', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Monica — AI-асистенти
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'monica.im' OR LOWER(`name`) = LOWER('Monica'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Monica', NULL, 'https://monica.im', NULL, NULL, 'AI-асистент у браузері та застосунках: чат з провідними моделями, підсумки сторінок і відео, переклад, написання текстів, генерація зображень і AI-агент.', 'An AI assistant in your browser and apps: chat with leading models, page and video summaries, translation, writing, image generation and an AI agent.', 'Monica — універсальний AI-асистент, що працює як розширення браузера, веб-застосунок, настільна та мобільна програма. На будь-якій сторінці він підсумовує текст і відео, перекладає, пояснює, допомагає написати чи переписати текст і відповісти на лист; є ChatPDF, генерація зображень і відео, глибоке дослідження, створення презентацій та агент, що виконує дії в браузері. В одній підписці доступні моделі GPT, Claude, Gemini та інші. Тарифи (річна оплата): Free; Pro — $99 на рік (1 500 розширених кредитів на місяць); Max — $299 на рік (4 500 кредитів, зараз діє знижка до $199); Ultra — $995 на рік (20 000 кредитів).', 'Monica is an all-in-one AI assistant that works as a browser extension, web app, desktop and mobile app. On any page it summarises text and video, translates, explains, helps you write or rewrite text and reply to emails; there is also ChatPDF, image and video generation, deep research, slide creation and an agent that performs actions in the browser. GPT, Claude, Gemini and other models are available in one subscription. Plans (billed yearly): Free; Pro at $99 a year (1,500 advanced credits a month); Max at $299 a year (4,500 credits, currently discounted to $199); Ultra at $995 a year (20,000 credits).', 'Розширення браузера, веб, настільна й мобільна версії
Підсумки сторінок, відео та PDF
Переклад і допомога з написанням текстів
Генерація зображень і відео, презентації
AI-агент у браузері', 'Browser extension, web, desktop and mobile versions
Summaries of pages, videos and PDFs
Translation and writing help
Image and video generation, slide decks
AI agent in the browser', 'Студенти, офісні працівники й контент-мейкери, яким потрібен AI під рукою на будь-якому сайті.', 'Students, office workers and content creators who want AI at hand on any website.', 'web,mobile,desktop', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'monica.im' OR LOWER(`name`) = LOWER('Monica')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'ai-assistants' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI assistant in your browser and apps: chat with leading models, page and video summaries, translation, writing, image generation and an AI agent.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Monica is an all-in-one AI assistant that works as a browser extension, web app, desktop and mobile app. On any page it summarises text and video, translates, explains, helps you write or rewrite text and reply to emails; there is also ChatPDF, image and video generation, deep research, slide creation and an agent that performs actions in the browser. GPT, Claude, Gemini and other models are available in one subscription. Plans (billed yearly): Free; Pro at $99 a year (1,500 advanced credits a month); Max at $299 a year (4,500 credits, currently discounted to $199); Ultra at $995 a year (20,000 credits).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Browser extension, web, desktop and mobile versions
Summaries of pages, videos and PDFs
Translation and writing help
Image and video generation, slide decks
AI agent in the browser', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Students, office workers and content creators who want AI at hand on any website.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Базовий доступ з обмеженнями', 'Basic access with limits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Basic access with limits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 99.00, 'year', '1 500 розширених кредитів на місяць; помісячно від $8,3', '1,500 advanced credits a month; from $8.3/mo' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '1,500 advanced credits a month; from $8.3/mo', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Max', 'Max', 299.00, 'year', '4 500 розширених кредитів на місяць; зараз зі знижкою $199 на рік', '4,500 advanced credits a month; currently discounted to $199 a year' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Max' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Max', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '4,500 advanced credits a month; currently discounted to $199 a year', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ultra', 'Ultra', 995.00, 'year', '20 000 розширених кредитів, необмежений доступ до базових і розширених моделей', '20,000 advanced credits, unlimited basic and advanced models' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ultra' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Ultra', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '20,000 advanced credits, unlimited basic and advanced models', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Sider — AI-асистенти
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'sider.ai' OR LOWER(`name`) = LOWER('Sider'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Sider', NULL, 'https://sider.ai', NULL, NULL, 'AI-бічна панель для браузера: чат з GPT, Claude, Gemini та іншими моделями, підсумки й переклад сторінок і PDF, автоматизація дій у браузері та генерація контенту.', 'An AI sidebar for your browser: chat with GPT, Claude, Gemini and other models, summaries and translation of pages and PDFs, browser task automation and content generation.', 'Sider — AI-асистент у вигляді бічної панелі браузера, а також веб- і мобільний застосунок. У режимі чату він відповідає на запитання з використанням провідних моделей, підсумовує довгі статті, перекладає сторінки, PDF і зображення та пояснює складні поняття. Режим Hand автоматизує дії в браузері: заповнює форми, порівнює ціни, збирає інформацію з кількох сайтів і розбирає пошту Gmail. Є інструменти для зміни будь-якої вебсторінки, генерації зображень, відео й слайдів та база знань Wisebase. Усі тарифи мають однаковий набір функцій і відрізняються кількістю кредитів і потужністю хмарного комп''ютера: Nano — $100 на рік, Lite — $250, Pro — $500, Max — $1 000 на рік.', 'Sider is an AI assistant in the form of a browser sidebar, plus a web and mobile app. In chat mode it answers questions using leading models, summarises long articles, translates pages, PDFs and images and explains complex concepts. Hand mode automates browser actions: filling in forms, comparing prices, gathering information across sites and organising your Gmail inbox. There are tools to change any web page, generate images, video and slides, and a Wisebase knowledge base. All plans include the same features and differ in credits and cloud computer power: Nano at $100 a year, Lite at $250, Pro at $500 and Max at $1,000 a year.', 'Бічна панель з провідними моделями в будь-якому сайті
Підсумки й переклад сторінок, PDF і зображень
Автоматизація дій у браузері (Hand)
Генерація зображень, відео й слайдів
База знань Wisebase', 'Sidebar with leading models on any website
Summaries and translation of pages, PDFs and images
Browser task automation (Hand)
Image, video and slide generation
Wisebase knowledge base', 'Люди, які багато читають і працюють у браузері: студенти, дослідники, маркетологи.', 'People who read and work in the browser a lot: students, researchers and marketers.', 'web,mobile,desktop', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'sider.ai' OR LOWER(`name`) = LOWER('Sider')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'ai-assistants' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI sidebar for your browser: chat with GPT, Claude, Gemini and other models, summaries and translation of pages and PDFs, browser task automation and content generation.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Sider is an AI assistant in the form of a browser sidebar, plus a web and mobile app. In chat mode it answers questions using leading models, summarises long articles, translates pages, PDFs and images and explains complex concepts. Hand mode automates browser actions: filling in forms, comparing prices, gathering information across sites and organising your Gmail inbox. There are tools to change any web page, generate images, video and slides, and a Wisebase knowledge base. All plans include the same features and differ in credits and cloud computer power: Nano at $100 a year, Lite at $250, Pro at $500 and Max at $1,000 a year.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Sidebar with leading models on any website
Summaries and translation of pages, PDFs and images
Browser task automation (Hand)
Image, video and slide generation
Wisebase knowledge base', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People who read and work in the browser a lot: students, researchers and marketers.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Nano', 'Nano', 100.00, 'year', 'Для простих епізодичних задач (≈$8,33/міс)', 'For simple occasional tasks (≈$8.33/mo)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Nano' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Nano', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'For simple occasional tasks (≈$8.33/mo)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Lite', 'Lite', 250.00, 'year', 'Для більшості щоденних задач (≈$20,83/міс)', 'For most everyday tasks (≈$20.83/mo)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Lite' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Lite', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'For most everyday tasks (≈$20.83/mo)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 500.00, 'year', 'Вища квота кредитів (≈$41,67/міс)', 'Higher credit quota (≈$41.67/mo)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Higher credit quota (≈$41.67/mo)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Max', 'Max', 1000.00, 'year', 'Найбільша квота й потужніший хмарний комп''ютер (≈$83,33/міс)', 'Largest quota and a more powerful cloud computer (≈$83.33/mo)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Max' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Max', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Largest quota and a more powerful cloud computer (≈$83.33/mo)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Merlin — AI-асистенти
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'getmerlin.in' OR LOWER(`name`) = LOWER('Merlin'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Merlin', NULL, 'https://www.getmerlin.in', NULL, NULL, 'AI-асистент у розширенні браузера та застосунках: чат з різними моделями, підсумки відео й сторінок, допомога з листами й текстами просто на сайті, де ви працюєте.', 'An AI assistant in a browser extension and apps: chat with various models, video and page summaries, and help with emails and text right on the site you are using.', 'Merlin — AI-асистент, який працює як розширення Chrome, веб-застосунок і мобільна програма. Він дає доступ до кількох провідних моделей в одному чаті, підсумовує відео YouTube і вебсторінки, допомагає писати й редагувати листи, пости та тексти прямо на сайтах і відповідає на запитання з пошуком в інтернеті. Безкоштовний план має обмежену кількість запитів; Pro коштує $228 на рік (≈$19 на місяць) з чесним лімітом використання; Teams — $180 на рік за користувача (≈$15 на місяць).', 'Merlin is an AI assistant that works as a Chrome extension, web app and mobile app. It gives access to several leading models in one chat, summarises YouTube videos and web pages, helps write and edit emails, posts and text right on websites and answers questions with web search. The free plan has a limited number of queries; Pro costs $228 a year (≈$19 a month) with a fair-use limit; Teams costs $180 a year per user (≈$15 a month).', 'Кілька провідних моделей в одному чаті
Підсумки відео YouTube і вебсторінок
Допомога з листами й текстами на будь-якому сайті
Відповіді з пошуком в інтернеті', 'Several leading models in one chat
YouTube video and web page summaries
Help with emails and text on any website
Answers with web search', 'Студенти, фрілансери й офісні працівники, які хочуть AI-помічника просто в браузері.', 'Students, freelancers and office workers who want an AI helper right in the browser.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'getmerlin.in' OR LOWER(`name`) = LOWER('Merlin')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'ai-assistants' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI assistant in a browser extension and apps: chat with various models, video and page summaries, and help with emails and text right on the site you are using.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Merlin is an AI assistant that works as a Chrome extension, web app and mobile app. It gives access to several leading models in one chat, summarises YouTube videos and web pages, helps write and edit emails, posts and text right on websites and answers questions with web search. The free plan has a limited number of queries; Pro costs $228 a year (≈$19 a month) with a fair-use limit; Teams costs $180 a year per user (≈$15 a month).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Several leading models in one chat
YouTube video and web page summaries
Help with emails and text on any website
Answers with web search', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Students, freelancers and office workers who want an AI helper right in the browser.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Обмежена кількість запитів', 'Limited number of queries' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Limited number of queries', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 228.00, 'year', '≈$19 на місяць, чесний ліміт використання', '≈$19 a month, fair-use limit' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '≈$19 a month, fair-use limit', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Teams', 'Teams', 180.00, 'year', 'За користувача на рік (≈$15 на місяць)', 'Per user a year (≈$15 a month)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Teams' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Teams', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per user a year (≈$15 a month)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- MaxAI — AI-асистенти
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'maxai.co' OR LOWER(`name`) = LOWER('MaxAI'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'MaxAI', NULL, 'https://www.maxai.co', NULL, NULL, 'AI-розширення для Chrome і Edge: одним кліком пише, покращує, перекладає й підсумовує будь-який текст на сайті, дає чат з GPT, Claude, Gemini та іншими моделями.', 'An AI extension for Chrome and Edge: with one click it writes, improves, translates and summarises any text on a website and gives you chat with GPT, Claude, Gemini and other models.', 'MaxAI — AI-асистент у вигляді розширення для Chrome та Edge і веб-застосунку. Виділіть текст на будь-якому сайті — і він його перепише, виправить граматику, перекладе, пояснить, підсумує чи допоможе відповісти. У бічній панелі доступний чат з моделями GPT, Claude, Gemini, Grok, Llama і DeepSeek, пошук в інтернеті, робота з PDF і відео та генерація зображень. Сервісом користуються понад мільйон людей і 2 000 команд. Є безкоштовний тариф; Pro коштує $30 на місяць або $12 на місяць при річній оплаті.', 'MaxAI is an AI assistant in the form of a Chrome and Edge extension and a web app. Select text on any website and it will rewrite it, fix grammar, translate, explain, summarise or help you reply. The sidebar offers chat with GPT, Claude, Gemini, Grok, Llama and DeepSeek models, web search, PDF and video chat and image generation. More than a million people and 2,000 teams use it. There is a free plan; Pro costs $30 a month or $12 a month billed yearly.', 'Дії з виділеним текстом на будь-якому сайті
Чат з GPT, Claude, Gemini, Grok, Llama, DeepSeek
Переклад, граматика й підсумки
Робота з PDF і відео, генерація зображень', 'Actions on selected text on any website
Chat with GPT, Claude, Gemini, Grok, Llama, DeepSeek
Translation, grammar and summaries
PDF and video chat, image generation', 'Ті, хто багато пише й читає в браузері: маркетологи, підтримка клієнтів, студенти.', 'People who write and read a lot in the browser: marketers, customer support and students.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'maxai.co' OR LOWER(`name`) = LOWER('MaxAI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'ai-assistants' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI extension for Chrome and Edge: with one click it writes, improves, translates and summarises any text on a website and gives you chat with GPT, Claude, Gemini and other models.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'MaxAI is an AI assistant in the form of a Chrome and Edge extension and a web app. Select text on any website and it will rewrite it, fix grammar, translate, explain, summarise or help you reply. The sidebar offers chat with GPT, Claude, Gemini, Grok, Llama and DeepSeek models, web search, PDF and video chat and image generation. More than a million people and 2,000 teams use it. There is a free plan; Pro costs $30 a month or $12 a month billed yearly.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Actions on selected text on any website
Chat with GPT, Claude, Gemini, Grok, Llama, DeepSeek
Translation, grammar and summaries
PDF and video chat, image generation', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People who write and read a lot in the browser: marketers, customer support and students.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Базові функції з обмеженнями', 'Basic features with limits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Basic features with limits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 30.00, 'month', 'Необмежені розширені функції; $12/міс при річній оплаті', 'Unlimited advanced features; $12/mo billed yearly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited advanced features; $12/mo billed yearly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('ChatGPT')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'ai-assistants' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Claude')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'ai-assistants' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Raycast')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'ai-assistants' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Saner.AI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'ai-assistants' LIMIT 1;
