SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: 70 нових AI (частина 4): письмо, фінанси та психологія (+ нова підкатегорія «Інструменти для психологів») — 12 нових продуктів, 0 прив'язок наявних
--   NovelAI — Публікації
--   Novelcrafter — Публікації
--   Squibler — Публікації
--   Ramp — Фінанси
--   Ash (Slingshot AI) — Ментальне здоров'я
--   Earkick — Ментальне здоров'я
--   Mindsera — Ментальне здоров'я
--   Upheal — Інструменти для психологів
--   Mentalyc — Інструменти для психологів
--   Blueprint — Інструменти для психологів
--   Lyssn — Інструменти для психологів
--   Limbic — Інструменти для психологів
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Публікації', 'Publications', 'publications' FROM `categories` c WHERE c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Фінанси', 'Finance', 'finance' FROM `categories` c WHERE c.`slug` = 'finance-legal' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Ментальне здоров''я', 'Mental Health', 'mental-health' FROM `categories` c WHERE c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Інструменти для психологів', 'Tools for Psychologists', 'psychologist-tools' FROM `categories` c WHERE c.`slug` = 'health-beauty' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- NovelAI — Публікації
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'novelai.net' OR LOWER(`name`) = LOWER('NovelAI'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'NovelAI', NULL, 'https://novelai.net', NULL, NULL, 'AI-помічник для написання історій і генератор аніме-зображень із захистом приватності: шифровані запити та повні комерційні права на результат.', 'An AI storytelling assistant and anime image generator with privacy built in: encrypted prompts and full commercial rights to your output.', 'NovelAI поєднує два творчі інструменти: помічника для написання історій, який продовжує й розвиває ваш текст, і генератор аніме-зображень з інструментами послідовності персонажів, інпейнтингом і редагуванням. Сервіс робить наголос на приватності: запити шифруються, а згенеровані зображення не зберігаються на серверах. Користувачі зберігають повні комерційні права на створене. Працює в браузері, зокрема на мобільних. Підписка — від $10 на місяць, також можна купувати внутрішню валюту Anlas для додаткових генерацій.', 'NovelAI combines two creative tools: a storytelling assistant that continues and develops your text, and an anime image generator with character consistency tools, inpainting and editing. Privacy is a priority: prompts are encrypted and generated images are not stored on servers. Users keep full commercial rights to what they create. It runs in the browser, including on mobile. Subscriptions start at $10 a month, and you can also buy Anlas, an in-app currency, for extra generations.', 'Помічник для написання історій
Генерація аніме-зображень
Послідовність персонажів та інпейнтинг
Шифровані запити', 'Storytelling assistant
Anime image generation
Character consistency and inpainting
Encrypted prompts', 'Письменники-аматори, автори фанфіків і художники.', 'Hobby writers, fan fiction authors and artists.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'novelai.net' OR LOWER(`name`) = LOWER('NovelAI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'publications' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI storytelling assistant and anime image generator with privacy built in: encrypted prompts and full commercial rights to your output.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'NovelAI combines two creative tools: a storytelling assistant that continues and develops your text, and an anime image generator with character consistency tools, inpainting and editing. Privacy is a priority: prompts are encrypted and generated images are not stored on servers. Users keep full commercial rights to what they create. It runs in the browser, including on mobile. Subscriptions start at $10 a month, and you can also buy Anlas, an in-app currency, for extra generations.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Storytelling assistant
Anime image generation
Character consistency and inpainting
Encrypted prompts', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Hobby writers, fan fiction authors and artists.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Від $10', 'From $10', 10.00, 'month', 'Підписки від $10 на місяць', 'Subscriptions from $10 a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Від $10' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'From $10', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Subscriptions from $10 a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Novelcrafter — Публікації
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'novelcrafter.com' OR LOWER(`name`) = LOWER('Novelcrafter'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Novelcrafter', NULL, 'https://www.novelcrafter.com', NULL, NULL, 'Платформа для написання романів: планування, Codex для персонажів і світу, серії книг та AI-функції з вашими власними ключами моделей.', 'A novel-writing platform: planning, a Codex for characters and worldbuilding, book series and AI features using your own model keys.', 'Novelcrafter допомагає письменникам від задуму до готового рукопису. Codex зберігає персонажів, місця й правила світу, книги можна об''єднувати в серії, а AI-функції — підсумки сцен, витягування персонажів, чат-майстерня й рецензування — працюють з вашими власними API-ключами до моделей. Тарифи: Scribe — $4 на місяць (інструменти письма, необмежені книги); Hobbyist — $8 (AI з власними ключами); Artisan — $14 (чат-майстерня й рецензування); Specialist — $20 (спільне письмо й команда). Є 21 день безкоштовно, ціни без акцій; після скасування дані доступні для читання.', 'Novelcrafter helps writers go from idea to finished manuscript. The Codex stores characters, places and world rules, books can be grouped into series, and AI features — scene summaries, character extraction, workshop chat and review — work with your own API keys for models. Plans: Scribe — $4 a month (writing tools, unlimited books); Hobbyist — $8 (AI with your own keys); Artisan — $14 (workshop chat and review); Specialist — $20 (collaborative writing and teams). There is a 21-day free trial and no sales or discounts; after cancelling, your data stays readable.', 'Codex для персонажів і світу
Серії книг і необмежені книги
AI з власними ключами моделей
Спільне письмо (Specialist)', 'Codex for characters and worldbuilding
Book series and unlimited books
AI with your own model keys
Collaborative writing (Specialist)', 'Письменники художньої літератури.', 'Fiction writers.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'novelcrafter.com' OR LOWER(`name`) = LOWER('Novelcrafter')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'publications' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A novel-writing platform: planning, a Codex for characters and worldbuilding, book series and AI features using your own model keys.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Novelcrafter helps writers go from idea to finished manuscript. The Codex stores characters, places and world rules, books can be grouped into series, and AI features — scene summaries, character extraction, workshop chat and review — work with your own API keys for models. Plans: Scribe — $4 a month (writing tools, unlimited books); Hobbyist — $8 (AI with your own keys); Artisan — $14 (workshop chat and review); Specialist — $20 (collaborative writing and teams). There is a 21-day free trial and no sales or discounts; after cancelling, your data stays readable.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Codex for characters and worldbuilding
Book series and unlimited books
AI with your own model keys
Collaborative writing (Specialist)', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Fiction writers.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Scribe', 'Scribe', 4.00, 'month', 'Інструменти письма, необмежені книги', 'Writing tools, unlimited books' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Scribe' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Scribe', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Writing tools, unlimited books', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Hobbyist', 'Hobbyist', 8.00, 'month', 'AI з власними ключами', 'AI with your own keys' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Hobbyist' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Hobbyist', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'AI with your own keys', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Artisan', 'Artisan', 14.00, 'month', 'Чат-майстерня й рецензування', 'Workshop chat and review' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Artisan' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Artisan', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Workshop chat and review', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Squibler — Публікації
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'squibler.io' OR LOWER(`name`) = LOWER('Squibler'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Squibler', NULL, 'https://www.squibler.io', NULL, NULL, 'AI-помічник для книжок і сценаріїв: генерує повноформатні рукописи на 200–300 сторінок, зберігає узгодженість сюжету й експортує в PDF і DOCX.', 'An AI assistant for books and screenplays: it generates full-length 200–300-page manuscripts, keeps the plot consistent and exports to PDF and DOCX.', 'Squibler допомагає письменникам розробляти романи й сценарії зі збереженням узгодженості сюжету — наприклад, продумати сюжетні повороти чи хибні сліди в детективі. Платні тарифи генерують повноформатні рукописи на 200–300 сторінок і експортують їх у PDF та DOCX. Сервісом користуються понад 20 000 авторів, права на текст залишаються за ними. Тарифи: Free — 1 000 AI-кредитів на місяць; Plus — $15,83 на місяць при річній оплаті ($29,99 помісячно, 10 000 кредитів); Pro — $49,17 на місяць при річній оплаті ($89,99 помісячно, необмежені кредити).', 'Squibler helps writers develop novels and screenplays while keeping the plot consistent — for example, working out plot twists or red herrings in a mystery. Paid plans generate full-length 200–300-page manuscripts and export them to PDF and DOCX. More than 20,000 authors use it, and they keep ownership of their work. Plans: Free — 1,000 AI credits a month; Plus — $15.83 a month billed annually ($29.99 monthly, 10,000 credits); Pro — $49.17 a month billed annually ($89.99 monthly, unlimited credits).', 'Генерація повноформатних рукописів
Книги й сценарії
Узгодженість сюжету
Експорт у PDF і DOCX', 'Full-length manuscript generation
Books and screenplays
Plot consistency
Export to PDF and DOCX', 'Письменники, сценаристи й автори нон-фікшн.', 'Novelists, screenwriters and non-fiction authors.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'squibler.io' OR LOWER(`name`) = LOWER('Squibler')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'publications' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI assistant for books and screenplays: it generates full-length 200–300-page manuscripts, keeps the plot consistent and exports to PDF and DOCX.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Squibler helps writers develop novels and screenplays while keeping the plot consistent — for example, working out plot twists or red herrings in a mystery. Paid plans generate full-length 200–300-page manuscripts and export them to PDF and DOCX. More than 20,000 authors use it, and they keep ownership of their work. Plans: Free — 1,000 AI credits a month; Plus — $15.83 a month billed annually ($29.99 monthly, 10,000 credits); Pro — $49.17 a month billed annually ($89.99 monthly, unlimited credits).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Full-length manuscript generation
Books and screenplays
Plot consistency
Export to PDF and DOCX', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Novelists, screenwriters and non-fiction authors.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '1 000 AI-кредитів на місяць', '1,000 AI credits a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '1,000 AI credits a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Plus', 'Plus', 29.99, 'month', '10 000 кредитів; $15,83/міс при річній оплаті', '10,000 credits; $15.83/mo billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Plus' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Plus', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '10,000 credits; $15.83/mo billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 89.99, 'month', 'Необмежені кредити; $49,17/міс при річній оплаті', 'Unlimited credits; $49.17/mo billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited credits; $49.17/mo billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Ramp — Фінанси
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'ramp.com' OR LOWER(`name`) = LOWER('Ramp'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Ramp', NULL, 'https://ramp.com', NULL, NULL, 'Фінансова платформа для бізнесу з AI: корпоративні картки, контроль витрат і відряджень, рахунки до сплати й автоматизація бухгалтерії з AI-перевіркою витрат.', 'An AI-powered finance platform for businesses: corporate cards, expense and travel management, accounts payable and accounting automation with AI expense review.', 'Ramp об''єднує корпоративні картки, облік витрат і відряджень, оплату рахунків, виставлення рахунків, казначейство та автоматизацію бухгалтерії з інтеграціями QuickBooks і Xero. Тариф Plus додає AI-перевірку витрат, розширену роботу з рахунками, інтеграції з NetSuite і Sage Intacct, кілька юросіб і глобальне покриття. Сервісом користуються понад 70 000 фінансових команд. Тарифи: Free — $0 за користувача; Plus — $15 за користувача на місяць плюс платформний збір (знижка 20% при річній оплаті, 30 днів безкоштовно); Enterprise — індивідуально. Сервіс орієнтований на компанії в США.', 'Ramp combines corporate cards, expense and travel management, bill payments, invoicing, treasury and accounting automation with QuickBooks and Xero integrations. The Plus plan adds AI expense review, advanced accounts payable, NetSuite and Sage Intacct integrations, multi-entity support and global coverage. More than 70,000 finance teams use it. Plans: Free — $0 per user; Plus — $15 per user a month plus a platform fee (20% off annual billing, 30-day free trial); Enterprise — custom. The service is aimed at US companies.', 'Корпоративні картки й облік витрат
AI-перевірка витрат (Plus)
Оплата рахунків і бухгалтерія
Інтеграції з QuickBooks, Xero, NetSuite', 'Corporate cards and expense management
AI expense review (Plus)
Bill pay and accounting
QuickBooks, Xero and NetSuite integrations', 'Фінансові команди компаній у США.', 'Finance teams at US companies.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'ramp.com' OR LOWER(`name`) = LOWER('Ramp')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' AND s.`slug` = 'finance' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI-powered finance platform for businesses: corporate cards, expense and travel management, accounts payable and accounting automation with AI expense review.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Ramp combines corporate cards, expense and travel management, bill payments, invoicing, treasury and accounting automation with QuickBooks and Xero integrations. The Plus plan adds AI expense review, advanced accounts payable, NetSuite and Sage Intacct integrations, multi-entity support and global coverage. More than 70,000 finance teams use it. Plans: Free — $0 per user; Plus — $15 per user a month plus a platform fee (20% off annual billing, 30-day free trial); Enterprise — custom. The service is aimed at US companies.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Corporate cards and expense management
AI expense review (Plus)
Bill pay and accounting
QuickBooks, Xero and NetSuite integrations', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Finance teams at US companies.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Картки, витрати, базові рахунки', 'Cards, expenses, basic AP' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Cards, expenses, basic AP', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Plus', 'Plus', 15.00, 'month', 'За користувача + платформний збір; AI-перевірка витрат', 'Per user + platform fee; AI expense review' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Plus' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Plus', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per user + platform fee; AI expense review', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Ash (Slingshot AI) — Ментальне здоров'я
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'talktoash.com' OR LOWER(`name`) = LOWER('Ash (Slingshot AI)'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Ash (Slingshot AI)', NULL, 'https://www.talktoash.com', NULL, NULL, 'AI-співрозмовник, створений спеціально для ментального здоров''я: підтримка 24/7 текстом чи голосом, пам''ять про вашу історію та щотижневі інсайти.', 'An AI built specifically for mental health: 24/7 support by text or voice, memory of your story and weekly insights.', 'Ash від Slingshot AI — AI, створений саме для підтримки ментального здоров''я, а не загальний чат-бот: його навчено на спеціалізованих психологічних даних. Він допомагає розібратися зі стресом, тривогою, стосунками та особистими труднощами, пов''язує думки, почуття й поведінку, запам''ятовує вашу історію та вподобання й щотижня надає персональні інсайти. Спілкуватися можна текстом або голосом цілодобово. Доступний на iOS і у вебі. Важливо: Ash не призначений для кризових ситуацій і не замінює професійне лікування — у кризі варто звертатися на гарячу лінію чи до фахівця. Ціни на сайті не опубліковано.', 'Ash from Slingshot AI is an AI built specifically for mental health support rather than a general chatbot: it is trained on specialised psychological data. It helps with stress, anxiety, relationships and personal challenges, connects thoughts, feelings and behaviours, remembers your story and preferences and gives personalised weekly insights. You can talk to it by text or voice around the clock. It is available on iOS and the web. Important: Ash is not designed for crises and does not replace professional treatment — in a crisis, contact a helpline or a professional. Pricing is not published on the website.', 'AI, навчений на психологічних даних
Текст або голос 24/7
Пам''ять про вашу історію
Щотижневі персональні інсайти', 'AI trained on psychological data
Text or voice 24/7
Remembers your story
Weekly personal insights', 'Дорослі, які шукають підтримку зі стресом, тривогою чи стосунками.', 'Adults seeking support with stress, anxiety or relationships.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'talktoash.com' OR LOWER(`name`) = LOWER('Ash (Slingshot AI)')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'mental-health' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI built specifically for mental health: 24/7 support by text or voice, memory of your story and weekly insights.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Ash from Slingshot AI is an AI built specifically for mental health support rather than a general chatbot: it is trained on specialised psychological data. It helps with stress, anxiety, relationships and personal challenges, connects thoughts, feelings and behaviours, remembers your story and preferences and gives personalised weekly insights. You can talk to it by text or voice around the clock. It is available on iOS and the web. Important: Ash is not designed for crises and does not replace professional treatment — in a crisis, contact a helpline or a professional. Pricing is not published on the website.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI trained on psychological data
Text or voice 24/7
Remembers your story
Weekly personal insights', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Adults seeking support with stress, anxiety or relationships.', 'manual' FROM DUAL WHERE @new = 1;

-- Earkick — Ментальне здоров'я
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'earkick.com' OR LOWER(`name`) = LOWER('Earkick'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Earkick', NULL, 'https://earkick.com', NULL, NULL, 'AI-трекер ментального здоров''я з компаньйоном-пандою: відстеження настрою та безкоштовний AI-чат підтримки без реєстрації.', 'An AI mental health tracker with a panda companion: mood tracking and a free AI support chat with no sign-up.', 'Earkick допомагає стежити за своїм емоційним станом і отримувати підтримку в розмові з AI-компаньйоном Panda. Застосунок відстежує показники ментального здоров''я та настрій, а чат PandaChat доступний безкоштовно й без реєстрації у вебі на chat.earkick.com. Є також блог про тривожність, стрес на роботі та здорові звички. Застосунок доступний на iOS. Earkick не замінює психотерапевта; у кризовій ситуації варто звертатися по професійну допомогу.', 'Earkick helps you track your emotional state and get support by talking to Panda, an AI companion. The app tracks mental health indicators and mood, and the PandaChat chat is available free and with no sign-up on the web at chat.earkick.com. There is also a blog about anxiety, workplace stress and healthy habits. The app is available on iOS. Earkick does not replace a therapist; in a crisis, seek professional help.', 'Відстеження настрою
AI-компаньйон Panda
Безкоштовний чат без реєстрації
Матеріали про тривожність і стрес', 'Mood tracking
Panda AI companion
Free chat with no sign-up
Articles on anxiety and stress', 'Люди, які хочуть стежити за настроєм і мати підтримку під рукою.', 'People who want to track their mood and have support at hand.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'earkick.com' OR LOWER(`name`) = LOWER('Earkick')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'mental-health' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI mental health tracker with a panda companion: mood tracking and a free AI support chat with no sign-up.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Earkick helps you track your emotional state and get support by talking to Panda, an AI companion. The app tracks mental health indicators and mood, and the PandaChat chat is available free and with no sign-up on the web at chat.earkick.com. There is also a blog about anxiety, workplace stress and healthy habits. The app is available on iOS. Earkick does not replace a therapist; in a crisis, seek professional help.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Mood tracking
Panda AI companion
Free chat with no sign-up
Articles on anxiety and stress', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People who want to track their mood and have support at hand.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовно', 'Free', 0.00, 'free', 'Чат Panda без реєстрації', 'Panda chat with no sign-up' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Безкоштовно' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Panda chat with no sign-up', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Mindsera — Ментальне здоров'я
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'mindsera.com' OR LOWER(`name`) = LOWER('Mindsera'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Mindsera', NULL, 'https://www.mindsera.com', NULL, NULL, 'AI-щоденник для ясності мислення: аналізує емоції, виявляє повторювані теми, пропонує 50+ ментальних моделей і оцінює особистість за моделлю Великої п''ятірки.', 'An AI journal for clear thinking: it analyses emotions, detects recurring topics, offers 50+ mental model templates and assesses personality using the Big Five.', 'Mindsera — «спортзал для розуму», що поєднує ведення щоденника з ментальними моделями. Записи можна писати, надиктовувати або сканувати з паперового щоденника; AI-компаньйон ставить запитання для глибшої рефлексії, аналізує емоції, знаходить повторювані теми й оцінює особистість за моделлю Великої п''ятірки. Є понад 50 шаблонів мислення (мислення з перших принципів, ікігай тощо), щотижневі підсумки й відстеження звичок. Дані шифруються й не використовуються для навчання моделей. Тарифи: Curious — безкоштовно; Genius — $14,99 на місяць або $129 на рік. Доступний у вебі, на iPhone та Android.', 'Mindsera is a ''gym for the mind'' that combines journaling with mental models. You can write, dictate or scan entries from a paper journal; the AI companion asks questions for deeper reflection, analyses emotions, finds recurring topics and assesses personality using the Big Five model. There are 50+ thinking templates (first-principles thinking, ikigai and more), weekly reviews and habit tracking. Data is encrypted and not used for model training. Plans: Curious — free; Genius — $14.99 a month or $129 a year. It is available on the web, iPhone and Android.', 'Щоденник текстом, голосом чи скануванням
Аналіз емоцій і повторюваних тем
50+ ментальних моделей
Оцінка особистості (Велика п''ятірка)', 'Journal by text, voice or scan
Emotion and recurring-topic analysis
50+ mental models
Big Five personality insights', 'Люди, які ведуть щоденник і працюють над самопізнанням.', 'People who journal and work on self-reflection.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'mindsera.com' OR LOWER(`name`) = LOWER('Mindsera')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'mental-health' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI journal for clear thinking: it analyses emotions, detects recurring topics, offers 50+ mental model templates and assesses personality using the Big Five.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Mindsera is a ''gym for the mind'' that combines journaling with mental models. You can write, dictate or scan entries from a paper journal; the AI companion asks questions for deeper reflection, analyses emotions, finds recurring topics and assesses personality using the Big Five model. There are 50+ thinking templates (first-principles thinking, ikigai and more), weekly reviews and habit tracking. Data is encrypted and not used for model training. Plans: Curious — free; Genius — $14.99 a month or $129 a year. It is available on the web, iPhone and Android.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Journal by text, voice or scan
Emotion and recurring-topic analysis
50+ mental models
Big Five personality insights', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People who journal and work on self-reflection.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Curious', 'Curious', 0.00, 'free', 'Базовий щоденник, звички й шаблони', 'Basic journaling, habits and templates' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Curious' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Curious', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Basic journaling, habits and templates', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Genius', 'Genius', 14.99, 'month', 'Аналіз емоцій, голос, особистість; $129 на рік', 'Emotion analysis, voice, personality; $129 a year' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Genius' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Genius', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Emotion analysis, voice, personality; $129 a year', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Upheal — Інструменти для психологів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'upheal.io' OR LOWER(`name`) = LOWER('Upheal'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Upheal', NULL, 'https://www.upheal.io', NULL, NULL, 'AI-нотатки й електронна медкарта для психотерапевтів: автоматичні записи сесій, плани лікування, телетерапія та облік практики, відповідно до HIPAA.', 'AI progress notes and an EHR for therapists: automatic session notes, treatment plans, telehealth and practice management, HIPAA-compliant.', 'Upheal звільняє психотерапевтів від рутинної документації. AI створює клінічні нотатки з відео, аудіо, диктовки чи завантажених файлів, допомагає складати плани лікування з відстеженням прогресу та перевіряє нотатки на відповідність вимогам. Платформа також включає захищені відеосесії, розклад, клієнтський портал, повідомлення та роботу зі страхуванням. Тарифи: Free — базові AI-нотатки для індивідуальної терапії; AI Notes — $39 на місяць (необмежені нотатки, усі типи сесій, телетерапія); EHR — $1 за сесію; EHR Pro — $99 на місяць. Є 30-денна гарантія повернення коштів.', 'Upheal frees therapists from routine documentation. AI creates clinical notes from video, audio, dictation or uploaded files, helps build treatment plans with progress tracking and checks notes for compliance. The platform also includes secure video sessions, scheduling, a client portal, messaging and insurance billing. Plans: Free — basic AI notes for individual therapy; AI Notes — $39 a month (unlimited notes, all session types, telehealth); EHR — $1 per session; EHR Pro — $99 a month. There is a 30-day money-back guarantee.', 'AI-нотатки з запису чи диктовки
Плани лікування й відстеження прогресу
Телетерапія відповідно до HIPAA
Розклад, портал клієнта, страхування', 'AI notes from recordings or dictation
Treatment plans and progress tracking
HIPAA-compliant telehealth
Scheduling, client portal, insurance', 'Психотерапевти, психологи й консультанти в приватній практиці.', 'Therapists, psychologists and counsellors in private practice.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'upheal.io' OR LOWER(`name`) = LOWER('Upheal')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'psychologist-tools' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'AI progress notes and an EHR for therapists: automatic session notes, treatment plans, telehealth and practice management, HIPAA-compliant.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Upheal frees therapists from routine documentation. AI creates clinical notes from video, audio, dictation or uploaded files, helps build treatment plans with progress tracking and checks notes for compliance. The platform also includes secure video sessions, scheduling, a client portal, messaging and insurance billing. Plans: Free — basic AI notes for individual therapy; AI Notes — $39 a month (unlimited notes, all session types, telehealth); EHR — $1 per session; EHR Pro — $99 a month. There is a 30-day money-back guarantee.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI notes from recordings or dictation
Treatment plans and progress tracking
HIPAA-compliant telehealth
Scheduling, client portal, insurance', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Therapists, psychologists and counsellors in private practice.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Базові AI-нотатки для індивідуальної терапії', 'Basic AI notes for individual therapy' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Basic AI notes for individual therapy', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'AI Notes', 'AI Notes', 39.00, 'month', 'Необмежені нотатки, усі типи сесій, телетерапія', 'Unlimited notes, all session types, telehealth' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'AI Notes' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'AI Notes', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited notes, all session types, telehealth', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'EHR Pro', 'EHR Pro', 99.00, 'month', 'Повна медкарта з AI-асистентом Pro', 'Full EHR with AI Assistant Pro' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'EHR Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'EHR Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Full EHR with AI Assistant Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Mentalyc — Інструменти для психологів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'mentalyc.com' OR LOWER(`name`) = LOWER('Mentalyc'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Mentalyc', NULL, 'https://www.mentalyc.com', NULL, NULL, 'AI-документування для психотерапевтів: записує сесії й створює нотатки у форматах SOAP, DAP, BIRP, допомагає з планами лікування; HIPAA і SOC 2.', 'AI documentation for therapists: it records sessions and creates notes in SOAP, DAP and BIRP formats and helps with treatment plans; HIPAA and SOC 2.', 'Mentalyc записує або приймає аудіо сесії, транскрибує його й автоматично створює структуровані терапевтичні нотатки в потрібному форматі — SOAP, DAP, BIRP та інших. Платформа допомагає з планами лікування й відстеженням прогресу, а Alliance Genie дає інсайти щодо терапевтичного альянсу. Відповідає HIPAA, PHIPA та SOC 2. Тарифи (помісячно): Mini — $19,99 (40 нотаток); Basic — $39,99 (100); Pro — $69,99 (160); Super — $119,99 (330); Team — $59,99 за місце (необмежені нотатки). Є 14-денний пробний період без картки.', 'Mentalyc records or accepts session audio, transcribes it and automatically creates structured therapy notes in the format you need — SOAP, DAP, BIRP and others. It helps with treatment planning and progress tracking, and Alliance Genie provides insights into the therapeutic alliance. It is HIPAA, PHIPA and SOC 2 compliant. Monthly plans: Mini — $19.99 (40 notes); Basic — $39.99 (100); Pro — $69.99 (160); Super — $119.99 (330); Team — $59.99 per seat (unlimited notes). There is a 14-day free trial with no card.', 'Нотатки SOAP, DAP, BIRP з запису сесії
Плани лікування й прогрес
Інсайти щодо терапевтичного альянсу
HIPAA, PHIPA, SOC 2', 'SOAP, DAP and BIRP notes from session audio
Treatment plans and progress
Therapeutic alliance insights
HIPAA, PHIPA, SOC 2', 'Психотерапевти, клінічні психологи й соціальні працівники.', 'Therapists, clinical psychologists and social workers.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'mentalyc.com' OR LOWER(`name`) = LOWER('Mentalyc')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'psychologist-tools' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'AI documentation for therapists: it records sessions and creates notes in SOAP, DAP and BIRP formats and helps with treatment plans; HIPAA and SOC 2.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Mentalyc records or accepts session audio, transcribes it and automatically creates structured therapy notes in the format you need — SOAP, DAP, BIRP and others. It helps with treatment planning and progress tracking, and Alliance Genie provides insights into the therapeutic alliance. It is HIPAA, PHIPA and SOC 2 compliant. Monthly plans: Mini — $19.99 (40 notes); Basic — $39.99 (100); Pro — $69.99 (160); Super — $119.99 (330); Team — $59.99 per seat (unlimited notes). There is a 14-day free trial with no card.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'SOAP, DAP and BIRP notes from session audio
Treatment plans and progress
Therapeutic alliance insights
HIPAA, PHIPA, SOC 2', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Therapists, clinical psychologists and social workers.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Mini', 'Mini', 19.99, 'month', '40 нотаток на місяць', '40 notes a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Mini' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Mini', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '40 notes a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Basic', 'Basic', 39.99, 'month', '100 нотаток на місяць', '100 notes a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Basic' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Basic', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '100 notes a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 69.99, 'month', '160 нотаток на місяць', '160 notes a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '160 notes a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Blueprint — Інструменти для психологів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'blueprint.ai' OR LOWER(`name`) = LOWER('Blueprint'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Blueprint', NULL, 'https://www.blueprint.ai', NULL, NULL, 'AI-асистент для психотерапевтів: нотатки й плани лікування, листи клієнтам, підготовка до сесій, оплата й страхування; поруч з вашою EHR або як повна система.', 'An AI assistant for therapists: notes and treatment plans, client letters, session prep, billing and insurance; alongside your EHR or as a full system.', 'Blueprint допомагає фахівцям з ментального здоров''я в усій роботі практики: пише нотатки й плани лікування, клінічні листи та повідомлення клієнтам, готує до сесій і допомагає з консультуванням випадків, веде облік, страхування, маркетинг і запис клієнтів та відстежує результати терапії. Працює поруч із наявною електронною медкартою або як повноцінна система з вбудованим AI. Відповідає HIPAA і SOC 2 Type 2, аудіо видаляється після транскрипції. Ним користуються понад 70 000 фахівців. Можна почати безкоштовно; ціни — на сторінці тарифів.', 'Blueprint supports mental health professionals across their practice: it writes notes and treatment plans, clinical letters and client messages, prepares sessions and helps with case consultation, handles billing, insurance, marketing and scheduling, and tracks therapy outcomes. It works alongside your existing EHR or as a full system with AI built in. It is HIPAA and SOC 2 Type 2 compliant, and audio is deleted after transcription. More than 70,000 professionals use it. You can start for free; prices are on the pricing page.', 'Нотатки, плани лікування й листи
Підготовка до сесій
Облік, страхування й запис
HIPAA, SOC 2, видалення аудіо', 'Notes, treatment plans and letters
Session prep
Billing, insurance and scheduling
HIPAA, SOC 2, audio deletion', 'Психотерапевти та практики ментального здоров''я.', 'Therapists and mental health practices.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'blueprint.ai' OR LOWER(`name`) = LOWER('Blueprint')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'psychologist-tools' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI assistant for therapists: notes and treatment plans, client letters, session prep, billing and insurance; alongside your EHR or as a full system.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Blueprint supports mental health professionals across their practice: it writes notes and treatment plans, clinical letters and client messages, prepares sessions and helps with case consultation, handles billing, insurance, marketing and scheduling, and tracks therapy outcomes. It works alongside your existing EHR or as a full system with AI built in. It is HIPAA and SOC 2 Type 2 compliant, and audio is deleted after transcription. More than 70,000 professionals use it. You can start for free; prices are on the pricing page.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Notes, treatment plans and letters
Session prep
Billing, insurance and scheduling
HIPAA, SOC 2, audio deletion', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Therapists and mental health practices.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовний старт', 'Free to start', 0.00, 'free', 'Можна почати безкоштовно; ціни на сайті', 'Start for free; prices on the website' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Безкоштовний старт' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free to start', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Start for free; prices on the website', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Lyssn — Інструменти для психологів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'lyssn.io' OR LOWER(`name`) = LOWER('Lyssn'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Lyssn', NULL, 'https://www.lyssn.io', NULL, NULL, 'AI для якості й навчання в психологічній допомозі: аналізує записи сесій на відповідність доказовим методам і дає фахівцям зворотний зв''язок для розвитку навичок.', 'AI for quality and training in behavioural health: it analyses session recordings for fidelity to evidence-based practices and gives clinicians feedback to build their skills.', 'Lyssn використовує обробку природної мови, щоб оцінювати терапевтичні сесії та навчання фахівців. Платформа транскрибує сесії, оцінює їхню відповідність доказовим методам терапії та надає модулі розвитку навичок зі зворотним зв''язком у реальному часі, а керівники отримують звіти про якість роботи команди. Розробку засновано на 17 роках академічних досліджень, понад 4,5 млн проаналізованих сесій і понад 65 рецензованих публікаціях. Lyssn використовують понад 100 організацій — державні агенції, системи психологічної допомоги, кризові служби. Ціни — за запитом.', 'Lyssn uses natural language processing to evaluate therapy sessions and clinician training. The platform transcribes sessions, assesses their fidelity to evidence-based therapies and provides skill-building modules with real-time feedback, while managers get reports on team quality. It is grounded in 17 years of academic research, more than 4.5 million analysed sessions and 65+ peer-reviewed publications. More than 100 organisations use Lyssn — government agencies, behavioural health systems and crisis services. Pricing is on request.', 'Оцінка відповідності доказовим методам
Транскрипція сесій
Тренування навичок зі зворотним зв''язком
Звіти про якість роботи команди', 'Fidelity to evidence-based practices
Session transcription
Skill training with feedback
Team quality reports', 'Організації психологічної допомоги, супервізори й навчальні програми.', 'Behavioural health organisations, supervisors and training programmes.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'lyssn.io' OR LOWER(`name`) = LOWER('Lyssn')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'psychologist-tools' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'AI for quality and training in behavioural health: it analyses session recordings for fidelity to evidence-based practices and gives clinicians feedback to build their skills.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Lyssn uses natural language processing to evaluate therapy sessions and clinician training. The platform transcribes sessions, assesses their fidelity to evidence-based therapies and provides skill-building modules with real-time feedback, while managers get reports on team quality. It is grounded in 17 years of academic research, more than 4.5 million analysed sessions and 65+ peer-reviewed publications. More than 100 organisations use Lyssn — government agencies, behavioural health systems and crisis services. Pricing is on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Fidelity to evidence-based practices
Session transcription
Skill training with feedback
Team quality reports', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Behavioural health organisations, supervisors and training programmes.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ціна за запитом', 'Price on request', NULL, 'year', 'Для організацій', 'For organisations' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ціна за запитом' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Price on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'For organisations', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Limbic — Інструменти для психологів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'limbic.ai' OR LOWER(`name`) = LOWER('Limbic'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Limbic', NULL, 'https://www.limbic.ai', NULL, NULL, 'Клінічний AI для служб психологічної допомоги: агенти для первинного прийому, тріажу й терапії; єдиний чат-бот у сфері ментального здоров''я з класом IIa у Великій Британії.', 'Clinical AI for mental health services: intake, triage and therapy agents; the only mental health chatbot with UK Class IIa medical device certification.', 'Limbic допомагає службам психологічної допомоги приймати більше пацієнтів. Limbic Access проводить первинний прийом і оцінювання, Limbic Care — клінічний AI-компаньйон між сесіями, а агенти вбудовуються в маршрути направлення та клінічні процеси. Limbic має сертифікацію медичного виробу класу IIa у Великій Британії й використовується в службах NHS Talking Therapies, страхових планах і системах охорони здоров''я. Клієнти повідомляють про вдвічі вищі показники одужання, на 23% менше відсівання та коротші черги. Ціни — після демонстрації.', 'Limbic helps mental health services see more patients. Limbic Access handles intake and assessments, Limbic Care is a clinical AI companion between sessions, and agents embed into referral pathways and clinical workflows. Limbic holds UK Class IIa medical device certification and is used by NHS Talking Therapies services, health plans and health systems. Customers report twice the recovery rates, 23% lower dropout and shorter waits. Pricing is provided after a demo.', 'Первинний прийом і оцінювання (Limbic Access)
Клінічний AI-компаньйон (Limbic Care)
Медичний виріб класу IIa (Велика Британія)
Використовується в NHS Talking Therapies', 'Intake and assessment (Limbic Access)
Clinical AI companion (Limbic Care)
UK Class IIa medical device
Used in NHS Talking Therapies', 'Служби психологічної допомоги, клініки та страхові плани.', 'Mental health services, clinics and health plans.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'limbic.ai' OR LOWER(`name`) = LOWER('Limbic')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'psychologist-tools' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Clinical AI for mental health services: intake, triage and therapy agents; the only mental health chatbot with UK Class IIa medical device certification.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Limbic helps mental health services see more patients. Limbic Access handles intake and assessments, Limbic Care is a clinical AI companion between sessions, and agents embed into referral pathways and clinical workflows. Limbic holds UK Class IIa medical device certification and is used by NHS Talking Therapies services, health plans and health systems. Customers report twice the recovery rates, 23% lower dropout and shorter waits. Pricing is provided after a demo.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Intake and assessment (Limbic Access)
Clinical AI companion (Limbic Care)
UK Class IIa medical device
Used in NHS Talking Therapies', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Mental health services, clinics and health plans.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ціна за запитом', 'Price on request', NULL, 'year', 'Ціни після демонстрації', 'Pricing after a demo' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ціна за запитом' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Price on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Pricing after a demo', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

