SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Бізнес та маркетинг» → нова підкатегорія «HR і рекрутинг» — 5 нових продуктів, 0 прив'язок наявних
--   Kickresume — HR і рекрутинг
--   Rezi — HR і рекрутинг
--   Workable — HR і рекрутинг
--   Juicebox — HR і рекрутинг
--   Metaview — HR і рекрутинг
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'HR і рекрутинг', 'HR & Recruiting', 'hr-recruiting' FROM `categories` c WHERE c.`slug` = 'business-marketing' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Kickresume — HR і рекрутинг
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'kickresume.com' OR LOWER(`name`) = LOWER('Kickresume'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Kickresume', NULL, 'https://www.kickresume.com', NULL, NULL, 'AI-конструктор резюме, супровідних листів і персональних сайтів: 40+ шаблонів, AI-автор тексту, перевірка резюме на сумісність з ATS і карта кар''єри.', 'An AI builder for resumes, cover letters and personal websites: 40+ templates, an AI writer, an ATS resume checker and a career map.', 'Kickresume допомагає швидко скласти резюме та супровідний лист, які виглядають професійно й проходять автоматичні системи відбору (ATS). AI пише й покращує тексти розділів, перевірка ATS показує, що виправити, а Career Map підказує можливі кар''єрні кроки. Доступно понад 40 шаблонів резюме й листів, тисячі прикладів і готових формулювань, а також конструктор персонального сайту. Дані зберігаються в ЄС відповідно до GDPR. Тарифи: Free — базові шаблони; Premium — $24 на місяць, $18 на місяць при оплаті за квартал ($54) або $8 на місяць при річній оплаті ($96); діє 14-денна гарантія повернення коштів.', 'Kickresume helps you quickly put together a resume and cover letter that look professional and pass applicant tracking systems (ATS). AI writes and improves section text, the ATS checker shows what to fix and Career Map suggests possible career moves. There are 40+ resume and cover letter templates, thousands of examples and ready phrases, and a personal website builder. Data is hosted in the EU under GDPR. Plans: Free — basic templates; Premium — $24 a month, $18 a month billed quarterly ($54) or $8 a month billed yearly ($96); a 14-day money-back guarantee applies.', 'AI-автор резюме й супровідних листів
40+ шаблонів
Перевірка резюме для ATS
Карта кар''єри та персональний сайт', 'AI resume and cover letter writer
40+ templates
ATS resume checker
Career Map and personal website', 'Шукачі роботи, студенти й випускники, які хочуть швидко зробити сильне резюме англійською.', 'Job seekers, students and graduates who want to create a strong resume quickly.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'kickresume.com' OR LOWER(`name`) = LOWER('Kickresume')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'hr-recruiting' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI builder for resumes, cover letters and personal websites: 40+ templates, an AI writer, an ATS resume checker and a career map.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Kickresume helps you quickly put together a resume and cover letter that look professional and pass applicant tracking systems (ATS). AI writes and improves section text, the ATS checker shows what to fix and Career Map suggests possible career moves. There are 40+ resume and cover letter templates, thousands of examples and ready phrases, and a personal website builder. Data is hosted in the EU under GDPR. Plans: Free — basic templates; Premium — $24 a month, $18 a month billed quarterly ($54) or $8 a month billed yearly ($96); a 14-day money-back guarantee applies.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI resume and cover letter writer
40+ templates
ATS resume checker
Career Map and personal website', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Job seekers, students and graduates who want to create a strong resume quickly.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '4 базові шаблони, приклади й готові фрази', '4 basic templates, examples and pre-written phrases' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '4 basic templates, examples and pre-written phrases', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premium (місяць)', 'Premium (monthly)', 24.00, 'month', '40+ шаблонів, AI-автор, перевірка ATS', '40+ templates, AI writer, ATS checker' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Premium (місяць)' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Premium (monthly)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '40+ templates, AI writer, ATS checker', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premium (рік)', 'Premium (yearly)', 96.00, 'year', '≈$8 на місяць; усі функції Premium', '≈$8 a month; all Premium features' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Premium (рік)' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Premium (yearly)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '≈$8 a month; all Premium features', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Rezi — HR і рекрутинг
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'rezi.ai' OR LOWER(`name`) = LOWER('Rezi'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Rezi', NULL, 'https://www.rezi.ai', NULL, NULL, 'AI-конструктор резюме з підбором ключових слів під вакансію, перевіркою на сумісність з ATS і практикою співбесід.', 'An AI resume builder with keyword targeting for each job, ATS compatibility checks and interview practice.', 'Rezi допомагає створювати й адаптувати резюме під конкретні вакансії. AI пише пункти досвіду, підбирає ключові слова з опису вакансії та перевіряє, чи пройде резюме автоматичні системи відбору (ATS); є також AI-практика співбесід. За даними компанії, з 2019 року сервісом скористалися понад 4,5 млн шукачів роботи, а 62% із них отримують запрошення на співбесіду. Тарифи: Free — 1 резюме й обмежені AI-інструменти; Pro — $29 на місяць (необмежені резюме, повний доступ до AI, щомісячна експертна перевірка); Lifetime — $149 одноразово; для організацій — $99 на місяць за 200 користувачів. На всі тарифи діє 30-денна гарантія повернення коштів.', 'Rezi helps you create and tailor resumes for specific jobs. AI writes experience bullet points, picks keywords from the job description and checks whether the resume will pass applicant tracking systems (ATS); there is also AI interview practice. According to the company, more than 4.5 million job seekers have used it since 2019, and 62% of them land an interview. Plans: Free — 1 resume and limited AI tools; Pro — $29 a month (unlimited resumes, full AI access, a monthly expert review); Lifetime — $149 one-time; for organisations — $99 a month per 200 users. All plans have a 30-day money-back guarantee.', 'AI-тексти для пунктів досвіду
Ключові слова з опису вакансії
Перевірка на сумісність з ATS
Практика співбесід', 'AI-written experience bullet points
Keywords from the job description
ATS compatibility check
Interview practice', 'Шукачі роботи, які подаються на багато вакансій і хочуть адаптувати резюме під кожну.', 'Job seekers applying to many roles who want to tailor their resume to each one.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'rezi.ai' OR LOWER(`name`) = LOWER('Rezi')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'hr-recruiting' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI resume builder with keyword targeting for each job, ATS compatibility checks and interview practice.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Rezi helps you create and tailor resumes for specific jobs. AI writes experience bullet points, picks keywords from the job description and checks whether the resume will pass applicant tracking systems (ATS); there is also AI interview practice. According to the company, more than 4.5 million job seekers have used it since 2019, and 62% of them land an interview. Plans: Free — 1 resume and limited AI tools; Pro — $29 a month (unlimited resumes, full AI access, a monthly expert review); Lifetime — $149 one-time; for organisations — $99 a month per 200 users. All plans have a 30-day money-back guarantee.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI-written experience bullet points
Keywords from the job description
ATS compatibility check
Interview practice', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Job seekers applying to many roles who want to tailor their resume to each one.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '1 резюме, обмежені AI-інструменти, 3 завантаження PDF', '1 resume, limited AI tools, 3 PDF downloads' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '1 resume, limited AI tools, 3 PDF downloads', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 29.00, 'month', 'Необмежені резюме й AI, щомісячна експертна перевірка', 'Unlimited resumes and AI, a monthly expert review' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited resumes and AI, a monthly expert review', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Lifetime', 'Lifetime', 149.00, 'one_time', 'Довічний доступ до функцій Pro', 'Lifetime access to Pro features' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Lifetime' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Lifetime', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Lifetime access to Pro features', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Workable — HR і рекрутинг
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'workable.com' OR LOWER(`name`) = LOWER('Workable'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Workable', NULL, 'https://www.workable.com', NULL, NULL, 'Платформа для найму та HR з AI-агентом рекрутера: пошук кандидатів серед 400+ млн профілів, ATS, розміщення вакансій на 200+ сайтах і HR-система.', 'A hiring and HR platform with an AI recruiting agent: sourcing from 400M+ profiles, an ATS, posting to 200+ job boards and an HR system.', 'Workable об''єднує рекрутинг і HR в одній системі. Вакансії публікуються одразу на понад 200 сайтах, кандидатів можна шукати серед понад 400 млн профілів, а система відстеження кандидатів (ATS) допомагає вести відбір і планувати співбесіди. HR-частина охоплює онбординг, відпустки, підготовку до виплати зарплат, довідник працівників і оргструктуру. AI-агент Workable бере на себе частину роботи рекрутера й оплачується кредитами: кожен платний акаунт отримує 3 000 безкоштовних кредитів, далі $0,095–0,12 за кредит. Тарифи на місяць: Standard — $299 (до 20 працівників); Premier — $599; Enterprise — $719; при річній оплаті на 20% дешевше. Є 15-денний пробний період.', 'Workable combines recruiting and HR in one system. Jobs are posted to 200+ job boards at once, candidates can be sourced from 400M+ profiles, and the applicant tracking system (ATS) helps run the selection process and schedule interviews. The HR side covers onboarding, time off, payroll preparation, an employee directory and org charts. The Workable AI agent takes over part of the recruiter''s work and is paid for with credits: every paid account gets 3,000 free credits, then $0.095–0.12 per credit. Monthly plans: Standard — $299 (up to 20 employees); Premier — $599; Enterprise — $719; 20% cheaper billed annually. There is a 15-day free trial.', 'Публікація вакансій на 200+ сайтах
Пошук серед 400+ млн профілів
ATS і планування співбесід
HR-система: онбординг, відпустки
AI-агент рекрутера', 'Posting to 200+ job boards
Sourcing from 400M+ profiles
ATS and interview scheduling
HR system: onboarding, time off
AI recruiting agent', 'Малий і середній бізнес та HR-команди, які регулярно наймають людей.', 'Small and mid-sized businesses and HR teams that hire regularly.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'workable.com' OR LOWER(`name`) = LOWER('Workable')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'hr-recruiting' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A hiring and HR platform with an AI recruiting agent: sourcing from 400M+ profiles, an ATS, posting to 200+ job boards and an HR system.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Workable combines recruiting and HR in one system. Jobs are posted to 200+ job boards at once, candidates can be sourced from 400M+ profiles, and the applicant tracking system (ATS) helps run the selection process and schedule interviews. The HR side covers onboarding, time off, payroll preparation, an employee directory and org charts. The Workable AI agent takes over part of the recruiter''s work and is paid for with credits: every paid account gets 3,000 free credits, then $0.095–0.12 per credit. Monthly plans: Standard — $299 (up to 20 employees); Premier — $599; Enterprise — $719; 20% cheaper billed annually. There is a 15-day free trial.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Posting to 200+ job boards
Sourcing from 400M+ profiles
ATS and interview scheduling
HR system: onboarding, time off
AI recruiting agent', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Small and mid-sized businesses and HR teams that hire regularly.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Standard', 'Standard', 299.00, 'month', 'До 20 працівників; при річній оплаті на 20% дешевше', 'Up to 20 employees; 20% cheaper billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Standard' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Standard', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Up to 20 employees; 20% cheaper billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premier', 'Premier', 599.00, 'month', 'Для команд, що ростуть; SMS, відеоінтерв''ю й тести включено', 'For growing teams; texting, video interviews and assessments included' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Premier' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Premier', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'For growing teams; texting, video interviews and assessments included', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Enterprise', 'Enterprise', 719.00, 'month', 'Для великих організацій', 'For large organisations' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Enterprise' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Enterprise', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'For large organisations', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Juicebox — HR і рекрутинг
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'juicebox.ai' OR LOWER(`name`) = LOWER('Juicebox'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Juicebox', NULL, 'https://juicebox.ai', NULL, NULL, 'AI-пошук кандидатів PeopleGPT: знаходить людей серед 800+ млн профілів за запитом звичайною мовою, без булевих операторів, і автоматизує outreach.', 'PeopleGPT AI candidate search: it finds people among 800M+ profiles from a plain-language query, without Boolean strings, and automates outreach.', 'Juicebox допомагає рекрутерам шукати кандидатів так, ніби вони пишуть запит у чат. PeopleGPT шукає серед понад 800 млн профілів по всьому світу, ранжує кандидатів і знаходить контакти, а автоматизовані послідовності листів допомагають зв''язатися з ними. Juicebox Agents працюють цілодобово й самі ведуть пошук. Сервіс інтегрується з 41 ATS та 21 CRM, ним користуються понад 25 000 команд. Тарифи за місце на місяць: Free — обмежений пошук; Starter — $99 (необмежений пошук, 500 кредитів контактів); Growth — $179 (до 5 місць, 1 500 кредитів); Business — за запитом; агент — $199 на місяць.', 'Juicebox lets recruiters search for candidates as if they were typing into a chat. PeopleGPT searches more than 800M profiles worldwide, ranks candidates and finds contact details, while automated email sequences help reach out to them. Juicebox Agents work around the clock and run searches on their own. It integrates with 41 ATS and 21 CRM platforms and is used by more than 25,000 teams. Plans per seat a month: Free — limited searches; Starter — $99 (unlimited searches, 500 contact credits); Growth — $179 (up to 5 seats, 1,500 credits); Business on request; an agent costs $199 a month.', 'Пошук кандидатів звичайною мовою
800+ млн профілів
Ранжування й пошук контактів
Автоматизовані листи та агенти 24/7', 'Natural-language candidate search
800M+ profiles
Ranking and contact lookup
Automated outreach and 24/7 agents', 'Рекрутери, кадрові агенції й стартапи, які самі шукають кандидатів.', 'Recruiters, staffing agencies and startups that source candidates themselves.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'juicebox.ai' OR LOWER(`name`) = LOWER('Juicebox')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'hr-recruiting' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'PeopleGPT AI candidate search: it finds people among 800M+ profiles from a plain-language query, without Boolean strings, and automates outreach.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Juicebox lets recruiters search for candidates as if they were typing into a chat. PeopleGPT searches more than 800M profiles worldwide, ranks candidates and finds contact details, while automated email sequences help reach out to them. Juicebox Agents work around the clock and run searches on their own. It integrates with 41 ATS and 21 CRM platforms and is used by more than 25,000 teams. Plans per seat a month: Free — limited searches; Starter — $99 (unlimited searches, 500 contact credits); Growth — $179 (up to 5 seats, 1,500 credits); Business on request; an agent costs $199 a month.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Natural-language candidate search
800M+ profiles
Ranking and contact lookup
Automated outreach and 24/7 agents', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Recruiters, staffing agencies and startups that source candidates themselves.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Обмежений пошук, AI-шаблони листів', 'Limited searches, AI email templates' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Limited searches, AI email templates', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Starter', 'Starter', 99.00, 'month', 'За місце: необмежений пошук, 500 кредитів контактів', 'Per seat: unlimited searches, 500 contact credits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Starter' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Starter', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per seat: unlimited searches, 500 contact credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Growth', 'Growth', 179.00, 'month', 'За місце: до 5 місць, 1 500 кредитів контактів, аналітика талантів', 'Per seat: up to 5 seats, 1,500 contact credits, talent insights' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Growth' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Growth', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per seat: up to 5 seats, 1,500 contact credits, talent insights', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Metaview — HR і рекрутинг
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'metaview.ai' OR LOWER(`name`) = LOWER('Metaview'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Metaview', NULL, 'https://www.metaview.ai', NULL, NULL, 'AI-платформа для рекрутингу: автоматично веде нотатки співбесід, шукає кандидатів і переглядає заявки, а ще дає аналітику найму.', 'An AI recruiting platform: it takes interview notes automatically, sources candidates and reviews applications, and provides hiring analytics.', 'Metaview знімає з рекрутерів рутину. Під час співбесід AI веде нотатки й готує зведення для відгуку через 10–20 хвилин після розмови, агенти самостійно шукають кандидатів і переглядають заявки за налаштованими правилами, а профіль ідеального кандидата уточнюється на основі рішень команди. Платформа інтегрується з Ashby, Greenhouse, Lever та іншими ATS і дає аналітику процесу найму. Тарифи за користувача на місяць: Free — перші 100 профілів пошуку; Pro — $100 (200 профілів на місяць); Max — $300 (необмежений пошук); Enterprise — за запитом.', 'Metaview takes routine work off recruiters'' plates. During interviews AI takes notes and prepares a summary for feedback within 10–20 minutes of the conversation, agents source candidates and review applications on their own according to set rules, and the Ideal Candidate Profile is refined based on the team''s decisions. It integrates with Ashby, Greenhouse, Lever and other ATS and provides hiring analytics. Plans per user a month: Free — the first 100 sourced profiles; Pro — $100 (200 profiles a month); Max — $300 (unlimited sourcing); Enterprise on request.', 'Автоматичні нотатки співбесід
AI-пошук кандидатів і перегляд заявок
Профіль ідеального кандидата
Інтеграція з Ashby, Greenhouse, Lever', 'Automatic interview notes
AI candidate sourcing and application review
Ideal Candidate Profile
Ashby, Greenhouse and Lever integration', 'Рекрутери й команди найму в компаніях, які проводять багато співбесід.', 'Recruiters and hiring teams at companies that run many interviews.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'metaview.ai' OR LOWER(`name`) = LOWER('Metaview')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'hr-recruiting' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI recruiting platform: it takes interview notes automatically, sources candidates and reviews applications, and provides hiring analytics.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Metaview takes routine work off recruiters'' plates. During interviews AI takes notes and prepares a summary for feedback within 10–20 minutes of the conversation, agents source candidates and review applications on their own according to set rules, and the Ideal Candidate Profile is refined based on the team''s decisions. It integrates with Ashby, Greenhouse, Lever and other ATS and provides hiring analytics. Plans per user a month: Free — the first 100 sourced profiles; Pro — $100 (200 profiles a month); Max — $300 (unlimited sourcing); Enterprise on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Automatic interview notes
AI candidate sourcing and application review
Ideal Candidate Profile
Ashby, Greenhouse and Lever integration', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Recruiters and hiring teams at companies that run many interviews.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Перші 100 профілів пошуку безкоштовно', 'First 100 sourced profiles free' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'First 100 sourced profiles free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 100.00, 'month', 'За користувача: 200 профілів на місяць', 'Per user: 200 profiles a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per user: 200 profiles a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Max', 'Max', 300.00, 'month', 'За користувача: необмежений пошук', 'Per user: unlimited sourcing' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Max' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Max', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per user: unlimited sourcing', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

