SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Текст та Чат-боти» → нова підкатегорія «Сумаризатори» — 5 нових продуктів, 0 прив'язок наявних
--   Recall — Сумаризатори
--   QuillBot — Сумаризатори
--   Scholarcy — Сумаризатори
--   NoteGPT — Сумаризатори
--   Glasp — Сумаризатори
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Сумаризатори', 'Summarizers', 'summarizers' FROM `categories` c WHERE c.`slug` = 'text-chatbots' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Recall — Сумаризатори
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'recall.it' OR LOWER(`name`) = LOWER('Recall'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Recall', NULL, 'https://www.recall.it', NULL, NULL, 'AI-сумаризатор і особиста база знань: зберігає статті, відео й PDF, робить короткі підсумки, сам розкладає їх за тегами та нагадує повторити через квізи.', 'An AI summarizer and personal knowledge base: it saves articles, videos and PDFs, creates short summaries, organises them with tags and helps you review through quizzes.', 'Recall перетворює все, що ви читаєте й дивитеся, на впорядковану базу знань. Статті, відео та PDF зберігаються в один клік, AI робить підсумок, автоматично розставляє розумні теги та пов''язує нові матеріали з уже збереженими у візуальний граф знань. Можна спілкуватися з AI на основі власної бази, інтернету чи обох одразу, слухати матеріали в режимі озвучення, а квізи з інтервальним повторенням допомагають краще запам''ятати прочитане. Під час перегляду сайтів Recall підказує пов''язані нотатки. Сервісом користуються понад 700 000 людей. Тарифи: Free — 10 AI-підсумків на місяць; Plus — $10 на місяць при річній оплаті (необмежені підсумки, чат, озвучення, квізи); Max — $38 на місяць при річній оплаті (вибір моделі ChatGPT, Claude чи Gemini, особистий онбординг).', 'Recall turns everything you read and watch into an organised knowledge base. Articles, videos and PDFs are saved in one click, AI writes a summary, adds smart tags automatically and links new material to what you have already saved in a visual knowledge graph. You can chat with AI over your own knowledge base, the internet or both, listen to content with text-to-speech, and quizzes with spaced repetition help you remember what you read. While you browse, Recall surfaces related notes. More than 700,000 people use it. Plans: Free — 10 AI summaries a month; Plus — $10 a month billed yearly (unlimited summaries, chat, listen mode, quizzes); Max — $38 a month billed yearly (choice of ChatGPT, Claude or Gemini models, 1:1 onboarding).', 'Підсумки статей, відео й PDF в один клік
Автоматичні теги та граф знань
AI-чат з вашою базою та інтернетом
Квізи з інтервальним повторенням
Озвучення матеріалів', 'One-click summaries of articles, videos and PDFs
Automatic tags and a knowledge graph
AI chat with your knowledge base and the web
Quizzes with spaced repetition
Text-to-speech listen mode', 'Люди, які постійно навчаються: студенти, дослідники, фахівці, що читають і дивляться багато матеріалів.', 'Lifelong learners: students, researchers and professionals who read and watch a lot of material.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'recall.it' OR LOWER(`name`) = LOWER('Recall')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'summarizers' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI summarizer and personal knowledge base: it saves articles, videos and PDFs, creates short summaries, organises them with tags and helps you review through quizzes.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Recall turns everything you read and watch into an organised knowledge base. Articles, videos and PDFs are saved in one click, AI writes a summary, adds smart tags automatically and links new material to what you have already saved in a visual knowledge graph. You can chat with AI over your own knowledge base, the internet or both, listen to content with text-to-speech, and quizzes with spaced repetition help you remember what you read. While you browse, Recall surfaces related notes. More than 700,000 people use it. Plans: Free — 10 AI summaries a month; Plus — $10 a month billed yearly (unlimited summaries, chat, listen mode, quizzes); Max — $38 a month billed yearly (choice of ChatGPT, Claude or Gemini models, 1:1 onboarding).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'One-click summaries of articles, videos and PDFs
Automatic tags and a knowledge graph
AI chat with your knowledge base and the web
Quizzes with spaced repetition
Text-to-speech listen mode', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Lifelong learners: students, researchers and professionals who read and watch a lot of material.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '10 AI-підсумків на місяць, необмежені нотатки й збережений контент', '10 AI summaries a month, unlimited notes and saved content' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '10 AI summaries a month, unlimited notes and saved content', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Plus', 'Plus', 10.00, 'month', 'При річній оплаті: необмежені підсумки, AI-чат, озвучення, квізи', 'Billed yearly: unlimited summaries, AI chat, listen mode, quizzes' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Plus' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Plus', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Billed yearly: unlimited summaries, AI chat, listen mode, quizzes', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Max', 'Max', 38.00, 'month', 'При річній оплаті: вибір моделі (ChatGPT, Claude, Gemini), особистий онбординг', 'Billed yearly: choice of model (ChatGPT, Claude, Gemini), 1:1 onboarding' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Max' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Max', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Billed yearly: choice of model (ChatGPT, Claude, Gemini), 1:1 onboarding', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- QuillBot — Сумаризатори
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'quillbot.com' OR LOWER(`name`) = LOWER('QuillBot'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'QuillBot', NULL, 'https://quillbot.com', NULL, NULL, 'Набір AI-інструментів для тексту: сумаризатор, перефразування, перевірка граматики, AI-детектор і «гуманізатор», перекладач та генератор цитувань.', 'A suite of AI writing tools: summarizer, paraphraser, grammar checker, AI detector and humanizer, translator and citation generator.', 'QuillBot — один з найпопулярніших онлайн-помічників для роботи з текстом. Сумаризатор скорочує статті та документи до ключових пунктів або короткого абзацу, перефразувальник переписує речення в різних стилях, а перевірка граматики виправляє помилки. Є AI-детектор, «гуманізатор» тексту, перевірка на плагіат, перекладач і генератор цитувань. Інструменти працюють у вебі та як розширення для Chrome. Базові функції безкоштовні з лімітами; Premium знімає обмеження й відкриває всі режими, при річній оплаті — від $4,17 на місяць (ціна може залежати від регіону).', 'QuillBot is one of the most popular online helpers for working with text. The summarizer condenses articles and documents into key points or a short paragraph, the paraphraser rewrites sentences in different styles, and the grammar checker fixes mistakes. There is also an AI detector, a text humanizer, a plagiarism checker, a translator and a citation generator. The tools work on the web and as a Chrome extension. Core features are free with limits; Premium removes the limits and unlocks all modes, from $4.17 a month billed annually (prices may vary by region).', 'Сумаризатор: ключові пункти чи абзац
Перефразування в різних стилях
Граматика, плагіат і AI-детектор
Переклад і генератор цитувань
Розширення для Chrome', 'Summarizer: key points or a paragraph
Paraphrasing in different styles
Grammar, plagiarism and AI detection
Translator and citation generator
Chrome extension', 'Студенти, автори й усі, хто пише англійською та хоче швидше працювати з текстами.', 'Students, writers and anyone who writes in English and wants to work with text faster.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'quillbot.com' OR LOWER(`name`) = LOWER('QuillBot')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'summarizers' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A suite of AI writing tools: summarizer, paraphraser, grammar checker, AI detector and humanizer, translator and citation generator.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'QuillBot is one of the most popular online helpers for working with text. The summarizer condenses articles and documents into key points or a short paragraph, the paraphraser rewrites sentences in different styles, and the grammar checker fixes mistakes. There is also an AI detector, a text humanizer, a plagiarism checker, a translator and a citation generator. The tools work on the web and as a Chrome extension. Core features are free with limits; Premium removes the limits and unlocks all modes, from $4.17 a month billed annually (prices may vary by region).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Summarizer: key points or a paragraph
Paraphrasing in different styles
Grammar, plagiarism and AI detection
Translator and citation generator
Chrome extension', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Students, writers and anyone who writes in English and wants to work with text faster.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Базові інструменти з лімітами', 'Core tools with limits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Core tools with limits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premium', 'Premium', 4.17, 'month', 'При річній оплаті; без лімітів, усі режими (ціна може залежати від регіону)', 'Billed annually; no limits, all modes (price may vary by region)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Premium' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Premium', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Billed annually; no limits, all modes (price may vary by region)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Scholarcy — Сумаризатори
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'scholarcy.com' OR LOWER(`name`) = LOWER('Scholarcy'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Scholarcy', NULL, 'https://www.scholarcy.com', NULL, NULL, 'Сумаризатор наукових статей: перетворює дослідження на картки з ключовими висновками, допомагає вести нотатки, будувати матрицю літератури й бібліографію.', 'A research paper summarizer: it turns studies into flashcards with key findings and helps you take notes, build a literature matrix and bibliographies.', 'Scholarcy створено для тих, хто читає багато наукових текстів. Сервіс приймає статті у різних форматах і робить з них «картки-підсумки»: основні висновки, методи, результати, обмеження та посилання. Тексти можна виділяти, коментувати й редагувати, картки — групувати в колекції та експортувати, а з кількох статей — зібрати матрицю літератури для огляду. Бібліографія формується в один клік. Безкоштовна версія обмежена 10 підсумками; місячний план коштує $4,99 на місяць з тижневим безкоштовним періодом і дає необмежені розширені підсумки.', 'Scholarcy is built for people who read a lot of academic text. It takes papers in various formats and turns them into ''flashcard summaries'': key findings, methods, results, limitations and references. You can highlight, annotate and edit text, group flashcards into collections and export them, and build a literature matrix from several papers for a review. Bibliographies are generated in one click. The free version is limited to 10 summaries; the monthly plan costs $4.99 a month with a one-week free trial and gives unlimited enhanced summaries.', 'Картки-підсумки наукових статей
Нотатки, виділення й редагування тексту
Матриця літератури для оглядів
Бібліографія в один клік', 'Flashcard summaries of research papers
Notes, highlights and text editing
Literature matrix for reviews
One-click bibliographies', 'Студенти, магістранти й науковці, які готують огляди літератури.', 'Students, master''s students and researchers preparing literature reviews.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'scholarcy.com' OR LOWER(`name`) = LOWER('Scholarcy')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'summarizers' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A research paper summarizer: it turns studies into flashcards with key findings and helps you take notes, build a literature matrix and bibliographies.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Scholarcy is built for people who read a lot of academic text. It takes papers in various formats and turns them into ''flashcard summaries'': key findings, methods, results, limitations and references. You can highlight, annotate and edit text, group flashcards into collections and export them, and build a literature matrix from several papers for a review. Bibliographies are generated in one click. The free version is limited to 10 summaries; the monthly plan costs $4.99 a month with a one-week free trial and gives unlimited enhanced summaries.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Flashcard summaries of research papers
Notes, highlights and text editing
Literature matrix for reviews
One-click bibliographies', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Students, master''s students and researchers preparing literature reviews.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'До 10 підсумків, експорт карток по одній', 'Up to 10 summaries, export flashcards one at a time' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Up to 10 summaries, export flashcards one at a time', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Monthly', 'Monthly', 4.99, 'month', 'Необмежені розширені підсумки, колекції, матриця літератури; тиждень безкоштовно', 'Unlimited enhanced summaries, collections, literature matrix; 1-week free trial' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Monthly' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Monthly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited enhanced summaries, collections, literature matrix; 1-week free trial', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- NoteGPT — Сумаризатори
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'notegpt.io' OR LOWER(`name`) = LOWER('NoteGPT'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'NoteGPT', NULL, 'https://notegpt.io', NULL, NULL, 'AI-сумаризатор відео YouTube, аудіо, PDF і вебсторінок: робить конспекти, ментальні карти й транскрипції, а також генерує презентації, озвучення й зображення.', 'An AI summarizer for YouTube videos, audio, PDFs and web pages: it creates notes, mind maps and transcripts, and also generates slides, voice-overs and images.', 'NoteGPT починався як сумаризатор відео YouTube, а тепер це набір AI-інструментів для навчання й роботи з контентом. Він транскрибує відео й аудіо, робить стислі конспекти, ментальні карти та переклади, дає змогу спілкуватися з документом чи відео в чаті. Додатково є AI-презентації, генерація мовлення й подкастів, зображень і коротких відео, AI-детектор та «гуманізатор». Тарифи (при помісячній оплаті): Pro — $9,99, Unlimited — $29, Max — $99 на місяць; при річній оплаті дешевше, є освітні знижки.', 'NoteGPT started as a YouTube video summarizer and is now a suite of AI tools for studying and working with content. It transcribes video and audio, creates concise notes, mind maps and translations, and lets you chat with a document or video. It also offers AI slides, speech and podcast generation, image and short video generation, an AI detector and a humanizer. Plans (billed monthly): Pro at $9.99, Unlimited at $29 and Max at $99 a month; annual billing is cheaper and education discounts are available.', 'Підсумки відео YouTube, аудіо, PDF і сайтів
Транскрипція, конспекти й ментальні карти
Чат з документом чи відео
AI-презентації, озвучення й зображення', 'Summaries of YouTube videos, audio, PDFs and websites
Transcription, notes and mind maps
Chat with a document or video
AI slides, voice-overs and images', 'Студенти й люди, які навчаються з відео та довгих документів.', 'Students and people who learn from videos and long documents.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'notegpt.io' OR LOWER(`name`) = LOWER('NoteGPT')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'summarizers' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI summarizer for YouTube videos, audio, PDFs and web pages: it creates notes, mind maps and transcripts, and also generates slides, voice-overs and images.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'NoteGPT started as a YouTube video summarizer and is now a suite of AI tools for studying and working with content. It transcribes video and audio, creates concise notes, mind maps and translations, and lets you chat with a document or video. It also offers AI slides, speech and podcast generation, image and short video generation, an AI detector and a humanizer. Plans (billed monthly): Pro at $9.99, Unlimited at $29 and Max at $99 a month; annual billing is cheaper and education discounts are available.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Summaries of YouTube videos, audio, PDFs and websites
Transcription, notes and mind maps
Chat with a document or video
AI slides, voice-overs and images', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Students and people who learn from videos and long documents.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 9.99, 'month', 'Базовий платний план; при річній оплаті $108 на рік', 'Entry paid plan; $108 a year billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Entry paid plan; $108 a year billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Unlimited', 'Unlimited', 29.00, 'month', 'Необмежені базові квоти; при річній оплаті $239–348 на рік', 'Unlimited basic quotas; $239–348 a year billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Unlimited' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Unlimited', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited basic quotas; $239–348 a year billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Max', 'Max', 99.00, 'month', '10 000 преміальних кредитів на місяць, комерційне використання', '10,000 premium credits a month, commercial use' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Max' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Max', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '10,000 premium credits a month, commercial use', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Glasp — Сумаризатори
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'glasp.co' OR LOWER(`name`) = LOWER('Glasp'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Glasp', NULL, 'https://glasp.co', NULL, NULL, 'Розширення для виділення цитат на сайтах і AI-підсумків відео YouTube та PDF, з експортом у Notion і публічною бібліотекою виділень.', 'An extension for highlighting quotes on websites and creating AI summaries of YouTube videos and PDFs, with export to Notion and a public library of highlights.', 'Glasp — інструмент для тих, хто багато читає в інтернеті. Він дає змогу виділяти й коментувати текст на будь-якому сайті, зберігати виділення в особистій чи публічній бібліотеці та бачити, що виділяють інші читачі. AI робить підсумки відео YouTube, PDF-файлів і аудіозаписів, відстежує нові відео на обраних каналах і дає змогу спілкуватися з контентом сторінки чи відео. Виділення щодня синхронізуються з Notion. Безкоштовний план: 3 базові підсумки YouTube на день, 30 PDF, 30 хвилин аудіо на місяць; Pro — $15 на місяць або $150 на рік (необмежені базові підсумки, 1 000 розширених підсумків на місяць, приватні виділення).', 'Glasp is a tool for people who read a lot online. It lets you highlight and annotate text on any website, keep highlights in a personal or public library and see what other readers highlight. AI summarises YouTube videos, PDF files and audio recordings, tracks new videos on chosen channels and lets you chat with the content of a page or video. Highlights sync to Notion daily. The free plan includes 3 basic YouTube summaries a day, 30 PDFs and 30 minutes of audio a month; Pro costs $15 a month or $150 a year (unlimited basic summaries, 1,000 advanced summaries a month, private highlights).', 'Виділення й нотатки на будь-якому сайті
AI-підсумки YouTube, PDF і аудіо
Відстеження каналів YouTube
Синхронізація з Notion', 'Highlights and notes on any website
AI summaries of YouTube, PDFs and audio
YouTube channel tracking
Sync to Notion', 'Читачі, студенти й дослідники, які збирають цитати та нотатки з інтернету.', 'Readers, students and researchers who collect quotes and notes from the web.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'glasp.co' OR LOWER(`name`) = LOWER('Glasp')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'summarizers' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An extension for highlighting quotes on websites and creating AI summaries of YouTube videos and PDFs, with export to Notion and a public library of highlights.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Glasp is a tool for people who read a lot online. It lets you highlight and annotate text on any website, keep highlights in a personal or public library and see what other readers highlight. AI summarises YouTube videos, PDF files and audio recordings, tracks new videos on chosen channels and lets you chat with the content of a page or video. Highlights sync to Notion daily. The free plan includes 3 basic YouTube summaries a day, 30 PDFs and 30 minutes of audio a month; Pro costs $15 a month or $150 a year (unlimited basic summaries, 1,000 advanced summaries a month, private highlights).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Highlights and notes on any website
AI summaries of YouTube, PDFs and audio
YouTube channel tracking
Sync to Notion', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Readers, students and researchers who collect quotes and notes from the web.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '3 базові підсумки YouTube на день, 30 PDF, 30 хв аудіо на місяць', '3 basic YouTube summaries a day, 30 PDFs, 30 min of audio a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '3 basic YouTube summaries a day, 30 PDFs, 30 min of audio a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 15.00, 'month', '$150 на рік при річній оплаті; 1 000 розширених підсумків на місяць, приватні виділення', '$150 a year billed annually; 1,000 advanced summaries a month, private highlights' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '$150 a year billed annually; 1,000 advanced summaries a month, private highlights', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

