SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Здоров'я та краса» → реабілітація й масаж — 7 продуктів
--   Sword Health — Здоров'я та краса › Реабілітація та фізіотерапія
--   Kemtai — Здоров'я та краса › Реабілітація та фізіотерапія
--   Exer Health — Здоров'я та краса › Реабілітація та фізіотерапія
--   Flok Health — Здоров'я та краса › Реабілітація та фізіотерапія
--   Aescape — Здоров'я та краса › Масаж і відновлення
--   Therabot — Здоров'я та краса › Масаж і відновлення
--   Therabody — Здоров'я та краса › Масаж і відновлення
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): вкладка «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT());
-- продукт додається лише якщо немає продукту з тим самим нормалізованим URL АБО назвою; наявному лише додаються
-- категорія й підкатегорія. Id тарифів шукаються за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Реабілітація та фізіотерапія', 'Rehabilitation & Physiotherapy', 'rehabilitation-physiotherapy' FROM `categories` c WHERE c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Масаж і відновлення', 'Massage & Recovery', 'massage-recovery' FROM `categories` c WHERE c.`slug` = 'health-beauty' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Sword Health — Здоров'я та краса › Реабілітація та фізіотерапія
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'swordhealth.com' OR LOWER(`name`) = LOWER('Sword Health'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Sword Health', NULL, 'https://swordhealth.com', NULL, NULL, 'Цифрова фізіотерапія вдома: AI-асистент Phoenix веде сесію вправ, слухає, як ви почуваєтесь, і на ходу змінює складність, а фізичний терапевт стежить за прогресом дистанційно.', 'Digital physical therapy at home: the Phoenix AI assistant guides your exercise session, listens to how you feel and adjusts difficulty on the fly, while a physical therapist monitors progress remotely.', 'Sword Health — платформа цифрової допомоги при болю в суглобах, спині та м''язах. Основна програма Thrive поєднує вправи вдома з датчиками руху й планшетом, AI-асистента Phoenix і живого фізичного терапевта. Phoenix супроводжує сесію: з ним можна говорити, він дає зворотний зв''язок щодо техніки та в реальному часі змінює складність і тривалість вправ. Терапевт переглядає результати й коригує план. Крім реабілітації опорно-рухового апарату, компанія має програми для здоров''я тазового дна та інші напрями, а до компанії приєдналася Kaia Health. Доступ зазвичай надають роботодавці та страхові плани, часто без оплати для учасника; ціни для приватних осіб не опубліковано. Сервіс не замінює очного лікаря при гострій травмі.', 'Sword Health is a digital care platform for joint, back and muscle pain. Its core programme, Thrive, combines home exercise with motion sensors and a tablet, the Phoenix AI assistant and a real physical therapist. Phoenix guides each session: you can talk to it, it gives feedback on form and adjusts exercise difficulty and duration in real time. The therapist reviews results and adjusts the plan. Beyond musculoskeletal rehab, the company runs pelvic health and other programmes, and Kaia Health has joined the company. Access is usually provided by employers and health plans, often at no cost to the member; prices for individuals are not published. The service does not replace an in-person doctor for an acute injury.', 'AI-асистент Phoenix веде сесію й змінює складність у реальному часі
Датчики руху та планшет для вправ удома
Дистанційний супровід фізичного терапевта
Програми для спини, суглобів і тазового дна', 'Phoenix AI assistant guides sessions and adapts difficulty in real time
Motion sensors and a tablet for home exercise
Remote support from a physical therapist
Programmes for back, joints and pelvic health', 'Працівники й застраховані, яким роботодавець чи страховий план надає програму реабілітації при хронічному болю в спині й суглобах.', 'Employees and plan members whose employer or health plan offers a rehab programme for chronic back and joint pain.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'swordhealth.com' OR LOWER(`name`) = LOWER('Sword Health')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'rehabilitation-physiotherapy' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Digital physical therapy at home: the Phoenix AI assistant guides your exercise session, listens to how you feel and adjusts difficulty on the fly, while a physical therapist monitors progress remotely.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Sword Health is a digital care platform for joint, back and muscle pain. Its core programme, Thrive, combines home exercise with motion sensors and a tablet, the Phoenix AI assistant and a real physical therapist. Phoenix guides each session: you can talk to it, it gives feedback on form and adjusts exercise difficulty and duration in real time. The therapist reviews results and adjusts the plan. Beyond musculoskeletal rehab, the company runs pelvic health and other programmes, and Kaia Health has joined the company. Access is usually provided by employers and health plans, often at no cost to the member; prices for individuals are not published. The service does not replace an in-person doctor for an acute injury.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Phoenix AI assistant guides sessions and adapts difficulty in real time
Motion sensors and a tablet for home exercise
Remote support from a physical therapist
Programmes for back, joints and pelvic health', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Employees and plan members whose employer or health plan offers a rehab programme for chronic back and joint pain.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ціна за запитом', 'Price on request', NULL, 'month', 'Через роботодавця чи страховий план, часто без оплати для учасника; деталі — swordhealth.com', 'Through an employer or health plan, often at no cost to the member; details at swordhealth.com' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ціна за запитом' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Price on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Through an employer or health plan, often at no cost to the member; details at swordhealth.com', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Kemtai — Здоров'я та краса › Реабілітація та фізіотерапія
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'kemtai.com' OR LOWER(`name`) = LOWER('Kemtai'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Kemtai', NULL, 'https://www.kemtai.com', NULL, NULL, 'Відстеження рухів через звичайну камеру для фізіотерапії: аналізує 111 точок тіла й підказує, як виправити техніку вправи, без датчиків і без встановлення застосунку.', 'Motion tracking through an ordinary camera for physical therapy: it analyses 111 body points and cues you to correct exercise form, with no sensors and no app to install.', 'Kemtai — веб-платформа для фізіотерапії та тренувань із відстеженням рухів за допомогою комп''ютерного зору. Камера телефона, планшета чи ноутбука фіксує 111 точок на тілі пацієнта — суглоби, обертання, положення хребта, — а система в реальному часі дає голосові й візуальні підказки щодо техніки. Обробка відбувається на самому пристрої, без запису відео. Бібліотека містить понад 2000 варіантів вправ; клініцисти призначають програми та стежать за виконанням через Kemtai CARE, а цифрові сервіси можуть вбудувати технологію через API. Напрями — опорно-руховий апарат, неврологічна реабілітація, дистанційний терапевтичний моніторинг. Продукт орієнтований на клініки та компанії; ціни не опубліковано.', 'Kemtai is a web platform for physical therapy and fitness with computer-vision motion tracking. The camera of a phone, tablet or laptop tracks 111 points on the patient''s body — joints, rotations, spine position — and the system gives real-time audio and visual cues on form. Processing happens on the device itself, with no video recorded. The library has more than 2,000 exercise variations; clinicians assign programmes and monitor adherence in Kemtai CARE, and digital health services can embed the technology via API. Use cases include musculoskeletal care, neurological rehabilitation and remote therapeutic monitoring. The product targets clinics and companies; pricing is not published.', 'Відстеження 111 точок тіла через камеру без датчиків
Підказки щодо техніки в реальному часі
Понад 2000 варіантів вправ
Кабінет клініциста Kemtai CARE і API для інтеграції', 'Tracks 111 body points through a camera, no sensors
Real-time cues on exercise form
More than 2,000 exercise variations
Kemtai CARE clinician portal and an integration API', 'Фізіотерапевтичні клініки, лікарні та цифрові сервіси здоров''я, які ведуть пацієнтів на дистанційній реабілітації.', 'Physical therapy clinics, hospitals and digital health services that run remote rehabilitation for patients.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'kemtai.com' OR LOWER(`name`) = LOWER('Kemtai')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'rehabilitation-physiotherapy' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Motion tracking through an ordinary camera for physical therapy: it analyses 111 body points and cues you to correct exercise form, with no sensors and no app to install.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Kemtai is a web platform for physical therapy and fitness with computer-vision motion tracking. The camera of a phone, tablet or laptop tracks 111 points on the patient''s body — joints, rotations, spine position — and the system gives real-time audio and visual cues on form. Processing happens on the device itself, with no video recorded. The library has more than 2,000 exercise variations; clinicians assign programmes and monitor adherence in Kemtai CARE, and digital health services can embed the technology via API. Use cases include musculoskeletal care, neurological rehabilitation and remote therapeutic monitoring. The product targets clinics and companies; pricing is not published.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Tracks 111 body points through a camera, no sensors
Real-time cues on exercise form
More than 2,000 exercise variations
Kemtai CARE clinician portal and an integration API', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Physical therapy clinics, hospitals and digital health services that run remote rehabilitation for patients.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ціна за запитом', 'Price on request', NULL, 'month', 'Для клінік і компаній; вартість на сайті не опублікована — див. kemtai.com', 'For clinics and companies; pricing is not published — see kemtai.com' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ціна за запитом' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Price on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'For clinics and companies; pricing is not published — see kemtai.com', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Exer Health — Здоров'я та краса › Реабілітація та фізіотерапія
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'exer.ai' OR LOWER(`name`) = LOWER('Exer Health'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Exer Health', NULL, 'https://www.exer.ai', NULL, NULL, 'Клінічний AI для оцінки рухів: застосунок Exer Health стежить за технікою домашніх вправ через камеру, а Exer Scan вимірює рухливість суглобів на прийомі.', 'Clinical AI for movement assessment: the Exer Health app watches home-exercise form through the camera, and Exer Scan measures joint mobility at the clinic.', 'Exer AI розробляє програмне забезпечення для оцінки та супроводу пацієнтів із проблемами опорно-рухового апарату на основі комп''ютерного зору. Exer Health — застосунок для пацієнта: під час домашніх вправ він через камеру телефона чи планшета перевіряє техніку, дає підказки в реальному часі та фіксує, чи дотримується людина програми. Exer Scan використовують у клініці для об''єктивного вимірювання рухливості, окремі модулі охоплюють кисть і зап''ясток (Exer Hands) та аналіз ходи (Exer Gait, бета). Ні датчиків, ні носимих пристроїв не потрібно. Програмне забезпечення має статус медичного виробу класу II FDA та інтегрується з електронними медкартами. Напрями — ортопедія, неврологія, профілактика падінь у літніх людей, фізіотерапія. Продукт продається клінікам і страховим планам; ціни не опубліковано.', 'Exer AI builds computer-vision software to assess and support patients with musculoskeletal problems. Exer Health is the patient app: during home exercise it uses the phone or tablet camera to check form, gives real-time cues and records whether the person sticks to the programme. Exer Scan is used in the clinic for objective mobility measurement, and separate modules cover the hand and wrist (Exer Hands) and gait analysis (Exer Gait, beta). No sensors or wearables are needed. The software is an FDA Class II medical device and integrates with electronic health records. Use cases include orthopaedics, neurology, fall prevention in older adults and physical therapy. It is sold to clinics and health plans; pricing is not published.', 'Перевірка техніки домашніх вправ через камеру
Об''єктивне вимірювання рухливості в клініці (Exer Scan)
Модулі для кисті й зап''ястка та аналізу ходи
Медичний виріб класу II FDA, інтеграція з медкартами', 'Home-exercise form checks through the camera
Objective mobility measurement in the clinic (Exer Scan)
Modules for hand and wrist and gait analysis
FDA Class II medical device, EHR integration', 'Ортопедичні й фізіотерапевтичні клініки та їхні пацієнти, які виконують призначені вправи вдома.', 'Orthopaedic and physical therapy clinics and their patients who do prescribed exercises at home.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'exer.ai' OR LOWER(`name`) = LOWER('Exer Health')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'rehabilitation-physiotherapy' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Clinical AI for movement assessment: the Exer Health app watches home-exercise form through the camera, and Exer Scan measures joint mobility at the clinic.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Exer AI builds computer-vision software to assess and support patients with musculoskeletal problems. Exer Health is the patient app: during home exercise it uses the phone or tablet camera to check form, gives real-time cues and records whether the person sticks to the programme. Exer Scan is used in the clinic for objective mobility measurement, and separate modules cover the hand and wrist (Exer Hands) and gait analysis (Exer Gait, beta). No sensors or wearables are needed. The software is an FDA Class II medical device and integrates with electronic health records. Use cases include orthopaedics, neurology, fall prevention in older adults and physical therapy. It is sold to clinics and health plans; pricing is not published.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Home-exercise form checks through the camera
Objective mobility measurement in the clinic (Exer Scan)
Modules for hand and wrist and gait analysis
FDA Class II medical device, EHR integration', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Orthopaedic and physical therapy clinics and their patients who do prescribed exercises at home.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ціна за запитом', 'Price on request', NULL, 'month', 'Для клінік і страхових планів; вартість не опублікована — див. exer.ai', 'For clinics and health plans; pricing is not published — see exer.ai' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ціна за запитом' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Price on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'For clinics and health plans; pricing is not published — see exer.ai', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Flok Health — Здоров'я та краса › Реабілітація та фізіотерапія
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'flok.health' OR LOWER(`name`) = LOWER('Flok Health'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Flok Health', NULL, 'https://www.flok.health', NULL, NULL, 'AI-клініка фізіотерапії у застосунку: консультації 24/7 без черг, персональна програма вправ при болю в спині, коліні чи артрозі, з підтримкою живих фізіотерапевтів.', 'An AI physiotherapy clinic in an app: 24/7 appointments with no waiting lists and a personal exercise plan for back pain, knee pain or osteoarthritis, backed by human physiotherapists.', 'Flok Health позиціонує себе як перша у світі AI-клініка фізіотерапії. У застосунку пацієнт у будь-який час проходить консультацію з AI-фізіотерапевтом: той розпитує про симптоми, оцінює стан і складає програму вправ, а далі коригує її за результатами. Напрями — біль у спині та коліні, остеоартроз та інші проблеми опорно-рухового апарату. За потреби підключаються живі фізіотерапевти. У Великій Британії Flok має сертифікацію медичного виробу класу IIa та реєстрацію CQC як постачальник AI-допомоги, співпрацює з трастами NHS. Доступ надається через організації-партнери, які надсилають пацієнтам посилання; ціни не опубліковано.', 'Flok Health presents itself as the world''s first AI physiotherapy clinic. In the app a patient can see an AI physiotherapist at any time: it asks about symptoms, assesses the condition and builds an exercise programme, then adjusts it based on results. Areas covered include back and knee pain, osteoarthritis and other musculoskeletal problems. Human physiotherapists step in when needed. In the UK Flok holds Class IIa medical device certification and CQC registration as an AI care provider, and works with NHS trusts. Access is provided through partner organisations that send patients a link; pricing is not published.', 'Консультації з AI-фізіотерапевтом 24/7 без черг
Персональна програма вправ із коригуванням за результатами
Підтримка живих фізіотерапевтів
Медичний виріб класу IIa, реєстрація CQC (Велика Британія)', '24/7 AI physiotherapist appointments with no waiting lists
Personal exercise plan adjusted to your results
Support from human physiotherapists
Class IIa medical device, CQC-registered (UK)', 'Пацієнти з болем у спині, коліні чи остеоартрозом, які отримують доступ через NHS або іншу організацію-партнера.', 'Patients with back pain, knee pain or osteoarthritis who get access through the NHS or another partner organisation.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'flok.health' OR LOWER(`name`) = LOWER('Flok Health')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'rehabilitation-physiotherapy' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI physiotherapy clinic in an app: 24/7 appointments with no waiting lists and a personal exercise plan for back pain, knee pain or osteoarthritis, backed by human physiotherapists.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Flok Health presents itself as the world''s first AI physiotherapy clinic. In the app a patient can see an AI physiotherapist at any time: it asks about symptoms, assesses the condition and builds an exercise programme, then adjusts it based on results. Areas covered include back and knee pain, osteoarthritis and other musculoskeletal problems. Human physiotherapists step in when needed. In the UK Flok holds Class IIa medical device certification and CQC registration as an AI care provider, and works with NHS trusts. Access is provided through partner organisations that send patients a link; pricing is not published.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', '24/7 AI physiotherapist appointments with no waiting lists
Personal exercise plan adjusted to your results
Support from human physiotherapists
Class IIa medical device, CQC-registered (UK)', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Patients with back pain, knee pain or osteoarthritis who get access through the NHS or another partner organisation.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ціна за запитом', 'Price on request', NULL, 'month', 'Доступ через організації-партнери (зокрема NHS); вартість не опублікована — див. flok.health', 'Access through partner organisations (including the NHS); pricing is not published — see flok.health' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ціна за запитом' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Price on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Access through partner organisations (including the NHS); pricing is not published — see flok.health', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Aescape — Здоров'я та краса › Масаж і відновлення
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'aescape.com' OR LOWER(`name`) = LOWER('Aescape'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Aescape', NULL, 'https://www.aescape.com', NULL, NULL, 'Роботизований масаж з AI: система сканує тіло, будує його карту й виконує масаж двома роботизованими руками; тиск, музику й екран можна змінювати під час сесії.', 'AI robotic massage: the system scans your body, builds a body map and massages you with two robotic arms; pressure, music and visuals can be changed during the session.', 'Aescape — роботизований масаж на основі AI. На початку сесії система сканує тіло й будує його 3D-карту, щоб точно націлювати рухи двох роботизованих рук. Масаж виконується в одязі, без олії та підготовки. Під час сесії можна в реальному часі змінювати тиск, звук і зображення на екрані, а наступні сесії враховують попередні. Тривалість — 15, 30, 45 або 60 хвилин. Установки Aescape працюють у понад 140 партнерських локаціях у США — фітнес-клубах і спа; записатися можна через застосунок за містом, поштовим індексом чи назвою партнера. Пакети сесій: Reset — 3 сесії по 30 хв за $147, Recovery — 6 сесій по 45 хв за $414, Ritual — 12 сесій по 15 хв за $348 (на сайті часто діють знижки). Не замінює медичний масаж при травмі.', 'Aescape is AI-powered robotic massage. At the start of a session the system scans your body and builds a 3D body map so its two robotic arms can target movements precisely. The massage is done fully clothed, with no oil or preparation. During the session you can change pressure, audio and on-screen visuals in real time, and later sessions build on earlier ones. Sessions last 15, 30, 45 or 60 minutes. Aescape units operate at more than 140 partner locations in the US — gyms and spas — and you book through the app by city, ZIP code or partner name. Session packs: Reset — 3 × 30 min for $147, Recovery — 6 × 45 min for $414, Ritual — 12 × 15 min for $348 (the site often runs discounts). It does not replace medical massage after an injury.', '3D-сканування тіла й масаж двома роботизованими руками
Зміна тиску, звуку й зображення під час сесії
Сесії 15–60 хв, у одязі, без олії
Понад 140 локацій у США, запис через застосунок', '3D body scan and massage with two robotic arms
Adjust pressure, audio and visuals during the session
15–60 min sessions, fully clothed, no oil
140+ US locations, booking through the app', 'Відвідувачі фітнес-клубів і спа в США, які хочуть регулярний масаж для відновлення без запису до масажиста.', 'Gym and spa visitors in the US who want regular recovery massage without booking a therapist.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'aescape.com' OR LOWER(`name`) = LOWER('Aescape')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'massage-recovery' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'AI robotic massage: the system scans your body, builds a body map and massages you with two robotic arms; pressure, music and visuals can be changed during the session.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Aescape is AI-powered robotic massage. At the start of a session the system scans your body and builds a 3D body map so its two robotic arms can target movements precisely. The massage is done fully clothed, with no oil or preparation. During the session you can change pressure, audio and on-screen visuals in real time, and later sessions build on earlier ones. Sessions last 15, 30, 45 or 60 minutes. Aescape units operate at more than 140 partner locations in the US — gyms and spas — and you book through the app by city, ZIP code or partner name. Session packs: Reset — 3 × 30 min for $147, Recovery — 6 × 45 min for $414, Ritual — 12 × 15 min for $348 (the site often runs discounts). It does not replace medical massage after an injury.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', '3D body scan and massage with two robotic arms
Adjust pressure, audio and visuals during the session
15–60 min sessions, fully clothed, no oil
140+ US locations, booking through the app', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Gym and spa visitors in the US who want regular recovery massage without booking a therapist.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Reset', 'Reset', 147.00, 'one_time', '3 сесії по 30 хв (без знижок; на сайті часто діють акції)', '3 × 30 min sessions (list price; the site often runs discounts)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Reset' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Reset', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '3 × 30 min sessions (list price; the site often runs discounts)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Recovery', 'Recovery', 414.00, 'one_time', '6 сесій по 45 хв (без знижок)', '6 × 45 min sessions (list price)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Recovery' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Recovery', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '6 × 45 min sessions (list price)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ritual', 'Ritual', 348.00, 'one_time', '12 сесій по 15 хв (без знижок)', '12 × 15 min sessions (list price)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ritual' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Ritual', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '12 × 15 min sessions (list price)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Therabot — Здоров'я та краса › Масаж і відновлення
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'therabot.com' OR LOWER(`name`) = LOWER('Therabot'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Therabot', NULL, 'https://therabot.com', NULL, NULL, 'Роботизований масажер для ніг, що сам рухається вздовж ноги, з AI-терапевтом у застосунку: описуєте голосом чи текстом, що болить, і він складає програму масажу.', 'A robotic leg massager that moves along your leg by itself, with an AI therapist in the app: describe what hurts by voice or text and it builds a massage programme.', 'Therabot — носимий роботизований масажер для ніг. Пристрій надягають на ногу, і він сам рухається вздовж неї, масажуючи трьома роликами — це втричі більше покриття, ніж у масажного ролика. У застосунку працює AI-терапевт: досить написати чи сказати, наприклад, «глибше попрацюй з литкою, легше біля щиколотки», і він складе персональну програму, а під час сесії змінить інтенсивність за голосовою командою. Є чотири режими масажу та змінні ролики; тиск — до 18 фунтів у моделі Core і до 25 фунтів у Max, батарея — 1,5 та 3 години відповідно. Пристрій зараз на передзамовленні: ціна від $499 до $699 залежно від моделі, перші 1000 пристроїв почнуть відвантажувати 6 жовтня 2026 року. У застосунку є платна підписка Pro з фірмовими програмами.', 'Therabot is a wearable robotic leg massager. You put it on your leg and it moves along the limb by itself, massaging with three rollers — three times the coverage of a foam roller. The app includes an AI therapist: just type or say something like "deep work on my calf, easy on my ankle" and it builds a personal programme, then changes intensity mid-session on a voice command. There are four massage patterns and swappable rollers; pressure goes up to 18 lb on the Core model and 25 lb on the Max, with 1.5 and 3 hours of battery respectively. The device is on pre-order: $499 to $699 depending on the model, and the first 1,000 units begin shipping on 6 October 2026. The app has a paid Pro subscription with signature programmes.', 'Автоматичний масаж ніг трьома роликами
AI-терапевт складає програму за текстовим чи голосовим описом
Зміна інтенсивності голосом під час сесії
Чотири режими масажу та змінні ролики', 'Automatic leg massage with three rollers
AI therapist builds a programme from a text or voice description
Voice control of intensity during the session
Four massage patterns and swappable rollers', 'Спортсмени й активні люди, які хочуть відновлювати м''язи ніг удома без масажиста чи ручного масажного ролика.', 'Athletes and active people who want to recover leg muscles at home without a therapist or a manual foam roller.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'therabot.com' OR LOWER(`name`) = LOWER('Therabot')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'massage-recovery' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A robotic leg massager that moves along your leg by itself, with an AI therapist in the app: describe what hurts by voice or text and it builds a massage programme.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Therabot is a wearable robotic leg massager. You put it on your leg and it moves along the limb by itself, massaging with three rollers — three times the coverage of a foam roller. The app includes an AI therapist: just type or say something like "deep work on my calf, easy on my ankle" and it builds a personal programme, then changes intensity mid-session on a voice command. There are four massage patterns and swappable rollers; pressure goes up to 18 lb on the Core model and 25 lb on the Max, with 1.5 and 3 hours of battery respectively. The device is on pre-order: $499 to $699 depending on the model, and the first 1,000 units begin shipping on 6 October 2026. The app has a paid Pro subscription with signature programmes.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Automatic leg massage with three rollers
AI therapist builds a programme from a text or voice description
Voice control of intensity during the session
Four massage patterns and swappable rollers', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Athletes and active people who want to recover leg muscles at home without a therapist or a manual foam roller.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Передзамовлення', 'Pre-order', 499.00, 'one_time', 'Від $499 до $699 залежно від моделі (Core / Max); відвантаження з 6 жовтня 2026', '$499 to $699 depending on the model (Core / Max); shipping from 6 October 2026' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Передзамовлення' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pre-order', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '$499 to $699 depending on the model (Core / Max); shipping from 6 October 2026', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Therabody — Здоров'я та краса › Масаж і відновлення
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'therabody.com' OR LOWER(`name`) = LOWER('Therabody'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Therabody', NULL, 'https://www.therabody.com', NULL, NULL, 'Застосунок до масажних пістолетів Theragun з безкоштовним AI-тренером Coach: складає персональний план відновлення за вашими цілями та даними з Garmin, Apple Health чи Strava.', 'The companion app for Theragun massage guns with the free AI Coach: it builds a personal recovery plan from your goals and data from Garmin, Apple Health or Strava.', 'Therabody — виробник масажних пістолетів Theragun та інших пристроїв для відновлення. У безкоштовному застосунку Therabody працює Coach — AI-функція, яка складає персональний план відновлення на основі ваших цілей, болючих зон, щоденної активності та наукових даних. Coach підключається до Garmin, Apple Health, Strava і Google Health Connect, протягом дня коригує план під фактичні навантаження та надсилає рекомендації. Застосунок пропонує готові програми від спортивних фахівців і фіксує сесії — тип терапії, тривалість, швидкість; окремі моделі (PRO Plus, Prime Plus, Sense, Mini 3-го покоління) записують сесії офлайн і синхронізують їх пізніше. Застосунок і Coach безкоштовні для iOS та Android, але для масажу потрібен власний пристрій Theragun, який купується окремо.', 'Therabody makes Theragun massage guns and other recovery devices. The free Therabody app includes Coach, an AI feature that builds a personal recovery plan from your goals, sore areas, daily activity and the latest research. Coach connects to Garmin, Apple Health, Strava and Google Health Connect, adjusts the plan through the day to your actual training load and sends recommendations. The app offers routines designed by sports scientists and logs sessions — therapy type, length and speed; some models (PRO Plus, Prime Plus, Sense, Mini 3rd Gen) record sessions offline and sync them later. The app and Coach are free on iOS and Android, but massage requires your own Theragun device, bought separately.', 'AI-тренер Coach з персональним планом відновлення
Синхронізація з Garmin, Apple Health, Strava, Google Health Connect
Готові програми від спортивних фахівців
Запис сесій масажу, зокрема офлайн на окремих моделях', 'AI Coach with a personal recovery plan
Sync with Garmin, Apple Health, Strava and Google Health Connect
Routines designed by sports scientists
Massage session logging, including offline on some models', 'Власники масажних пістолетів Theragun, спортсмени й люди, які регулярно тренуються та хочуть системно відновлюватися.', 'Theragun owners, athletes and people who train regularly and want a structured recovery routine.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'therabody.com' OR LOWER(`name`) = LOWER('Therabody')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'massage-recovery' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'The companion app for Theragun massage guns with the free AI Coach: it builds a personal recovery plan from your goals and data from Garmin, Apple Health or Strava.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Therabody makes Theragun massage guns and other recovery devices. The free Therabody app includes Coach, an AI feature that builds a personal recovery plan from your goals, sore areas, daily activity and the latest research. Coach connects to Garmin, Apple Health, Strava and Google Health Connect, adjusts the plan through the day to your actual training load and sends recommendations. The app offers routines designed by sports scientists and logs sessions — therapy type, length and speed; some models (PRO Plus, Prime Plus, Sense, Mini 3rd Gen) record sessions offline and sync them later. The app and Coach are free on iOS and Android, but massage requires your own Theragun device, bought separately.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI Coach with a personal recovery plan
Sync with Garmin, Apple Health, Strava and Google Health Connect
Routines designed by sports scientists
Massage session logging, including offline on some models', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Theragun owners, athletes and people who train regularly and want a structured recovery routine.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовно', 'Free', 0.00, 'free', 'Застосунок і AI-тренер Coach безкоштовні; пристрій Theragun купується окремо', 'The app and AI Coach are free; a Theragun device is bought separately' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Безкоштовно' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'The app and AI Coach are free; a Theragun device is bought separately', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
