SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Розробка та IT» → «Конструктори сайтів»; «Продуктивність» → «Управління проєктами» — 4 нових продуктів, 14 прив'язок наявних
--   Durable — Конструктори сайтів
--   Hostinger Website Builder — Конструктори сайтів
--   Squarespace — Конструктори сайтів
--   Jira — Управління проєктами
--   (наявний) Framer → Конструктори сайтів
--   (наявний) Wix → Конструктори сайтів
--   (наявний) Webflow → Конструктори сайтів
--   (наявний) Relume → Конструктори сайтів
--   (наявний) Lovable → Конструктори сайтів
--   (наявний) Asana → Управління проєктами
--   (наявний) ClickUp → Управління проєктами
--   (наявний) monday.com → Управління проєктами
--   (наявний) Linear → Управління проєктами
--   (наявний) Trello → Управління проєктами
--   (наявний) Wrike → Управління проєктами
--   (наявний) Taskade → Управління проєктами
--   (наявний) Notion AI → Управління проєктами
--   (наявний) Motion → Управління проєктами
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Конструктори сайтів', 'Website Builders', 'website-builders' FROM `categories` c WHERE c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Управління проєктами', 'Project Management', 'project-management' FROM `categories` c WHERE c.`slug` = 'productivity' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Durable — Конструктори сайтів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'durable.com' OR LOWER(`name`) = LOWER('Durable'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Durable', NULL, 'https://durable.com', NULL, NULL, 'AI-конструктор сайтів для малого бізнесу: створює сайт за 30 секунд, а також дає CRM, онлайн-бронювання, SEO та AI-агентів для блогу й лідів.', 'An AI website builder for small businesses: it creates a site in 30 seconds and also provides a CRM, online booking, SEO and AI agents for blogging and leads.', 'Durable допомагає підприємцям запустити сайт без дизайнера й програміста: досить описати бізнес — і AI за кілька секунд згенерує сайт з текстами й зображеннями, який потім можна редагувати. Окрім сайту, в одному місці є проста CRM, онлайн-бронювання, SEO-налаштування, AI-чат і агенти, що пишуть статті для блогу й допомагають збирати ліди. Власний домен безкоштовний з будь-якою підпискою. Сервісом користуються понад 3 млн компаній. Тарифи: Free — сайт на піддомені, 5 AI-зображень і 10 AI-повідомлень на місяць; Launch — $22 на місяць ($187 на рік); Grow — $41 на місяць ($348 на рік, необмежена команда, щоденні публікації в блозі).', 'Durable helps entrepreneurs launch a website without a designer or developer: describe your business and AI generates a site with text and images in seconds, which you can then edit. Besides the site, it offers a simple CRM, online booking, SEO settings, AI chat and agents that write blog posts and help capture leads, all in one place. A custom domain is free with any subscription. More than 3 million businesses use it. Plans: Free — a site on a subdomain, 5 AI images and 10 AI messages a month; Launch — $22 a month ($187 a year); Grow — $41 a month ($348 a year, unlimited team, daily blog publishing).', 'Сайт з AI за 30 секунд
CRM і онлайн-бронювання
SEO та AI-агенти для блогу й лідів
Безкоштовний власний домен', 'An AI-built site in 30 seconds
CRM and online booking
SEO and AI agents for blog and leads
Free custom domain', 'Малий бізнес, самозайняті й сервісні компанії, яким потрібен сайт швидко й недорого.', 'Small businesses, sole traders and service companies that need a website quickly and affordably.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'durable.com' OR LOWER(`name`) = LOWER('Durable')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'website-builders' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI website builder for small businesses: it creates a site in 30 seconds and also provides a CRM, online booking, SEO and AI agents for blogging and leads.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Durable helps entrepreneurs launch a website without a designer or developer: describe your business and AI generates a site with text and images in seconds, which you can then edit. Besides the site, it offers a simple CRM, online booking, SEO settings, AI chat and agents that write blog posts and help capture leads, all in one place. A custom domain is free with any subscription. More than 3 million businesses use it. Plans: Free — a site on a subdomain, 5 AI images and 10 AI messages a month; Launch — $22 a month ($187 a year); Grow — $41 a month ($348 a year, unlimited team, daily blog publishing).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'An AI-built site in 30 seconds
CRM and online booking
SEO and AI agents for blog and leads
Free custom domain', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Small businesses, sole traders and service companies that need a website quickly and affordably.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Сайт на піддомені, 5 AI-зображень і 10 AI-повідомлень на місяць', 'Site on a subdomain, 5 AI images and 10 AI messages a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Site on a subdomain, 5 AI images and 10 AI messages a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Launch', 'Launch', 22.00, 'month', 'Власний домен, 50 зображень, бронювання, SEO; $187 на рік', 'Custom domain, 50 images, bookings, SEO; $187 a year' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Launch' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Launch', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Custom domain, 50 images, bookings, SEO; $187 a year', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Grow', 'Grow', 41.00, 'month', 'Необмежена команда, 500 зображень, необмежений AI-чат; $348 на рік', 'Unlimited team, 500 images, unlimited AI chat; $348 a year' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Grow' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Grow', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited team, 500 images, unlimited AI chat; $348 a year', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Hostinger Website Builder — Конструктори сайтів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'hostinger.com/ai-website-builder' OR LOWER(`name`) = LOWER('Hostinger Website Builder'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Hostinger Website Builder', NULL, 'https://www.hostinger.com/ai-website-builder', NULL, NULL, 'AI-конструктор сайтів від Hostinger з хостингом, доменом і поштою: AI генерує сайт за описом, а агентний режим будує інтернет-магазини й застосунки в діалозі.', 'Hostinger''s AI website builder with hosting, a domain and email: AI generates a site from a description, and agentic mode builds stores and apps through conversation.', 'Конструктор сайтів Hostinger поєднує AI-генерацію з хостингом. У звичайному режимі AI миттєво створює сайт за вашим описом, і його можна доопрацювати перетягуванням блоків; агентний режим («vibe coding») дає змогу в діалозі будувати складніші проєкти — інтернет-магазини, сайти з підпискою, інтерактивні застосунки. До пакета входять хостинг, SSL, безкоштовний домен на перший рік (на довгих тарифах), поштові скриньки, понад 400 шаблонів, SEO-інструменти й AI для текстів, а продаж в інтернет-магазині без комісії. Акційні ціни при оплаті на 48 місяців: Premium — $2,99 на місяць (до 3 сайтів); Unlimited — $3,99 (необмежені сайти); Cloud Startup — $7,99 на місяць.', 'Hostinger''s website builder combines AI generation with hosting. In standard mode AI instantly creates a site from your description, which you can refine with drag-and-drop; agentic mode (''vibe coding'') lets you build more complex projects — online stores, membership sites and interactive apps — through conversation. The package includes hosting, SSL, a free domain for the first year (on longer plans), email mailboxes, 400+ templates, SEO tools and AI writing, with 0% transaction fees for online stores. Promotional prices on 48-month plans: Premium — $2.99 a month (up to 3 sites); Unlimited — $3.99 (unlimited sites); Cloud Startup — $7.99 a month.', 'Сайт з AI за описом
Агентний режим для магазинів і застосунків
Хостинг, SSL, домен і пошта в пакеті
400+ шаблонів і SEO-інструменти', 'AI site from a description
Agentic mode for stores and apps
Hosting, SSL, domain and email included
400+ templates and SEO tools', 'Підприємці, блогери й малий бізнес, які хочуть сайт разом із хостингом за низьку ціну.', 'Entrepreneurs, bloggers and small businesses that want a site with hosting at a low price.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'hostinger.com/ai-website-builder' OR LOWER(`name`) = LOWER('Hostinger Website Builder')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'website-builders' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Hostinger''s AI website builder with hosting, a domain and email: AI generates a site from a description, and agentic mode builds stores and apps through conversation.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Hostinger''s website builder combines AI generation with hosting. In standard mode AI instantly creates a site from your description, which you can refine with drag-and-drop; agentic mode (''vibe coding'') lets you build more complex projects — online stores, membership sites and interactive apps — through conversation. The package includes hosting, SSL, a free domain for the first year (on longer plans), email mailboxes, 400+ templates, SEO tools and AI writing, with 0% transaction fees for online stores. Promotional prices on 48-month plans: Premium — $2.99 a month (up to 3 sites); Unlimited — $3.99 (unlimited sites); Cloud Startup — $7.99 a month.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI site from a description
Agentic mode for stores and apps
Hosting, SSL, domain and email included
400+ templates and SEO tools', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Entrepreneurs, bloggers and small businesses that want a site with hosting at a low price.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premium', 'Premium', 2.99, 'month', 'Акційна ціна при оплаті на 48 міс.; до 3 сайтів, 5 AI-кредитів', 'Promo price on a 48-month plan; up to 3 sites, 5 AI credits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Premium' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Premium', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Promo price on a 48-month plan; up to 3 sites, 5 AI credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Unlimited', 'Unlimited', 3.99, 'month', 'Акційна ціна при оплаті на 48 міс.; необмежені сайти, 15 AI-кредитів', 'Promo price on a 48-month plan; unlimited sites, 15 AI credits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Unlimited' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Unlimited', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Promo price on a 48-month plan; unlimited sites, 15 AI credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Cloud Startup', 'Cloud Startup', 7.99, 'month', 'Акційна ціна при оплаті на 48 міс.; хмарний хостинг, агент Hostinger', 'Promo price on a 48-month plan; cloud hosting, Hostinger agent' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Cloud Startup' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Cloud Startup', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Promo price on a 48-month plan; cloud hosting, Hostinger agent', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Squarespace — Конструктори сайтів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'squarespace.com' OR LOWER(`name`) = LOWER('Squarespace'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Squarespace', NULL, 'https://www.squarespace.com', NULL, NULL, 'Конструктор сайтів і інтернет-магазинів з дизайнерськими шаблонами та AI-інструментами для створення сайту й текстів; 14 днів безкоштовно.', 'A website and online store builder with designer templates and AI tools for building the site and writing copy; 14-day free trial.', 'Squarespace відомий охайними дизайнерськими шаблонами та простим редактором перетягування. AI допомагає швидко зібрати сайт і писати тексти, а платформа охоплює інтернет-магазин, членства, бронювання, блог і маркетингові інструменти. Сайти адаптовані під мобільні, трафік необмежений, підтримка працює цілодобово, а на річних тарифах домен перший рік безкоштовний. Тарифи (при річній оплаті / помісячно): Basic — $12 / $19 (комісія 2% з продажів, 10 разових AI-кредитів); Core — $17 / $27 (без комісії, 20 AI-кредитів на місяць, пошта Google Workspace на перший рік); Advanced — $25 / $36 (найнижчі комісії платежів, 120 AI-кредитів на місяць). Кожен сайт починається з 14-денного пробного періоду.', 'Squarespace is known for polished designer templates and a simple drag-and-drop editor. AI helps you assemble a site quickly and write copy, and the platform covers online stores, memberships, bookings, blogging and marketing tools. Sites are mobile-optimised, bandwidth is unlimited, support is 24/7, and annual plans include a free domain for the first year. Plans (billed annually / monthly): Basic — $12 / $19 (2% transaction fee, 10 one-time AI credits); Core — $17 / $27 (0% transaction fee, 20 AI credits a month, Google Workspace email for the first year); Advanced — $25 / $36 (lowest payment processing fees, 120 AI credits a month). Every site starts with a 14-day free trial.', 'Дизайнерські шаблони й редактор перетягування
AI для створення сайту й текстів
Інтернет-магазин, членства, бронювання
Безкоштовний домен на рік (річні тарифи)', 'Designer templates and drag-and-drop editor
AI for building the site and writing copy
Online store, memberships, bookings
Free domain for a year (annual plans)', 'Креативні фахівці, малий бізнес і інтернет-магазини, яким важливий вигляд сайту.', 'Creatives, small businesses and online stores that care about how their site looks.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'squarespace.com' OR LOWER(`name`) = LOWER('Squarespace')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'website-builders' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A website and online store builder with designer templates and AI tools for building the site and writing copy; 14-day free trial.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Squarespace is known for polished designer templates and a simple drag-and-drop editor. AI helps you assemble a site quickly and write copy, and the platform covers online stores, memberships, bookings, blogging and marketing tools. Sites are mobile-optimised, bandwidth is unlimited, support is 24/7, and annual plans include a free domain for the first year. Plans (billed annually / monthly): Basic — $12 / $19 (2% transaction fee, 10 one-time AI credits); Core — $17 / $27 (0% transaction fee, 20 AI credits a month, Google Workspace email for the first year); Advanced — $25 / $36 (lowest payment processing fees, 120 AI credits a month). Every site starts with a 14-day free trial.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Designer templates and drag-and-drop editor
AI for building the site and writing copy
Online store, memberships, bookings
Free domain for a year (annual plans)', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Creatives, small businesses and online stores that care about how their site looks.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Basic', 'Basic', 12.00, 'month', 'При річній оплаті ($19 помісячно), комісія 2% з продажів', 'Billed annually ($19 monthly), 2% transaction fee' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Basic' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Basic', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Billed annually ($19 monthly), 2% transaction fee', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Core', 'Core', 17.00, 'month', 'При річній оплаті ($27 помісячно), без комісії, 20 AI-кредитів на місяць', 'Billed annually ($27 monthly), 0% transaction fee, 20 AI credits a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Core' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Core', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Billed annually ($27 monthly), 0% transaction fee, 20 AI credits a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Advanced', 'Advanced', 25.00, 'month', 'При річній оплаті ($36 помісячно), 120 AI-кредитів на місяць', 'Billed annually ($36 monthly), 120 AI credits a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Advanced' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Advanced', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Billed annually ($36 monthly), 120 AI credits a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Jira — Управління проєктами
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'atlassian.com/software/jira' OR LOWER(`name`) = LOWER('Jira'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Jira', NULL, 'https://www.atlassian.com/software/jira', NULL, NULL, 'Система управління проєктами й задачами від Atlassian з AI Rovo: пошук, чат і агенти, що розуміють вашу роботу, плюс автоматизації.', 'Atlassian''s project and work management system with Rovo AI: search, chat and agents that understand your work, plus automations.', 'Jira — один із найпоширеніших інструментів для планування й відстеження роботи команд, від розробки ПЗ до маркетингу та операцій. Задачі ведуться на дошках, у списках, таймлайнах і спринтах, а автоматизації беруть на себе рутинні дії. У всі платні тарифи вбудовано Atlassian Rovo — AI-пошук, чат і агентів, які розуміють контекст ваших проєктів, а також AI-функції в самих задачах. Тарифи за користувача на місяць: Free — до невеликої команди безкоштовно; Standard — $7,91 (400 кроків автоматизації, 25 кредитів Rovo); Premium — $14,54 (750 кроків, 70 кредитів Rovo); Enterprise — за запитом.', 'Jira is one of the most widely used tools for planning and tracking team work, from software development to marketing and operations. Work is managed on boards, lists, timelines and sprints, and automations take care of routine actions. All paid plans include Atlassian Rovo — AI search, chat and agents that understand the context of your projects — plus AI features inside work items. Plans per user a month: Free — free for small teams; Standard — $7.91 (400 automation steps, 25 Rovo credits); Premium — $14.54 (750 automation steps, 70 Rovo credits); Enterprise on request.', 'Дошки, списки, таймлайни й спринти
AI Rovo: пошук, чат і агенти
Автоматизації рутинних дій
Інтеграції з екосистемою Atlassian', 'Boards, lists, timelines and sprints
Rovo AI: search, chat and agents
Automation of routine actions
Atlassian ecosystem integrations', 'Команди розробки, продукту, маркетингу й операцій у компаніях будь-якого розміру.', 'Software, product, marketing and operations teams at companies of any size.', 'web,mobile,desktop', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'atlassian.com/software/jira' OR LOWER(`name`) = LOWER('Jira')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'project-management' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Atlassian''s project and work management system with Rovo AI: search, chat and agents that understand your work, plus automations.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Jira is one of the most widely used tools for planning and tracking team work, from software development to marketing and operations. Work is managed on boards, lists, timelines and sprints, and automations take care of routine actions. All paid plans include Atlassian Rovo — AI search, chat and agents that understand the context of your projects — plus AI features inside work items. Plans per user a month: Free — free for small teams; Standard — $7.91 (400 automation steps, 25 Rovo credits); Premium — $14.54 (750 automation steps, 70 Rovo credits); Enterprise on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Boards, lists, timelines and sprints
Rovo AI: search, chat and agents
Automation of routine actions
Atlassian ecosystem integrations', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Software, product, marketing and operations teams at companies of any size.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Безкоштовно для невеликих команд', 'Free for small teams' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Free for small teams', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Standard', 'Standard', 7.91, 'month', 'За користувача: 400 кроків автоматизації, 25 кредитів Rovo', 'Per user: 400 automation steps, 25 Rovo credits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Standard' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Standard', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per user: 400 automation steps, 25 Rovo credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premium', 'Premium', 14.54, 'month', 'За користувача: 750 кроків автоматизації, 70 кредитів Rovo', 'Per user: 750 automation steps, 70 Rovo credits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Premium' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Premium', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per user: 750 automation steps, 70 Rovo credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Framer')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'website-builders' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Wix')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'website-builders' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Webflow')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'website-builders' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Relume')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'website-builders' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Lovable')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'website-builders' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Asana')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'project-management' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('ClickUp')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'project-management' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('monday.com')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'project-management' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Linear')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'project-management' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Trello')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'project-management' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Wrike')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'project-management' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Taskade')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'project-management' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Notion AI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'project-management' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Motion')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'project-management' LIMIT 1;
