SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-09-25: «Дизайн та креатив» — 35 продуктів, що були лише в локальній БД
-- (на ailabhub-directory.com їх не було: product.php?id=N → «Продукт не знайдено»). 81 тарифів.
-- Підкатегорії: Візуалізація даних, Аналіз даних, Звіти, Кольори, UI/UX.
--   Tableau — Дизайн та креатив / Аналіз даних, Дизайн та креатив / Візуалізація даних
--   Microsoft Power BI — Дизайн та креатив / Візуалізація даних, Дизайн та креатив / Звіти
--   Google Looker Studio — Дизайн та креатив / Візуалізація даних, Дизайн та креатив / Звіти
--   Metabase — Дизайн та креатив / Аналіз даних, Дизайн та креатив / Візуалізація даних
--   Microsoft Excel — Дизайн та креатив / Аналіз даних, Дизайн та креатив / Звіти
--   Coolors — Дизайн та креатив / Кольори
--   Huemint — Дизайн та креатив / Кольори
--   Colormind — Дизайн та креатив / Кольори
--   Muzli AI Colors — Дизайн та креатив / Кольори
--   ColorMagic — Дизайн та креатив / Кольори
--   Palette.fm — Дизайн та креатив / Кольори
--   Adobe Color — Дизайн та креатив / Кольори
--   ColorKit — Дизайн та креатив / Кольори
--   Uizard — Дизайн та креатив / UI/UX
--   Visily — Дизайн та креатив / UI/UX
--   Relume — Дизайн та креатив / UI/UX
--   v0 — Дизайн та креатив / UI/UX
--   Builder.io — Дизайн та креатив / UI/UX
--   Anima — Дизайн та креатив / UI/UX
--   Locofy — Дизайн та креатив / UI/UX
--   TeleportHQ — Дизайн та креатив / UI/UX
--   Polymer — Дизайн та креатив / Аналіз даних, Дизайн та креатив / Візуалізація даних
--   Hex — Дизайн та креатив / Аналіз даних
--   Deepnote — Дизайн та креатив / Аналіз даних
--   Rows — Дизайн та креатив / Аналіз даних, Дизайн та креатив / Візуалізація даних
--   Better Analyst — Дизайн та креатив / Аналіз даних
--   Sigma Computing — Дизайн та креатив / Аналіз даних
--   Count — Дизайн та креатив / Аналіз даних
--   Klipfolio — Дизайн та креатив / Звіти
--   Whatagraph — Дизайн та креатив / Звіти
--   Supermetrics — Дизайн та креатив / Звіти
--   Zoho Analytics — Дизайн та креатив / Звіти
--   Geckoboard — Дизайн та креатив / Звіти
--   Grow (Grow Data Platform) — Дизайн та креатив / Звіти
--   ReportGarden — Дизайн та креатив / Звіти
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): вкладка SQL (або Імпорт) → цей файл → Вперёд.
-- БЕЗ ФІКСОВАНИХ id: продукт додається, лише якщо продукту з таким самим нормалізованим URL ще немає;
-- його id береться через @pid, категорії/підкатегорії — за slug. Тарифи — лише для щойно доданого продукту.
-- Безпечно повторювати; жодних DROP / DELETE / перестворення таблиць. created_by не переноситься (NULL).
-- Автопереклади (product_translations, pricing_plan_translations; усі source = auto) не переносяться —
-- сайт згенерує їх заново при першому показі англійською.
-- =====================================================================

-- Tableau
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Tableau', NULL, 'https://tableau.com', NULL, NULL, 'Один із найвідоміших інструментів візуалізації даних — перетворює складні таблиці на наочні, інтерактивні дашборди методом перетягування елементів.', NULL, 'Tableau дозволяє підключитись до практично будь-якого джерела даних (бази даних, таблиці, хмарні сховища) і побудувати наочні інтерактивні дашборди без написання коду, методом перетягування елементів. Вважається золотим стандартом якості візуалізації даних у галузі, з дуже гнучким контролем над дизайном графіків. Тепер частина Salesforce, з AI-функціями Tableau Pulse для розмовної аналітики.', NULL, 'Побудова інтерактивних дашбордів без коду\nПідключення до практично будь-якого джерела даних\nГнучкий контроль над дизайном візуалізацій\nAI-розмовна аналітика (Tableau Pulse)', NULL, 'Аналітики даних, команди звітності, компанії, що потребують якісної візуалізації складних даних', NULL, 'web,desktop', 'course', 'published', '0', 'found', '2026-09-05 06:57:02' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'tableau.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'tableau.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-analysis';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-visualization';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Viewer', NULL, '15.00', 'month', 'лише перегляд готових дашбордів', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Explorer', NULL, '42.00', 'month', 'взаємодія з дашбордами й базовий аналіз', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Creator', NULL, '75.00', 'month', 'повне створення дашбордів і аналіз', NULL FROM DUAL WHERE @new = 1;

-- Microsoft Power BI
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Microsoft Power BI', NULL, 'https://powerbi.microsoft.com', NULL, NULL, 'Один із найпопулярніших і найдоступніших інструментів бізнес-аналітики — глибока інтеграція з Microsoft 365 і вбудований AI-помічник Copilot.', NULL, 'Power BI перетворює дані з таблиць, баз даних і хмарних сервісів на інтерактивні звіти й дашборди. Особливо вигідний для компаній, що вже користуються Microsoft 365 — глибоко інтегрується з Excel, Teams і SharePoint. Вбудований Copilot дозволяє ставити запитання про дані звичайною мовою й отримувати готові візуалізації у відповідь.', NULL, 'Побудова інтерактивних звітів і дашбордів\nГлибока інтеграція з Excel, Teams, SharePoint\nAI-помічник Copilot для запитів звичайною мовою\nАвтоматичне оновлення даних за розкладом', NULL, 'Компанії будь-якого розміру, особливо ті, що вже користуються Microsoft 365', NULL, 'web,mobile,desktop', 'course', 'published', '0', 'found', '2026-09-05 06:57:02' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'powerbi.microsoft.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'powerbi.microsoft.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-visualization';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'reports';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Desktop', NULL, '0.00', 'free', 'локальне створення звітів без публікації', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', NULL, '14.00', 'month', 'публікація й спільний доступ до звітів', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premium Per User', NULL, '24.00', 'month', 'розширені AI-функції та обсяги даних', NULL FROM DUAL WHERE @new = 1;

-- Google Looker Studio
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Google Looker Studio', NULL, 'https://lookerstudio.google.com', NULL, NULL, 'Повністю безкоштовний інструмент візуалізації даних від Google — особливо зручний для тих, хто вже користується Google Analytics, Ads чи Sheets.', NULL, 'Google Looker Studio дозволяє перетворити дані з Google Analytics, Google Ads, Google Sheets, BigQuery та понад 800 інших джерел на наочні звіти й дашборди без коду. Базовий функціонал повністю безкоштовний і достатній для більшості малих команд і маркетологів. Особливо популярний вибір для тих, хто вже працює в екосистемі Google.', NULL, 'Підключення до Google Analytics, Ads, Sheets, BigQuery та 800+ інших джерел\nПобудова звітів і дашбордів без коду\nСпільний доступ і співавторство в реальному часі\nГотові шаблони звітів', NULL, 'Маркетологи, малі команди, будь-хто, хто вже працює з продуктами Google', NULL, 'web', 'basic', 'published', '0', 'no_partnership', '2026-09-05 06:57:02' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'lookerstudio.google.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'lookerstudio.google.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-visualization';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'reports';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', NULL, '0.00', 'free', 'необмежені звіти, 24 конектори Google', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', NULL, '9.00', 'month', 'розширена співпраця й адміністрування (за проєкт)', NULL FROM DUAL WHERE @new = 1;

-- Metabase
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Metabase', NULL, 'https://metabase.com', NULL, NULL, 'Безкоштовний відкритий інструмент для аналізу даних — дозволяє ставити запитання про дані звичайною мовою без знання SQL.', NULL, 'Metabase — відкритий інструмент бізнес-аналітики, що дозволяє неспеціалістам ставити запитання про дані звичайною мовою (наприклад \"скільки продажів було минулого місяця\") і отримувати готові графіки у відповідь, без потреби писати SQL-запити. Можна встановити на власний сервер безкоштовно, або скористатись хмарною версією.', NULL, 'Запитання про дані звичайною мовою без SQL\nПобудова дашбордів і графіків\nМожливість самостійного розміщення на власному сервері\nАвтоматичні сповіщення при зміні показників', NULL, 'Невеликі команди й компанії, що хочуть безкоштовну або недорогу альтернативу великим BI-платформам', NULL, 'web', 'basic', 'published', '0', 'no_partnership', '2026-09-05 06:57:02' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'metabase.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'metabase.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-analysis';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-visualization';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Open Source', NULL, '0.00', 'free', 'самостійне розміщення на власному сервері, повний функціонал', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Starter', NULL, '85.00', 'month', 'хмарна версія для невеликих команд', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', NULL, '500.00', 'month', 'розширені функції для команд середнього розміру', NULL FROM DUAL WHERE @new = 1;

-- Microsoft Excel
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Microsoft Excel', NULL, 'https://microsoft.com/microsoft-365/excel', NULL, NULL, 'Найпоширеніша у світі програма для роботи з таблицями й аналізу даних, тепер із вбудованим AI-помічником Copilot для формул і аналізу.', NULL, 'Microsoft Excel залишається найпоширенішим у світі інструментом для роботи з таблицями даних — розрахунки, зведені таблиці, графіки. AI-помічник Copilot всередині Excel допомагає писати складні формули звичайною мовою, автоматично аналізує дані й пропонує інсайти, яких людина могла не помітити. Базові навички Excel вважаються необхідним мінімумом у більшості офісних професій.', NULL, 'Розрахунки й формули для роботи з таблицями даних\nAI-помічник Copilot для формул звичайною мовою\nЗведені таблиці та графіки\nАвтоматичний аналіз даних з пропозицією інсайтів', NULL, 'Практично будь-яка професія, що працює з таблицями даних — від фінансів до маркетингу', NULL, 'web,mobile,desktop', 'basic', 'published', '0', 'found', '2026-09-05 06:57:02' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'microsoft.com/microsoft-365/excel');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'microsoft.com/microsoft-365/excel' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-analysis';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'reports';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Microsoft 365 Personal', NULL, '6.99', 'month', 'Excel разом з іншими застосунками Office', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Microsoft 365 Business', NULL, '12.50', 'month', 'для команд і компаній', NULL FROM DUAL WHERE @new = 1;

-- Coolors
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Coolors', NULL, 'https://coolors.co', NULL, NULL, 'Наддшвидкий генератор кольорових палітр — нова палітра за пробіл, понад 10 млн готових схем. Безкоштовно з обмеженнями, Pro — $3/міс.', NULL, 'Coolors дозволяє миттєво генерувати палітри клавішею пробіл, витягувати кольори із зображень, перевіряти контраст доступності та переглядати палітру на макетах.', NULL, 'Миттєва генерація палітри клавішею пробіл\nВитягування кольорів із завантажених зображень\nПеревірка контрасту для доступності\nAI Color Bot для розширеної генерації (Pro)', NULL, 'Дизайнери й розробники, яким потрібна швидка кольорова інспірація', NULL, 'web,mobile', 'none', 'published', '0', 'found', '2026-09-15 18:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'coolors.co');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'coolors.co' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'colors';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', NULL, '0.00', 'free', 'до 10 збережених палітр, 1 проєкт', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', NULL, '3.00', 'month', 'необмежені палітри й проєкти, Coolors AI', NULL FROM DUAL WHERE @new = 1;

-- Huemint
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Huemint', NULL, 'https://huemint.com', NULL, NULL, 'AI-генератор кольорових палітр на основі машинного навчання — одразу показує палітру на прикладах брендингу й дизайну. Повністю безкоштовний.', NULL, 'Huemint використовує ML-модель, щоб одразу застосовувати згенеровані кольори до зразків ілюстрацій, логотипів і макетів. Сильна сторона — генерація цілісних брендових кольорових систем.', NULL, 'Генерація палітр із застосуванням на прикладах дизайну\nФокус на брендових кольорових системах\nКонтроль контрасту між кольорами\nБез реєстрації й оплати', NULL, 'Дизайнери, що одразу хочуть бачити палітру в контексті реального макета', NULL, 'web', 'none', 'published', '0', 'no_partnership', '2026-09-15 18:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'huemint.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'huemint.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'colors';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовний', NULL, '0.00', 'free', 'повний доступ без реєстрації й оплати', NULL FROM DUAL WHERE @new = 1;

-- Colormind
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Colormind', NULL, 'http://colormind.io', NULL, NULL, 'AI-генератор палітр на основі глибокого навчання (GAN), тренований на палітрах з Adobe Color й Dribbble. Повністю безкоштовний.', NULL, 'Colormind щодня підвантажує нові датасети реальних палітр із фотографій, фільмів та мистецтва, а нейромережа-класифікатор оцінює естетичну привабливість результату. Є REST API.', NULL, 'Генерація палітр через GAN, треновану на реальних джерелах\nЩоденне оновлення датасетів для нової інспірації\nМожливість \"заблокувати\" окремі кольори при генерації\nБезкоштовний REST API для особистого використання', NULL, 'Дизайнери й розробники, що хочуть API для генерації палітр', NULL, 'web', 'none', 'published', '0', 'no_partnership', '2026-09-15 18:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'colormind.io');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'colormind.io' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'colors';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовний', NULL, '0.00', 'free', 'сайт і API для особистого використання', NULL FROM DUAL WHERE @new = 1;

-- Muzli AI Colors
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Muzli AI Colors', NULL, 'https://colors.muz.li', NULL, NULL, 'AI-генератор палітр від екосистеми Muzli — палітри за ключовим словом, настроєм чи базовим кольором з експортом у Figma/CSS/Tailwind. Повністю безкоштовний.', NULL, 'Muzli Colors дає доступ до тисяч трендових кольорових комбінацій, зібраних із реальних креативних проєктів, і генерує палітри за ключовим словом, настроєм, базовим кольором чи референсом.', NULL, 'Генерація палітр за ключовим словом чи настроєм\nТисячі трендових палітр зі спільноти\nЕкспорт у Figma, CSS, Tailwind\nПошук за базовим кольором чи референсом', NULL, 'Дизайнери, яким потрібні готові до впровадження палітри', NULL, 'web', 'none', 'published', '0', 'no_partnership', '2026-09-15 18:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'colors.muz.li');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'colors.muz.li' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'colors';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовний', NULL, '0.00', 'free', 'повний доступ до генератора й бібліотеки палітр', NULL FROM DUAL WHERE @new = 1;

-- ColorMagic
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'ColorMagic', NULL, 'https://colormagic.app', NULL, NULL, 'AI-генератор палітр на основі GPT — опиши настрій чи завантаж фото, отримай готову палітру. Безкоштовний план, Pro — $6/міс.', NULL, 'ColorMagic перетворює текстовий опис настрою або завантажене зображення на готову кольорову палітру за допомогою GPT-моделі. Дозволяє коригувати насиченість і яскравість, копіювати коди в HEX/RGB/HSL.', NULL, 'Генерація палітри за текстовим описом настрою (GPT)\nВитягування палітри із завантаженого фото\nКоригування насиченості, яскравості й відтінку\nБезкоштовний публічний API', NULL, 'Дизайнери й розробники, що хочуть палітру за словесним описом', NULL, 'web', 'none', 'published', '0', 'no_partnership', '2026-09-15 18:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'colormagic.app');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'colormagic.app' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'colors';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', NULL, '0.00', 'free', 'генерація за ключовим словом, витяг кольору з фото', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', NULL, '6.00', 'month', 'необмежена генерація палітр', NULL FROM DUAL WHERE @new = 1;

-- Palette.fm
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Palette.fm', NULL, 'https://palette.fm', NULL, NULL, 'AI-колоризація чорно-білих фотографій — понад 21 фільтр кольорових стилів. Пробний кредит безкоштовно, підписка від $6/міс.', NULL, 'Palette.fm використовує AI, щоб реалістично розфарбувати чорно-білі фотографії, пропонуючи 21+ фільтр кольорового стилю з можливістю тонкого налаштування відтінків.', NULL, 'AI-колоризація чорно-білих фото\nПонад 21 фільтр кольорового стилю\nНалаштування відтінків результату\nДо 10x швидша обробка на підписці', NULL, 'Фотографи й архіви, що відновлюють колір у старих знімках', NULL, 'web', 'none', 'published', '0', 'found', '2026-09-15 18:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'palette.fm');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'palette.fm' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'colors';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', NULL, '0.00', 'free', '1 пробний кредит без водяного знаку', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Підписка', NULL, '6.00', 'month', '480 кредитів на рік (оплата щорічна)', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Разовий пакет', NULL, '49.00', 'one_time', '75 кредитів, дійсні 2 роки', NULL FROM DUAL WHERE @new = 1;

-- Adobe Color
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Adobe Color', NULL, 'https://color.adobe.com', NULL, NULL, 'Безкоштовний інструмент Adobe для створення й дослідження кольорових палітр за правилами гармонії кольору. Глибша інтеграція — через підписку Creative Cloud.', NULL, 'Adobe Color дозволяє створювати палітри на кольоровому колесі за класичними правилами гармонії, витягувати кольори із зображень і досліджувати тренди спільноти.', NULL, 'Кольорове колесо з правилами гармонії\nВитягування палітри із зображення\nСпільнота й трендові палітри користувачів\nПряма інтеграція з Photoshop, Illustrator', NULL, 'Дизайнери в екосистемі Adobe, що добирають кольори для проєктів', NULL, 'web,mobile', 'none', 'published', '0', 'found', '2026-09-15 18:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'color.adobe.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'color.adobe.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'colors';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', NULL, '0.00', 'free', 'повний доступ до генератора палітр', NULL FROM DUAL WHERE @new = 1;

-- ColorKit
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'ColorKit', NULL, 'https://colorkit.co', NULL, NULL, 'Безкоштовна колекція інструментів для роботи з кольором — генератори палітр, градієнтів і конвертери кольорових кодів.', NULL, 'ColorKit — набір безкоштовних веб-утиліт для дизайнерів: генератори кольорових палітр і градієнтів, конвертер кодів, перевірка контрасту та бібліотека готових палітр для натхнення.', NULL, 'Генератор кольорових палітр і градієнтів\nКонвертер кольорових кодів HEX/RGB/HSL\nПеревірка контрасту доступності\nБібліотека готових палітр', NULL, 'Дизайнери й розробники, яким потрібен швидкий набір кольорових утиліт', NULL, 'web', 'none', 'published', '0', 'no_partnership', '2026-09-15 18:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'colorkit.co');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'colorkit.co' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'colors';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовний', NULL, '0.00', 'free', 'повний доступ до всіх інструментів', NULL FROM DUAL WHERE @new = 1;

-- Uizard
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Uizard', NULL, 'https://uizard.io', NULL, NULL, 'AI-платформа для UI-дизайну, вайрфреймів і прототипів — генерує дизайн з тексту через Autodesigner 2.0. Безкоштовно (3 генерації/міс), Pro від $12/міс.', NULL, 'Uizard дозволяє швидко перетворювати ідеї на інтерактивні дизайни через AI-двигун Autodesigner: сканер скріншотів і вайрфреймів, AI-асистент дизайну, теплові карти та експорт коду.', NULL, 'Autodesigner 2.0 — генерація дизайну з текстового промпту\nСканер скріншотів і вайрфреймів\nAI-асистент дизайну та теплові карти\nЕкспорт коду в React CSS, плагін для Figma', NULL, 'Дизайнери й не-дизайнери, що хочуть швидко перетворити ідею на дизайн', NULL, 'web', 'none', 'published', '0', 'no_partnership', '2026-09-15 19:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'uizard.io');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'uizard.io' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'ui-ux';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', NULL, '0.00', 'free', '3 AI-генерації/міс, 2 проєкти', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', NULL, '12.00', 'month', '500 AI-генерацій/міс (річна оплата)', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Business', NULL, '39.00', 'month', '5000 AI-генерацій/міс (річна оплата)', NULL FROM DUAL WHERE @new = 1;

-- Visily
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Visily', NULL, 'https://www.visily.ai', NULL, NULL, 'Колаборативна платформа для вайрфреймів, діаграм і прототипів з AI-генерацією за контекстом. Безкоштовний старт, Pro — $11/міс.', NULL, 'Visily дозволяє командам будь-якого рівня швидко створювати вайрфрейми, діаграми й інтерактивні прототипи, з імпортом/експортом у Figma, експортом коду та інтеграціями.', NULL, 'AI-генерація дизайну з урахуванням контексту\nВайрфреймінг і діаграми в реальному часі\nІмпорт/експорт у Figma, експорт коду\nІнтеграції з Notion, Jira, Slack', NULL, 'Команди, що швидко створюють вайрфрейми й прототипи спільно', NULL, 'web', 'none', 'published', '0', 'no_partnership', '2026-09-15 19:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'visily.ai');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'visily.ai' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'ui-ux';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Starter', NULL, '0.00', 'free', '300 AI-кредитів/міс, 2 дошки', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', NULL, '11.00', 'month', '3000 AI-кредитів/міс (річна оплата)', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Business', NULL, '29.00', 'month', '10000 AI-кредитів/міс, SAML SSO', NULL FROM DUAL WHERE @new = 1;

-- Relume
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Relume', NULL, 'https://www.relume.ai', NULL, NULL, 'AI-платформа для створення сайтів і дизайн-систем — генерує бриф, структуру сайту, вайрфрейми й дизайн. Безкоштовно назавжди, Pro від $14/міс.', NULL, 'Relume через спеціалізованих AI-агентів генерує повну структуру сайту й компоненти, з експортом у Figma, Webflow і React, та власним хостингом.', NULL, 'Генерація брифу, структури сайту й дизайну через AI-агентів\nПонад 1000 компонентів для Figma, Webflow, React\nБезкоштовний хостинг на власному піддомені\nSEO-налаштування (robots.txt, sitemap, JSON-LD)', NULL, 'Дизайнери й маркетологи, що швидко будують сайти й дизайн-системи', NULL, 'web', 'none', 'published', '0', 'found', '2026-09-15 19:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'relume.ai');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'relume.ai' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'ui-ux';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', NULL, '0.00', 'free', '30 компонентів, обмежений AI назавжди', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', NULL, '14.00', 'month', 'базове використання AI', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Team', NULL, '36.00', 'month', 'необмежений спільний доступ', NULL FROM DUAL WHERE @new = 1;

-- v0
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'v0', NULL, 'https://v0.app', NULL, NULL, 'AI-інструмент від Vercel для генерації коду та UI з опису — Design Mode для візуального редагування, деплой одразу на Vercel. Безкоштовний старт, Plus — $30/міс.', NULL, 'v0 генерує робочий UI-код із текстового промпту чи макета, дозволяє візуально редагувати результат у Design Mode, синхронізується з GitHub і деплоїться напряму на Vercel.', NULL, 'Генерація UI-коду з текстового опису\nDesign Mode — візуальне редагування згенерованого\nСинхронізація з GitHub, деплой на Vercel\nДоступ до кількох AI-моделей (за тарифом)', NULL, 'Розробники й дизайнери, що швидко переходять від ідеї до робочого UI', NULL, 'web,mobile', 'basic', 'published', '0', 'no_partnership', '2026-09-15 19:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'v0.app');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'v0.app' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'ui-ux';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', NULL, '0.00', 'free', '$5 кредитів/міс, 7 повідомлень/день', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Plus', NULL, '30.00', 'month', '$30 кредитів/міс, командний білінг', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Business', NULL, '100.00', 'month', 'пріоритетна підтримка', NULL FROM DUAL WHERE @new = 1;

-- Builder.io
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Builder.io', NULL, 'https://www.builder.io', NULL, NULL, 'AI-платформа для генерації коду й контенту — візуальний IDE з підтримкою дизайн-систем. Безкоштовно, Pro від $24/користувача/міс.', NULL, 'Builder.io поєднує візуальний IDE для генерації коду з AI-контрольованою CMS, підтримує інтеграції з GitHub/GitLab/Bitbucket, плагін для Figma й розширення для VS Code.', NULL, 'Візуальний IDE для генерації коду з урахуванням дизайн-системи\nAI-контрольована візуальна CMS\nПлагін Figma та розширення VS Code\nСпільна робота в реальному часі', NULL, 'Команди розробки й маркетингу, що прискорюють вихід продукту через AI', NULL, 'web', 'basic', 'published', '0', 'found', '2026-09-15 19:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'builder.io');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'builder.io' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'ui-ux';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', NULL, '0.00', 'free', 'до 5 користувачів, 60 кредитів/міс', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', NULL, '24.00', 'month', '500 кредитів/міс', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Team', NULL, '40.00', 'month', 'до 20 користувачів', NULL FROM DUAL WHERE @new = 1;

-- Anima
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Anima', NULL, 'https://www.animaapp.com', NULL, NULL, 'Платформа перетворення дизайну на код — з Figma, скріншотів сайтів чи AI-промпту в HTML/React/Vue. Безкоштовний старт, Enterprise від $500/міс.', NULL, 'Anima конвертує Figma-дизайни, живі сайти чи зображення на робочий код, з AI-агентом Buddy для допомоги в Figma та MCP-інтеграцією з Claude.', NULL, 'Figma в код (HTML, React, Vue)\nКлонування живих сайтів у редагований код\nAI-агент Buddy — копілот дизайну у Figma\nMCP-інтеграція з Claude та іншими AI-інструментами', NULL, 'Дизайнери й розробники, що перетворюють макети на робочий код', NULL, 'web,desktop', 'basic', 'published', '0', 'no_partnership', '2026-09-15 19:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'animaapp.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'animaapp.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'ui-ux';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', NULL, '0.00', 'free', '5 чат-повідомлень/день, 5 імпортів дизайну/день', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Enterprise', NULL, '500.00', 'month', 'SSO, MFA, розширена безпека (річна оплата)', NULL FROM DUAL WHERE @new = 1;

-- Locofy
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Locofy', NULL, 'https://www.locofy.ai', NULL, NULL, 'AI-платформа \"Design to Code\" — перетворює макети на робочий фронтенд-код.', NULL, 'Locofy автоматизує перехід від дизайну до коду через AI, конвертуючи макети у фронтенд-код для швидшої розробки.', NULL, 'AI-конвертація дизайну в код\nDesign-to-code робочий процес\nЕкспорт у популярні фронтенд-фреймворки\nІнтеграція з Figma', NULL, 'Розробники й дизайнери, що автоматизують перехід від макета до коду', NULL, 'web', 'basic', 'published', '0', 'no_partnership', '2026-09-15 19:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'locofy.ai');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'locofy.ai' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'ui-ux';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Тарифи не розкриті публічно', NULL, '0.00', 'free', 'уточнити на офіційному сайті', NULL FROM DUAL WHERE @new = 1;

-- TeleportHQ
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'TeleportHQ', NULL, 'https://teleporthq.io', NULL, NULL, 'Візуальний конструктор сайтів, застосунків і онлайн-магазинів з AI-асистентом і експортом коду. 7-денний трайл, Pro від $14/міс.', NULL, 'TeleportHQ дає AI-асистента прямо в редакторі для побудови сайтів і застосунків, з експортом коду в React, Next.js, Vue, Angular чи HTML/CSS, вбудованою CMS, блогом та e-commerce функціями.', NULL, 'AI-асистент для побудови сайтів і застосунків\nЕкспорт коду в React, Next.js, Vue, Angular\nВбудована CMS, блог, e-commerce\nПлагін Figma-в-код, аналітика й хостинг у комплекті', NULL, 'Дизайнери й розробники, що будують сайти й застосунки з експортом у код', NULL, 'web', 'basic', 'published', '0', 'no_partnership', '2026-09-15 19:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'teleporthq.io');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'teleporthq.io' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'ui-ux';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, '7-денний трайл', NULL, '0.00', 'free', 'без картки', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', NULL, '14.00', 'month', '1 сайт, необмежені сторінки', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premium', NULL, '28.00', 'month', 'необмежені сайти, повний доступ', NULL FROM DUAL WHERE @new = 1;

-- Polymer
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Polymer', NULL, 'https://polymersearch.com', NULL, NULL, 'Платформа візуалізації даних і дашбордів без коду — підключи дані, отримай AI-інсайти. Базовий тариф від $10/міс.', NULL, 'Polymer будує інтерактивні дашборди й звіти з Shopify, Google Sheets, Google Analytics, Facebook/Google Ads та інших джерел, а розмовний AI відповідає на запитання про дані візуально.', NULL, 'Автогенерація дашбордів і виявлення прихованих інсайтів\nРозмовний AI-запит до даних природною мовою\nВбудована аналітика для зовнішніх застосунків\nІнтеграції з Shopify, Google Ads, Salesforce, CSV/XLS', NULL, 'Аналітики, власники ecommerce, маркетингові команди й агенції', NULL, 'web', 'none', 'published', '0', 'no_partnership', '2026-09-15 21:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'polymersearch.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'polymersearch.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-analysis';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-visualization';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Basic', NULL, '10.00', 'month', '1 редактор, ручна синхронізація', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Starter', NULL, '50.00', 'month', 'щоденна синхронізація, усі конектори', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', NULL, '100.00', 'month', 'погодинна синхронізація, 5 акаунтів на конектор', NULL FROM DUAL WHERE @new = 1;

-- Hex
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Hex', NULL, 'https://hex.tech', NULL, NULL, 'Аналітична платформа з агентними ноутбуками й AI-чатами для дослідження даних. Community — безкоштовно, Professional від $36/редактора/міс.', NULL, 'Hex поєднує ноутбуки з AI-агентами для аналізу даних, розмовну аналітику (Threads) для самостійного дослідження та публікацію інтерактивних дата-застосунків.', NULL, 'Агентні ноутбуки з AI для аналізу даних\nThreads — розмовна аналітика для самообслуговування\nПублікація інтерактивних дата-застосунків\nSSO, аудит-логи, сертифікації відповідності', NULL, 'Дата-аналітики, команди й підприємства, що будують спільну аналітику', NULL, 'web', 'basic', 'published', '0', 'no_partnership', '2026-09-15 21:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'hex.tech');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'hex.tech' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-analysis';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Community', NULL, '0.00', 'free', 'для хобістів і невеликих проєктів', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Professional', NULL, '36.00', 'month', 'для окремих професіоналів', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Team', NULL, '75.00', 'month', '14-денний тріал, для команд', NULL FROM DUAL WHERE @new = 1;

-- Deepnote
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Deepnote', NULL, 'https://deepnote.com', NULL, NULL, 'Спільні хмарні ноутбуки для аналізу даних з AI-автодоповненням коду (Python/SQL). Безкоштовно назавжди, Team від $39/редактора/міс.', NULL, 'Deepnote дає командам спільно писати й виконувати код для аналітики та ML у реальному часі, з AI-генерацією коду, інтерактивними дата-застосунками та підтримкою ETL-пайплайнів.', NULL, 'Спільні ноутбуки в реальному часі (Python, SQL)\nDeepnote AI — автодоповнення й генерація коду\nІнтерактивні дата-застосунки й дашборди\nІнтеграції зі Snowflake, BigQuery, Databricks', NULL, 'Дата-аналітики, науковці й інженерні команди', NULL, 'web', 'basic', 'published', '0', 'no_partnership', '2026-09-15 21:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'deepnote.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'deepnote.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-analysis';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', NULL, '0.00', 'free', 'до 3 редакторів, 5 проєктів', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Team', NULL, '39.00', 'month', 'необмежені редактори, AI/CPU/GPU кредити', NULL FROM DUAL WHERE @new = 1;

-- Rows
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Rows', NULL, 'https://rows.com', NULL, NULL, 'AI-таблиця для команд — витягує дані з PDF, імпортує бізнес-дані й аналізує їх через AI. Безкоштовний план, Plus від $8/користувача/міс.', NULL, 'Rows поєднує звичну таблицю з AI-аналітиком, що обробляє PDF та зображення, збагачує клітинки даними напряму з хмарних сервісів і дозволяє будувати кастомні воркфлоу через API.', NULL, 'AI-аналітик для запитів до даних\nAI Vision — витяг даних з PDF і зображень\nАвтоматизація імпорту з хмарних сервісів\nAPI для кастомних воркфлоу', NULL, 'Команди, що обробляють бізнес-дані в масштабі', NULL, 'web', 'none', 'published', '0', 'no_partnership', '2026-09-15 21:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'rows.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'rows.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-analysis';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-visualization';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', NULL, '0.00', 'free', '5 AI-задач/міс, 10 інтеграцій', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Plus', NULL, '8.00', 'month', '200 AI-задач/міс, щоденна автоматизація', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', NULL, '79.00', 'month', 'базовий тариф команди + $8/користувача', NULL FROM DUAL WHERE @new = 1;

-- Better Analyst
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Better Analyst', NULL, 'https://betteranalyst.com', NULL, NULL, 'Універсальна AI-платформа аналітики — підключення даних, дашборди, автоматизовані звіти в одному робочому просторі (колишній Formula Bot). Starter від $10/міс.', NULL, 'Better Analyst обʼєднує візуалізацію, трансформацію й автоматизацію даних, генерує дашборди за шаблонами й автоматизовані пайплайни звітності з понад 30 конекторами.', NULL, 'AI-дашборди за шаблонами з кастомізацією\nАвтоматизовані та заплановані потоки даних\nТекстовий аналіз: тональність, переклад, ключові слова\nПонад 30 конекторів даних і вбудована аналітика через iframe', NULL, 'Соло-аналітики, малий бізнес і команди, що автоматизують звітність', NULL, 'web', 'none', 'published', '0', 'no_partnership', '2026-09-15 21:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'betteranalyst.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'betteranalyst.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-analysis';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Starter', NULL, '10.00', 'month', '250 повідомлень чату/міс, 2 дашборди', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Max', NULL, '20.00', 'month', 'необмежені повідомлення, 5000 AI-дій', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Business', NULL, '40.00', 'month', '15000 AI-дій, 20 дашбордів', NULL FROM DUAL WHERE @new = 1;

-- Sigma Computing
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Sigma Computing', NULL, 'https://www.sigmacomputing.com', NULL, NULL, 'BI-платформа з AI-застосунками й агентами для роботи з даними в реальному часі напряму в сховищі даних. Ціна за запитом.', NULL, 'Sigma поєднує BI з AI-інструментарієм і агентами, що діють автономно на живих даних, зі спредшит-інтерфейсом для запису назад у джерело.', NULL, 'AI-застосунки, що працюють на живих даних\nАвтономні AI-агенти для дій над даними\nСпредшит-інтерфейс з можливістю запису в джерело\nВбудована аналітика (white-label)', NULL, 'Фінанси, продажі, supply chain команди у фінтех, охороні здоровʼя, рітейлі', NULL, 'web', 'basic', 'published', '0', 'found', '2026-09-15 21:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'sigmacomputing.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'sigmacomputing.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-analysis';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Тарифи не розкриті публічно', NULL, '0.00', 'free', 'доступний безкоштовний тріал', NULL FROM DUAL WHERE @new = 1;

-- Count
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Count', NULL, 'https://count.co', NULL, NULL, 'Колаборативна BI-платформа для дослідження й моделювання даних через SQL/Python/no-code з AI-агентом. Безкоштовний план, Pro від $49/редактора/міс.', NULL, 'Count поєднує SQL, Python і no-code комірки на спільному канвасі для дослідження даних, з AI Agent для автоматизованого аналізу. Використовує DuckDB для розвантаження щоденних запитів.', NULL, 'AI Agent для автоматизованого аналізу даних\nSQL, Python і no-code комірки на одному канвасі\nКанвас для спільної роботи з коментарями й анотаціями\nREST API та MCP-доступ', NULL, 'Дата-команди, продуктові команди та керівники, що приймають рішення на даних', NULL, 'web', 'basic', 'published', '0', 'no_partnership', '2026-09-15 21:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'count.co');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'count.co' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'data-analysis';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', NULL, '0.00', 'free', '3 редактори, CSV-підключення, 3 канваси', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', NULL, '49.00', 'month', 'необмежені редактори, 2 підключення до БД', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Scale', NULL, '69.00', 'month', 'мінімум 15 редакторів, необмежені підключення', NULL FROM DUAL WHERE @new = 1;

-- Klipfolio
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Klipfolio', NULL, 'https://www.klipfolio.com', NULL, NULL, 'Дашборд-платформа з 130+ інтеграціями для побудови кастомних звітів у реальному часі. Від $120/міс (річна оплата).', NULL, 'Klipfolio підключається до сотень сервісів і API для побудови кастомних дашбордів і звітів. Має окрему партнерську програму для агенцій із white-label-брендуванням.', NULL, '130+ готових інтеграцій даних\nКастомні дашборди з автооновленням (до щохвилинного)\nPDF-звіти за розкладом\nWhite-label рішення для агенцій', NULL, 'Агенції та команди, що будують кастомні дашборди для клієнтів', NULL, 'web', 'basic', 'published', '0', 'found', '2026-09-15 21:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'klipfolio.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'klipfolio.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'reports';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Base', NULL, '120.00', 'month', '3 дашборди, оновлення раз на 4 год', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Grow', NULL, '190.00', 'month', '10 дашбордів, оновлення щогодини', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Team', NULL, '310.00', 'month', '20 дашбордів, SSO', NULL FROM DUAL WHERE @new = 1;

-- Whatagraph
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Whatagraph', NULL, 'https://whatagraph.com', NULL, NULL, 'Маркетингова платформа звітності з AI-агентами IQ для автоматичної генерації звітів одним кліком. Тарифи від €699/міс.', NULL, 'Whatagraph обʼєднує дані з кількох маркетингових джерел в автоматизовані звіти з KPI-моніторингом і сповіщеннями. IQ Agents автоматизують створення звітів через AI.', NULL, 'AI-агенти IQ для автогенерації звітів\nОбʼєднання даних з кількох маркетингових джерел\nWhite-label звіти з кастомним доменом\nKPI-огляди зі сповіщеннями про відхилення', NULL, 'Маркетингові агенції з комплексною звітністю для клієнтів', NULL, 'web', 'basic', 'published', '0', 'no_partnership', '2026-09-15 21:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'whatagraph.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'whatagraph.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'reports';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Max', NULL, '699.00', 'month', 'розширені інтеграції, white-label', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Prime', NULL, '0.00', 'free', 'кастомна ціна, преміум-інтеграції', NULL FROM DUAL WHERE @new = 1;

-- Supermetrics
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Supermetrics', NULL, 'https://supermetrics.com', NULL, NULL, 'Платформа маркетингової аналітики — обʼєднує дані з 200+ джерел і передає їх в AI-інструменти, BI-системи чи сховища даних. Від €49/міс.', NULL, 'Supermetrics підключає маркетингові джерела до Claude/ChatGPT, Looker Studio, Power BI чи сховищ на кшталт BigQuery, з автоматизованою звітністю та AI-кредитами.', NULL, '200+ джерел маркетингових даних\nПередача даних в AI-інструменти (Claude, ChatGPT)\nАвтоматизована звітність і трансформація даних\nAI-кредити на кожному тарифі', NULL, 'Маркетингові команди, що зводять дані з багатьох рекламних платформ', NULL, 'web', 'basic', 'published', '0', 'no_partnership', '2026-09-15 21:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'supermetrics.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'supermetrics.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'reports';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Starter', NULL, '39.00', 'month', '1 напрямок, 3 джерела даних (річна оплата)', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Growth', NULL, '159.00', 'month', '7 джерел, 2 користувачі', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', NULL, '399.00', 'month', '10 джерел, 3 користувачі', NULL FROM DUAL WHERE @new = 1;

-- Zoho Analytics
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Zoho Analytics', NULL, 'https://www.zoho.com/analytics', NULL, NULL, 'BI-платформа зі звітами, дашбордами й AI-предиктивною аналітикою. Безкоштовний план (2 користувачі), платні — за запитом.', NULL, 'Zoho Analytics дає інструменти для побудови звітів і дашбордів з підключенням багатьох джерел даних, доповнені AI-функціями предиктивного аналізу й автоматичних інсайтів.', NULL, 'AI-предиктивна аналітика та автоматичні інсайти\nНеобмежені звіти й дашборди на всіх тарифах\nПідключення багатьох джерел даних\n15-денний пробний період без картки', NULL, 'Бізнес-аналітики й команди, що будують BI-звіти', NULL, 'web,mobile', 'basic', 'published', '0', 'no_partnership', '2026-09-15 21:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'zoho.com/analytics');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'zoho.com/analytics' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'reports';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', NULL, '0.00', 'free', '2 користувачі, 10К рядків', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Basic', NULL, '0.00', 'free', 'від 2 користувачів, точна ціна за запитом', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Standard', NULL, '0.00', 'free', 'від 5 користувачів, точна ціна за запитом', NULL FROM DUAL WHERE @new = 1;

-- Geckoboard
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Geckoboard', NULL, 'https://www.geckoboard.com', NULL, NULL, 'Дашборд у реальному часі з 90+ джерелами даних і показом на TV-екранах офісу. Від $79/міс (річна оплата).', NULL, 'Geckoboard візуалізує метрики в реальному часі з підключенням до HubSpot, Salesforce, Zendesk та інших, з автоматичними знімками в Slack/Teams/email.', NULL, '90+ інтеграцій джерел даних\nПоказ дашбордів на TV-екранах\nАвтоматичні знімки в Slack, Teams, email\nСповіщення про досягнення порогових значень', NULL, 'Команди, що показують живі метрики на екранах в офісі', NULL, 'web', 'none', 'published', '0', 'no_partnership', '2026-09-15 21:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'geckoboard.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'geckoboard.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'reports';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Essentials', NULL, '79.00', 'month', '2 дашборди, 1 редактор (річна оплата)', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Performance', NULL, '319.00', 'month', '20 дашбордів, алерти, дрилдаун', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Enterprise', NULL, '0.00', 'free', 'необмежено, SSO, аудит-логи', NULL FROM DUAL WHERE @new = 1;

-- Grow (Grow Data Platform)
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'Grow (Grow Data Platform)', NULL, 'https://www.growdataplatform.ai', NULL, NULL, 'No-code BI-платформа з 150+ конекторами даних для автоматизованої звітності без SQL. Тарифи за запитом.', NULL, 'Grow дає non-технічним користувачам самостійно будувати ETL-конвеєри, дашборди й KPI-звіти без знання SQL, з підключенням до BigQuery, HubSpot, Salesforce та інших джерел.', NULL, '150+ готових конекторів даних\nNo-code ETL та підготовка даних\nІнтерактивні дашборди й KPI-візуалізація\nНеобмежена кількість користувачів з контролем доступу', NULL, 'Нетехнічні команди, що хочуть самостійно будувати BI-звіти', NULL, 'web', 'none', 'published', '0', 'no_partnership', '2026-09-15 21:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'growdataplatform.ai');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'growdataplatform.ai' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'reports';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Тарифи не розкриті публічно', NULL, '0.00', 'free', 'лише запит безкоштовного тріалу', NULL FROM DUAL WHERE @new = 1;

-- ReportGarden
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_at`) SELECT 'ReportGarden', NULL, 'https://www.reportgarden.com', NULL, NULL, 'Платформа автоматизованих маркетингових звітів (SMM, SEO, платна реклама) для агенцій. Від $75/міс.', NULL, 'ReportGarden автоматизує генерацію звітів із соцмереж, SEO та платної реклами, обʼєднуючи дані з 100+ джерел у кастомізовані звіти для клієнтів агенції.', NULL, 'Автоматизовані звіти SMM, SEO, платної реклами\nОбʼєднання даних зі 100+ джерел\nКастомні метрики й шаблони звітів\n14-денний пробний період без картки', NULL, 'Маркетингові агенції, що звітують перед клієнтами', NULL, 'web', 'basic', 'published', '0', 'found', '2026-09-15 21:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'reportgarden.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'reportgarden.com' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE c.`slug` = 'design-creative';
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE c.`slug` = 'design-creative' AND s.`slug` = 'reports';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Standard', NULL, '75.00', 'month', 'до 5 клієнтів, необмежені звіти', NULL FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Professional', NULL, '125.00', 'month', 'до 10 клієнтів, преміум-шаблони', NULL FROM DUAL WHERE @new = 1;
