SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-09-30: «Здоров'я та краса» → «Реабілітація та фізіотерапія» — 4 продукти
--   Hinge Health — Здоров'я та краса › Реабілітація та фізіотерапія
--   Rehab AI (AIMD) — Здоров'я та краса › Реабілітація та фізіотерапія
--   PhysioAI (AI Posture Therapy) — Здоров'я та краса › Реабілітація та фізіотерапія
--   SPRY — Здоров'я та краса › Реабілітація та фізіотерапія
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): вкладка SQL → вставити вміст файлу → Вперёд.
-- Без фіксованих id і без DROP / DELETE: підкатегорія — INSERT IGNORE (унікальний ключ category_id + slug);
-- продукт — лише якщо немає продукту з тим самим нормалізованим URL АБО назвою; інакше наявному продукту
-- лише додаються категорія й підкатегорія, тарифи й переклади не чіпаються.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Реабілітація та фізіотерапія', 'Rehabilitation & Physiotherapy', 'rehabilitation-physiotherapy' FROM `categories` c WHERE c.`slug` = 'health-beauty' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Hinge Health — Здоров'я та краса › Реабілітація та фізіотерапія
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Hinge Health', NULL, 'https://www.hingehealth.com', NULL, NULL, 'Цифрова платформа реабілітації опорно-рухового апарату: комп''ютерний зір через камеру телефону стежить за технікою вправ для спини, коліна, стегна, шиї й плеча та дає зворотний зв''язок у реальному часі.', 'A digital musculoskeletal rehabilitation platform: computer vision through your phone camera tracks exercise form for the back, knee, hip, neck and shoulder and gives real-time feedback.', 'Hinge Health — одна з найбільших цифрових платформ реабілітації опорно-рухового апарату в США. Користувач отримує структуровану програму вправ під конкретну проблему — біль у спині, коліні, стегні, шиї чи плечі або відновлення після травми — і виконує її вдома. Технологія комп''ютерного зору через камеру телефону відстежує техніку виконання вправ і в реальному часі підказує, як виправити рух. Паралельно з пацієнтом дистанційно працює фізичний терапевт, а прогрес зберігається й відображається з часом. Сервіс часто надається безкоштовно через роботодавця чи медичну страховку; умови прямої підписки — за запитом. Платформа не замінює очну консультацію лікаря при гострому болю чи серйозній травмі.', 'Hinge Health is one of the largest digital musculoskeletal rehabilitation platforms in the US. Users get a structured exercise programme for a specific problem — back, knee, hip, neck or shoulder pain, or recovery after an injury — and follow it at home. Computer vision through the phone camera tracks exercise form and gives real-time cues on how to correct the movement. A physical therapist supports the patient remotely, and progress is saved and shown over time. The service is often provided free through an employer or health insurance; direct subscription terms are available on request. The platform does not replace an in-person doctor visit for acute pain or a serious injury.', 'Відстеження техніки вправ через камеру телефону
Структуровані програми під конкретну проблему (спина, коліно, плече)
Дистанційна підтримка фізичного терапевта
Відстеження прогресу з часом', 'Exercise form tracking through the phone camera
Structured programmes for a specific problem (back, knee, shoulder)
Remote support from a physical therapist
Progress tracking over time', 'Люди з болем у спині, суглобах чи після травми, які проходять реабілітацію вдома.', 'People with back or joint pain or recovering from an injury who do their rehabilitation at home.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-09-30 00:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'hingehealth.com' OR LOWER(`name`) = LOWER('Hinge Health')));
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'hingehealth.com' OR LOWER(`name`) = LOWER('Hinge Health')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'rehabilitation-physiotherapy' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A digital musculoskeletal rehabilitation platform: computer vision through your phone camera tracks exercise form for the back, knee, hip, neck and shoulder and gives real-time feedback.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Hinge Health is one of the largest digital musculoskeletal rehabilitation platforms in the US. Users get a structured exercise programme for a specific problem — back, knee, hip, neck or shoulder pain, or recovery after an injury — and follow it at home. Computer vision through the phone camera tracks exercise form and gives real-time cues on how to correct the movement. A physical therapist supports the patient remotely, and progress is saved and shown over time. The service is often provided free through an employer or health insurance; direct subscription terms are available on request. The platform does not replace an in-person doctor visit for acute pain or a serious injury.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Exercise form tracking through the phone camera
Structured programmes for a specific problem (back, knee, shoulder)
Remote support from a physical therapist
Progress tracking over time', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People with back or joint pain or recovering from an injury who do their rehabilitation at home.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ціна за запитом', 'Price on request', NULL, 'month', 'Зазвичай безкоштовно через роботодавця чи медичну страховку; пряма підписка — за запитом', 'Usually free through an employer or health insurance; direct subscription on request' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, LAST_INSERT_ID(), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Price on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Usually free through an employer or health insurance; direct subscription on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Rehab AI (AIMD) — Здоров'я та краса › Реабілітація та фізіотерапія
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Rehab AI (AIMD)', NULL, 'https://play.google.com/store/apps/details?id=global.aimd.rehabai', NULL, NULL, 'AI-асистент реабілітації з базою знань на основі доказової медицини: фізична, спортивна та неврологічна реабілітація для фахівців, студентів і пацієнтів.', 'An AI rehabilitation assistant with an evidence-based knowledge base covering physical, sports and neurological rehabilitation for professionals, students and patients.', 'Rehab AI від AIMD — мобільний AI-асистент для реабілітації, що спирається на базу знань доказової медицини. Він працює як довідник з реабілітаційних протоколів і має кілька спеціалізованих напрямків: фізична, спортивна та неврологічна реабілітація. Фахівцям — фізіотерапевтам, ерготерапевтам і лікарям — застосунок допомагає швидко знаходити обґрунтовані підходи та підтримує ухвалення рішень, студентам медичних спеціальностей слугує навчальним матеріалом, а пацієнтам дає змогу знайти перевірену інформацію про відновлення. Відповіді AI мають довідковий характер і не замінюють клінічне рішення фахівця. Умови використання й вартість — див. сторінку застосунку.', 'Rehab AI by AIMD is a mobile AI rehabilitation assistant built on an evidence-based medicine knowledge base. It works as a reference for rehabilitation protocols and has several specialised tracks: physical, sports and neurological rehabilitation. For professionals — physiotherapists, occupational therapists and doctors — the app helps find well-grounded approaches quickly and supports decision-making; for medical students it serves as learning material; and patients can use it to find reliable information about recovery. AI answers are for reference only and do not replace a clinician''s judgement. For terms of use and pricing, see the app page.', 'AI-довідник з реабілітаційних протоколів
Спеціалізовані напрямки: фізична, спортивна, неврологічна реабілітація
Підтримка рішень для фахівців
Освітні матеріали на основі доказової медицини', 'AI reference for rehabilitation protocols
Specialised tracks: physical, sports and neurological rehabilitation
Decision support for professionals
Evidence-based educational materials', 'Фізіотерапевти, ерготерапевти, лікарі, студенти медичних спеціальностей і пацієнти, які шукають перевірену інформацію про реабілітацію.', 'Physiotherapists, occupational therapists, doctors, medical students and patients looking for reliable rehabilitation information.', 'mobile', 'basic', 'published', 0, 'found', @uid, '2026-09-30 00:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'play.google.com/store/apps/details?id=global.aimd.rehabai' OR LOWER(`name`) = LOWER('Rehab AI (AIMD)')));
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'play.google.com/store/apps/details?id=global.aimd.rehabai' OR LOWER(`name`) = LOWER('Rehab AI (AIMD)')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'rehabilitation-physiotherapy' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI rehabilitation assistant with an evidence-based knowledge base covering physical, sports and neurological rehabilitation for professionals, students and patients.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Rehab AI by AIMD is a mobile AI rehabilitation assistant built on an evidence-based medicine knowledge base. It works as a reference for rehabilitation protocols and has several specialised tracks: physical, sports and neurological rehabilitation. For professionals — physiotherapists, occupational therapists and doctors — the app helps find well-grounded approaches quickly and supports decision-making; for medical students it serves as learning material; and patients can use it to find reliable information about recovery. AI answers are for reference only and do not replace a clinician''s judgement. For terms of use and pricing, see the app page.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI reference for rehabilitation protocols
Specialised tracks: physical, sports and neurological rehabilitation
Decision support for professionals
Evidence-based educational materials', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Physiotherapists, occupational therapists, doctors, medical students and patients looking for reliable rehabilitation information.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ціна за запитом', 'Price on request', NULL, 'month', 'Вартість — див. сторінку застосунку в Google Play', 'Pricing: see the app page on Google Play' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, LAST_INSERT_ID(), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Price on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Pricing: see the app page on Google Play', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- PhysioAI (AI Posture Therapy) — Здоров'я та краса › Реабілітація та фізіотерапія
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'PhysioAI (AI Posture Therapy)', NULL, 'https://apps.apple.com/us/app/ai-posture-therapy-physioai/id6756598601', NULL, NULL, 'Сканує поставу через камеру телефону й формує персональний план домашніх вправ для корекції; план можна експортувати в PDF для фахівця чи друку.', 'Scans your posture with the phone camera and builds a personal home exercise plan to correct it; the plan can be exported to PDF for a professional or for printing.', 'PhysioAI (AI Posture Therapy) — мобільний застосунок, який за допомогою штучного інтелекту сканує поставу й положення тіла через камеру телефону. За результатами сканування він підбирає персональні вправи для корекції та формує план домашніх тренувань із покроковими інструкціями. План можна експортувати у PDF, щоб роздрукувати, займатися офлайн або поділитися з фізіотерапевтом чи тренером. Повторні сканування допомагають бачити зміни з часом. Застосунок підходить для самостійної роботи над поставою вдома при дискомфорті в шиї, спині чи плечах від повсякденного навантаження; він не ставить діагноз і не замінює консультацію лікаря. Базове сканування безкоштовне, повний план вправ доступний у Pro-підписці.', 'PhysioAI (AI Posture Therapy) is a mobile app that uses AI to scan your posture and body alignment with the phone camera. Based on the scan it picks personal corrective exercises and builds a home workout plan with step-by-step instructions. The plan can be exported to PDF to print, follow offline or share with a physiotherapist or coach. Repeat scans help you see changes over time. The app suits self-guided posture work at home for everyday neck, back or shoulder discomfort; it does not diagnose and does not replace a doctor''s consultation. The basic scan is free, and the full exercise plan is available with a Pro subscription.', 'AI-сканування постави через камеру
Персональні рекомендації вправ за результатами сканування
План вправ у PDF для друку чи фахівця
Домашні тренування з покроковими інструкціями', 'AI posture scanning with the camera
Personal exercise recommendations based on the scan
PDF exercise plan to print or share with a professional
Home workouts with step-by-step instructions', 'Люди, які хочуть самостійно покращити поставу вдома без візиту до фахівця.', 'People who want to improve their posture on their own at home without visiting a specialist.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-09-30 00:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'apps.apple.com/us/app/ai-posture-therapy-physioai/id6756598601' OR LOWER(`name`) = LOWER('PhysioAI (AI Posture Therapy)')));
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'apps.apple.com/us/app/ai-posture-therapy-physioai/id6756598601' OR LOWER(`name`) = LOWER('PhysioAI (AI Posture Therapy)')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'rehabilitation-physiotherapy' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Scans your posture with the phone camera and builds a personal home exercise plan to correct it; the plan can be exported to PDF for a professional or for printing.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'PhysioAI (AI Posture Therapy) is a mobile app that uses AI to scan your posture and body alignment with the phone camera. Based on the scan it picks personal corrective exercises and builds a home workout plan with step-by-step instructions. The plan can be exported to PDF to print, follow offline or share with a physiotherapist or coach. Repeat scans help you see changes over time. The app suits self-guided posture work at home for everyday neck, back or shoulder discomfort; it does not diagnose and does not replace a doctor''s consultation. The basic scan is free, and the full exercise plan is available with a Pro subscription.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI posture scanning with the camera
Personal exercise recommendations based on the scan
PDF exercise plan to print or share with a professional
Home workouts with step-by-step instructions', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People who want to improve their posture on their own at home without visiting a specialist.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Базове сканування постави', 'Basic posture scan' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, LAST_INSERT_ID(), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Basic posture scan', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 9.99, 'month', 'Повний персональний план вправ', 'Full personal exercise plan' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, LAST_INSERT_ID(), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Full personal exercise plan', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- SPRY — Здоров'я та краса › Реабілітація та фізіотерапія
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'SPRY', NULL, 'https://www.sprypt.com', NULL, NULL, 'Платформа управління клінікою фізичної терапії: запис і розклад, автоматизація документації, робота зі страховими попередніми погодженнями та аналітика.', 'A practice management platform for physical therapy clinics: scheduling, automated documentation, insurance prior authorisations and analytics.', 'SPRY — комплексна B2B-платформа для клінік фізичної терапії, ерготерапії та реабілітаційних центрів. Вона об''єднує запис пацієнтів і керування розкладом, автоматизацію медичної документації та роботу зі страховими компаніями. Автоматизація попередніх погоджень лікування зі страховиками скорочує затримки перед початком терапії й зменшує ручну адміністративну роботу персоналу. Вбудована аналітика показує ефективність клініки, завантаження фахівців і фінансові показники. Рішення орієнтоване на ринок США, вартість розраховується індивідуально за запитом.', 'SPRY is an all-in-one B2B platform for physical therapy and occupational therapy clinics and rehabilitation centres. It brings together patient booking and schedule management, automated medical documentation and work with insurance companies. Automating treatment prior authorisations with insurers cuts delays before therapy starts and reduces manual admin work for staff. Built-in analytics show clinic performance, clinician utilisation and financial metrics. The solution is aimed at the US market, and pricing is quoted individually on request.', 'Керування записом і розкладом клініки
Автоматизація медичної документації
Робота зі страховими попередніми погодженнями
Аналітика ефективності клініки', 'Clinic booking and schedule management
Automated medical documentation
Insurance prior authorisation handling
Clinic performance analytics', 'Клініки фізичної терапії, ерготерапії та реабілітаційні центри.', 'Physical therapy and occupational therapy clinics and rehabilitation centres.', 'web', 'basic', 'published', 0, 'found', @uid, '2026-09-30 00:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'sprypt.com' OR LOWER(`name`) = LOWER('SPRY')));
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'sprypt.com' OR LOWER(`name`) = LOWER('SPRY')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'rehabilitation-physiotherapy' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A practice management platform for physical therapy clinics: scheduling, automated documentation, insurance prior authorisations and analytics.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'SPRY is an all-in-one B2B platform for physical therapy and occupational therapy clinics and rehabilitation centres. It brings together patient booking and schedule management, automated medical documentation and work with insurance companies. Automating treatment prior authorisations with insurers cuts delays before therapy starts and reduces manual admin work for staff. Built-in analytics show clinic performance, clinician utilisation and financial metrics. The solution is aimed at the US market, and pricing is quoted individually on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Clinic booking and schedule management
Automated medical documentation
Insurance prior authorisation handling
Clinic performance analytics', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Physical therapy and occupational therapy clinics and rehabilitation centres.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ціна за запитом', 'Price on request', NULL, 'month', 'B2B-рішення для клінік: вартість за запитом — див. sprypt.com', 'B2B solution for clinics: pricing on request — see sprypt.com' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, LAST_INSERT_ID(), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Price on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'B2B solution for clinics: pricing on request — see sprypt.com', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
