SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: Нові підкатегорії «Подорожі», «Покупки», «Розпізнавання тексту (OCR)» і «AI-компаньйони» — 9 нових продуктів, 2 прив'язок наявних
--   Mindtrip — Подорожі
--   Layla — Подорожі
--   Wonderplan — Подорожі
--   Phia — Покупки
--   Daydream — Покупки
--   Mathpix — Розпізнавання тексту (OCR)
--   ABBYY FineReader PDF — Розпізнавання тексту (OCR)
--   Nanonets — Розпізнавання тексту (OCR)
--   Replika — AI-компаньйони
--   (наявний) Roadtrippers → Подорожі
--   (наявний) Character.AI → AI-компаньйони
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Подорожі', 'Travel', 'travel' FROM `categories` c WHERE c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Покупки', 'Shopping', 'shopping' FROM `categories` c WHERE c.`slug` = 'my-home' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Розпізнавання тексту (OCR)', 'Text Recognition (OCR)', 'ocr' FROM `categories` c WHERE c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'AI-компаньйони', 'AI Companions', 'ai-companions' FROM `categories` c WHERE c.`slug` = 'text-chatbots' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Mindtrip — Подорожі
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'mindtrip.ai' OR LOWER(`name`) = LOWER('Mindtrip'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Mindtrip', NULL, 'https://mindtrip.ai', NULL, NULL, 'AI-помічник для подорожей, який запам''ятовує ваш стиль, підбирає перельоти, житло й ресторани, стежить за цінами та збирає маршрут і бронювання в одному місці.', 'An AI travel assistant that remembers your style, finds flights, stays and restaurants, watches prices and keeps your itinerary and bookings in one place.', 'Mindtrip — персональний AI-помічник для планування й бронювання подорожей. Він запам''ятовує ваші вподобання, тож не треба щоразу пояснювати, що вам подобається, і підбирає перельоти, житло, ресторани, екскурсії та події відповідно до ваших пріоритетів. Помічник попереджає про зниження цін, зміни рейсів і вільні столики, а маршрут, ідеї та бронювання зберігаються в одній поїздці. Бронювати можна прямо на платформі. Працює у вебі та в застосунку для iOS; ціни сервіс на сайті не публікує.', 'Mindtrip is a personal AI assistant for planning and booking trips. It remembers your preferences, so you do not have to explain your taste every time, and finds flights, stays, restaurants, experiences and events that match your priorities. It alerts you to price drops, flight changes and restaurant availability, and keeps your itinerary, ideas and bookings together in one trip. You can book directly on the platform. It works on the web and in an iOS app; pricing is not published on the website.', 'Запам''ятовує ваш стиль подорожей
Підбір перельотів, житла й ресторанів
Сповіщення про ціни та зміни рейсів
Маршрут і бронювання в одному місці', 'Remembers your travel style
Finds flights, stays and restaurants
Price-drop and flight-change alerts
Itinerary and bookings in one place', 'Мандрівники, які хочуть спланувати поїздку швидко й з урахуванням своїх уподобань.', 'Travellers who want to plan trips quickly and around their own preferences.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'mindtrip.ai' OR LOWER(`name`) = LOWER('Mindtrip')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'travel' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI travel assistant that remembers your style, finds flights, stays and restaurants, watches prices and keeps your itinerary and bookings in one place.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Mindtrip is a personal AI assistant for planning and booking trips. It remembers your preferences, so you do not have to explain your taste every time, and finds flights, stays, restaurants, experiences and events that match your priorities. It alerts you to price drops, flight changes and restaurant availability, and keeps your itinerary, ideas and bookings together in one trip. You can book directly on the platform. It works on the web and in an iOS app; pricing is not published on the website.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Remembers your travel style
Finds flights, stays and restaurants
Price-drop and flight-change alerts
Itinerary and bookings in one place', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Travellers who want to plan trips quickly and around their own preferences.', 'manual' FROM DUAL WHERE @new = 1;

-- Layla — Подорожі
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'layla.ai' OR LOWER(`name`) = LOWER('Layla'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Layla', NULL, 'https://layla.ai', NULL, NULL, 'AI-планувальник подорожей: створює маршрут за кілька хвилин, надихає ідеями, допомагає з автоподорожжю чи поїздкою в останній момент; за потреби — допомога експертів.', 'An AI trip planner: it builds an itinerary in minutes, offers inspiration and helps with road trips or last-minute getaways, with travel experts on hand when needed.', 'Layla допомагає спланувати подорож у розмові з AI. Можна попросити створити новий маршрут, підказати, куди поїхати, зібрати автоподорож або спланувати поїздку в останній момент — Layla запропонує план по днях з місцями, активностями й житлом, а доопрацювати його допоможуть експерти з подорожей. Сервісом уже складено понад 2 млн поїздок. Ціни на сайті не опубліковано.', 'Layla helps you plan a trip in conversation with AI. You can ask it to build a new itinerary, suggest where to go, plan a road trip or organise a last-minute getaway — Layla proposes a day-by-day plan with places, activities and stays, and travel experts can help polish it. More than 2 million trips have been planned with it. Pricing is not published on the website.', 'Маршрут по днях за кілька хвилин
Ідеї, куди поїхати
Автоподорожі та поїздки в останній момент
Допомога експертів з подорожей', 'Day-by-day itinerary in minutes
Inspiration on where to go
Road trips and last-minute trips
Help from travel experts', 'Мандрівники, які не люблять довго планувати поїздки самостійно.', 'Travellers who do not like spending hours planning trips themselves.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'layla.ai' OR LOWER(`name`) = LOWER('Layla')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'travel' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI trip planner: it builds an itinerary in minutes, offers inspiration and helps with road trips or last-minute getaways, with travel experts on hand when needed.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Layla helps you plan a trip in conversation with AI. You can ask it to build a new itinerary, suggest where to go, plan a road trip or organise a last-minute getaway — Layla proposes a day-by-day plan with places, activities and stays, and travel experts can help polish it. More than 2 million trips have been planned with it. Pricing is not published on the website.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Day-by-day itinerary in minutes
Inspiration on where to go
Road trips and last-minute trips
Help from travel experts', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Travellers who do not like spending hours planning trips themselves.', 'manual' FROM DUAL WHERE @new = 1;

-- Wonderplan — Подорожі
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'wonderplan.ai' OR LOWER(`name`) = LOWER('Wonderplan'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Wonderplan', NULL, 'https://wonderplan.ai', NULL, NULL, 'Безкоштовний AI-планувальник подорожей: створює персональний маршрут під ваші вподобання, рекомендує житло й дає завантажити план у PDF.', 'A free AI trip planner: it creates a personal itinerary around your preferences, recommends places to stay and lets you download the plan as a PDF.', 'Wonderplan складає персональний маршрут подорожі за вашими вподобаннями — напрямком, датами, бюджетом та інтересами. Готовий план можна змінювати: переставляти, додавати й видаляти місця; AI рекомендує житло, а всі поїздки зберігаються в особистому кабінеті. Маршрут можна завантажити у PDF, щоб мати його під рукою без інтернету. Сервіс зараз безкоштовний.', 'Wonderplan builds a personal travel itinerary around your preferences — destination, dates, budget and interests. You can edit the finished plan by reordering, adding and removing places; AI recommends accommodation, and all your trips are kept in a personal dashboard. The itinerary can be downloaded as a PDF so you have it offline. The service is currently free.', 'Персональний маршрут за вподобаннями
Редагування маршруту
Рекомендації житла
Завантаження в PDF', 'Personal itinerary based on preferences
Itinerary editing
Accommodation recommendations
PDF download', 'Мандрівники, які хочуть безкоштовно отримати готовий план поїздки.', 'Travellers who want a ready trip plan for free.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'wonderplan.ai' OR LOWER(`name`) = LOWER('Wonderplan')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'travel' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A free AI trip planner: it creates a personal itinerary around your preferences, recommends places to stay and lets you download the plan as a PDF.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Wonderplan builds a personal travel itinerary around your preferences — destination, dates, budget and interests. You can edit the finished plan by reordering, adding and removing places; AI recommends accommodation, and all your trips are kept in a personal dashboard. The itinerary can be downloaded as a PDF so you have it offline. The service is currently free.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Personal itinerary based on preferences
Itinerary editing
Accommodation recommendations
PDF download', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Travellers who want a ready trip plan for free.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовно', 'Free', 0.00, 'free', 'Сервіс зараз безкоштовний', 'The service is currently free' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Безкоштовно' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'The service is currently free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Phia — Покупки
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'phia.com' OR LOWER(`name`) = LOWER('Phia'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Phia', NULL, 'https://phia.com', NULL, NULL, 'AI-агент для покупок одягу й аксесуарів: шукає речі за описом на 220 000+ сайтах і знаходить дешевші варіанти товару, який ви переглядаєте.', 'An AI shopping agent for fashion: it searches 220,000+ sites from your description and finds cheaper alternatives to the item you are viewing.', 'Phia допомагає не переплачувати за одяг і аксесуари. Опишіть, що шукаєте, — наприклад, «шкіряна куртка до $300» чи «сумка для офісу», — і AI-агент знайде відповідні речі на понад 220 000 сайтів. Розширення для Chrome на сторінці будь-якого товару показує дешевші альтернативи та найнижчу ціну, а за покупки можна отримувати подарункові картки. Ціни сервіс на сайті не публікує.', 'Phia helps you avoid overpaying for clothes and accessories. Describe what you are looking for — for example, ''a leather jacket under $300'' or ''a tote for the office'' — and the AI agent finds matching items across more than 220,000 sites. The Chrome extension shows cheaper alternatives and the lowest price on any product page, and you can earn gift cards for purchases. Pricing is not published on the website.', 'Пошук речей за описом на 220 000+ сайтах
Дешевші альтернативи на сторінці товару
Розширення для Chrome
Подарункові картки за покупки', 'Search 220,000+ sites by description
Cheaper alternatives on product pages
Chrome extension
Gift cards for purchases', 'Покупці одягу й аксесуарів онлайн, які хочуть знайти найкращу ціну.', 'Online fashion shoppers who want the best price.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'phia.com' OR LOWER(`name`) = LOWER('Phia')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'my-home' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'my-home' AND s.`slug` = 'shopping' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI shopping agent for fashion: it searches 220,000+ sites from your description and finds cheaper alternatives to the item you are viewing.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Phia helps you avoid overpaying for clothes and accessories. Describe what you are looking for — for example, ''a leather jacket under $300'' or ''a tote for the office'' — and the AI agent finds matching items across more than 220,000 sites. The Chrome extension shows cheaper alternatives and the lowest price on any product page, and you can earn gift cards for purchases. Pricing is not published on the website.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Search 220,000+ sites by description
Cheaper alternatives on product pages
Chrome extension
Gift cards for purchases', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Online fashion shoppers who want the best price.', 'manual' FROM DUAL WHERE @new = 1;

-- Daydream — Покупки
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'daydream.ing' OR LOWER(`name`) = LOWER('Daydream'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Daydream', NULL, 'https://daydream.ing', NULL, NULL, 'Персональний AI-агент моди: шукайте одяг у 10 000+ магазинах і брендах через один чат, з урахуванням вашого профілю стилю.', 'A personal AI fashion agent: shop across 10,000+ stores and brands through one chat, tailored to your style profile.', 'Daydream дає змогу купувати одяг, просто розповідаючи в чаті, що вам потрібно. Ви створюєте профіль стилю, а AI-агент шукає підхожі речі в понад 10 000 магазинах і брендах моди та показує їх в одному місці, тож не треба відкривати десятки сайтів. Сервіс доступний у вебі та в застосунку. Ціни на сайті не опубліковано.', 'Daydream lets you shop for clothes simply by describing what you need in a chat. You build a style profile, and the AI agent searches more than 10,000 fashion stores and brands and shows matching items in one place, so you do not need to open dozens of sites. It is available on the web and as an app. Pricing is not published on the website.', 'Покупки одягу через чат
10 000+ магазинів і брендів
Профіль стилю
Веб і застосунок', 'Shop for clothes through chat
10,000+ stores and brands
Style profile
Web and app', 'Люди, які купують одяг онлайн і хочуть швидше знаходити речі під свій стиль.', 'People who buy clothes online and want to find pieces that match their style faster.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'daydream.ing' OR LOWER(`name`) = LOWER('Daydream')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'my-home' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'my-home' AND s.`slug` = 'shopping' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A personal AI fashion agent: shop across 10,000+ stores and brands through one chat, tailored to your style profile.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Daydream lets you shop for clothes simply by describing what you need in a chat. You build a style profile, and the AI agent searches more than 10,000 fashion stores and brands and shows matching items in one place, so you do not need to open dozens of sites. It is available on the web and as an app. Pricing is not published on the website.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Shop for clothes through chat
10,000+ stores and brands
Style profile
Web and app', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People who buy clothes online and want to find pieces that match their style faster.', 'manual' FROM DUAL WHERE @new = 1;

-- Mathpix — Розпізнавання тексту (OCR)
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'mathpix.com' OR LOWER(`name`) = LOWER('Mathpix'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Mathpix', NULL, 'https://mathpix.com', NULL, NULL, 'Розпізнавання тексту для науки й техніки: перетворює зображення, PDF і рукописи з формулами й таблицями на LaTeX, Markdown, Word та інші формати.', 'OCR for science and engineering: it converts images, PDFs and handwriting with equations and tables into LaTeX, Markdown, Word and other formats.', 'Mathpix спеціалізується на розпізнаванні наукових і технічних документів, де звичайний OCR губить формули. Інструмент Snip робить знімок екрана з формулою, текстом чи таблицею й перетворює його на LaTeX, Markdown або інший формат, а цілі PDF і рукописні нотатки конвертуються в редаговані документи. Для розробників є OCR API, для організацій — розгортання у приватній хмарі та захищений сервіс конвертації. Тарифи: Snip Free — безкоштовно; Snip Pro — від $4,99 на місяць; API — від $0,002 за зображення; приватна хмара — $25 000 на рік (25 млн сторінок).', 'Mathpix specialises in recognising scientific and technical documents, where regular OCR loses the equations. The Snip tool takes a screenshot of an equation, text or table and turns it into LaTeX, Markdown or another format, and whole PDFs and handwritten notes are converted into editable documents. Developers get an OCR API, and organisations can use a private cloud deployment and a secure conversion service. Plans: Snip Free — free; Snip Pro — from $4.99 a month; API — from $0.002 per image; private cloud — $25,000 a year (25M pages).', 'Формули й таблиці в LaTeX і Markdown
Конвертація PDF і рукописів
Snip для знімків екрана
OCR API та приватна хмара', 'Equations and tables to LaTeX and Markdown
PDF and handwriting conversion
Snip for screenshots
OCR API and private cloud', 'Студенти, науковці, викладачі й інженери, які працюють з формулами.', 'Students, researchers, teachers and engineers who work with equations.', 'web,mobile,desktop', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'mathpix.com' OR LOWER(`name`) = LOWER('Mathpix')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' AND s.`slug` = 'ocr' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'OCR for science and engineering: it converts images, PDFs and handwriting with equations and tables into LaTeX, Markdown, Word and other formats.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Mathpix specialises in recognising scientific and technical documents, where regular OCR loses the equations. The Snip tool takes a screenshot of an equation, text or table and turns it into LaTeX, Markdown or another format, and whole PDFs and handwritten notes are converted into editable documents. Developers get an OCR API, and organisations can use a private cloud deployment and a secure conversion service. Plans: Snip Free — free; Snip Pro — from $4.99 a month; API — from $0.002 per image; private cloud — $25,000 a year (25M pages).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Equations and tables to LaTeX and Markdown
PDF and handwriting conversion
Snip for screenshots
OCR API and private cloud', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Students, researchers, teachers and engineers who work with equations.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Snip Free', 'Snip Free', 0.00, 'free', 'Безкоштовний тариф Snip', 'Free Snip plan' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Snip Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Snip Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Free Snip plan', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Snip Pro', 'Snip Pro', 4.99, 'month', 'Від $4,99 на місяць', 'From $4.99 a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Snip Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Snip Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'From $4.99 a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- ABBYY FineReader PDF — Розпізнавання тексту (OCR)
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'pdf.abbyy.com' OR LOWER(`name`) = LOWER('ABBYY FineReader PDF'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'ABBYY FineReader PDF', NULL, 'https://pdf.abbyy.com', NULL, NULL, 'PDF-редактор з OCR і AI від ABBYY: оцифровує скани, редагує PDF, порівнює документи й перетворює файли на редаговані Word та Excel.', 'ABBYY''s PDF editor with OCR and AI: it digitises scans, edits PDFs, compares documents and converts files into editable Word and Excel.', 'ABBYY FineReader PDF — застосунок для роботи з документами, що поєднує розпізнавання тексту (OCR) і AI. Він перетворює скановані документи й фото на редагований текст, дає змогу редагувати PDF, порівнювати версії документів і конвертувати файли у Word, Excel та інші формати. Є версії Standard, Corporate (з порівнянням документів і автоматичною конвертацією до 5 000 сторінок на місяць) та для Mac, застосунок для iOS і серверне розгортання. Підписка — на місяць, рік або три роки; є 7-денний безкоштовний пробний період, а ціна залежить від регіону.', 'ABBYY FineReader PDF is a document productivity app combining text recognition (OCR) and AI. It turns scanned documents and photos into editable text, lets you edit PDFs, compare document versions and convert files to Word, Excel and other formats. There are Standard and Corporate editions (the latter with document comparison and automated conversion of up to 5,000 pages a month), a Mac version, an iOS app and a server deployment. Subscriptions are monthly, yearly or three-yearly; there is a 7-day free trial, and pricing depends on the region.', 'OCR сканів і фото
Редагування та порівняння PDF
Конвертація у Word і Excel
Windows, macOS, iOS і сервер', 'OCR for scans and photos
PDF editing and comparison
Conversion to Word and Excel
Windows, macOS, iOS and server', 'Офіси, юристи, бухгалтери й усі, хто багато працює зі сканами та PDF.', 'Offices, lawyers, accountants and anyone who works a lot with scans and PDFs.', 'desktop,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'pdf.abbyy.com' OR LOWER(`name`) = LOWER('ABBYY FineReader PDF')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' AND s.`slug` = 'ocr' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'ABBYY''s PDF editor with OCR and AI: it digitises scans, edits PDFs, compares documents and converts files into editable Word and Excel.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'ABBYY FineReader PDF is a document productivity app combining text recognition (OCR) and AI. It turns scanned documents and photos into editable text, lets you edit PDFs, compare document versions and convert files to Word, Excel and other formats. There are Standard and Corporate editions (the latter with document comparison and automated conversion of up to 5,000 pages a month), a Mac version, an iOS app and a server deployment. Subscriptions are monthly, yearly or three-yearly; there is a 7-day free trial, and pricing depends on the region.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'OCR for scans and photos
PDF editing and comparison
Conversion to Word and Excel
Windows, macOS, iOS and server', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Offices, lawyers, accountants and anyone who works a lot with scans and PDFs.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Пробний період', 'Free trial', 0.00, 'free', '7 днів безкоштовно; ціна підписки залежить від регіону', '7-day free trial; subscription price depends on region' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Пробний період' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free trial', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '7-day free trial; subscription price depends on region', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Nanonets — Розпізнавання тексту (OCR)
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'nanonets.com' OR LOWER(`name`) = LOWER('Nanonets'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Nanonets', NULL, 'https://nanonets.com', NULL, NULL, 'AI-платформа для обробки документів: витягує дані з рахунків, форм і листів, класифікує їх і передає в бізнес-системи через налаштовувані процеси.', 'An AI document processing platform: it extracts data from invoices, forms and emails, classifies it and passes it to business systems through configurable workflows.', 'Nanonets автоматизує процеси, де багато неструктурованих документів. Процес збирається з блоків — витягування даних, класифікація, генеративний AI, маршрутизація, — а результат передається в облікові та інші бізнес-системи через API, пошту чи інтеграції. Оплата лише за виконані блоки, без плати за місця: прості операції — $0,02, стандартний AI — $0,10, складний AI — $0,30 за запуск. Тарифи: Starter — $50 стартових кредитів, далі $100 на місяць за 100 кредитів (до 3 користувачів); Growth — об''ємні ціни зі знижкою до 40%; Enterprise — HIPAA, SOC 2, SSO й розгортання на власних серверах.', 'Nanonets automates processes that involve lots of unstructured documents. A workflow is built from blocks — data extraction, classification, generative AI and routing — and the result is passed to accounting and other business systems via API, email or integrations. You pay only for blocks that run, with no seat fees: simple operations cost $0.02, standard AI $0.10 and complex AI $0.30 per run. Plans: Starter — $50 in starting credits, then $100 a month for 100 credits (up to 3 users); Growth — volume pricing with up to 40% off; Enterprise — HIPAA, SOC 2, SSO and on-premises deployment.', 'Витягування даних з документів
Класифікація та генеративний AI
Процеси з блоків та інтеграції
Оплата лише за виконані кроки', 'Data extraction from documents
Classification and generative AI
Block-based workflows and integrations
Pay only for steps that run', 'Бухгалтерії, операційні й фінансові команди компаній з великим документообігом.', 'Accounting, operations and finance teams at companies with heavy paperwork.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'nanonets.com' OR LOWER(`name`) = LOWER('Nanonets')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' AND s.`slug` = 'ocr' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI document processing platform: it extracts data from invoices, forms and emails, classifies it and passes it to business systems through configurable workflows.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Nanonets automates processes that involve lots of unstructured documents. A workflow is built from blocks — data extraction, classification, generative AI and routing — and the result is passed to accounting and other business systems via API, email or integrations. You pay only for blocks that run, with no seat fees: simple operations cost $0.02, standard AI $0.10 and complex AI $0.30 per run. Plans: Starter — $50 in starting credits, then $100 a month for 100 credits (up to 3 users); Growth — volume pricing with up to 40% off; Enterprise — HIPAA, SOC 2, SSO and on-premises deployment.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Data extraction from documents
Classification and generative AI
Block-based workflows and integrations
Pay only for steps that run', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Accounting, operations and finance teams at companies with heavy paperwork.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Starter', 'Starter', 100.00, 'month', '$50 стартових кредитів, далі $100 за 100 кредитів на місяць', '$50 starting credits, then $100 for 100 credits a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Starter' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Starter', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '$50 starting credits, then $100 for 100 credits a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Replika — AI-компаньйони
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'replika.com' OR LOWER(`name`) = LOWER('Replika'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Replika', NULL, 'https://replika.com', NULL, NULL, 'AI-компаньйон для розмов і емоційної підтримки: пам''ятає подробиці вашого життя, має налаштовуваний вигляд і характер, підтримує голосові дзвінки; 18+.', 'An AI companion for conversation and emotional support: it remembers details of your life, has a customisable look and personality and supports voice calls; 18+.', 'Replika — застосунок з AI-співрозмовником, який позиціонує себе як «AI-друг на кожен день». Компаньйон запам''ятовує ваші стосунки, розпорядок, інтереси та інші подробиці, тож розмови продовжуються з урахуванням контексту. Зовнішність і характер можна налаштувати, доступні голосові дзвінки, обмін фото та селфі. Replika користуються понад 42 млн людей. Застосунок доступний на iOS і Android, є також вебверсія; призначений для користувачів від 18 років. Ціни на сайті не опубліковано. Replika не замінює психологічну допомогу.', 'Replika is an app with an AI conversational partner that presents itself as ''the AI friend to do life with''. The companion remembers your relationships, routines, interests and other details, so conversations continue with context. Its look and personality can be customised, and voice calls and photo and selfie sharing are available. More than 42 million people use Replika. It is available on iOS and Android, with a web version too, and is intended for users aged 18+. Pricing is not published on the website. Replika does not replace mental health care.', 'Пам''ять про подробиці вашого життя
Налаштування вигляду й характеру
Голосові дзвінки
iOS, Android і веб', 'Remembers details of your life
Customisable look and personality
Voice calls
iOS, Android and web', 'Дорослі, які шукають співрозмовника для щоденних розмов.', 'Adults looking for a conversational companion for everyday chats.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'replika.com' OR LOWER(`name`) = LOWER('Replika')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'ai-companions' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI companion for conversation and emotional support: it remembers details of your life, has a customisable look and personality and supports voice calls; 18+.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Replika is an app with an AI conversational partner that presents itself as ''the AI friend to do life with''. The companion remembers your relationships, routines, interests and other details, so conversations continue with context. Its look and personality can be customised, and voice calls and photo and selfie sharing are available. More than 42 million people use Replika. It is available on iOS and Android, with a web version too, and is intended for users aged 18+. Pricing is not published on the website. Replika does not replace mental health care.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Remembers details of your life
Customisable look and personality
Voice calls
iOS, Android and web', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Adults looking for a conversational companion for everyday chats.', 'manual' FROM DUAL WHERE @new = 1;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Roadtrippers')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'travel' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Character.AI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'ai-companions' LIMIT 1;
