SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Інструменти та автоматизація» → нова підкатегорія «AI-агенти» — 7 нових продуктів, 5 прив'язок наявних
--   Manus — AI-агенти
--   Genspark — AI-агенти
--   Relevance AI — AI-агенти
--   CrewAI — AI-агенти
--   Gumloop — AI-агенти
--   Dust — AI-агенти
--   Devin — AI-агенти
--   (наявний) Lindy → AI-агенти
--   (наявний) n8n → AI-агенти
--   (наявний) Zapier → AI-агенти
--   (наявний) Make (Integromat) → AI-агенти
--   (наявний) Replit Agent → AI-агенти
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'AI-агенти', 'AI Agents', 'ai-agents' FROM `categories` c WHERE c.`slug` = 'tools-automation' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Manus — AI-агенти
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'manus.im' OR LOWER(`name`) = LOWER('Manus'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Manus', NULL, 'https://manus.im', NULL, NULL, 'Автономний AI-агент, який сам виконує багатокрокові завдання: глибоке дослідження теми, створення сайтів і презентацій, робота в браузері — від запиту до готового результату.', 'An autonomous AI agent that carries out multi-step tasks on its own: in-depth research, building websites and slide decks, working in the browser — from a request to a finished result.', 'Manus — універсальний AI-агент, якому дають завдання, а не окремі запитання. Він сам планує кроки, шукає інформацію, працює з браузером і файлами та повертає готовий результат: аналітичний звіт, сайт, презентацію, зображення чи відео. Режим Wide Research розподіляє велике дослідження між багатьма паралельними підзадачами. Можна запускати до 20 завдань одночасно й планувати завдання за розкладом. Працює у вебі, як настільний і мобільний застосунок, а також як розширення браузера. Оплата — за кредити: платні тарифи коштують $20, $40 і $200 на місяць (4 000, 8 000 і 40 000 кредитів), щодня додаються 300 кредитів; річна оплата дешевша на 17%.', 'Manus is a general-purpose AI agent that you give tasks rather than individual questions. It plans the steps itself, searches for information, works with the browser and files, and returns a finished result: an analytical report, a website, a slide deck, an image or a video. Wide Research mode splits a large research job into many parallel sub-tasks. You can run up to 20 tasks at once and schedule tasks. It works on the web, as a desktop and mobile app, and as a browser extension. Usage is paid in credits: paid plans cost $20, $40 and $200 a month (4,000, 8,000 and 40,000 credits), with 300 refresh credits added daily; annual billing is 17% cheaper.', 'Виконання багатокрокових завдань від запиту до результату
Wide Research — паралельне глибоке дослідження
Створення сайтів, презентацій, зображень і відео
До 20 одночасних і запланованих завдань
Веб, настільний і мобільний застосунки, розширення браузера', 'Multi-step tasks from request to finished result
Wide Research — parallel in-depth research
Builds websites, slide decks, images and video
Up to 20 concurrent and scheduled tasks
Web, desktop and mobile apps, browser extension', 'Аналітики, маркетологи, підприємці й усі, хто хоче доручати AI цілі завдання, а не лише ставити запитання.', 'Analysts, marketers, entrepreneurs and anyone who wants to hand whole tasks to AI rather than just ask questions.', 'web,mobile,desktop', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'manus.im' OR LOWER(`name`) = LOWER('Manus')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' AND s.`slug` = 'ai-agents' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An autonomous AI agent that carries out multi-step tasks on its own: in-depth research, building websites and slide decks, working in the browser — from a request to a finished result.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Manus is a general-purpose AI agent that you give tasks rather than individual questions. It plans the steps itself, searches for information, works with the browser and files, and returns a finished result: an analytical report, a website, a slide deck, an image or a video. Wide Research mode splits a large research job into many parallel sub-tasks. You can run up to 20 tasks at once and schedule tasks. It works on the web, as a desktop and mobile app, and as a browser extension. Usage is paid in credits: paid plans cost $20, $40 and $200 a month (4,000, 8,000 and 40,000 credits), with 300 refresh credits added daily; annual billing is 17% cheaper.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Multi-step tasks from request to finished result
Wide Research — parallel in-depth research
Builds websites, slide decks, images and video
Up to 20 concurrent and scheduled tasks
Web, desktop and mobile apps, browser extension', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Analysts, marketers, entrepreneurs and anyone who wants to hand whole tasks to AI rather than just ask questions.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Standard', 'Standard', 20.00, 'month', '4 000 кредитів на місяць + 300 щодня, до 20 одночасних завдань', '4,000 credits a month + 300 daily, up to 20 concurrent tasks' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Standard' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Standard', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '4,000 credits a month + 300 daily, up to 20 concurrent tasks', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Customizable', 'Customizable', 40.00, 'month', '8 000 кредитів на місяць (обсяг можна змінювати) + 300 щодня', '8,000 credits a month (adjustable) + 300 daily' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Customizable' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Customizable', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '8,000 credits a month (adjustable) + 300 daily', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Extended', 'Extended', 200.00, 'month', '40 000 кредитів на місяць + 300 щодня для інтенсивної роботи', '40,000 credits a month + 300 daily for heavy use' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Extended' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Extended', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '40,000 credits a month + 300 daily for heavy use', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Genspark — AI-агенти
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'genspark.ai' OR LOWER(`name`) = LOWER('Genspark'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Genspark', NULL, 'https://www.genspark.ai', NULL, NULL, 'AI-робочий простір із «супер-агентом»: за одним запитом готує презентації, таблиці, документи й дослідження, використовуючи провідні моделі GPT, Claude і Gemini.', 'An AI workspace with a ''super agent'': from a single request it prepares slide decks, spreadsheets, documents and research using leading GPT, Claude and Gemini models.', 'Genspark — AI-робочий простір, побудований довкола супер-агента, який сам обирає інструменти й моделі під завдання. Він уміє готувати AI-презентації та AI-таблиці, писати документи, проводити глибоке дослідження з джерелами, генерувати зображення й відео та працювати з файлами в AI Drive. В одній підписці доступні провідні моделі — GPT, Claude, Gemini та інші. Є безкоштовний доступ з обмеженнями; платні тарифи: Plus — $24,99 на місяць (10 000 кредитів) і Pro — $249,99 на місяць (125 000 кредитів), при річній оплаті дешевше. Для компаній є окремі бізнес-тарифи.', 'Genspark is an AI workspace built around a super agent that picks the right tools and models for each task. It can produce AI slides and AI sheets, write documents, run in-depth research with sources, generate images and video, and work with files in AI Drive. Leading models — GPT, Claude, Gemini and others — are available in one subscription. There is limited free access; paid plans are Plus at $24.99 a month (10,000 credits) and Pro at $249.99 a month (125,000 credits), cheaper with annual billing. Separate business plans are available for companies.', 'Супер-агент сам обирає інструменти й моделі
AI-презентації, AI-таблиці та документи
Глибоке дослідження з джерелами
GPT, Claude і Gemini в одній підписці
Сховище файлів AI Drive', 'Super agent picks tools and models itself
AI slides, AI sheets and documents
In-depth research with sources
GPT, Claude and Gemini in one subscription
AI Drive file storage', 'Офісні працівники, аналітики й підприємці, яким потрібні готові презентації, таблиці й звіти без ручної роботи.', 'Office workers, analysts and entrepreneurs who need ready slides, spreadsheets and reports without manual work.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'genspark.ai' OR LOWER(`name`) = LOWER('Genspark')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' AND s.`slug` = 'ai-agents' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI workspace with a ''super agent'': from a single request it prepares slide decks, spreadsheets, documents and research using leading GPT, Claude and Gemini models.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Genspark is an AI workspace built around a super agent that picks the right tools and models for each task. It can produce AI slides and AI sheets, write documents, run in-depth research with sources, generate images and video, and work with files in AI Drive. Leading models — GPT, Claude, Gemini and others — are available in one subscription. There is limited free access; paid plans are Plus at $24.99 a month (10,000 credits) and Pro at $249.99 a month (125,000 credits), cheaper with annual billing. Separate business plans are available for companies.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Super agent picks tools and models itself
AI slides, AI sheets and documents
In-depth research with sources
GPT, Claude and Gemini in one subscription
AI Drive file storage', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Office workers, analysts and entrepreneurs who need ready slides, spreadsheets and reports without manual work.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Plus', 'Plus', 24.99, 'month', '10 000 кредитів на місяць; при річній оплаті $19,99/міс', '10,000 credits a month; $19.99/mo billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Plus' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Plus', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '10,000 credits a month; $19.99/mo billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 249.99, 'month', '125 000 кредитів на місяць; при річній оплаті $199,99/міс', '125,000 credits a month; $199.99/mo billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '125,000 credits a month; $199.99/mo billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Relevance AI — AI-агенти
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'relevanceai.com' OR LOWER(`name`) = LOWER('Relevance AI'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Relevance AI', NULL, 'https://relevanceai.com', NULL, NULL, 'Платформа для побудови «AI-команди» компанії: агенти для продажів, підтримки й операцій, що працюють з 2 000+ інтеграціями, дзвонять і ведуть зустрічі.', 'A platform for building a company''s ''AI workforce'': agents for sales, support and operations that work with 2,000+ integrations and can make calls and join meetings.', 'Relevance AI допомагає компаніям створювати AI-агентів, які беруть на себе рутинні процеси — від кваліфікації лідів і досліджень для продажів до обробки звернень і внутрішніх операцій. Агентам задають інструкції, підключають інструменти та дані, а далі вони працюють самостійно або в зв''язці з іншими агентами. Платформа має понад 2 000 інтеграцій, агентів для дзвінків і зустрічей, керування доступами (SSO, ролі) та необмежену кількість агентів, інструментів і користувачів у корпоративному тарифі. Ціни на сайті не опубліковано — тариф Enterprise узгоджується з відділом продажів.', 'Relevance AI helps companies build AI agents that take over routine processes — from lead qualification and sales research to handling requests and internal operations. You give agents instructions, connect tools and data, and they then work on their own or alongside other agents. The platform offers 2,000+ integrations, calling and meeting agents, access management (SSO, roles) and unlimited agents, tools and users on the enterprise plan. Pricing is not published on the website — the Enterprise plan is agreed with sales.', 'Конструктор AI-агентів без програмування
Понад 2 000 інтеграцій
Агенти для дзвінків і зустрічей
SSO та рольовий доступ', 'No-code AI agent builder
2,000+ integrations
Calling and meeting agents
SSO and role-based access', 'Відділи продажів, підтримки й операцій у компаніях, які хочуть автоматизувати процеси AI-агентами.', 'Sales, support and operations teams in companies that want to automate processes with AI agents.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'relevanceai.com' OR LOWER(`name`) = LOWER('Relevance AI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' AND s.`slug` = 'ai-agents' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A platform for building a company''s ''AI workforce'': agents for sales, support and operations that work with 2,000+ integrations and can make calls and join meetings.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Relevance AI helps companies build AI agents that take over routine processes — from lead qualification and sales research to handling requests and internal operations. You give agents instructions, connect tools and data, and they then work on their own or alongside other agents. The platform offers 2,000+ integrations, calling and meeting agents, access management (SSO, roles) and unlimited agents, tools and users on the enterprise plan. Pricing is not published on the website — the Enterprise plan is agreed with sales.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'No-code AI agent builder
2,000+ integrations
Calling and meeting agents
SSO and role-based access', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Sales, support and operations teams in companies that want to automate processes with AI agents.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Enterprise', 'Enterprise', NULL, 'month', 'Ціна за запитом: необмежені агенти, інструменти й користувачі, 2 000+ інтеграцій', 'Price on request: unlimited agents, tools and users, 2,000+ integrations' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Enterprise' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Enterprise', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Price on request: unlimited agents, tools and users, 2,000+ integrations', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- CrewAI — AI-агенти
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'crewai.com' OR LOWER(`name`) = LOWER('CrewAI'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'CrewAI', NULL, 'https://www.crewai.com', NULL, NULL, 'Платформа для мультиагентних AI-процесів: команду агентів з ролями збирають у візуальному редакторі чи коді на відкритому фреймворку CrewAI і запускають у хмарі.', 'A platform for multi-agent AI workflows: build a crew of agents with roles in a visual editor or in code with the open-source CrewAI framework, then run it in the cloud.', 'CrewAI — відкритий фреймворк і хмарна платформа для створення команд AI-агентів, де кожен агент має свою роль, завдання та інструменти, а разом вони виконують складний процес. Розробники пишуть агентів на Python, а для решти є візуальний редактор з AI-помічником і синхронізація з GitHub. Платформа відповідає і за запуск, і за контроль: моніторинг, політики, маскування персональних даних, SSO та розгортання в хмарі CrewAI або у власній інфраструктурі. Безкоштовний тариф Basic дає 50 запусків процесів на місяць; Enterprise — за індивідуальною ціною з онбордингом і підтримкою інженерів.', 'CrewAI is an open-source framework and cloud platform for building crews of AI agents, where each agent has its own role, tasks and tools and together they carry out a complex process. Developers write agents in Python, and everyone else gets a visual editor with an AI copilot plus GitHub sync. The platform handles both running and governing agents: monitoring, policies, PII redaction, SSO and deployment in the CrewAI cloud or your own infrastructure. The free Basic plan includes 50 workflow executions a month; Enterprise is custom-priced with onboarding and engineering support.', 'Команди агентів з ролями та завданнями
Відкритий фреймворк на Python
Візуальний редактор з AI-помічником
Моніторинг, політики, SSO, розгортання у власній інфраструктурі', 'Crews of agents with roles and tasks
Open-source Python framework
Visual editor with an AI copilot
Monitoring, policies, SSO, self-hosted deployment', 'Розробники та корпоративні команди, які будують і запускають мультиагентні процеси.', 'Developers and enterprise teams that build and run multi-agent workflows.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'crewai.com' OR LOWER(`name`) = LOWER('CrewAI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' AND s.`slug` = 'ai-agents' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A platform for multi-agent AI workflows: build a crew of agents with roles in a visual editor or in code with the open-source CrewAI framework, then run it in the cloud.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'CrewAI is an open-source framework and cloud platform for building crews of AI agents, where each agent has its own role, tasks and tools and together they carry out a complex process. Developers write agents in Python, and everyone else gets a visual editor with an AI copilot plus GitHub sync. The platform handles both running and governing agents: monitoring, policies, PII redaction, SSO and deployment in the CrewAI cloud or your own infrastructure. The free Basic plan includes 50 workflow executions a month; Enterprise is custom-priced with onboarding and engineering support.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Crews of agents with roles and tasks
Open-source Python framework
Visual editor with an AI copilot
Monitoring, policies, SSO, self-hosted deployment', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Developers and enterprise teams that build and run multi-agent workflows.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Basic', 'Basic', 0.00, 'free', 'Візуальний редактор, AI-помічник, 50 запусків процесів на місяць', 'Visual editor, AI copilot, 50 workflow executions a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Basic' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Basic', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Visual editor, AI copilot, 50 workflow executions a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Enterprise', 'Enterprise', NULL, 'month', 'Ціна за запитом: SSO, політики, розгортання у VPC, онбординг', 'Price on request: SSO, policies, VPC deployment, onboarding' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Enterprise' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Enterprise', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Price on request: SSO, policies, VPC deployment, onboarding', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Gumloop — AI-агенти
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'gumloop.com' OR LOWER(`name`) = LOWER('Gumloop'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Gumloop', NULL, 'https://www.gumloop.com', NULL, NULL, 'Конструктор AI-агентів і автоматизацій для команд: агенти працюють з даними компанії через сотні конекторів і 35+ моделей, без програмування.', 'An AI agent and automation builder for teams: agents work with company data through hundreds of connectors and 35+ models, with no coding.', 'Gumloop дає змогу будувати AI-агентів і автоматизовані процеси для щоденної роботи команд — від обробки листів і заявок до звітів і досліджень. Агенти підключаються до робочих сервісів через конектори, використовують понад 35 моделей (можна підключити власні API-ключі) та спільну базу знань компанії Company Brain. Тариф Pro починається від $37 на місяць: необмежені агенти, місця й команди, 20 000 кредитів на місяць і 14-денний безкоштовний пробний період. Enterprise — індивідуальна ціна з VPC, рольовим доступом і виділеною підтримкою.', 'Gumloop lets you build AI agents and automated workflows for teams'' day-to-day work — from handling emails and requests to reports and research. Agents connect to work tools through connectors, use 35+ models (you can bring your own API keys) and a shared company knowledge base, Company Brain. The Pro plan starts at $37 a month: unlimited agents, seats and teams, 20,000 credits a month and a 14-day free trial. Enterprise is custom-priced with VPC, role-based access and dedicated support.', 'Необмежені агенти, місця й команди
35+ моделей і власні API-ключі
База знань компанії Company Brain
Хостинг MCP-серверів', 'Unlimited agents, seats and teams
35+ models and your own API keys
Company Brain knowledge base
MCP server hosting', 'Команди операцій, маркетингу й продажів, які хочуть автоматизувати рутину AI-агентами без розробників.', 'Operations, marketing and sales teams that want to automate routine work with AI agents without developers.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'gumloop.com' OR LOWER(`name`) = LOWER('Gumloop')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' AND s.`slug` = 'ai-agents' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI agent and automation builder for teams: agents work with company data through hundreds of connectors and 35+ models, with no coding.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Gumloop lets you build AI agents and automated workflows for teams'' day-to-day work — from handling emails and requests to reports and research. Agents connect to work tools through connectors, use 35+ models (you can bring your own API keys) and a shared company knowledge base, Company Brain. The Pro plan starts at $37 a month: unlimited agents, seats and teams, 20,000 credits a month and a 14-day free trial. Enterprise is custom-priced with VPC, role-based access and dedicated support.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Unlimited agents, seats and teams
35+ models and your own API keys
Company Brain knowledge base
MCP server hosting', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Operations, marketing and sales teams that want to automate routine work with AI agents without developers.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 37.00, 'month', 'Від $37/міс: необмежені агенти й місця, 20 000 кредитів, 14 днів безкоштовно', 'From $37/mo: unlimited agents and seats, 20,000 credits, 14-day free trial' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'From $37/mo: unlimited agents and seats, 20,000 credits, 14-day free trial', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Enterprise', 'Enterprise', NULL, 'month', 'Ціна за запитом: VPC, рольовий доступ, виділена підтримка', 'Price on request: VPC, role-based access, dedicated support' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Enterprise' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Enterprise', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Price on request: VPC, role-based access, dedicated support', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Dust — AI-агенти
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'dust.tt' OR LOWER(`name`) = LOWER('Dust'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Dust', NULL, 'https://dust.tt', NULL, NULL, 'Платформа корпоративних AI-агентів, підключених до даних компанії — Slack, Notion, GitHub та інших; агентів створюють самі співробітники, без розробників.', 'A platform for company AI agents connected to company data — Slack, Notion, GitHub and more; employees build agents themselves, without developers.', 'Dust дає командам змогу створювати власних AI-агентів, які мають доступ до знань компанії: документів, переписки, задач і коду з Slack, Notion, GitHub та інших сервісів. Агенти відповідають на запитання з посиланнями на джерела, готують звіти, допомагають підтримці й продажам і можуть працювати в зв''язці. Доступно понад 20 моделей. Тарифи — за користувача: Free (500 кредитів), Pro — €30 на місяць (€24 при річній оплаті, 8 000 кредитів), Max — €150 на місяць (€120 при річній оплаті, 40 000 кредитів); Enterprise — за запитом, з розгортанням в окремому середовищі.', 'Dust lets teams build their own AI agents with access to company knowledge: documents, conversations, tasks and code from Slack, Notion, GitHub and other services. Agents answer questions with links to sources, prepare reports, help support and sales teams and can work together. More than 20 models are available. Plans are per user: Free (500 credits), Pro at €30 a month (€24 billed yearly, 8,000 credits) and Max at €150 a month (€120 billed yearly, 40,000 credits); Enterprise is on request, with single-tenant deployment.', 'Агенти з доступом до даних компанії
Інтеграції зі Slack, Notion, GitHub та ін.
Понад 20 моделей
Відповіді з посиланнями на джерела', 'Agents with access to company data
Slack, Notion, GitHub and other integrations
20+ models
Answers with links to sources', 'Компанії, які хочуть дати кожному співробітнику агентів, що знають внутрішні документи й процеси.', 'Companies that want every employee to have agents that know internal documents and processes.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'dust.tt' OR LOWER(`name`) = LOWER('Dust')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' AND s.`slug` = 'ai-agents' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A platform for company AI agents connected to company data — Slack, Notion, GitHub and more; employees build agents themselves, without developers.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Dust lets teams build their own AI agents with access to company knowledge: documents, conversations, tasks and code from Slack, Notion, GitHub and other services. Agents answer questions with links to sources, prepare reports, help support and sales teams and can work together. More than 20 models are available. Plans are per user: Free (500 credits), Pro at €30 a month (€24 billed yearly, 8,000 credits) and Max at €150 a month (€120 billed yearly, 40,000 credits); Enterprise is on request, with single-tenant deployment.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Agents with access to company data
Slack, Notion, GitHub and other integrations
20+ models
Answers with links to sources', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Companies that want every employee to have agents that know internal documents and processes.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '500 кредитів назавжди', '500 lifetime credits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '500 lifetime credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', NULL, 'month', '€30 за користувача на місяць (€24 при річній оплаті), 8 000 кредитів', '€30 per user a month (€24 billed yearly), 8,000 credits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '€30 per user a month (€24 billed yearly), 8,000 credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Max', 'Max', NULL, 'month', '€150 за користувача на місяць (€120 при річній оплаті), 40 000 кредитів', '€150 per user a month (€120 billed yearly), 40,000 credits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Max' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Max', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '€150 per user a month (€120 billed yearly), 40,000 credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Devin — AI-агенти
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'devin.ai' OR LOWER(`name`) = LOWER('Devin'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Devin', NULL, 'https://devin.ai', NULL, NULL, 'AI-інженер-програміст від Cognition: агенти самостійно пишуть, тестують і виправляють код у хмарі, а розробник ставить завдання й перевіряє результат.', 'An AI software engineer from Cognition: agents write, test and fix code on their own in the cloud, while the developer sets tasks and reviews the result.', 'Devin — AI-агент для розробки програмного забезпечення від компанії Cognition. Йому можна доручити завдання — виправити баг, додати функцію, провести рефакторинг чи міграцію, — і він сам вивчає репозиторій, пише код, запускає тести й готує зміни на перевірку. Хмарні агенти працюють паралельно, тож кілька завдань можна вести одночасно. Тарифи: Free — обмежена квота; Pro — $20 на місяць; Max — $200 на місяць зі значно більшими квотами; Team — $80 на місяць плюс $40 за кожного розробника (до 200 користувачів); Enterprise — за запитом, з SSO та розгортанням у VPC.', 'Devin is an AI agent for software development from Cognition. You can hand it a task — fix a bug, add a feature, refactor or migrate code — and it studies the repository, writes the code, runs tests and prepares changes for review. Cloud agents run in parallel, so several tasks can be handled at once. Plans: Free with a light quota; Pro at $20 a month; Max at $200 a month with much higher quotas; Team at $80 a month plus $40 per developer (up to 200 users); Enterprise on request, with SSO and VPC deployment.', 'Самостійне виконання завдань у репозиторії
Написання коду, тести й підготовка змін на перевірку
Паралельні хмарні агенти
Командний тариф з панеллю адміністратора', 'Completes tasks in the repository on its own
Writes code, runs tests and prepares changes for review
Parallel cloud agents
Team plan with an admin dashboard', 'Розробники та інженерні команди, які хочуть делегувати AI рутинні задачі з коду.', 'Developers and engineering teams that want to delegate routine coding tasks to AI.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'devin.ai' OR LOWER(`name`) = LOWER('Devin')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' AND s.`slug` = 'ai-agents' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI software engineer from Cognition: agents write, test and fix code on their own in the cloud, while the developer sets tasks and reviews the result.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Devin is an AI agent for software development from Cognition. You can hand it a task — fix a bug, add a feature, refactor or migrate code — and it studies the repository, writes the code, runs tests and prepares changes for review. Cloud agents run in parallel, so several tasks can be handled at once. Plans: Free with a light quota; Pro at $20 a month; Max at $200 a month with much higher quotas; Team at $80 a month plus $40 per developer (up to 200 users); Enterprise on request, with SSO and VPC deployment.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Completes tasks in the repository on its own
Writes code, runs tests and prepares changes for review
Parallel cloud agents
Team plan with an admin dashboard', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Developers and engineering teams that want to delegate routine coding tasks to AI.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Обмежена квота для роботи з агентами', 'A light quota for coding with agents' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'A light quota for coding with agents', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 20.00, 'month', 'Більші квоти, провідні моделі, хмарні агенти', 'Higher quotas, frontier models, cloud agents' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Higher quotas, frontier models, cloud agents', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Max', 'Max', 200.00, 'month', 'Усе з Pro зі значно більшими квотами', 'Everything in Pro with much higher quotas' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Max' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Max', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Everything in Pro with much higher quotas', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Team', 'Team', 80.00, 'month', '$80/міс + $40/міс за кожного розробника, до 200 користувачів', '$80/mo + $40/mo per developer, up to 200 users' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Team' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Team', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '$80/mo + $40/mo per developer, up to 200 users', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Lindy')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' AND s.`slug` = 'ai-agents' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('n8n')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' AND s.`slug` = 'ai-agents' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Zapier')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' AND s.`slug` = 'ai-agents' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Make (Integromat)')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' AND s.`slug` = 'ai-agents' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Replit Agent')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'tools-automation' AND s.`slug` = 'ai-agents' LIMIT 1;
