SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Фінанси та юридичні» → нові підкатегорії «Нерухомість» і «Крипто та Web3» — 5 нових продуктів, 3 прив'язок наявних
--   ListingAI — Нерухомість
--   Rechat — Нерухомість
--   Restb.ai — Нерухомість
--   Nansen — Крипто та Web3
--   Blockworks Research (Messari) — Крипто та Web3
--   (наявний) Collov AI → Нерухомість
--   (наявний) REimagineHome → Нерухомість
--   (наявний) Interior AI → Нерухомість
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Нерухомість', 'Real Estate', 'real-estate' FROM `categories` c WHERE c.`slug` = 'finance-legal' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Крипто та Web3', 'Crypto & Web3', 'crypto-web3' FROM `categories` c WHERE c.`slug` = 'finance-legal' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- ListingAI — Нерухомість
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'listingai.co' OR LOWER(`name`) = LOWER('ListingAI'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'ListingAI', NULL, 'https://www.listingai.co', NULL, NULL, 'AI-набір маркетингу для ріелторів: описи об''єктів для MLS з перевіркою Fair Housing, віртуальний стейджинг, дописи для соцмереж і сайти об''єктів з одного введення.', 'An AI marketing kit for real estate agents: MLS-ready listing descriptions with Fair Housing checks, virtual staging, social posts and listing websites from a single entry.', 'ListingAI допомагає агентам з нерухомості просувати об''єкти без копірайтера й дизайнера. Ви один раз вносите дані про об''єкт, а сервіс готує опис для MLS з перевіркою на відповідність правилам Fair Housing, віртуальний стейджинг і «вечірні» фото, дописи, Reels та Stories для Facebook, Instagram і LinkedIn, сайт і лендинг об''єкта, порівняльний аналіз ринку (CMA), звіти для продавця та огляди місцевого ринку. Є також AI-редактор зображень і генератор ділових портретів. Сервісом користуються понад 30 000 агентів, зокрема з Keller Williams, Compass, RE/MAX і Coldwell Banker. Платні тарифи — від $19 на місяць, є безкоштовний пробний період без картки.', 'ListingAI helps real estate agents market properties without a copywriter or designer. You enter the property details once, and it produces an MLS-ready description checked for Fair Housing compliance, virtual staging and twilight photos, posts, Reels and Stories for Facebook, Instagram and LinkedIn, a listing website and landing page, a comparative market analysis (CMA), seller reports and local market updates. There is also an AI image editor and a headshot generator. More than 30,000 agents use it, including agents at Keller Williams, Compass, RE/MAX and Coldwell Banker. Paid plans start at $19 a month, with a free trial and no card required.', 'Описи для MLS з перевіркою Fair Housing
Віртуальний стейджинг і «вечірні» фото
Контент для соцмереж і сайти об''єктів
CMA та звіти для продавців', 'MLS-ready descriptions with Fair Housing checks
Virtual staging and twilight photos
Social content and listing websites
CMAs and seller reports', 'Агенти з нерухомості та брокерські агенції.', 'Real estate agents and brokerages.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'listingai.co' OR LOWER(`name`) = LOWER('ListingAI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' AND s.`slug` = 'real-estate' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI marketing kit for real estate agents: MLS-ready listing descriptions with Fair Housing checks, virtual staging, social posts and listing websites from a single entry.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'ListingAI helps real estate agents market properties without a copywriter or designer. You enter the property details once, and it produces an MLS-ready description checked for Fair Housing compliance, virtual staging and twilight photos, posts, Reels and Stories for Facebook, Instagram and LinkedIn, a listing website and landing page, a comparative market analysis (CMA), seller reports and local market updates. There is also an AI image editor and a headshot generator. More than 30,000 agents use it, including agents at Keller Williams, Compass, RE/MAX and Coldwell Banker. Paid plans start at $19 a month, with a free trial and no card required.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'MLS-ready descriptions with Fair Housing checks
Virtual staging and twilight photos
Social content and listing websites
CMAs and seller reports', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Real estate agents and brokerages.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Від $19', 'From $19', 19.00, 'month', 'Платні тарифи від $19 на місяць; безкоштовний пробний період', 'Paid plans from $19 a month; free trial' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Від $19' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'From $19', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Paid plans from $19 a month; free trial', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Rechat — Нерухомість
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'rechat.ai' OR LOWER(`name`) = LOWER('Rechat'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Rechat', NULL, 'https://rechat.ai', NULL, NULL, 'Операційна система для агентств нерухомості: CRM, маркетинг, супровід угод і AI-асистентка Lucy, яка пише листи, створює контент і сайти об''єктів.', 'An operating system for real estate brokerages: CRM, marketing, deal management and Lucy, an AI assistant that drafts emails and creates content and listing websites.', 'Rechat об''єднує інструменти агентства нерухомості в одній платформі. Studio відповідає за дизайн і публікацію сайтів, листів, дописів, друкованих матеріалів і реклами; People — за контакти, розподіл лідів, задачі, календар і автоматизації; Deals — за супровід угод: об''єкти, пропозиції, чек-листи, електронні підписи через DocuSign і дані MLS. AI-асистентка Lucy розуміє голосові команди, пише листи й контент, генерує сайти об''єктів і пропонує автоматизації. Є застосунки для iOS та Android, інтеграції з Google, Outlook, Zillow і Realtor.com. Ціни не опубліковано — їх надають після демонстрації.', 'Rechat brings a brokerage''s tools together in one platform. Studio handles design and publishing of websites, emails, social posts, print materials and ads; People handles contacts, lead routing, tasks, calendar and automations; Deals handles transactions: listings, offers, checklists, e-signatures via DocuSign and MLS data. Lucy, the AI assistant, understands voice commands, drafts emails and content, generates listing websites and suggests automations. There are iOS and Android apps and integrations with Google, Outlook, Zillow and Realtor.com. Pricing is not published — it is provided after a demo.', 'CRM і розподіл лідів
Маркетинг: сайти, листи, соцмережі, друк
Супровід угод, DocuSign і MLS
AI-асистентка Lucy', 'CRM and lead routing
Marketing: websites, emails, social, print
Deal management, DocuSign and MLS
Lucy AI assistant', 'Брокерські агенції нерухомості та їхні агенти.', 'Real estate brokerages and their agents.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'rechat.ai' OR LOWER(`name`) = LOWER('Rechat')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' AND s.`slug` = 'real-estate' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An operating system for real estate brokerages: CRM, marketing, deal management and Lucy, an AI assistant that drafts emails and creates content and listing websites.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Rechat brings a brokerage''s tools together in one platform. Studio handles design and publishing of websites, emails, social posts, print materials and ads; People handles contacts, lead routing, tasks, calendar and automations; Deals handles transactions: listings, offers, checklists, e-signatures via DocuSign and MLS data. Lucy, the AI assistant, understands voice commands, drafts emails and content, generates listing websites and suggests automations. There are iOS and Android apps and integrations with Google, Outlook, Zillow and Realtor.com. Pricing is not published — it is provided after a demo.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'CRM and lead routing
Marketing: websites, emails, social, print
Deal management, DocuSign and MLS
Lucy AI assistant', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Real estate brokerages and their agents.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ціна за запитом', 'Price on request', NULL, 'month', 'Ціни надають після демонстрації', 'Pricing provided after a demo' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ціна за запитом' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Price on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Pricing provided after a demo', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Restb.ai — Нерухомість
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'restb.ai' OR LOWER(`name`) = LOWER('Restb.ai'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Restb.ai', NULL, 'https://restb.ai', NULL, NULL, 'Комп''ютерний зір для нерухомості: автоматично розпізнає на фото тип кімнати, оздоблення, стан об''єкта й особливості та генерує описи для порталів, оцінювачів і страховиків.', 'Computer vision for real estate: it automatically recognises room types, finishes, property condition and features in photos and generates descriptions for portals, appraisers and insurers.', 'Restb.ai перетворює фото нерухомості на структуровані дані. AI розпізнає тип приміщення, особливості й архітектурний стиль, оцінює стан об''єкта, знаходить схожі й порівнянні об''єкти, генерує підписи та описи, перевіряє фото на водяні знаки й дублікати та оцінює складність об''єкта для оцінювачів. Клієнти — сервіси автоматичної оцінки й інвестори, оцінювачі й інспектори, бази MLS, портали пошуку нерухомості та страхові компанії; серед партнерів — Blackstone, Lemonade і CoreLogic. Ціна індивідуальна й залежить від обсягу.', 'Restb.ai turns property photos into structured data. AI recognises room types, features and architectural styles, assesses property condition, finds similar and comparable properties, generates captions and descriptions, checks photos for watermarks and duplicates and estimates property complexity for appraisers. Customers include automated valuation services and investors, appraisers and inspectors, MLSs, property search portals and insurers; partners include Blackstone, Lemonade and CoreLogic. Pricing is custom and depends on volume.', 'Розпізнавання кімнат, оздоблення й стилю
Оцінка стану об''єкта
Автоматичні описи та підписи
Перевірка фото й пошук порівнянних об''єктів', 'Room, feature and style recognition
Property condition assessment
Automatic descriptions and captions
Photo compliance checks and comparables', 'Портали нерухомості, MLS, оцінювачі, інвестори та страховики.', 'Property portals, MLSs, appraisers, investors and insurers.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'restb.ai' OR LOWER(`name`) = LOWER('Restb.ai')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' AND s.`slug` = 'real-estate' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Computer vision for real estate: it automatically recognises room types, finishes, property condition and features in photos and generates descriptions for portals, appraisers and insurers.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Restb.ai turns property photos into structured data. AI recognises room types, features and architectural styles, assesses property condition, finds similar and comparable properties, generates captions and descriptions, checks photos for watermarks and duplicates and estimates property complexity for appraisers. Customers include automated valuation services and investors, appraisers and inspectors, MLSs, property search portals and insurers; partners include Blackstone, Lemonade and CoreLogic. Pricing is custom and depends on volume.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Room, feature and style recognition
Property condition assessment
Automatic descriptions and captions
Photo compliance checks and comparables', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Property portals, MLSs, appraisers, investors and insurers.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ціна за запитом', 'Price on request', NULL, 'month', 'Індивідуальна ціна залежно від обсягу', 'Custom pricing based on volume' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ціна за запитом' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Price on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Custom pricing based on volume', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Nansen — Крипто та Web3
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'nansen.ai' OR LOWER(`name`) = LOWER('Nansen'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Nansen', NULL, 'https://www.nansen.ai', NULL, NULL, 'Ончейн-аналітика з AI: показує дії «розумних грошей», прибутковість гаманців і токенів, дає AI-сповіщення та глибоке AI-дослідження гаманців.', 'On-chain analytics with AI: it shows what ''smart money'' is doing and wallet and token performance, with AI alerts and deep AI research on wallets.', 'Nansen аналізує дані блокчейнів і мітить гаманці, щоб було видно, що роблять фонди, великі гравці та «розумні гроші». Платформа показує прибутковість окремих гаманців, рух токенів і сегменти власників, дає змогу створювати власні мітки, списки спостереження й сповіщення та вивантажувати дані. AI-функції включають розумні сповіщення, AI-аналіз токенів і глибоке AI-дослідження гаманців, а також API та MCP для розробників. Доступні веб і мобільний застосунок. Тариф Pro коштує $69 на місяць або $49 на місяць при річній оплаті. Nansen — аналітичний інструмент, а не інвестиційна порада; криптоактиви пов''язані з високими ризиками.', 'Nansen analyses blockchain data and labels wallets so you can see what funds, large holders and ''smart money'' are doing. The platform shows the performance of individual wallets, token flows and holder segments and lets you create custom labels, watchlists and alerts and export data. AI features include smart alerts, AI token analysis and deep AI research on wallets, plus API and MCP access for developers. Web and mobile apps are available. The Pro plan costs $69 a month or $49 a month billed annually. Nansen is an analytics tool, not investment advice; crypto assets carry high risk.', 'Мітки гаманців і дані «розумних грошей»
Прибутковість гаманців і рух токенів
AI-сповіщення та AI-дослідження гаманців
API та MCP', 'Wallet labels and smart money data
Wallet PnL and token flows
AI alerts and AI wallet research
API and MCP', 'Криптотрейдери, аналітики та фонди, які досліджують ончейн-дані.', 'Crypto traders, analysts and funds researching on-chain data.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'nansen.ai' OR LOWER(`name`) = LOWER('Nansen')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' AND s.`slug` = 'crypto-web3' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'On-chain analytics with AI: it shows what ''smart money'' is doing and wallet and token performance, with AI alerts and deep AI research on wallets.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Nansen analyses blockchain data and labels wallets so you can see what funds, large holders and ''smart money'' are doing. The platform shows the performance of individual wallets, token flows and holder segments and lets you create custom labels, watchlists and alerts and export data. AI features include smart alerts, AI token analysis and deep AI research on wallets, plus API and MCP access for developers. Web and mobile apps are available. The Pro plan costs $69 a month or $49 a month billed annually. Nansen is an analytics tool, not investment advice; crypto assets carry high risk.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Wallet labels and smart money data
Wallet PnL and token flows
AI alerts and AI wallet research
API and MCP', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Crypto traders, analysts and funds researching on-chain data.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 69.00, 'month', '$49 на місяць при річній оплаті; повний доступ до даних і AI-функцій', '$49 a month billed annually; full data and AI features' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '$49 a month billed annually; full data and AI features', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Blockworks Research (Messari) — Крипто та Web3
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'blockworks.com' OR LOWER(`name`) = LOWER('Blockworks Research (Messari)'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Blockworks Research (Messari)', NULL, 'https://blockworks.com', NULL, NULL, 'Дослідницька платформа про криптоактиви, до якої переїхав Messari: профілі активів, дані про раунди фінансування, AI-дайджести, підсумки статей і AI-чат.', 'A crypto research platform that Messari has moved to: asset profiles, fundraising data, AI digests, article summaries and AI chat.', 'Blockworks Research — платформа даних і аналітики про криптоактиви; дослідницький сервіс Messari переїхав саме сюди (старий messari.io доступний з налаштувань акаунта до 31 жовтня 2026 року). Платформа містить профілі активів, дані про раунди фінансування з експортом, ончейн-відстеження та скринери на основі Blockworks AI. AI-інструменти щодня готують дайджести вашого списку спостереження, підсумки статей і новин та відповідають на запитання в AI-чаті. Тарифи: Free — базовий доступ; Pro — $375 на місяць при річній оплаті ($4 500 на рік), зокрема щомісячні дзвінки з аналітиками. Платформа не надає інвестиційних порад.', 'Blockworks Research is a crypto data and analytics platform, and Messari''s research service has moved here (the old messari.io is available from account settings until 31 October 2026). It includes asset profiles, fundraising data with exports, on-chain tracking and screeners powered by Blockworks AI. AI tools prepare daily digests of your watchlist and summaries of articles and news and answer questions in AI chat. Plans: Free — basic access; Pro — $375 a month billed annually ($4,500 a year), including monthly calls with analysts. The platform does not provide investment advice.', 'Профілі криптоактивів і дані про фінансування
AI-дайджести списку спостереження
AI-підсумки статей і новин
AI-чат і скринери', 'Crypto asset profiles and fundraising data
AI watchlist digests
AI article and news summaries
AI chat and screeners', 'Криптоаналітики, фонди й професійні інвестори.', 'Crypto analysts, funds and professional investors.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'blockworks.com' OR LOWER(`name`) = LOWER('Blockworks Research (Messari)')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' AND s.`slug` = 'crypto-web3' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A crypto research platform that Messari has moved to: asset profiles, fundraising data, AI digests, article summaries and AI chat.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Blockworks Research is a crypto data and analytics platform, and Messari''s research service has moved here (the old messari.io is available from account settings until 31 October 2026). It includes asset profiles, fundraising data with exports, on-chain tracking and screeners powered by Blockworks AI. AI tools prepare daily digests of your watchlist and summaries of articles and news and answer questions in AI chat. Plans: Free — basic access; Pro — $375 a month billed annually ($4,500 a year), including monthly calls with analysts. The platform does not provide investment advice.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Crypto asset profiles and fundraising data
AI watchlist digests
AI article and news summaries
AI chat and screeners', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Crypto analysts, funds and professional investors.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Базовий доступ до профілів активів', 'Basic access to asset profiles' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Basic access to asset profiles', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 4500.00, 'year', '≈$375 на місяць при річній оплаті, AI-інструменти, дзвінки з аналітиками', '≈$375 a month billed annually, AI tools, analyst calls' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '≈$375 a month billed annually, AI tools, analyst calls', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Collov AI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' AND s.`slug` = 'real-estate' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('REimagineHome')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' AND s.`slug` = 'real-estate' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Interior AI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'finance-legal' AND s.`slug` = 'real-estate' LIMIT 1;
