SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Мультимедіа» → нова підкатегорія «Транскрипція» (+ прив'язки до «Сумаризаторів») — 5 нових продуктів, 13 прив'язок наявних
--   Happy Scribe — Транскрипція
--   Notta — Транскрипція
--   TurboScribe — Транскрипція
--   MacWhisper — Транскрипція
--   Tactiq — Транскрипція
--   (наявний) Otter.ai → Транскрипція
--   (наявний) Rev → Транскрипція
--   (наявний) Descript → Транскрипція
--   (наявний) Fireflies.ai → Транскрипція
--   (наявний) Sonix → Транскрипція
--   (наявний) Trint → Транскрипція
--   (наявний) AssemblyAI → Транскрипція
--   (наявний) Deepgram → Транскрипція
--   (наявний) Fathom → Транскрипція
--   (наявний) Monica → Сумаризатори
--   (наявний) Sider → Сумаризатори
--   (наявний) Merlin → Сумаризатори
--   (наявний) Gemini Notebook (NotebookLM) → Сумаризатори
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Транскрипція', 'Transcription', 'transcription' FROM `categories` c WHERE c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Сумаризатори', 'Summarizers', 'summarizers' FROM `categories` c WHERE c.`slug` = 'text-chatbots' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Happy Scribe — Транскрипція
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'happyscribe.com' OR LOWER(`name`) = LOWER('Happy Scribe'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Happy Scribe', NULL, 'https://www.happyscribe.com', NULL, NULL, 'AI-транскрипція та субтитри понад 150 мовами, нотатки й підсумки зустрічей, а за потреби — вичитка тексту людиною.', 'AI transcription and subtitles in 150+ languages, meeting notes and summaries, plus optional human proofreading.', 'Happy Scribe перетворює аудіо й відео на текст і субтитри понад 150 мовами. Транскрипт можна вичитати в редакторі та експортувати в потрібному форматі. Сервіс також записує зустрічі та робить нотатки, підсумки й список дій, а в платних тарифах доступний AI-чат з транскриптами. Якщо потрібна максимальна точність, текст може вичитати людина (від $2 за хвилину). Тарифи (при річній оплаті): Free — пробні 10 хвилин; Basic — $8,50 на місяць (120 хв); Pro — $19 на місяць (600 хв); Business — $59 на місяць (6 000 хв); помісячно — $17, $29 і $89. Додаткові хвилини — $0,20.', 'Happy Scribe turns audio and video into text and subtitles in more than 150 languages. You can proofread a transcript in the editor and export it in the format you need. It also records meetings and produces notes, summaries and action items, and paid plans add AI chat with your transcripts. When maximum accuracy matters, a human can proofread the text (from $2 a minute). Plans (billed annually): Free — a 10-minute trial; Basic — $8.50 a month (120 min); Pro — $19 a month (600 min); Business — $59 a month (6,000 min); billed monthly — $17, $29 and $89. Extra minutes cost $0.20.', 'Транскрипція й субтитри 150+ мовами
Редактор і експорт у різних форматах
Нотатки, підсумки й дії зі зустрічей
Вичитка людиною за потреби', 'Transcription and subtitles in 150+ languages
Editor and export in multiple formats
Meeting notes, summaries and action items
Optional human proofreading', 'Журналісти, відеомейкери, дослідники й команди, яким потрібні точні транскрипти та субтитри.', 'Journalists, video creators, researchers and teams that need accurate transcripts and subtitles.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'happyscribe.com' OR LOWER(`name`) = LOWER('Happy Scribe')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'transcription' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'AI transcription and subtitles in 150+ languages, meeting notes and summaries, plus optional human proofreading.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Happy Scribe turns audio and video into text and subtitles in more than 150 languages. You can proofread a transcript in the editor and export it in the format you need. It also records meetings and produces notes, summaries and action items, and paid plans add AI chat with your transcripts. When maximum accuracy matters, a human can proofread the text (from $2 a minute). Plans (billed annually): Free — a 10-minute trial; Basic — $8.50 a month (120 min); Pro — $19 a month (600 min); Business — $59 a month (6,000 min); billed monthly — $17, $29 and $89. Extra minutes cost $0.20.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Transcription and subtitles in 150+ languages
Editor and export in multiple formats
Meeting notes, summaries and action items
Optional human proofreading', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Journalists, video creators, researchers and teams that need accurate transcripts and subtitles.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Пробні 10 хвилин, запис зустрічей до 45 хв', '10-minute trial, meeting recordings up to 45 min' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '10-minute trial, meeting recordings up to 45 min', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Basic', 'Basic', 8.50, 'month', '120 хв на місяць при річній оплаті ($17 помісячно)', '120 min a month billed annually ($17 monthly)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Basic' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Basic', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '120 min a month billed annually ($17 monthly)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 19.00, 'month', '600 хв на місяць, AI-чат ($29 помісячно)', '600 min a month, AI chat ($29 monthly)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '600 min a month, AI chat ($29 monthly)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Business', 'Business', 59.00, 'month', '6 000 хв на місяць, робочий простір команди ($89 помісячно)', '6,000 min a month, team workspace ($89 monthly)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Business' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Business', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '6,000 min a month, team workspace ($89 monthly)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Notta — Транскрипція
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'notta.ai' OR LOWER(`name`) = LOWER('Notta'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Notta', NULL, 'https://www.notta.ai', NULL, NULL, 'AI-транскрипція зустрічей, аудіо й відео в реальному часі з розпізнаванням спікерів, підсумками та інтеграцією з Zoom, Google Meet і Teams.', 'Real-time AI transcription of meetings, audio and video with speaker identification, summaries and integration with Zoom, Google Meet and Teams.', 'Notta перетворює зустрічі, аудіо та відео на текст, у якому зручно шукати. Він транскрибує в реальному часі, розпізнає спікерів, підтримує власний словник термінів і двомовну транскрипцію, а після зустрічі готує AI-підсумок, документи й надсилає результати в Slack. Записувати зустрічі в Zoom, Google Meet і Microsoft Teams можна як за допомогою бота, так і без нього. Сервіс відповідає SOC 2, ISO 27001, GDPR і HIPAA. Тарифи: Free — 120 хв на місяць (до 3 хв на запис); Pro — $13,99 на місяць (1 800 хв, записи до 5 годин); Business — $27,99 на місяць (необмежена транскрипція, командна робота); при річній оплаті на 40% дешевше; Enterprise — за запитом.', 'Notta turns meetings, audio and video into searchable text. It transcribes in real time, identifies speakers, supports a custom vocabulary and bilingual transcription, and after a meeting produces an AI summary and documents and sends results to Slack. Meetings in Zoom, Google Meet and Microsoft Teams can be recorded with or without a bot. It is SOC 2, ISO 27001, GDPR and HIPAA compliant. Plans: Free — 120 min a month (up to 3 min per recording); Pro — $13.99 a month (1,800 min, recordings up to 5 hours); Business — $27.99 a month (unlimited transcription, team collaboration); 40% cheaper billed annually; Enterprise on request.', 'Транскрипція в реальному часі
Розпізнавання спікерів і власний словник
Запис Zoom, Google Meet, Teams з ботом або без
AI-підсумки та інтеграція зі Slack', 'Real-time transcription
Speaker identification and custom vocabulary
Records Zoom, Google Meet and Teams with or without a bot
AI summaries and Slack integration', 'Команди, менеджери й фахівці з продажів, які проводять багато онлайн-зустрічей.', 'Teams, managers and sales professionals who run a lot of online meetings.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'notta.ai' OR LOWER(`name`) = LOWER('Notta')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'transcription' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Real-time AI transcription of meetings, audio and video with speaker identification, summaries and integration with Zoom, Google Meet and Teams.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Notta turns meetings, audio and video into searchable text. It transcribes in real time, identifies speakers, supports a custom vocabulary and bilingual transcription, and after a meeting produces an AI summary and documents and sends results to Slack. Meetings in Zoom, Google Meet and Microsoft Teams can be recorded with or without a bot. It is SOC 2, ISO 27001, GDPR and HIPAA compliant. Plans: Free — 120 min a month (up to 3 min per recording); Pro — $13.99 a month (1,800 min, recordings up to 5 hours); Business — $27.99 a month (unlimited transcription, team collaboration); 40% cheaper billed annually; Enterprise on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Real-time transcription
Speaker identification and custom vocabulary
Records Zoom, Google Meet and Teams with or without a bot
AI summaries and Slack integration', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Teams, managers and sales professionals who run a lot of online meetings.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '120 хв на місяць, до 3 хв на запис', '120 min a month, up to 3 min per recording' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '120 min a month, up to 3 min per recording', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 13.99, 'month', '1 800 хв на місяць, записи до 5 годин; $8,17/міс при річній оплаті', '1,800 min a month, recordings up to 5 hours; $8.17/mo billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '1,800 min a month, recordings up to 5 hours; $8.17/mo billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Business', 'Business', 27.99, 'month', 'Необмежена транскрипція, командна робота; $16,67/міс при річній оплаті', 'Unlimited transcription, team collaboration; $16.67/mo billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Business' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Business', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited transcription, team collaboration; $16.67/mo billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- TurboScribe — Транскрипція
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'turboscribe.ai' OR LOWER(`name`) = LOWER('TurboScribe'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'TurboScribe', NULL, 'https://turboscribe.ai', NULL, NULL, 'Швидка AI-транскрипція аудіо й відео з необмеженою кількістю файлів у платному тарифі, файлами до 10 годин і перекладом понад 130 мовами.', 'Fast AI transcription of audio and video with unlimited files on the paid plan, files up to 10 hours and translation into 130+ languages.', 'TurboScribe розшифровує аудіо- та відеофайли в текст і орієнтований на великі обсяги за фіксовану ціну. Безкоштовно можна транскрибувати 3 файли на день тривалістю до 30 хвилин. Тариф Unlimited знімає обмеження на кількість транскрипцій для одного користувача: файли до 10 годин або 5 ГБ, до 50 файлів одночасно, усі режими транскрипції, переклад понад 134 мовами, масовий експорт і необмежене сховище. Unlimited коштує $120 на рік ($10 на місяць) при річній оплаті; помісячна оплата вдвічі дорожча.', 'TurboScribe converts audio and video files to text and is aimed at large volumes for a flat price. For free you can transcribe 3 files a day of up to 30 minutes each. The Unlimited plan removes the limit on transcriptions for one user: files up to 10 hours or 5 GB, up to 50 files at once, all transcription modes, translation into 134+ languages, bulk export and unlimited storage. Unlimited costs $120 a year ($10 a month) billed annually; monthly billing costs twice as much.', 'Необмежені транскрипції в тарифі Unlimited
Файли до 10 годин, до 50 одночасно
Переклад понад 134 мовами
Масовий експорт і необмежене сховище', 'Unlimited transcriptions on the Unlimited plan
Files up to 10 hours, up to 50 at once
Translation into 134+ languages
Bulk export and unlimited storage', 'Подкастери, журналісти, студенти й дослідники, яким треба розшифровувати багато записів.', 'Podcasters, journalists, students and researchers who need to transcribe lots of recordings.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'turboscribe.ai' OR LOWER(`name`) = LOWER('TurboScribe')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'transcription' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Fast AI transcription of audio and video with unlimited files on the paid plan, files up to 10 hours and translation into 130+ languages.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'TurboScribe converts audio and video files to text and is aimed at large volumes for a flat price. For free you can transcribe 3 files a day of up to 30 minutes each. The Unlimited plan removes the limit on transcriptions for one user: files up to 10 hours or 5 GB, up to 50 files at once, all transcription modes, translation into 134+ languages, bulk export and unlimited storage. Unlimited costs $120 a year ($10 a month) billed annually; monthly billing costs twice as much.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Unlimited transcriptions on the Unlimited plan
Files up to 10 hours, up to 50 at once
Translation into 134+ languages
Bulk export and unlimited storage', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Podcasters, journalists, students and researchers who need to transcribe lots of recordings.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '3 файли на день, до 30 хв кожен', '3 files a day, up to 30 min each' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '3 files a day, up to 30 min each', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Unlimited', 'Unlimited', 120.00, 'year', '≈$10 на місяць при річній оплаті; необмежені транскрипції, файли до 10 годин', '≈$10 a month billed annually; unlimited transcriptions, files up to 10 hours' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Unlimited' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Unlimited', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '≈$10 a month billed annually; unlimited transcriptions, files up to 10 hours', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- MacWhisper — Транскрипція
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'macwhisper.com' OR LOWER(`name`) = LOWER('MacWhisper'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'MacWhisper', NULL, 'https://www.macwhisper.com', NULL, NULL, 'Транскрипція на самому Mac за допомогою моделей Whisper: файли, записи зустрічей і системна диктовка без відправлення аудіо в хмару; є версія для iPhone та iPad.', 'On-device transcription on your Mac with Whisper models: files, meeting recordings and system-wide dictation without sending audio to the cloud; also available for iPhone and iPad.', 'MacWhisper — застосунок для macOS, який транскрибує аудіо локально за допомогою моделей Whisper, тож записи не залишають ваш комп''ютер. Досить перетягнути файл, щоб отримати якісний текст; можна записувати з мікрофона, автоматично записувати зустрічі в Zoom, Teams, Webex, Discord та інших програмах, шукати за текстом і спікерами в усіх транскриптах і редагувати їх у зручному редакторі. Системна диктовка на базі Whisper може замінити стандартну диктовку Apple. У версії Pro доступні всі моделі, покращення тексту й робота з AI-сервісами (OpenAI, Anthropic, Groq, Ollama та інші) через власні ключі, переклад через DeepL. Базова версія безкоштовна; ліцензія Pro для особистого використання — €65 одноразово, є пакети для команд. Застосунок доступний і для iPhone та iPad.', 'MacWhisper is a macOS app that transcribes audio locally with Whisper models, so recordings never leave your computer. Just drag in a file to get a high-quality transcript; you can also record from a microphone, automatically record meetings in Zoom, Teams, Webex, Discord and other apps, search by text and speaker across all transcripts and edit them in a capable editor. Whisper-based system-wide dictation can replace Apple''s built-in dictation. Pro unlocks all models, text clean-up and AI services (OpenAI, Anthropic, Groq, Ollama and more) with your own keys, plus translation via DeepL. The basic version is free; a Pro licence for personal use is a one-time €65, with team packs available. The app is also available for iPhone and iPad.', 'Локальна транскрипція моделями Whisper
Автозапис зустрічей у Zoom, Teams, Webex
Системна диктовка на базі Whisper
Пошук за текстом і спікерами
Версія для iPhone та iPad', 'Local transcription with Whisper models
Automatic meeting recording in Zoom, Teams, Webex
Whisper-based system-wide dictation
Search by text and speaker
Also on iPhone and iPad', 'Користувачі Mac, для яких важлива приватність: журналісти, юристи, дослідники, автори.', 'Mac users who care about privacy: journalists, lawyers, researchers and writers.', 'desktop,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'macwhisper.com' OR LOWER(`name`) = LOWER('MacWhisper')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'transcription' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'On-device transcription on your Mac with Whisper models: files, meeting recordings and system-wide dictation without sending audio to the cloud; also available for iPhone and iPad.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'MacWhisper is a macOS app that transcribes audio locally with Whisper models, so recordings never leave your computer. Just drag in a file to get a high-quality transcript; you can also record from a microphone, automatically record meetings in Zoom, Teams, Webex, Discord and other apps, search by text and speaker across all transcripts and edit them in a capable editor. Whisper-based system-wide dictation can replace Apple''s built-in dictation. Pro unlocks all models, text clean-up and AI services (OpenAI, Anthropic, Groq, Ollama and more) with your own keys, plus translation via DeepL. The basic version is free; a Pro licence for personal use is a one-time €65, with team packs available. The app is also available for iPhone and iPad.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Local transcription with Whisper models
Automatic meeting recording in Zoom, Teams, Webex
Whisper-based system-wide dictation
Search by text and speaker
Also on iPhone and iPad', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Mac users who care about privacy: journalists, lawyers, researchers and writers.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Базова транскрипція на пристрої', 'Basic on-device transcription' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Basic on-device transcription', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', NULL, 'one_time', '€65 одноразово, особиста ліцензія; пакети від 5 ліцензій дешевші', '€65 one-time, personal licence; packs of 5+ licences are cheaper' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '€65 one-time, personal licence; packs of 5+ licences are cheaper', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Tactiq — Транскрипція
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'tactiq.io' OR LOWER(`name`) = LOWER('Tactiq'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Tactiq', NULL, 'https://tactiq.io', NULL, NULL, 'Розширення Chrome для транскрипції онлайн-зустрічей у реальному часі з AI-підсумками й діями; не потребує бота в дзвінку.', 'A Chrome extension for real-time transcription of online meetings with AI summaries and action items; no bot needs to join the call.', 'Tactiq транскрибує онлайн-зустрічі прямо в браузері: розширення для Chrome фіксує розмову в реальному часі без додавання бота до дзвінка. Після зустрічі AI готує підсумки, ключові висновки та список дій, транскрипти можна ділити з колегами й експортувати, а під час зустрічі доступні AI-підказки. У командних тарифах транскрипти автоматично надсилаються учасникам команди. Тарифи (при річній оплаті, за користувача на місяць): Free — 10 транскриптів і 5 AI-кредитів на місяць; Pro — $8 (необмежені транскрипти, 10 AI-кредитів); Team — $16,67 (необмежені AI-кредити, до 20 користувачів); Business — $29,17 (20–200 користувачів).', 'Tactiq transcribes online meetings right in the browser: the Chrome extension captures the conversation in real time without adding a bot to the call. After the meeting AI prepares summaries, key takeaways and action items, transcripts can be shared with colleagues and exported, and in-meeting AI is available during the call. Team plans automatically share transcripts with the team. Plans (billed annually, per user a month): Free — 10 transcripts and 5 AI credits a month; Pro — $8 (unlimited transcripts, 10 AI credits); Team — $16.67 (unlimited AI credits, up to 20 users); Business — $29.17 (20–200 users).', 'Транскрипція зустрічей у реальному часі без бота
AI-підсумки, висновки й дії
AI-підказки під час зустрічі
Спільний доступ і експорт транскриптів', 'Real-time meeting transcription without a bot
AI summaries, takeaways and action items
In-meeting AI
Transcript sharing and export', 'Працівники й команди, які щодня проводять онлайн-зустрічі та хочуть мати текст і підсумки.', 'Professionals and teams who have online meetings every day and want transcripts and summaries.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'tactiq.io' OR LOWER(`name`) = LOWER('Tactiq')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'transcription' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A Chrome extension for real-time transcription of online meetings with AI summaries and action items; no bot needs to join the call.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Tactiq transcribes online meetings right in the browser: the Chrome extension captures the conversation in real time without adding a bot to the call. After the meeting AI prepares summaries, key takeaways and action items, transcripts can be shared with colleagues and exported, and in-meeting AI is available during the call. Team plans automatically share transcripts with the team. Plans (billed annually, per user a month): Free — 10 transcripts and 5 AI credits a month; Pro — $8 (unlimited transcripts, 10 AI credits); Team — $16.67 (unlimited AI credits, up to 20 users); Business — $29.17 (20–200 users).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Real-time meeting transcription without a bot
AI summaries, takeaways and action items
In-meeting AI
Transcript sharing and export', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Professionals and teams who have online meetings every day and want transcripts and summaries.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '10 транскриптів і 5 AI-кредитів на місяць', '10 transcripts and 5 AI credits a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '10 transcripts and 5 AI credits a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 8.00, 'month', 'За користувача при річній оплаті: необмежені транскрипти, 10 AI-кредитів', 'Per user billed annually: unlimited transcripts, 10 AI credits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per user billed annually: unlimited transcripts, 10 AI credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Team', 'Team', 16.67, 'month', 'За користувача при річній оплаті: необмежені AI-кредити, до 20 користувачів', 'Per user billed annually: unlimited AI credits, up to 20 users' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Team' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Team', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per user billed annually: unlimited AI credits, up to 20 users', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Business', 'Business', 29.17, 'month', 'За користувача при річній оплаті: 20–200 користувачів', 'Per user billed annually: 20–200 users' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Business' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Business', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per user billed annually: 20–200 users', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Otter.ai')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'transcription' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Rev')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'transcription' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Descript')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'transcription' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Fireflies.ai')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'transcription' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Sonix')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'transcription' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Trint')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'transcription' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('AssemblyAI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'transcription' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Deepgram')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'transcription' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Fathom')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'transcription' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Monica')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'summarizers' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Sider')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'summarizers' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Merlin')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'summarizers' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Gemini Notebook (NotebookLM)')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'summarizers' LIMIT 1;
