SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Здоров'я та краса» → «Ментальне здоров'я»; «Мій дім» → «Дизайн інтер'єру» — 7 нових продуктів, 2 прив'язок наявних
--   Wysa — Ментальне здоров'я
--   Headspace — Ментальне здоров'я
--   Rosebud — Ментальне здоров'я
--   Interior AI — Дизайн інтер'єру
--   Planner 5D — Дизайн інтер'єру
--   REimagineHome — Дизайн інтер'єру
--   Collov AI — Дизайн інтер'єру
--   (наявний) Calm → Ментальне здоров'я
--   (наявний) Homestyler → Дизайн інтер'єру
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Ментальне здоров''я', 'Mental Health', 'mental-health' FROM `categories` c WHERE c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Дизайн інтер''єру', 'Interior Design', 'interior-design' FROM `categories` c WHERE c.`slug` = 'my-home' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Wysa — Ментальне здоров'я
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'wysa.com' OR LOWER(`name`) = LOWER('Wysa'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Wysa', NULL, 'https://www.wysa.com', NULL, NULL, 'Анонімний AI-помічник для ментального здоров''я на основі доказових підходів: самодопомога, супровід між сесіями з терапевтом і програми для організацій.', 'An anonymous AI mental health companion based on evidence-based approaches: self-help, support between therapy sessions and programmes for organisations.', 'Wysa — AI-помічник для ментального здоров''я, створений як безпечна й доказова альтернатива звичайним чат-ботам. Розмова повністю анонімна, без стигми й обмежень у часі: Wysa допомагає впоратися з тривогою, стресом і поганим настроєм за допомогою вправ і технік на основі доказових підходів. Сервіс підтримує людину на всіх етапах — від першого кроку й самодопомоги до спрямування до фахівця та супроводу між сесіями з терапевтом. Компанія співпрацює з роботодавцями, страховими компаніями та системами охорони здоров''я, які впроваджують Wysa у власні моделі допомоги. Wysa не замінює професійну допомогу в кризовій ситуації. Ціни для організацій — за запитом.', 'Wysa is an AI mental health companion built as a safe, evidence-based alternative to general chatbots. Conversations are completely anonymous, without stigma or time limits: Wysa helps you deal with anxiety, stress and low mood through exercises and techniques grounded in evidence-based approaches. It supports people at every stage — from the first step and self-help to referral to a professional and support between therapy sessions. The company works with employers, insurers and health systems that build Wysa into their care models. Wysa does not replace professional help in a crisis. Pricing for organisations is on request.', 'Анонімні розмови без обмежень у часі
Вправи на основі доказових підходів
Супровід між сесіями з терапевтом
Програми для роботодавців і систем охорони здоров''я', 'Anonymous conversations with no time limits
Exercises based on evidence-based approaches
Support between therapy sessions
Programmes for employers and health systems', 'Люди, які хочуть підтримати свій емоційний стан, а також роботодавці й медичні організації.', 'People who want to look after their emotional wellbeing, plus employers and healthcare organisations.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'wysa.com' OR LOWER(`name`) = LOWER('Wysa')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'mental-health' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An anonymous AI mental health companion based on evidence-based approaches: self-help, support between therapy sessions and programmes for organisations.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Wysa is an AI mental health companion built as a safe, evidence-based alternative to general chatbots. Conversations are completely anonymous, without stigma or time limits: Wysa helps you deal with anxiety, stress and low mood through exercises and techniques grounded in evidence-based approaches. It supports people at every stage — from the first step and self-help to referral to a professional and support between therapy sessions. The company works with employers, insurers and health systems that build Wysa into their care models. Wysa does not replace professional help in a crisis. Pricing for organisations is on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Anonymous conversations with no time limits
Exercises based on evidence-based approaches
Support between therapy sessions
Programmes for employers and health systems', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People who want to look after their emotional wellbeing, plus employers and healthcare organisations.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Для організацій', 'For organisations', NULL, 'month', 'Ціна за запитом для роботодавців, страховиків і систем охорони здоров''я', 'Price on request for employers, insurers and health systems' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Для організацій' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'For organisations', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Price on request for employers, insurers and health systems', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Headspace — Ментальне здоров'я
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'headspace.com' OR LOWER(`name`) = LOWER('Headspace'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Headspace', NULL, 'https://www.headspace.com', NULL, NULL, 'Застосунок для медитацій і ментального здоров''я з AI-компаньйоном Ebb, який вислуховує голосом чи текстом і підбирає медитації та вправи саме для вас.', 'A meditation and mental health app with Ebb, an AI companion that listens by voice or text and suggests meditations and exercises just for you.', 'Headspace — один із найвідоміших застосунків для медитацій, сну й зниження стресу. Його AI-компаньйон Ebb допомагає активно рефлексувати: з ним можна говорити голосом або писати, він пам''ятає попередні розмови, розуміє, що з вами відбувається, і пропонує відповідні медитації та вправи з бібліотеки Headspace. Ebb доступний цілодобово, має вбудовані захисні механізми й за потреби спрямовує до кризових служб. Зараз Ebb доступний платним учасникам 18+ у США, Великій Британії, Канаді й Австралії англійською мовою. Підписка оформлюється помісячно або на рік, є сімейний план і 14-денний безкоштовний пробний період.', 'Headspace is one of the best-known apps for meditation, sleep and stress relief. Its AI companion Ebb helps you actively self-reflect: you can talk to it by voice or text, it remembers previous conversations, understands what you are going through and suggests suitable meditations and activities from the Headspace library. Ebb is available 24/7, has built-in safeguards and connects you to crisis support when needed. Ebb is currently available to paid members aged 18+ in the US, UK, Canada and Australia in English. Subscriptions are monthly or annual, with a family plan and a 14-day free trial.', 'AI-компаньйон Ebb (голос або текст)
Персональні добірки медитацій і вправ
Медитації, сон і зниження стресу
Сімейний план', 'Ebb AI companion (voice or text)
Personalised meditations and activities
Meditation, sleep and stress relief
Family plan', 'Люди, які хочуть менше стресу й кращий сон і шукають регулярну практику медитації.', 'People who want less stress and better sleep and are looking for a regular meditation practice.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'headspace.com' OR LOWER(`name`) = LOWER('Headspace')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'mental-health' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A meditation and mental health app with Ebb, an AI companion that listens by voice or text and suggests meditations and exercises just for you.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Headspace is one of the best-known apps for meditation, sleep and stress relief. Its AI companion Ebb helps you actively self-reflect: you can talk to it by voice or text, it remembers previous conversations, understands what you are going through and suggests suitable meditations and activities from the Headspace library. Ebb is available 24/7, has built-in safeguards and connects you to crisis support when needed. Ebb is currently available to paid members aged 18+ in the US, UK, Canada and Australia in English. Subscriptions are monthly or annual, with a family plan and a 14-day free trial.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Ebb AI companion (voice or text)
Personalised meditations and activities
Meditation, sleep and stress relief
Family plan', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People who want less stress and better sleep and are looking for a regular meditation practice.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Пробний період', 'Free trial', 0.00, 'free', '14 днів безкоштовно, далі місячна або річна підписка', '14 days free, then a monthly or annual subscription' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Пробний період' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free trial', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '14 days free, then a monthly or annual subscription', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Rosebud — Ментальне здоров'я
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'rosebud.app' OR LOWER(`name`) = LOWER('Rosebud'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Rosebud', NULL, 'https://www.rosebud.app', NULL, NULL, 'AI-щоденник для особистого розвитку: допомагає проговорити емоції, помічає закономірності у ваших записах і підтримує звички.', 'An AI journal for personal growth: it helps you process emotions, spots patterns in your entries and supports your habits.', 'Rosebud поєднує ведення щоденника, формування звичок і емоційну підтримку. Ви пишете або надиктовуєте думки, а AI ставить уточнювальні запитання, допомагає розібратися в емоціях, пам''ятає попередні записи та знаходить у них закономірності й нові інсайти про вас. Дані шифруються під час передачі та зберігання. Застосуноком користуються понад 100 000 людей, його рекомендують психологи й коучі. Rosebud не замінює терапію. Базове використання безкоштовне; Rosebud Bloom коштує $12,99 на місяць або $107,99 на рік, є безкоштовний пробний період і знижки для студентів та людей з інвалідністю.', 'Rosebud combines journaling, habit-building and emotional support. You write or dictate your thoughts, and AI asks follow-up questions, helps you make sense of your emotions, remembers past entries and finds patterns and new insights about you in them. Data is encrypted in transit and at rest. More than 100,000 people use the app, and psychologists and coaches recommend it. Rosebud does not replace therapy. Basic use is free; Rosebud Bloom costs $12.99 a month or $107.99 a year, with a free trial and student and disability discounts.', 'AI-щоденник з уточнювальними запитаннями
Закономірності й інсайти з ваших записів
Формування звичок
Шифрування даних', 'AI journal with follow-up questions
Patterns and insights from your entries
Habit-building
Data encryption', 'Люди, які ведуть щоденник і працюють над особистим розвитком та емоційним станом.', 'People who journal and work on personal growth and emotional wellbeing.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'rosebud.app' OR LOWER(`name`) = LOWER('Rosebud')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'mental-health' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI journal for personal growth: it helps you process emotions, spots patterns in your entries and supports your habits.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Rosebud combines journaling, habit-building and emotional support. You write or dictate your thoughts, and AI asks follow-up questions, helps you make sense of your emotions, remembers past entries and finds patterns and new insights about you in them. Data is encrypted in transit and at rest. More than 100,000 people use the app, and psychologists and coaches recommend it. Rosebud does not replace therapy. Basic use is free; Rosebud Bloom costs $12.99 a month or $107.99 a year, with a free trial and student and disability discounts.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI journal with follow-up questions
Patterns and insights from your entries
Habit-building
Data encryption', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People who journal and work on personal growth and emotional wellbeing.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Базове використання безкоштовно', 'Basic use is free' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Basic use is free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Bloom (місяць)', 'Bloom (monthly)', 12.99, 'month', 'Повний доступ; безкоштовний пробний період', 'Full access; free trial' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Bloom (місяць)' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Bloom (monthly)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Full access; free trial', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Bloom (рік)', 'Bloom (annual)', 107.99, 'year', '≈$8,99 на місяць; знижки для студентів', '≈$8.99 a month; student discounts' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Bloom (рік)' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Bloom (annual)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '≈$8.99 a month; student discounts', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Interior AI — Дизайн інтер'єру
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'interiorai.com' OR LOWER(`name`) = LOWER('Interior AI'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Interior AI', NULL, 'https://interiorai.com', NULL, NULL, 'AI-редизайн інтер''єру за фото: завантажте кімнату, оберіть один з 55+ стилів і за ~25 секунд отримайте фотореалістичний варіант, а також віртуальний стейджинг.', 'AI interior redesign from a photo: upload a room, pick one of 55+ styles and get a photorealistic redesign in about 25 seconds, plus virtual staging.', 'Interior AI перетворює фото кімнати на новий дизайн. Завантажте зображення, оберіть тип приміщення (понад 30) і стиль (понад 55) — і приблизно за 25 секунд отримаєте фотореалістичний варіант інтер''єру. Сервіс також робить віртуальний стейджинг порожніх приміщень, перетворює ескізи й файли SketchUp на реалістичні візуалізації, створює 3D-прогулянки й відео та працює із зовнішнім простором і садом. Його створив інді-розробник Пітер Левелс. Тарифи при річній оплаті: Pro — $349 на рік (1 000 дизайнів); Premium — $599 на рік (5 000 дизайнів, інструменти редагування); Ultra — $1 199 на рік (25 000 дизайнів, пріоритетна швидкість); помісячно — $49, $99 і $199.', 'Interior AI turns a photo of a room into a new design. Upload an image, choose a room type (30+) and a style (55+), and in about 25 seconds you get a photorealistic redesign. It also does virtual staging of empty rooms, turns sketches and SketchUp files into realistic renders, creates 3D walkthroughs and videos, and works with exteriors and gardens. It was built by indie developer Pieter Levels. Plans billed yearly: Pro — $349 a year (1,000 designs); Premium — $599 a year (5,000 designs, editing tools); Ultra — $1,199 a year (25,000 designs, priority speed); monthly — $49, $99 and $199.', 'Редизайн кімнати за фото в 55+ стилях
Віртуальний стейджинг порожніх приміщень
Ескізи й SketchUp у фотореалістичні візуалізації
3D-прогулянки та дизайн саду', 'Room redesign from a photo in 55+ styles
Virtual staging of empty rooms
Sketches and SketchUp to photorealistic renders
3D walkthroughs and garden design', 'Власники житла, дизайнери інтер''єру й ріелтори.', 'Homeowners, interior designers and real estate agents.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'interiorai.com' OR LOWER(`name`) = LOWER('Interior AI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'my-home' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'my-home' AND s.`slug` = 'interior-design' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'AI interior redesign from a photo: upload a room, pick one of 55+ styles and get a photorealistic redesign in about 25 seconds, plus virtual staging.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Interior AI turns a photo of a room into a new design. Upload an image, choose a room type (30+) and a style (55+), and in about 25 seconds you get a photorealistic redesign. It also does virtual staging of empty rooms, turns sketches and SketchUp files into realistic renders, creates 3D walkthroughs and videos, and works with exteriors and gardens. It was built by indie developer Pieter Levels. Plans billed yearly: Pro — $349 a year (1,000 designs); Premium — $599 a year (5,000 designs, editing tools); Ultra — $1,199 a year (25,000 designs, priority speed); monthly — $49, $99 and $199.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Room redesign from a photo in 55+ styles
Virtual staging of empty rooms
Sketches and SketchUp to photorealistic renders
3D walkthroughs and garden design', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Homeowners, interior designers and real estate agents.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 349.00, 'year', '1 000 дизайнів (≈$29/міс), помісячно $49', '1,000 designs (≈$29/mo), $49 monthly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '1,000 designs (≈$29/mo), $49 monthly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premium', 'Premium', 599.00, 'year', '5 000 дизайнів, інструменти редагування; помісячно $99', '5,000 designs, editing tools; $99 monthly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Premium' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Premium', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '5,000 designs, editing tools; $99 monthly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ultra', 'Ultra', 1199.00, 'year', '25 000 дизайнів, пріоритетна швидкість; помісячно $199', '25,000 designs, priority speed; $199 monthly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ultra' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Ultra', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '25,000 designs, priority speed; $199 monthly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Planner 5D — Дизайн інтер'єру
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'planner5d.com' OR LOWER(`name`) = LOWER('Planner 5D'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Planner 5D', NULL, 'https://planner5d.com', NULL, NULL, 'Онлайн-планувальник дому й інтер''єру в 2D і 3D з AI: розпізнавання планування з фото, AI Studio для концепцій і рендерів; веб, iOS, Android, Windows і macOS.', 'An online home and interior planner in 2D and 3D with AI: floor plan recognition from photos and AI Studio for concepts and renders; web, iOS, Android, Windows and macOS.', 'Planner 5D дає змогу спланувати квартиру, будинок чи окрему кімнату без спеціальних навичок. У 2D малюють планування, а в 3D розставляють меблі й оздоблення з великої бібліотеки. AI розпізнає план з фото й перетворює його на редагований 3D-проєкт, а AI Studio допомагає з концепціями, візуалізаціями та презентаціями для клієнтів. Є спільна робота в реальному часі. Сервісом користуються понад 120 млн людей — від власників житла до дизайнерів і архітекторів. Тарифи: Free; Premium — $19,99 на місяць або $59,99 на рік; Professional — $49,99 на місяць або $399,99 на рік; Enterprise — за запитом.', 'Planner 5D lets you plan an apartment, house or single room without special skills. You draw the layout in 2D and place furniture and finishes from a large library in 3D. AI recognises a floor plan from a photo and turns it into an editable 3D project, while AI Studio helps with concepts, renders and client presentations. Real-time collaboration is supported. More than 120 million people use it — from homeowners to designers and architects. Plans: Free; Premium — $19.99 a month or $59.99 a year; Professional — $49.99 a month or $399.99 a year; Enterprise on request.', 'Планування в 2D і 3D
AI-розпізнавання плану з фото
AI Studio: концепції, рендери, презентації
Веб, iOS, Android, Windows і macOS', '2D and 3D planning
AI floor plan recognition from photos
AI Studio: concepts, renders, presentations
Web, iOS, Android, Windows and macOS', 'Власники житла, які планують ремонт, а також дизайнери інтер''єру й архітектори.', 'Homeowners planning a renovation, plus interior designers and architects.', 'web,mobile,desktop', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'planner5d.com' OR LOWER(`name`) = LOWER('Planner 5D')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'my-home' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'my-home' AND s.`slug` = 'interior-design' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An online home and interior planner in 2D and 3D with AI: floor plan recognition from photos and AI Studio for concepts and renders; web, iOS, Android, Windows and macOS.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Planner 5D lets you plan an apartment, house or single room without special skills. You draw the layout in 2D and place furniture and finishes from a large library in 3D. AI recognises a floor plan from a photo and turns it into an editable 3D project, while AI Studio helps with concepts, renders and client presentations. Real-time collaboration is supported. More than 120 million people use it — from homeowners to designers and architects. Plans: Free; Premium — $19.99 a month or $59.99 a year; Professional — $49.99 a month or $399.99 a year; Enterprise on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', '2D and 3D planning
AI floor plan recognition from photos
AI Studio: concepts, renders, presentations
Web, iOS, Android, Windows and macOS', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Homeowners planning a renovation, plus interior designers and architects.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Базовий редактор 2D/3D', 'Basic 2D/3D editor' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Basic 2D/3D editor', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premium', 'Premium', 59.99, 'year', '$19,99 помісячно', '$19.99 monthly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Premium' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Premium', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '$19.99 monthly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Professional', 'Professional', 399.99, 'year', 'Для фахівців; $49,99 помісячно', 'For professionals; $49.99 monthly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Professional' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Professional', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'For professionals; $49.99 monthly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- REimagineHome — Дизайн інтер'єру
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'reimaginehome.ai' OR LOWER(`name`) = LOWER('REimagineHome'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'REimagineHome', NULL, 'https://www.reimaginehome.ai', NULL, NULL, 'AI-візуалізація інтер''єру й екстер''єру за фото: редизайн кімнат, віртуальний стейджинг, ландшафт і видалення об''єктів, з підбором реальних товарів.', 'AI interior and exterior visualisation from photos: room redesigns, virtual staging, landscaping and object removal, with real product discovery.', 'REimagineHome допомагає уявити, як виглядатиме житло після змін, і ухвалити рішення. За фото сервіс робить редизайн кімнат, віртуальний стейджинг, зміни ландшафту та фасаду, прибирає зайві об''єкти й показує реальні товари, які можна купити. Працювати можна в діалозі з AI, використовувати референсні фото й поступово вносити правки, не починаючи заново; для ріелторів є пакетна обробка фото оголошень. Кредити витрачаються лише на генерації, а обговорення ідей безкоштовне. Є 5 безкоштовних дизайнів без картки; платні тарифи Essential (30 кредитів), Pro (200), Advanced (400) і Agency (900) коштують від $14 до $99 на місяць.', 'REimagineHome helps you picture what your home will look like after changes and make decisions. From a photo it creates room redesigns, virtual staging, landscaping and facade changes, removes unwanted objects and shows real products you can buy. You can work in a conversation with AI, use reference photos and make incremental edits without starting over; real estate agents get batch processing of listing photos. Credits are spent only on generations, while discussing ideas is free. There are 5 free designs with no card; the paid Essential (30 credits), Pro (200), Advanced (400) and Agency (900) plans range from $14 to $99 a month.', 'Редизайн інтер''єру й екстер''єру за фото
Віртуальний стейджинг і видалення об''єктів
Діалог з AI та поступові правки
Підбір реальних товарів', 'Interior and exterior redesign from photos
Virtual staging and object removal
Conversational AI and incremental edits
Real product discovery', 'Власники житла, ріелтори та дизайнери.', 'Homeowners, real estate agents and designers.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'reimaginehome.ai' OR LOWER(`name`) = LOWER('REimagineHome')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'my-home' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'my-home' AND s.`slug` = 'interior-design' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'AI interior and exterior visualisation from photos: room redesigns, virtual staging, landscaping and object removal, with real product discovery.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'REimagineHome helps you picture what your home will look like after changes and make decisions. From a photo it creates room redesigns, virtual staging, landscaping and facade changes, removes unwanted objects and shows real products you can buy. You can work in a conversation with AI, use reference photos and make incremental edits without starting over; real estate agents get batch processing of listing photos. Credits are spent only on generations, while discussing ideas is free. There are 5 free designs with no card; the paid Essential (30 credits), Pro (200), Advanced (400) and Agency (900) plans range from $14 to $99 a month.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Interior and exterior redesign from photos
Virtual staging and object removal
Conversational AI and incremental edits
Real product discovery', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Homeowners, real estate agents and designers.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовно', 'Free', 0.00, 'free', '5 дизайнів без картки', '5 designs, no card required' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Безкоштовно' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '5 designs, no card required', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Essential', 'Essential', 14.00, 'month', '30 кредитів на місяць; старші тарифи — до $99/міс', '30 credits a month; higher plans up to $99/mo' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Essential' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Essential', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '30 credits a month; higher plans up to $99/mo', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Collov AI — Дизайн інтер'єру
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'collov.ai' OR LOWER(`name`) = LOWER('Collov AI'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Collov AI', NULL, 'https://collov.ai', NULL, NULL, 'AI-віртуальний стейджинг і дизайн інтер''єру: перетворює порожні кімнати на мебльовані, прибирає меблі, змінює погоду й газон на фото нерухомості.', 'AI virtual staging and interior design: it turns empty rooms into furnished ones, removes furniture and changes weather and lawns in property photos.', 'Collov AI створено насамперед для ринку нерухомості. Сервіс віртуально мебляє порожні кімнати на фото, дозволяє перегенеровувати варіанти без обмежень, прибирати наявні меблі, робити «вечірні» знімки, замінювати газон і покращувати погоду на фото. Старші тарифи додають стейджинг з кількох ракурсів і віртуальні тури, а Enterprise — API. Фото надаються з комерційною ліцензією, без водяних знаків. Тарифи на місяць: Standard — $19 (60 фото-кредитів); Advanced — $49 (150); Premium — $79 (263); Enterprise — $127 (526, API); при річній оплаті — $228, $588, $948 і $1 524.', 'Collov AI is built primarily for real estate. It virtually furnishes empty rooms in photos, lets you regenerate options without limits, remove existing furniture, create twilight shots, replace lawns and improve the weather in photos. Higher plans add multi-angle staging and virtual tours, and Enterprise adds an API. Photos come with a commercial licence and no watermarks. Monthly plans: Standard — $19 (60 photo credits); Advanced — $49 (150); Premium — $79 (263); Enterprise — $127 (526, API); billed annually — $228, $588, $948 and $1,524.', 'Віртуальний стейджинг порожніх кімнат
Видалення меблів, «вечірні» фото, заміна газону
Необмежена перегенерація
Віртуальні тури та API', 'Virtual staging of empty rooms
Furniture removal, twilight shots, lawn replacement
Unlimited regeneration
Virtual tours and API', 'Ріелтори, агенції нерухомості, забудовники й дизайнери інтер''єру.', 'Real estate agents, brokerages, developers and interior designers.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'collov.ai' OR LOWER(`name`) = LOWER('Collov AI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'my-home' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'my-home' AND s.`slug` = 'interior-design' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'AI virtual staging and interior design: it turns empty rooms into furnished ones, removes furniture and changes weather and lawns in property photos.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Collov AI is built primarily for real estate. It virtually furnishes empty rooms in photos, lets you regenerate options without limits, remove existing furniture, create twilight shots, replace lawns and improve the weather in photos. Higher plans add multi-angle staging and virtual tours, and Enterprise adds an API. Photos come with a commercial licence and no watermarks. Monthly plans: Standard — $19 (60 photo credits); Advanced — $49 (150); Premium — $79 (263); Enterprise — $127 (526, API); billed annually — $228, $588, $948 and $1,524.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Virtual staging of empty rooms
Furniture removal, twilight shots, lawn replacement
Unlimited regeneration
Virtual tours and API', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Real estate agents, brokerages, developers and interior designers.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Standard', 'Standard', 19.00, 'month', '60 фото-кредитів, без водяних знаків', '60 photo credits, no watermarks' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Standard' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Standard', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '60 photo credits, no watermarks', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Advanced', 'Advanced', 49.00, 'month', '150 фото-кредитів', '150 photo credits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Advanced' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Advanced', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '150 photo credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premium', 'Premium', 79.00, 'month', '263 фото-кредити, віртуальні тури', '263 photo credits, virtual tours' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Premium' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Premium', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '263 photo credits, virtual tours', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Calm')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'mental-health' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Homestyler')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'my-home' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'my-home' AND s.`slug` = 'interior-design' LIMIT 1;
