SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Розробка та IT» → нова підкатегорія «No-code / Low-code» — 7 нових продуктів, 2 прив'язок наявних
--   Lovable — No-code / Low-code
--   Bolt.new — No-code / Low-code
--   Softr — No-code / Low-code
--   Glide — No-code / Low-code
--   Adalo — No-code / Low-code
--   FlutterFlow — No-code / Low-code
--   Retool — No-code / Low-code
--   (наявний) Bubble → No-code / Low-code
--   (наявний) Airtable → No-code / Low-code
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'No-code / Low-code', 'No-code / Low-code', 'no-code-low-code' FROM `categories` c WHERE c.`slug` = 'development-it' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Lovable — No-code / Low-code
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'lovable.dev' OR LOWER(`name`) = LOWER('Lovable'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Lovable', NULL, 'https://lovable.dev', NULL, NULL, 'AI-конструктор вебзастосунків: описуєте ідею в чаті — і Lovable створює сайт чи застосунок з базою даних, хостингом і власним доменом, без знання програмування.', 'An AI web app builder: describe your idea in chat and Lovable builds a website or app with a database, hosting and a custom domain, with no coding knowledge needed.', 'Lovable позиціонує себе як AI-інженера, з яким кожен може створювати продукти для вебу. Ви описуєте, що потрібно, звичайною мовою, а Lovable генерує повноцінний вебзастосунок і доопрацьовує його за наступними повідомленнями; є режим планування, де AI спершу узгоджує план змін. Проєкти одразу розгортаються в хмарі Lovable з базою даних і хостингом, їх можна публікувати на піддомені lovable.app чи власному домені, працювати разом із командою та налаштовувати ролі. Оплата — кредитами за повідомлення. Тарифи: Free — 5 кредитів на день (до 30 на місяць); Pro — $25 на місяць (100 кредитів, перенесення залишку, власні домени); Business — $50 на місяць (командний простір, рольовий доступ, SSO); Enterprise — за запитом.', 'Lovable presents itself as an AI software engineer that lets anyone build for the web. You describe what you need in plain language, Lovable generates a full web app and refines it with each follow-up message; a plan mode lets the AI agree a plan of changes first. Projects deploy straight to Lovable Cloud with a database and hosting, can be published on a lovable.app subdomain or your own domain, and support team collaboration and roles. Usage is paid in credits per message. Plans: Free — 5 credits a day (up to 30 a month); Pro — $25 a month (100 credits, credit rollover, custom domains); Business — $50 a month (team workspace, role-based access, SSO); Enterprise on request.', 'Створення вебзастосунку з опису в чаті
Хмара Lovable: база даних і хостинг
Режим планування змін
Власні домени та командна робота', 'Builds a web app from a chat description
Lovable Cloud: database and hosting
Plan mode for changes
Custom domains and team collaboration', 'Підприємці, продакт-менеджери й дизайнери, які хочуть швидко зробити MVP чи внутрішній інструмент без розробників.', 'Founders, product managers and designers who want to ship an MVP or internal tool quickly without developers.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'lovable.dev' OR LOWER(`name`) = LOWER('Lovable')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'no-code-low-code' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI web app builder: describe your idea in chat and Lovable builds a website or app with a database, hosting and a custom domain, with no coding knowledge needed.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Lovable presents itself as an AI software engineer that lets anyone build for the web. You describe what you need in plain language, Lovable generates a full web app and refines it with each follow-up message; a plan mode lets the AI agree a plan of changes first. Projects deploy straight to Lovable Cloud with a database and hosting, can be published on a lovable.app subdomain or your own domain, and support team collaboration and roles. Usage is paid in credits per message. Plans: Free — 5 credits a day (up to 30 a month); Pro — $25 a month (100 credits, credit rollover, custom domains); Business — $50 a month (team workspace, role-based access, SSO); Enterprise on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Builds a web app from a chat description
Lovable Cloud: database and hosting
Plan mode for changes
Custom domains and team collaboration', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Founders, product managers and designers who want to ship an MVP or internal tool quickly without developers.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '5 кредитів на день (до 30 на місяць), приватні проєкти, хмара', '5 credits a day (up to 30 a month), private projects, cloud' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '5 credits a day (up to 30 a month), private projects, cloud', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 25.00, 'month', '100 кредитів на місяць, перенесення залишку, власні домени', '100 credits a month, rollover, custom domains' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '100 credits a month, rollover, custom domains', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Business', 'Business', 50.00, 'month', '100 кредитів, командний простір, рольовий доступ, SSO', '100 credits, team workspace, role-based access, SSO' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Business' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Business', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '100 credits, team workspace, role-based access, SSO', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Bolt.new — No-code / Low-code
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'bolt.new' OR LOWER(`name`) = LOWER('Bolt.new'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Bolt.new', NULL, 'https://bolt.new', NULL, NULL, 'AI-конструктор сайтів і застосунків від StackBlitz: з текстового опису створює повноцінний застосунок з хостингом і базою даних прямо в браузері.', 'An AI site and app builder from StackBlitz: from a text description it creates a full app with hosting and a database right in the browser.', 'Bolt.new від StackBlitz дає змогу створювати сайти, дашборди, інтернет-магазини та внутрішні застосунки без програмування: ви пишете, що потрібно, а AI генерує й запускає застосунок прямо в браузері, після чого його можна доопрацьовувати в чаті чи вручну в коді. Безкоштовно доступні публічні й приватні проєкти, хостинг і бази даних. Тарифи: Free — до 300 тис. токенів на день і 1 млн на місяць; Pro — $25 на місяць (10 млн токенів, без брендингу Bolt, власні домени, AI-редагування зображень); Teams — $30 за учасника на місяць; Enterprise — за запитом, з SSO та журналами аудиту.', 'Bolt.new by StackBlitz lets you build websites, dashboards, storefronts and internal apps without coding: you write what you need, the AI generates and runs the app right in the browser, and you can then refine it in chat or by hand in the code. Public and private projects, hosting and databases are available for free. Plans: Free — up to 300K tokens a day and 1M a month; Pro — $25 a month (10M tokens, no Bolt branding, custom domains, AI image editing); Teams — $30 per member a month; Enterprise on request, with SSO and audit logs.', 'Застосунок з текстового опису прямо в браузері
Хостинг і бази даних
Редагування в чаті або в коді
Власні домени (Pro)', 'App from a text description right in the browser
Hosting and databases
Edit in chat or in code
Custom domains (Pro)', 'Підприємці, малий бізнес і розробники, яким потрібен робочий прототип чи застосунок за кілька годин.', 'Founders, small businesses and developers who need a working prototype or app within hours.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'bolt.new' OR LOWER(`name`) = LOWER('Bolt.new')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'no-code-low-code' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI site and app builder from StackBlitz: from a text description it creates a full app with hosting and a database right in the browser.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Bolt.new by StackBlitz lets you build websites, dashboards, storefronts and internal apps without coding: you write what you need, the AI generates and runs the app right in the browser, and you can then refine it in chat or by hand in the code. Public and private projects, hosting and databases are available for free. Plans: Free — up to 300K tokens a day and 1M a month; Pro — $25 a month (10M tokens, no Bolt branding, custom domains, AI image editing); Teams — $30 per member a month; Enterprise on request, with SSO and audit logs.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'App from a text description right in the browser
Hosting and databases
Edit in chat or in code
Custom domains (Pro)', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Founders, small businesses and developers who need a working prototype or app within hours.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '300 тис. токенів на день, 1 млн на місяць, хостинг і бази даних', '300K tokens a day, 1M a month, hosting and databases' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '300K tokens a day, 1M a month, hosting and databases', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 25.00, 'month', '10 млн токенів на місяць, без брендингу, власні домени', '10M tokens a month, no branding, custom domains' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '10M tokens a month, no branding, custom domains', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Teams', 'Teams', 30.00, 'month', 'За учасника: 10 млн токенів, централізована оплата, командна робота', 'Per member: 10M tokens, centralised billing, team collaboration' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Teams' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Teams', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per member: 10M tokens, centralised billing, team collaboration', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Softr — No-code / Low-code
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'softr.io' OR LOWER(`name`) = LOWER('Softr'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Softr', NULL, 'https://www.softr.io', NULL, NULL, 'No-code конструктор бізнес-застосунків з AI: внутрішні інструменти, клієнтські портали й CRM з базою даних, автоматизаціями та інтеграціями.', 'A no-code business app builder with AI: internal tools, client portals and CRMs with a database, workflow automation and integrations.', 'Softr — AI-конструктор застосунків для бізнес-операцій. На ньому без коду збирають внутрішні інструменти, клієнтські й партнерські портали, CRM, системи заявок та інші застосунки з вбудованою базою даних або підключенням до Airtable, Google Sheets та інших джерел. Є автоматизація процесів, AI-функції всередині застосунків, керування доступами й безпека корпоративного рівня. Softr довіряють понад мільйон компаній. Тарифи (при річній оплаті): Free; Basic — $19 на місяць; Pro — $99 на місяць; Business — $329 на місяць; кожен тариф включає певну кількість AI-кредитів, є безкоштовний пробний період.', 'Softr is an AI app builder for business operations. Without code you can assemble internal tools, client and partner portals, CRMs, request systems and other apps with a built-in database or connections to Airtable, Google Sheets and other sources. It includes workflow automation, AI features inside apps, access control and enterprise-grade security. More than a million businesses trust Softr. Plans (billed yearly): Free; Basic at $19 a month; Pro at $99 a month; Business at $329 a month; each plan includes a set number of AI credits, and there is a free trial.', 'Внутрішні інструменти, портали й CRM без коду
Вбудована база даних та інтеграції
Автоматизація процесів
AI-функції в застосунках', 'Internal tools, portals and CRMs without code
Built-in database and integrations
Workflow automation
AI features inside apps', 'Малий і середній бізнес, операційні команди та агенції, яким потрібні власні бізнес-застосунки.', 'Small and mid-sized businesses, operations teams and agencies that need their own business apps.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'softr.io' OR LOWER(`name`) = LOWER('Softr')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'no-code-low-code' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A no-code business app builder with AI: internal tools, client portals and CRMs with a database, workflow automation and integrations.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Softr is an AI app builder for business operations. Without code you can assemble internal tools, client and partner portals, CRMs, request systems and other apps with a built-in database or connections to Airtable, Google Sheets and other sources. It includes workflow automation, AI features inside apps, access control and enterprise-grade security. More than a million businesses trust Softr. Plans (billed yearly): Free; Basic at $19 a month; Pro at $99 a month; Business at $329 a month; each plan includes a set number of AI credits, and there is a free trial.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Internal tools, portals and CRMs without code
Built-in database and integrations
Workflow automation
AI features inside apps', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Small and mid-sized businesses, operations teams and agencies that need their own business apps.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Ознайомлення з можливостями, 5 AI-кредитів на місяць', 'Explore Softr, 5 AI credits a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Explore Softr, 5 AI credits a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Basic', 'Basic', 19.00, 'month', 'При річній оплаті; для особистої продуктивності', 'Billed yearly; for personal work productivity' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Basic' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Basic', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Billed yearly; for personal work productivity', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 99.00, 'month', 'При річній оплаті; для невеликих команд', 'Billed yearly; for small teams' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Billed yearly; for small teams', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Business', 'Business', 329.00, 'month', 'При річній оплаті; для компаній із розвиненими системами', 'Billed yearly; for companies building advanced systems' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Business' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Business', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Billed yearly; for companies building advanced systems', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Glide — No-code / Low-code
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'glideapps.com' OR LOWER(`name`) = LOWER('Glide'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Glide', NULL, 'https://www.glideapps.com', NULL, NULL, 'AI-платформа для внутрішніх бізнес-застосунків: створює застосунок з таблиці, файлу або текстового запиту, з AI-функціями та автоматизаціями.', 'An AI platform for internal business apps: it builds an app from a spreadsheet, a file or a text prompt, with AI features and workflows.', 'Glide допомагає командам створювати власне програмне забезпечення для бізнесу значно швидше, ніж звичайною розробкою. Застосунок можна зібрати з Google Sheets чи Excel, із завантаженого файлу або просто з текстового опису, а потім налаштувати екрани, дані, ролі й автоматизовані процеси. AI вбудовується прямо в застосунок — для обробки тексту, зображень і документів. Тарифи: Free; Basic — $25 на місяць (100 кредитів, 2 опубліковані застосунки); Plus — $50 на місяць (250 кредитів, 5 застосунків, публічні застосунки); Pro — від $125 на місяць (від 500 кредитів, необмежені застосунки й процеси); Enterprise — за запитом.', 'Glide helps teams build custom business software much faster than traditional development. An app can be built from Google Sheets or Excel, an uploaded file or just a text description, and then you configure screens, data, roles and automated workflows. AI is built right into the app — for processing text, images and documents. Plans: Free; Basic at $25 a month (100 credits, 2 published apps); Plus at $50 a month (250 credits, 5 apps, public apps); Pro from $125 a month (from 500 credits, unlimited apps and workflows); Enterprise on request.', 'Застосунок з таблиці, файлу чи текстового запиту
AI-функції всередині застосунку
Автоматизовані процеси
Ролі та керування доступом', 'App from a spreadsheet, file or text prompt
AI features inside the app
Automated workflows
Roles and access control', 'Операційні команди й малий бізнес, які хочуть замінити таблиці зручними внутрішніми застосунками.', 'Operations teams and small businesses that want to replace spreadsheets with proper internal apps.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'glideapps.com' OR LOWER(`name`) = LOWER('Glide')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'no-code-low-code' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI platform for internal business apps: it builds an app from a spreadsheet, a file or a text prompt, with AI features and workflows.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Glide helps teams build custom business software much faster than traditional development. An app can be built from Google Sheets or Excel, an uploaded file or just a text description, and then you configure screens, data, roles and automated workflows. AI is built right into the app — for processing text, images and documents. Plans: Free; Basic at $25 a month (100 credits, 2 published apps); Plus at $50 a month (250 credits, 5 apps, public apps); Pro from $125 a month (from 500 credits, unlimited apps and workflows); Enterprise on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'App from a spreadsheet, file or text prompt
AI features inside the app
Automated workflows
Roles and access control', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Operations teams and small businesses that want to replace spreadsheets with proper internal apps.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Обмежені кредити, 2 учасники, 10 проєктів', 'Limited credits, 2 team members, 10 projects' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Limited credits, 2 team members, 10 projects', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Basic', 'Basic', 25.00, 'month', '100 кредитів, 2 опубліковані застосунки', '100 credits, 2 published apps' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Basic' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Basic', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '100 credits, 2 published apps', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Plus', 'Plus', 50.00, 'month', '250 кредитів, 5 застосунків, публічна публікація', '250 credits, 5 apps, public publishing' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Plus' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Plus', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '250 credits, 5 apps, public publishing', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 125.00, 'month', 'Від 500 кредитів, необмежені застосунки й процеси, підтримка', 'From 500 credits, unlimited apps and workflows, human support' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'From 500 credits, unlimited apps and workflows, human support', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Adalo — No-code / Low-code
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'adalo.com' OR LOWER(`name`) = LOWER('Adalo'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Adalo', NULL, 'https://www.adalo.com', NULL, NULL, 'No-code конструктор нативних застосунків для iOS і Android та вебзастосунків з базою даних; AI-асистент Ada будує й змінює застосунок за текстовим запитом.', 'A no-code builder for native iOS and Android apps and web apps with a database; the Ada AI assistant builds and edits the app from text prompts.', 'Adalo дає змогу створювати вебзастосунки та нативні застосунки для iOS і Android з одного візуального полотна, без коду. Дизайн збирається з готових компонентів, дані зберігаються у вбудованій базі, а AI-асистент Ada допомагає будувати й змінювати застосунок за текстовими запитами. Готовий застосунок можна опублікувати в App Store і Google Play або на власному домені. Плата не залежить від кількості користувачів чи використання AI. Тарифи (помісячно): Free; Starter — $45 (1 опублікований застосунок); Professional — $65 (2 застосунки, 5 редакторів, геолокація, аналітика); Team — $200 (5 застосунків, 10 редакторів, white label); при річній оплаті на 20% дешевше.', 'Adalo lets you build web apps and native iOS and Android apps from a single visual canvas, without code. The design is assembled from ready-made components, data lives in a built-in database, and the Ada AI assistant helps build and edit the app from text prompts. A finished app can be published to the App Store and Google Play or on your own domain. Pricing does not depend on users or AI usage. Plans (monthly): Free; Starter at $45 (1 published app); Professional at $65 (2 apps, 5 editors, geolocation, analytics); Team at $200 (5 apps, 10 editors, white labelling); 20% cheaper billed yearly.', 'Нативні застосунки iOS і Android та веб
AI-асистент Ada
Вбудована база даних
Публікація в App Store і Google Play
Без плати за використання', 'Native iOS and Android apps plus web
Ada AI assistant
Built-in database
Publishing to the App Store and Google Play
No usage-based charges', 'Підприємці й малий бізнес, які хочуть випустити мобільний застосунок без команди розробників.', 'Entrepreneurs and small businesses that want to launch a mobile app without a development team.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'adalo.com' OR LOWER(`name`) = LOWER('Adalo')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'no-code-low-code' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A no-code builder for native iOS and Android apps and web apps with a database; the Ada AI assistant builds and edits the app from text prompts.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Adalo lets you build web apps and native iOS and Android apps from a single visual canvas, without code. The design is assembled from ready-made components, data lives in a built-in database, and the Ada AI assistant helps build and edit the app from text prompts. A finished app can be published to the App Store and Google Play or on your own domain. Pricing does not depend on users or AI usage. Plans (monthly): Free; Starter at $45 (1 published app); Professional at $65 (2 apps, 5 editors, geolocation, analytics); Team at $200 (5 apps, 10 editors, white labelling); 20% cheaper billed yearly.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Native iOS and Android apps plus web
Ada AI assistant
Built-in database
Publishing to the App Store and Google Play
No usage-based charges', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Entrepreneurs and small businesses that want to launch a mobile app without a development team.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '500 записів на застосунок, необмежені екрани, AI-асистент Ada', '500 records per app, unlimited screens, Ada AI assistant' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '500 records per app, unlimited screens, Ada AI assistant', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Starter', 'Starter', 45.00, 'month', '1 опублікований застосунок, власний домен, App Store; $36/міс при річній оплаті', '1 published app, custom domain, App Store; $36/mo billed yearly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Starter' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Starter', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '1 published app, custom domain, App Store; $36/mo billed yearly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Professional', 'Professional', 65.00, 'month', '2 застосунки, 5 редакторів, геолокація, аналітика; $52/міс при річній оплаті', '2 apps, 5 editors, geolocation, analytics; $52/mo billed yearly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Professional' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Professional', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '2 apps, 5 editors, geolocation, analytics; $52/mo billed yearly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Team', 'Team', 200.00, 'month', '5 застосунків, 10 редакторів, white label; $160/міс при річній оплаті', '5 apps, 10 editors, white labelling; $160/mo billed yearly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Team' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Team', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '5 apps, 10 editors, white labelling; $160/mo billed yearly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- FlutterFlow — No-code / Low-code
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'flutterflow.io' OR LOWER(`name`) = LOWER('FlutterFlow'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'FlutterFlow', NULL, 'https://flutterflow.io', NULL, NULL, 'Візуальний low-code конструктор застосунків на Flutter для мобільних, вебу й десктопу, з AI-генерацією, 1 000+ шаблонів і можливістю завантажити код.', 'A visual low-code Flutter app builder for mobile, web and desktop, with AI generation, 1,000+ templates and code export.', 'FlutterFlow — платформа візуальної розробки застосунків на Flutter. Екрани збираються з компонентів або понад 1 000 готових шаблонів, AI допомагає генерувати сторінки й логіку, а дані підключаються через API та бази даних. З одного проєкту виходять мобільні, веб- і настільні застосунки, які можна тестувати прямо в редакторі. На платних тарифах доступне завантаження коду й APK, на командних — спільна робота в реальному часі, гілки та інтеграція з GitHub. Тарифи (помісячно): Free — до 2 проєктів; Basic — $39; Growth — $80 за перше місце; Business — $150 за перше місце; при річній оплаті приблизно на 25% дешевше.', 'FlutterFlow is a visual development platform for Flutter apps. Screens are built from components or 1,000+ ready templates, AI helps generate pages and logic, and data connects through APIs and databases. One project produces mobile, web and desktop apps that you can test right in the editor. Paid plans let you download the code and APK, and team plans add real-time collaboration, branching and GitHub integration. Plans (monthly): Free — up to 2 projects; Basic — $39; Growth — $80 for the first seat; Business — $150 for the first seat; about 25% cheaper billed yearly.', 'Візуальна розробка на Flutter
Мобільні, веб- і настільні застосунки
AI-генерація сторінок і 1 000+ шаблонів
Завантаження коду та APK
GitHub і спільна робота', 'Visual Flutter development
Mobile, web and desktop apps
AI page generation and 1,000+ templates
Code and APK export
GitHub and real-time collaboration', 'Розробники, стартапи й агенції, які хочуть швидше будувати застосунки й зберігати контроль над кодом.', 'Developers, startups and agencies that want to build apps faster while keeping control of the code.', 'web,desktop', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'flutterflow.io' OR LOWER(`name`) = LOWER('FlutterFlow')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'no-code-low-code' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A visual low-code Flutter app builder for mobile, web and desktop, with AI generation, 1,000+ templates and code export.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'FlutterFlow is a visual development platform for Flutter apps. Screens are built from components or 1,000+ ready templates, AI helps generate pages and logic, and data connects through APIs and databases. One project produces mobile, web and desktop apps that you can test right in the editor. Paid plans let you download the code and APK, and team plans add real-time collaboration, branching and GitHub integration. Plans (monthly): Free — up to 2 projects; Basic — $39; Growth — $80 for the first seat; Business — $150 for the first seat; about 25% cheaper billed yearly.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Visual Flutter development
Mobile, web and desktop apps
AI page generation and 1,000+ templates
Code and APK export
GitHub and real-time collaboration', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Developers, startups and agencies that want to build apps faster while keeping control of the code.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'До 2 проєктів, 10 lite-кредитів', 'Up to 2 projects, 10 lite credits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Up to 2 projects, 10 lite credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Basic', 'Basic', 39.00, 'month', 'Необмежені проєкти, завантаження коду й APK', 'Unlimited projects, code and APK download' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Basic' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Basic', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited projects, code and APK download', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Growth', 'Growth', 80.00, 'month', 'За перше місце ($55 за друге), спільна робота, GitHub', 'First seat ($55 for the second), collaboration, GitHub' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Growth' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Growth', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'First seat ($55 for the second), collaboration, GitHub', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Business', 'Business', 150.00, 'month', 'За перше місце ($85 за місця 2–5), до 5 користувачів, гілки', 'First seat ($85 for seats 2–5), up to 5 users, branching' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Business' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Business', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'First seat ($85 for seats 2–5), up to 5 users, branching', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Retool — No-code / Low-code
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'retool.com' OR LOWER(`name`) = LOWER('Retool'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Retool', NULL, 'https://retool.com', NULL, NULL, 'Low-code платформа для внутрішніх інструментів, автоматизацій і AI-агентів компанії, підключених до ваших баз даних, API та сервісів.', 'A low-code platform for a company''s internal tools, automations and AI agents, connected to your databases, APIs and services.', 'Retool допомагає розробникам, аналітикам і бізнес-командам швидко створювати внутрішні застосунки — адмінки, панелі підтримки, дашборди — та автоматизовані процеси, підключені до власних баз даних і API. Інтерфейс збирається з готових компонентів, логіка пишеться на JavaScript і SQL, а AI допомагає генерувати застосунки й будувати агентів. Тарифи — за користувача на місяць: Free — до 5 користувачів і 500 запусків процесів; Team — $12 за розробника і $7 за внутрішнього користувача; Business — $65 і $18; при річній оплаті на 20% дешевше; Enterprise — за запитом, з SSO, журналами аудиту й контролем версій.', 'Retool helps developers, analysts and business teams quickly build internal apps — admin panels, support consoles, dashboards — and automated workflows connected to their own databases and APIs. The UI is assembled from ready-made components, logic is written in JavaScript and SQL, and AI helps generate apps and build agents. Plans are per user a month: Free — up to 5 users and 500 workflow runs; Team — $12 per builder and $7 per internal user; Business — $65 and $18; 20% cheaper billed yearly; Enterprise on request, with SSO, audit logs and source control.', 'Внутрішні застосунки з готових компонентів
Підключення до баз даних і API
Автоматизовані процеси та AI-агенти
JavaScript і SQL для логіки', 'Internal apps from ready-made components
Connections to databases and APIs
Automated workflows and AI agents
JavaScript and SQL for logic', 'Інженерні та операційні команди компаній, яким потрібні внутрішні інструменти на власних даних.', 'Engineering and operations teams that need internal tools on top of their own data.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'retool.com' OR LOWER(`name`) = LOWER('Retool')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'no-code-low-code' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A low-code platform for a company''s internal tools, automations and AI agents, connected to your databases, APIs and services.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Retool helps developers, analysts and business teams quickly build internal apps — admin panels, support consoles, dashboards — and automated workflows connected to their own databases and APIs. The UI is assembled from ready-made components, logic is written in JavaScript and SQL, and AI helps generate apps and build agents. Plans are per user a month: Free — up to 5 users and 500 workflow runs; Team — $12 per builder and $7 per internal user; Business — $65 and $18; 20% cheaper billed yearly; Enterprise on request, with SSO, audit logs and source control.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Internal apps from ready-made components
Connections to databases and APIs
Automated workflows and AI agents
JavaScript and SQL for logic', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Engineering and operations teams that need internal tools on top of their own data.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'До 5 користувачів, 500 запусків процесів на місяць', 'Up to 5 users, 500 workflow runs a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Up to 5 users, 500 workflow runs a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Team', 'Team', 12.00, 'month', 'За розробника ($7 за внутрішнього користувача); $10 при річній оплаті', 'Per builder ($7 per internal user); $10 billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Team' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Team', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per builder ($7 per internal user); $10 billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Business', 'Business', 65.00, 'month', 'За розробника ($18 за внутрішнього користувача); $50 при річній оплаті', 'Per builder ($18 per internal user); $50 billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Business' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Business', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per builder ($18 per internal user); $50 billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Bubble')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'no-code-low-code' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Airtable')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'development-it' AND s.`slug` = 'no-code-low-code' LIMIT 1;
