-- AI LAB HUB: пакет batch_0001, продуктів: 8, 2026-09-21 00:57
SET NAMES utf8mb4;
START TRANSACTION;

-- getimg.ai
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `short_description`, `full_description`, `main_features`, `target_audience`, `platform`, `skill_level`, `status`, `partnership_status`, `internal_registration_url`, `created_at`) SELECT 'getimg.ai', 'assets/images/logos/getimg-ai.webp', 'https://getimg.ai', 'Єдиний робочий простір для створення та редагування зображень, відео, музики й голосу з провідними моделями ШІ — без пошуку моделей і складного налаштування.', 'getimg.ai об\'єднує в одному просторі створення зображень, відео, музики й мовлення за допомогою провідних моделей ШІ, які автоматично підбираються під завдання. Є генерація й редагування зображень, збільшення розміру та роздільності зображень і відео, зміна розміру, видалення фону, створення музики та голосу. На сайті згадано моделі GPT Image, Qwen Image, Grok Imagine та Wan, які регулярно додаються. Працювати можна як індивідуально, так і командою; усі тарифи передбачають комерційні права, а кількість кредитів на місяць та доступні моделі залежать від тарифу. Є оплата помісячно або на рік зі знижкою 20%.', 'Створення та редагування зображень різними моделями ШІ\nСтворення відео\nСтворення музики та голосу\nЗбільшення роздільності зображень і відео\nВидалення фону та зміна розміру зображень\nКомандна робота в одному просторі\nКомерційні права на всіх тарифах', 'Автори контенту та команди, які створюють зображення, відео й аудіо за допомогою ШІ', 'web', 'none', 'published', 'found', 'https://partners.dub.co/getimg-ai/apply', NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'getimg.ai');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'getimg.ai' ORDER BY `id` LIMIT 1);
INSERT INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @new = 1 AND c.`name` = 'Мультимедіа' AND s.`name` = 'Генерація зображень';
INSERT INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @new = 1 AND c.`name` = 'Мультимедіа' AND s.`name` = 'Генерація відео';
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @new = 1 AND c.`name` = 'Мультимедіа';

-- Civitai
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `short_description`, `full_description`, `main_features`, `target_audience`, `platform`, `skill_level`, `status`, `partnership_status`, `internal_registration_url`, `created_at`) SELECT 'Civitai', NULL, 'https://civitai.com', 'Спільнота для пошуку, створення й обміну зображеннями та моделями ШІ: тисячі безкоштовних моделей Stable Diffusion і Flux, а також генерація власних картинок.', 'Civitai — спільнота творців генеративного ШІ, де можна знаходити безкоштовні моделі Stable Diffusion і Flux, переглядати зображення, відео та 3D-моделі, створені користувачами, і генерувати власні. На сайті є розділи моделей, зображень, відео, статей, коміксів і конкурсів. Внутрішня валюта Buzz використовується для генерації; платні членства Bronze, Silver і Gold дають щомісячні Buzz, безрекламний перегляд, пріоритетну генерацію, приватні моделі, ранній доступ до нових функцій і програму для авторів, у якій можна заробляти на своїх моделях.', 'Каталог безкоштовних моделей Stable Diffusion і Flux\nГенерація зображень на сайті\nГалереї зображень, відео та 3D-моделей спільноти\nВнутрішня валюта Buzz для генерації\nПлатні членства з пріоритетною генерацією та приватними моделями\nПрограма для авторів моделей', 'Творці й любителі генеративного ШІ, які шукають моделі та діляться роботами', 'web', 'basic', 'published', 'found', NULL, NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'civitai.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'civitai.com' ORDER BY `id` LIMIT 1);
INSERT INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @new = 1 AND c.`name` = 'Мультимедіа' AND s.`name` = 'Генерація зображень';
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @new = 1 AND c.`name` = 'Мультимедіа';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `price`, `period`, `description`) SELECT @pid, 'Bronze', 10, 'month', '10 000 Green Buzz на місяць, 3 приватні моделі, безрекламний перегляд' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `price`, `period`, `description`) SELECT @pid, 'Silver', 25, 'month', '25 000 Green Buzz на місяць, 10 приватних моделей, преміум-підтримка' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `price`, `period`, `description`) SELECT @pid, 'Gold', 50, 'month', '50 000 Green Buzz на місяць' FROM DUAL WHERE @new = 1;

-- Pixlr
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `short_description`, `full_description`, `main_features`, `target_audience`, `platform`, `skill_level`, `status`, `partnership_status`, `internal_registration_url`, `created_at`) SELECT 'Pixlr', 'assets/images/logos/pixlr-com.webp', 'https://pixlr.com', 'Безкоштовний онлайн-фоторедактор і генератор зображень зі ШІ: редагуйте фото, створюйте картинки й відео за текстом, міняйте обличчя та прибирайте фон прямо в браузері.', 'Pixlr — набір онлайн-редакторів фото, інструментів дизайну та функцій ШІ, які працюють у браузері без встановлення. Можна редагувати й покращувати фото, створювати зображення й відео за текстовим описом, замінювати обличчя, видаляти фон і об\'єкти, робити колажі, заповнювати або розширювати зображення генеративними інструментами та збільшувати роздільність. Є асистент, який змінює зображення за описом словами. Для генерації використовуються різні моделі, зокрема Flux, Kling, Recraft, Google Veo та Stable Diffusion. Базові можливості безкоштовні, платні плани додають більше кредитів ШІ, приватний режим, бібліотеку шрифтів і шаблонів та відсутність реклами.', 'Створення зображень і відео за текстовим описом\nРедагування фото ШІ: заміна об\'єктів, видалення фону\nГенеративне заповнення та розширення зображень\nЗаміна облич і фотоколажі\nЗбільшення роздільності зображень\nКілька моделей ШІ на вибір', 'Усі, хто редагує фото й створює зображення, від новачків до авторів контенту', 'web', 'none', 'published', 'found', NULL, NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'pixlr.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'pixlr.com' ORDER BY `id` LIMIT 1);
INSERT INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @new = 1 AND c.`name` = 'Мультимедіа' AND s.`name` = 'Генерація зображень';
INSERT INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @new = 1 AND c.`name` = 'Мультимедіа' AND s.`name` = 'Фотографія';
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @new = 1 AND c.`name` = 'Мультимедіа';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `price`, `period`, `description`) SELECT @pid, 'Plus', 2.49, 'month', '80 кредитів ШІ на місяць, без реклами; $1.99 за місяць при оплаті за рік' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `price`, `period`, `description`) SELECT @pid, 'Premium', 9.99, 'month', '1000 кредитів ШІ на місяць, усі моделі, приватний режим; $7.99 за місяць при оплаті за рік' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `price`, `period`, `description`) SELECT @pid, 'Ultra', 24.99, 'month', 'необмежені «швидкі» генерації зображень; $19.99 за місяць при оплаті за рік' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `price`, `period`, `description`) SELECT @pid, 'Ultra Max', 49.99, 'month', '$39.99 за місяць при оплаті за рік' FROM DUAL WHERE @new = 1;

-- DeepAI
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `short_description`, `full_description`, `main_features`, `target_audience`, `platform`, `skill_level`, `status`, `partnership_status`, `internal_registration_url`, `created_at`) SELECT 'DeepAI', NULL, 'https://deepai.org', 'Універсальна платформа зі ШІ: створення зображень, відео, музики й голосу, редагування фото та розмовний чат — просто в браузері, без обов\'язкової реєстрації.', 'DeepAI — платформа творчих інструментів зі штучним інтелектом, що працює в браузері. За одним запитом можна створити зображення, відредагувати фото, зробити коротке відео, скласти музику або поспілкуватися з AI-чатом голосом. Є генератор зображень, редактор фото, видалення фону, розфарбування чорно-білих фото, підвищення роздільності, а також інструменти для розпізнавання зображень створених ШІ й API для розробників. Спробувати можна безкоштовно й без облікового запису. Підписка DeepAI Pro за $9.99 на місяць дає великі ліміти, приватні генерації та відсутність реклами; понад ліміт витрати списуються з передоплаченого гаманця. Є мобільний застосунок і розширення для Chrome.', 'Генератор зображень за текстовим описом\nСтворення відео та музики\nРедактор фото: видалення фону, розфарбування, підвищення роздільності\nГолосовий чат зі ШІ\nAPI для розробників\nМобільний застосунок і розширення для Chrome', 'Любителі, художники та розробники, яким потрібні доступні інструменти зі ШІ', 'web,mobile', 'none', 'published', 'found', NULL, NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'deepai.org');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'deepai.org' ORDER BY `id` LIMIT 1);
INSERT INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @new = 1 AND c.`name` = 'Мультимедіа' AND s.`name` = 'Генерація зображень';
INSERT INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @new = 1 AND c.`name` = 'Мультимедіа' AND s.`name` = 'Генерація відео';
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @new = 1 AND c.`name` = 'Мультимедіа';
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `price`, `period`, `description`) SELECT @pid, 'DeepAI Pro', 9.99, 'month', 'великі щомісячні ліміти, приватні генерації, без реклами; понад ліміт — списання з гаманця' FROM DUAL WHERE @new = 1;

-- SeaArt AI
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `short_description`, `full_description`, `main_features`, `target_audience`, `platform`, `skill_level`, `status`, `partnership_status`, `internal_registration_url`, `created_at`) SELECT 'SeaArt AI', 'assets/images/logos/seaart-ai.webp', 'https://seaart.ai', 'Універсальна платформа й спільнота для створення зображень, відео та персонажів за допомогою ШІ: генеруйте, змінюйте чужі роботи й діліться своїми.', 'SeaArt AI — спільнота творців, де ідеї перетворюються на зображення, відео та персонажів за лічені хвилини. Можна створювати зображення й відео за допомогою широкого вибору моделей (згадано Veo, Sora, Kling, Wan, Flux, Seedream, Nano Banana та інші), переробляти роботи інших користувачів у форматі «Remix», використовувати шаблони й ефекти. Є генератор зображень, збільшення роздільності, фільтри, гумка та видалення фону, а також відеофункції: рух камери, синхронізація губ, відео за референсом. Доступний мобільний застосунок SeaArt.', 'Генератор зображень і відео на різних моделях\nRemix — переробка робіт спільноти\nШаблони, ефекти й фільтри\nЗбільшення роздільності, видалення фону та об\'єктів\nВідеофункції: рух камери, синхронізація губ\nМобільний застосунок', 'Творці та любителі візуального ШІ-контенту', 'web,mobile', 'none', 'published', 'found', NULL, NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'seaart.ai');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'seaart.ai' ORDER BY `id` LIMIT 1);
INSERT INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @new = 1 AND c.`name` = 'Мультимедіа' AND s.`name` = 'Генерація зображень';
INSERT INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @new = 1 AND c.`name` = 'Мультимедіа' AND s.`name` = 'Генерація відео';
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @new = 1 AND c.`name` = 'Мультимедіа';

-- Mage
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `short_description`, `full_description`, `main_features`, `target_audience`, `platform`, `skill_level`, `status`, `partnership_status`, `internal_registration_url`, `created_at`) SELECT 'Mage', 'assets/images/logos/mage-space.webp', 'https://mage.space', 'Безлімітний генератор зображень і відео зі ШІ прямо в браузері: безкоштовний старт, різні моделі, послідовні персонажі та режим приватності за замовчуванням.', 'Mage — безкоштовний на старті генератор зображень і відео, який працює в браузері. Підтримує багато моделей, серед яких Stable Diffusion, Flux, Qwen, Wan, Nano Banana та Veo, а також власні моделі з більшою творчою свободою. Можна створити послідовного AI-персонажа з одного референсного зображення й використовувати його в необмеженій кількості зображень і відео. Функція Motion Control переносить рух з референсного відео на персонажа. Безкоштовно можна почати, а «Gems» дозволяють запускати будь-яку модель на вимогу без підписки; преміум-членство додає необмежену генерацію, щомісячні Gems та ексклюзивні функції. Генерації приватні за замовчуванням.', 'Генерація зображень і відео в браузері\nПонад десяток моделей: Stable Diffusion, Flux, Wan, Veo та інші\nПослідовні AI-персонажі за одним референсом\nMotion Control: перенесення руху з відео на персонажа\nGems для запуску моделей на вимогу без підписки\nПриватні генерації за замовчуванням', 'Художники й автори персонажів для історій та контенту', 'web', 'none', 'published', 'found', NULL, NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'mage.space');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'mage.space' ORDER BY `id` LIMIT 1);
INSERT INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @new = 1 AND c.`name` = 'Мультимедіа' AND s.`name` = 'Генерація зображень';
INSERT INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @new = 1 AND c.`name` = 'Мультимедіа' AND s.`name` = 'Генерація відео';
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @new = 1 AND c.`name` = 'Мультимедіа';

-- Scenario
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `short_description`, `full_description`, `main_features`, `target_audience`, `platform`, `skill_level`, `status`, `partnership_status`, `internal_registration_url`, `created_at`) SELECT 'Scenario', 'assets/images/logos/scenario-com.webp', 'https://scenario.com', 'Платформа творчого ШІ для команд і розробників: власні моделі, навчені на вашому стилі, робочі процеси й доступ до сотень моделей для зображень, відео, 3D та аудіо.', 'Scenario — платформа, на якій команди будують робочі процеси для зображень, відео, аудіо й 3D або просто описують завдання, а помічник Genie виконує решту. Можна навчити власну модель на 5–100 еталонних зображень, щоб результати послідовно зберігали ваш стиль і правила бренду. Платформа дає доступ до сотень моделей від десятків постачальників, порівняння результатів поруч, візуальний редактор багатокрокових процесів, агентів, які пакетно створюють матеріали, API для розробників та MCP для агентів. Сайт заявляє відповідність SOC 2 Type II та приватність за замовчуванням.', 'Навчання власних моделей на 5–100 зображеннях\nДоступ до сотень моделей для зображень, відео, 3D й аудіо\nВізуальний редактор робочих процесів\nАгенти для пакетного створення матеріалів\nAPI для розробників і MCP для агентів\nSSO та відповідність SOC 2 Type II', 'Ігрові й творчі студії, команди дизайну та розробники, яким потрібні послідовні матеріали в єдиному стилі', 'web', 'basic', 'published', 'found', NULL, NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'scenario.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'scenario.com' ORDER BY `id` LIMIT 1);
INSERT INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @new = 1 AND c.`name` = 'Мультимедіа' AND s.`name` = 'Генерація зображень';
INSERT INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @new = 1 AND c.`name` = 'Мультимедіа' AND s.`name` = '3D та анімація';
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @new = 1 AND c.`name` = 'Мультимедіа';

-- StarryAI
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `short_description`, `full_description`, `main_features`, `target_audience`, `platform`, `skill_level`, `status`, `partnership_status`, `internal_registration_url`, `created_at`) SELECT 'StarryAI', 'assets/images/logos/starryai-com.webp', 'https://starryai.com', 'Генератор зображень за текстом чи емодзі зі ШІ: безкоштовні щоденні картинки без водяних знаків, понад тисяча стилів і повне право власності на створене.', 'StarryAI створює зображення за вашими словами або емодзі. Щодня доступні безкоштовні зображення без водяних знаків, а після реєстрації рахунок поповнюється 5 люменами (25 зображень). Сайт підкреслює, що ви залишаєтесь власником створених зображень і маєте комерційні права. Є понад 1000 стилів і моделей, а також інструменти для покращення зображень, підвищення роздільності та видалення фону. Серед напрямів на сайті — портрети, аніме, ілюстрації, персонажі, інтер\'єри, аватари й портретні фото.', 'Генерація зображень за текстом чи емодзі\nБезкоштовні щоденні зображення без водяних знаків\nПонад 1000 стилів і моделей\nПокращення, збільшення роздільності та видалення фону\nПовне право власності й комерційні права на створене', 'Всі, хто хоче швидко створювати ШІ-зображення для творчості та особистих і комерційних проєктів', 'web', 'none', 'published', 'found', NULL, NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'starryai.com');
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'starryai.com' ORDER BY `id` LIMIT 1);
INSERT INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @new = 1 AND c.`name` = 'Мультимедіа' AND s.`name` = 'Генерація зображень';
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @new = 1 AND c.`name` = 'Мультимедіа';

COMMIT;
