SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-09-29: «Здоров'я та краса» → нова підкатегорія «Реабілітація та фізіотерапія» — 2 продукти
--   PosturaZen — Здоров'я та краса › Реабілітація та фізіотерапія
--   ScolioEx — Здоров'я та краса › Реабілітація та фізіотерапія
-- Сайти й ціни перевірено на офіційних сторінках 2026-09-29 (posturazen.com, App Store США).
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): вкладка SQL → вставити вміст файлу → Вперёд.
-- Без фіксованих id і без DROP / DELETE: підкатегорія — INSERT IGNORE (унікальний ключ category_id + slug);
-- продукт — лише якщо немає продукту з тим самим нормалізованим URL АБО назвою; інакше наявному продукту
-- лише додаються категорія й підкатегорія, тарифи й переклади не чіпаються.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- Разом із цим SQL на хостинг треба залити public/category.php (іконка нової підкатегорії).
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Реабілітація та фізіотерапія', 'Rehabilitation & Physiotherapy', 'rehabilitation-physiotherapy' FROM `categories` c WHERE c.`slug` = 'health-beauty' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- PosturaZen — Здоров'я та краса › Реабілітація та фізіотерапія
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'PosturaZen', NULL, 'https://posturazen.com', NULL, NULL, 'Сканує поставу через камеру телефону: оцінює кут Кобба, різницю висоти плечей і положення таза без рентгена та показує зміни з часом. Це інструмент скринінгу й моніторингу, а не заміна рентгена чи діагнозу лікаря.', 'Scans posture with your phone camera: estimates the Cobb angle, shoulder height difference and pelvic position without an X-ray and shows changes over time. It is a screening and monitoring tool, not a replacement for an X-ray or a doctor''s diagnosis.', 'PosturaZen — мобільний застосунок зі штучним інтелектом, який допомагає помітити й відстежувати проблеми з поставою та ознаки викривлення хребта. Достатньо камери телефону: застосунок аналізує положення тіла й оцінює кут Кобба, різницю висоти плечей, положення таза, виступання лопаток та інші показники — без рентгена. Результати зберігаються у звітах із 3D-моделюванням, тож можна бачити, як змінюється постава з часом, і передати звіт лікарю чи фізіотерапевту. AI Workout Companion стежить за технікою призначених вправ у реальному часі й підказує, як виконувати їх правильно. Важливо: PosturaZen — інструмент скринінгу й моніторингу, він не замінює рентген і не ставить медичний діагноз; рішення про лікування ухвалює лікар. Застосунок готується до виходу на iOS та Android, зараз триває бета-тестування. Ціни на сайті не опубліковані.', 'PosturaZen is an AI-powered mobile app that helps you spot and track posture problems and signs of spinal curvature. All it needs is your phone camera: the app analyses body position and estimates the Cobb angle, shoulder height difference, pelvic position, shoulder blade projection and other measurements — without an X-ray. Results are saved in reports with 3D modelling, so you can see how your posture changes over time and share a report with a doctor or physiotherapist. The AI Workout Companion watches your form during prescribed exercises in real time and guides you to do them correctly. Important: PosturaZen is a screening and monitoring tool; it does not replace an X-ray or give a medical diagnosis, and treatment decisions are made by a doctor. The app is preparing to launch on iOS and Android and is currently in beta testing. Pricing is not published on the website.', 'AI-сканування постави й оцінка кута Кобба через камеру телефону
Вимірювання різниці висоти плечей і положення таза без рентгена
Відстеження прогресу з часом через звіти й 3D-моделювання
AI-контроль техніки виконання вправ у реальному часі
Звіти для передачі лікарю чи фізіотерапевту', 'AI posture scanning and Cobb angle estimation with your phone camera
Shoulder height difference and pelvic position measured without an X-ray
Progress tracking over time with reports and 3D modelling
Real-time AI feedback on exercise form
Reports to share with a doctor or physiotherapist', 'Батьки, які стежать за поставою дитини, дорослі з підозрою на сколіоз, а також пацієнти з уже встановленим діагнозом, яким потрібно відстежувати стан між візитами до лікаря.', 'Parents keeping an eye on their child''s posture, adults who suspect scoliosis, and patients with a confirmed diagnosis who want to monitor their condition between doctor visits.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-09-29 00:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'posturazen.com' OR LOWER(`name`) = LOWER('PosturaZen')));
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'posturazen.com' OR LOWER(`name`) = LOWER('PosturaZen')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'rehabilitation-physiotherapy' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Scans posture with your phone camera: estimates the Cobb angle, shoulder height difference and pelvic position without an X-ray and shows changes over time. It is a screening and monitoring tool, not a replacement for an X-ray or a doctor''s diagnosis.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'PosturaZen is an AI-powered mobile app that helps you spot and track posture problems and signs of spinal curvature. All it needs is your phone camera: the app analyses body position and estimates the Cobb angle, shoulder height difference, pelvic position, shoulder blade projection and other measurements — without an X-ray. Results are saved in reports with 3D modelling, so you can see how your posture changes over time and share a report with a doctor or physiotherapist. The AI Workout Companion watches your form during prescribed exercises in real time and guides you to do them correctly. Important: PosturaZen is a screening and monitoring tool; it does not replace an X-ray or give a medical diagnosis, and treatment decisions are made by a doctor. The app is preparing to launch on iOS and Android and is currently in beta testing. Pricing is not published on the website.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI posture scanning and Cobb angle estimation with your phone camera
Shoulder height difference and pelvic position measured without an X-ray
Progress tracking over time with reports and 3D modelling
Real-time AI feedback on exercise form
Reports to share with a doctor or physiotherapist', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Parents keeping an eye on their child''s posture, adults who suspect scoliosis, and patients with a confirmed diagnosis who want to monitor their condition between doctor visits.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ціна за запитом', 'Price on request', NULL, 'month', 'За запитом: вартість на сайті не опублікована — див. posturazen.com', 'On request: pricing is not published — see posturazen.com' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, LAST_INSERT_ID(), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Price on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'On request: pricing is not published — see posturazen.com', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- ScolioEx — Здоров'я та краса › Реабілітація та фізіотерапія
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'ScolioEx', NULL, 'https://apps.apple.com/us/app/scolioex-scoliosis-exercises/id6755197741', NULL, NULL, 'Відеовправи при сколіозі від фізіотерапевта, який сам живе зі сколіозом: постава, баланс, рухливість і зміцнення кора вдома без обладнання. Застосунок позиціонує себе як персональний гід з руху, а не медичне лікування.', 'Scoliosis exercise videos from a physiotherapist who lives with scoliosis: posture, balance, mobility and core strength at home with no equipment. The app presents itself as a personal movement guide, not medical treatment.', 'ScolioEx — застосунок із відеовправами для людей зі сколіозом, створений фізіотерапевтом, який сам живе з цим діагнозом. Заняття спрямовані на поставу, баланс, рухливість і зміцнення м''язів кора, допомагають зняти напругу й покращити вирівнювання тіла. Кожна вправа має зрозумілий відеосупровід і підказки, тож займатися можна вдома у власному темпі — без обладнання й без відвідування клініки. Можна збирати персональні добірки вправ, стежити за прогресом і вмикати нагадування, щоб займатися регулярно. Застосунок працює на iPhone, iPad і Mac і синхронізує дані через iCloud. Важливо: ScolioEx сам наголошує, що він не є медичним лікуванням, а лише персональним гідом з руху; план лікування сколіозу варто узгоджувати з лікарем. Застосунок безкоштовний для завантаження: 5 вправ доступні всім, повна бібліотека відкривається одноразовою покупкою без підписки, є 14-денний пробний період.', 'ScolioEx is an exercise video app for people with scoliosis, created by a physiotherapist who lives with the condition. Sessions focus on posture, balance, mobility and core strength, helping to ease tension and improve alignment. Every exercise comes with clear video guidance and cues, so you can train at home at your own pace — with no equipment and no clinic visits. You can build personal exercise collections, track your progress and set reminders to keep a regular routine. The app runs on iPhone, iPad and Mac and syncs through iCloud. Important: ScolioEx itself states that it is not medical treatment but a personal movement guide; a scoliosis treatment plan should be agreed with a doctor. The app is free to download: 5 exercises are available to everyone, the full library is unlocked with a one-time purchase with no subscription, and there is a 14-day free trial.', 'Відеовправи для постави, балансу й мобільності
Персоналізовані добірки вправ
Відстеження прогресу й нагадування
Заняття вдома без обладнання
Синхронізація через iCloud на iPhone, iPad і Mac', 'Video exercises for posture, balance and mobility
Personalised exercise collections
Progress tracking and reminders
Home workouts with no equipment
iCloud sync across iPhone, iPad and Mac', 'Люди зі сколіозом, які хочуть регулярно займатися вдома без обладнання й без відвідування клініки.', 'People with scoliosis who want a regular home exercise routine with no equipment and no clinic visits.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-09-29 00:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'apps.apple.com/us/app/scolioex-scoliosis-exercises/id6755197741' OR LOWER(`name`) = LOWER('ScolioEx')));
SET @new = ROW_COUNT();
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'apps.apple.com/us/app/scolioex-scoliosis-exercises/id6755197741' OR LOWER(`name`) = LOWER('ScolioEx')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'rehabilitation-physiotherapy' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Scoliosis exercise videos from a physiotherapist who lives with scoliosis: posture, balance, mobility and core strength at home with no equipment. The app presents itself as a personal movement guide, not medical treatment.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'ScolioEx is an exercise video app for people with scoliosis, created by a physiotherapist who lives with the condition. Sessions focus on posture, balance, mobility and core strength, helping to ease tension and improve alignment. Every exercise comes with clear video guidance and cues, so you can train at home at your own pace — with no equipment and no clinic visits. You can build personal exercise collections, track your progress and set reminders to keep a regular routine. The app runs on iPhone, iPad and Mac and syncs through iCloud. Important: ScolioEx itself states that it is not medical treatment but a personal movement guide; a scoliosis treatment plan should be agreed with a doctor. The app is free to download: 5 exercises are available to everyone, the full library is unlocked with a one-time purchase with no subscription, and there is a 14-day free trial.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Video exercises for posture, balance and mobility
Personalised exercise collections
Progress tracking and reminders
Home workouts with no equipment
iCloud sync across iPhone, iPad and Mac', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People with scoliosis who want a regular home exercise routine with no equipment and no clinic visits.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовно', 'Free', 0.00, 'free', '5 вправ для всіх і 14-денний пробний період Premium без банківської картки', '5 exercises for everyone and a 14-day Premium trial with no credit card' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, LAST_INSERT_ID(), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '5 exercises for everyone and a 14-day Premium trial with no credit card', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premium Lifetime', 'Premium Lifetime', 9.99, 'one_time', 'Одноразова покупка без підписки: повна бібліотека вправ (ціна в App Store США)', 'One-time purchase, no subscription: the full exercise library (US App Store price)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, LAST_INSERT_ID(), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Premium Lifetime', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'One-time purchase, no subscription: the full exercise library (US App Store price)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

