SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Освіта та знання» → нова підкатегорія «Дослідження та пошук» — 7 нових продуктів, 5 прив'язок наявних
--   Gemini Notebook (NotebookLM) — Дослідження та пошук
--   Kagi — Дослідження та пошук
--   scite — Дослідження та пошук
--   ResearchRabbit — Дослідження та пошук
--   Undermind — Дослідження та пошук
--   Exa — Дослідження та пошук
--   You.com — Дослідження та пошук
--   (наявний) Perplexity → Дослідження та пошук
--   (наявний) Elicit → Дослідження та пошук
--   (наявний) Consensus → Дослідження та пошук
--   (наявний) SciSpace → Дослідження та пошук
--   (наявний) Semantic Scholar → Дослідження та пошук
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Дослідження та пошук', 'Research & Search', 'research-search' FROM `categories` c WHERE c.`slug` = 'education-knowledge' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Gemini Notebook (NotebookLM) — Дослідження та пошук
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'notebook.google' OR LOWER(`name`) = LOWER('Gemini Notebook (NotebookLM)'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Gemini Notebook (NotebookLM)', NULL, 'https://notebook.google', NULL, NULL, 'AI-помічник Google для досліджень на ваших джерелах (колишній NotebookLM): відповідає лише на основі завантажених документів, робить аудіопереказ, відеоогляди та ментальні карти.', 'Google''s AI research assistant grounded in your own sources (formerly NotebookLM): it answers only from the documents you add and creates audio overviews, video overviews and mind maps.', 'Gemini Notebook — так тепер називається NotebookLM, інструмент Google для роботи з власними джерелами. У блокнот додають документи, PDF, сайти, відео чи нотатки, і AI на основі моделей Gemini відповідає на запитання, посилаючись саме на ці матеріали, а не на інтернет загалом. Він уміє робити інтерактивні аудіоперекази у форматі розмови, відеоогляди, ментальні карти, конспекти й навчальні матеріали. Є добірка публічних блокнотів, з яких можна почати. Працює у вебі та в мобільних застосунках. Базові можливості безкоштовні; розширені ліміти доступні в планах Google AI Plus, AI Pro та AI Ultra (в Україні AI Pro — ₴909,99 на місяць).', 'Gemini Notebook is the new name of NotebookLM, Google''s tool for working with your own sources. You add documents, PDFs, websites, videos or notes to a notebook, and AI built on Gemini models answers questions citing exactly those materials rather than the web at large. It can create interactive audio overviews in a conversation format, video overviews, mind maps, summaries and study materials. A collection of public notebooks helps you get started. It works on the web and in mobile apps. Core features are free; higher limits come with the Google AI Plus, AI Pro and AI Ultra plans (AI Pro costs ₴909.99 a month in Ukraine).', 'Відповіді лише на основі ваших джерел із посиланнями
Аудіопереказ у форматі розмови
Відеоогляди й ментальні карти
Конспекти та навчальні матеріали
Веб і мобільні застосунки', 'Answers grounded only in your sources, with citations
Audio overviews in a conversation format
Video overviews and mind maps
Summaries and study materials
Web and mobile apps', 'Студенти, дослідники, журналісти й аналітики, які працюють з великою кількістю власних матеріалів.', 'Students, researchers, journalists and analysts who work with large sets of their own materials.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'notebook.google' OR LOWER(`name`) = LOWER('Gemini Notebook (NotebookLM)')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' AND s.`slug` = 'research-search' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Google''s AI research assistant grounded in your own sources (formerly NotebookLM): it answers only from the documents you add and creates audio overviews, video overviews and mind maps.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Gemini Notebook is the new name of NotebookLM, Google''s tool for working with your own sources. You add documents, PDFs, websites, videos or notes to a notebook, and AI built on Gemini models answers questions citing exactly those materials rather than the web at large. It can create interactive audio overviews in a conversation format, video overviews, mind maps, summaries and study materials. A collection of public notebooks helps you get started. It works on the web and in mobile apps. Core features are free; higher limits come with the Google AI Plus, AI Pro and AI Ultra plans (AI Pro costs ₴909.99 a month in Ukraine).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Answers grounded only in your sources, with citations
Audio overviews in a conversation format
Video overviews and mind maps
Summaries and study materials
Web and mobile apps', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Students, researchers, journalists and analysts who work with large sets of their own materials.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовно', 'Free', 0.00, 'free', 'Базові можливості з обмеженнями', 'Core features with limits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Безкоштовно' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Core features with limits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'У складі Google AI Pro', 'Included in Google AI Pro', NULL, 'month', '₴909,99 на місяць в Україні: у 5 разів більше результатів у Gemini Notebook', '₴909.99 a month in Ukraine: 5× more Gemini Notebook output' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'У складі Google AI Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Included in Google AI Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '₴909.99 a month in Ukraine: 5× more Gemini Notebook output', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Kagi — Дослідження та пошук
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'kagi.com' OR LOWER(`name`) = LOWER('Kagi'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Kagi', NULL, 'https://kagi.com', NULL, NULL, 'Платна пошукова система без реклами й стеження, з AI-асистентом: якісна видача, налаштування сайтів у результатах і режим глибокого дослідження з провідними моделями.', 'A paid search engine with no ads or tracking and an AI assistant: high-quality results, control over which sites rank, and a research mode with leading models.', 'Kagi — пошукова система, яку фінансують самі користувачі, тому в ній немає реклами, трекінгу та SEO-сміття. Видачу можна налаштовувати: підвищувати, знижувати чи блокувати окремі сайти, використовувати лінзи для тематичного пошуку. Kagi Assistant дає доступ до моделей Claude, GPT, Gemini та інших, з режимами швидкої відповіді й глибокого дослідження з джерелами. Тарифи: пробний — безкоштовно 100 пошуків; Starter — $5 на місяць (300 пошуків); Professional — $10 на місяць (необмежений пошук); Ultimate — $25 на місяць (необмежений пошук, режим Research і преміальні моделі). Річна оплата дешевша на 10%, а в місяці без використання гроші не списуються.', 'Kagi is a search engine funded by its users, so it has no ads, tracking or SEO spam. You can tune results: raise, lower or block specific sites and use lenses for topic-focused search. Kagi Assistant gives access to Claude, GPT, Gemini and other models, with quick-answer and in-depth research modes with sources. Plans: Trial — 100 free searches; Starter — $5 a month (300 searches); Professional — $10 a month (unlimited search); Ultimate — $25 a month (unlimited search, Research mode and premium models). Annual billing is 10% cheaper, and you are not charged in months without usage.', 'Пошук без реклами й трекінгу
Налаштування сайтів у видачі та лінзи
Kagi Assistant з Claude, GPT, Gemini
Режим глибокого дослідження з джерелами', 'Search with no ads or tracking
Site ranking controls and lenses
Kagi Assistant with Claude, GPT, Gemini
In-depth research mode with sources', 'Ті, кому важлива приватність і якісна видача без реклами: розробники, дослідники, журналісти.', 'People who value privacy and clean, ad-free results: developers, researchers and journalists.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'kagi.com' OR LOWER(`name`) = LOWER('Kagi')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' AND s.`slug` = 'research-search' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A paid search engine with no ads or tracking and an AI assistant: high-quality results, control over which sites rank, and a research mode with leading models.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Kagi is a search engine funded by its users, so it has no ads, tracking or SEO spam. You can tune results: raise, lower or block specific sites and use lenses for topic-focused search. Kagi Assistant gives access to Claude, GPT, Gemini and other models, with quick-answer and in-depth research modes with sources. Plans: Trial — 100 free searches; Starter — $5 a month (300 searches); Professional — $10 a month (unlimited search); Ultimate — $25 a month (unlimited search, Research mode and premium models). Annual billing is 10% cheaper, and you are not charged in months without usage.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Search with no ads or tracking
Site ranking controls and lenses
Kagi Assistant with Claude, GPT, Gemini
In-depth research mode with sources', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People who value privacy and clean, ad-free results: developers, researchers and journalists.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Trial', 'Trial', 0.00, 'free', '100 пошуків і 100 запитів до асистента', '100 searches and 100 Assistant interactions' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Trial' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Trial', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '100 searches and 100 Assistant interactions', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Starter', 'Starter', 5.00, 'month', '300 пошуків на місяць, швидкий режим асистента', '300 searches a month, Quick mode Assistant' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Starter' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Starter', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '300 searches a month, Quick mode Assistant', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Professional', 'Professional', 10.00, 'month', 'Необмежений пошук, розширене використання асистента', 'Unlimited search, expanded Assistant usage' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Professional' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Professional', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited search, expanded Assistant usage', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ultimate', 'Ultimate', 25.00, 'month', 'Необмежений пошук, режим Research, преміальні моделі', 'Unlimited search, Research mode, premium models' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ultimate' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Ultimate', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited search, Research mode, premium models', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- scite — Дослідження та пошук
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'scite.ai' OR LOWER(`name`) = LOWER('scite'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'scite', NULL, 'https://scite.ai', NULL, NULL, 'AI-асистент для наукових досліджень зі Smart Citations: показує, чи підтверджують наступні роботи висновки статті, чи заперечують їх, і відповідає з посиланнями на джерела.', 'An AI research assistant with Smart Citations: it shows whether later studies support or contradict a paper''s findings and answers with references to sources.', 'scite допомагає знаходити й оцінювати наукову літературу. Його головна особливість — Smart Citations: для кожної статті видно, у якому контексті її цитують і чи підтверджують наступні дослідження її висновки, чи суперечать їм. База охоплює понад 1,6 млрд цитувань із більш ніж 300 млн наукових джерел. AI-асистент відповідає на запитання з посиланнями на реальні статті, є пошук, колекції статей, API та доступ через MCP для інших AI-інструментів. Тарифи: Connect — безкоштовно (лише MCP); Basic — $20 на місяць ($240 на рік); Pro — $50 на місяць ($600 на рік, з API). Для Basic і Pro є 7-денний пробний період.', 'scite helps you find and evaluate scientific literature. Its key feature is Smart Citations: for each paper you see the context in which it is cited and whether later studies support or contradict its findings. The database covers more than 1.6 billion citations from over 300 million scholarly sources. The AI assistant answers questions with references to real papers, and there is search, paper collections, an API and MCP access for other AI tools. Plans: Connect — free (MCP only); Basic — $20 a month ($240 a year); Pro — $50 a month ($600 a year, with API). Basic and Pro have a 7-day free trial.', 'Smart Citations: підтверджує чи заперечує
1,6 млрд+ цитувань із 300 млн+ джерел
AI-асистент з посиланнями на статті
Колекції статей, API та MCP', 'Smart Citations: supporting or contrasting
1.6B+ citations from 300M+ sources
AI assistant with references to papers
Paper collections, API and MCP', 'Науковці, аспіранти, студенти й медичні фахівці, яким потрібна перевірена наукова база.', 'Scientists, PhD students, students and medical professionals who need a verified evidence base.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'scite.ai' OR LOWER(`name`) = LOWER('scite')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' AND s.`slug` = 'research-search' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI research assistant with Smart Citations: it shows whether later studies support or contradict a paper''s findings and answers with references to sources.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'scite helps you find and evaluate scientific literature. Its key feature is Smart Citations: for each paper you see the context in which it is cited and whether later studies support or contradict its findings. The database covers more than 1.6 billion citations from over 300 million scholarly sources. The AI assistant answers questions with references to real papers, and there is search, paper collections, an API and MCP access for other AI tools. Plans: Connect — free (MCP only); Basic — $20 a month ($240 a year); Pro — $50 a month ($600 a year, with API). Basic and Pro have a 7-day free trial.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Smart Citations: supporting or contrasting
1.6B+ citations from 300M+ sources
AI assistant with references to papers
Paper collections, API and MCP', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Scientists, PhD students, students and medical professionals who need a verified evidence base.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Connect', 'Connect', 0.00, 'free', 'Лише доступ через MCP, без асистента й пошуку', 'MCP access only, no Assistant or Search' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Connect' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Connect', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'MCP access only, no Assistant or Search', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Basic', 'Basic', 20.00, 'month', 'Повний асистент і пошук, колекції до 1 000 статей; $240 на рік', 'Full Assistant and Search, collections up to 1,000 papers; $240 a year' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Basic' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Basic', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Full Assistant and Search, collections up to 1,000 papers; $240 a year', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 50.00, 'month', 'Усе з Basic + API з кредитом $60, колекції до 10 000 статей; $600 на рік', 'Everything in Basic + API with $60 credit, collections up to 10,000 papers; $600 a year' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Everything in Basic + API with $60 credit, collections up to 10,000 papers; $600 a year', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- ResearchRabbit — Дослідження та пошук
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'researchrabbit.ai' OR LOWER(`name`) = LOWER('ResearchRabbit'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'ResearchRabbit', NULL, 'https://www.researchrabbit.ai', NULL, NULL, 'Інструмент для огляду літератури: за кількома обраними статтями знаходить пов''язані роботи серед 310+ млн публікацій і показує їхні зв''язки на візуальній карті.', 'A literature review tool: from a few papers you pick, it finds related work among 310M+ publications and shows how they connect on a visual map.', 'ResearchRabbit замінює пошук за ключовими словами на дослідження «кролячою норою»: ви додаєте кілька статей, а сервіс знаходить схожі роботи, попередні й наступні дослідження та впливових авторів, будуючи візуальну мапу зв''язків. Рекомендації вчаться на вашому виборі, а бібліотека синхронізується з менеджерами посилань. База — понад 310 млн наукових статей, сервісом користуються понад мільйон дослідників. Безкоштовний тариф дає необмежений пошук і колекції (до 50 «опорних» статей); ResearchRabbit+ коштує $10 на місяць (до 300 статей, розширені налаштування, кілька проєктів, сповіщення); для установ — індивідуальні умови. Для понад 100 країн діють регіональні знижки.', 'ResearchRabbit replaces keyword search with ''rabbit hole'' exploration: you add a few papers and the service finds similar work, earlier and later studies and influential authors, building a visual map of connections. Recommendations learn from your choices, and the library syncs with reference managers. The database covers more than 310 million scholarly articles, and over a million researchers use it. The free plan gives unlimited searches and collections (up to 50 seed articles); ResearchRabbit+ costs $10 a month (up to 300 seed articles, advanced controls, multiple projects and alerts); institutions get custom terms. Country-specific discounts apply in more than 100 countries.', 'Пошук пов''язаних статей за обраними «опорними»
Візуальна мапа зв''язків між роботами
310+ млн наукових статей
Синхронізація з менеджерами посилань', 'Finds related papers from your seed articles
Visual map of connections between papers
310M+ scholarly articles
Sync with reference managers', 'Студенти, аспіранти й науковці, які пишуть огляд літератури.', 'Students, PhD candidates and scientists writing a literature review.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'researchrabbit.ai' OR LOWER(`name`) = LOWER('ResearchRabbit')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' AND s.`slug` = 'research-search' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A literature review tool: from a few papers you pick, it finds related work among 310M+ publications and shows how they connect on a visual map.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'ResearchRabbit replaces keyword search with ''rabbit hole'' exploration: you add a few papers and the service finds similar work, earlier and later studies and influential authors, building a visual map of connections. Recommendations learn from your choices, and the library syncs with reference managers. The database covers more than 310 million scholarly articles, and over a million researchers use it. The free plan gives unlimited searches and collections (up to 50 seed articles); ResearchRabbit+ costs $10 a month (up to 300 seed articles, advanced controls, multiple projects and alerts); institutions get custom terms. Country-specific discounts apply in more than 100 countries.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Finds related papers from your seed articles
Visual map of connections between papers
310M+ scholarly articles
Sync with reference managers', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Students, PhD candidates and scientists writing a literature review.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free Forever', 'Free Forever', 0.00, 'free', 'Необмежений пошук і колекції, до 50 опорних статей', 'Unlimited searches and collections, up to 50 seed articles' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free Forever' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free Forever', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited searches and collections, up to 50 seed articles', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'ResearchRabbit+', 'ResearchRabbit+', 10.00, 'month', 'До 300 опорних статей, розширені налаштування, кілька проєктів, сповіщення', 'Up to 300 seed articles, advanced controls, multiple projects, alerts' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'ResearchRabbit+' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'ResearchRabbit+', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Up to 300 seed articles, advanced controls, multiple projects, alerts', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Institution', 'Institution', NULL, 'year', 'Ціна за запитом: знижки на обсяг, керування користувачами, аналітика', 'Price on request: volume discounts, user management, analytics' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Institution' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Institution', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Price on request: volume discounts, user management, analytics', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Undermind — Дослідження та пошук
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'undermind.ai' OR LOWER(`name`) = LOWER('Undermind'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Undermind', NULL, 'https://www.undermind.ai', NULL, NULL, 'AI-агент для пошуку наукових статей: уточнює ваше запитання, ретельно перебирає літературу й знаходить найрелевантніші роботи, з якими далі можна працювати глибше.', 'An AI agent for finding scientific papers: it clarifies your question, searches the literature thoroughly and finds the most relevant work, which you can then explore in depth.', 'Undermind — дослідницький AI-агент для наукової літератури. Спершу він ставить уточнювальні запитання, щоб зрозуміти, що саме ви шукаєте, а потім систематично перебирає публікації, читає їх і повертає впорядкований список найрелевантніших робіт з поясненнями. За тестами компанії, за 10 хвилин він знаходить 85% з двадцяти найважливіших статей, тоді як інші AI-агенти пошуку — близько половини. Сервіс інтегрується з Claude, ChatGPT та іншими інструментами, ним користуються науковці MIT, Гарварду, Caltech та фармацевтичних компаній. Тарифи: Free; Pro — $16 на місяць при річній оплаті (повнотекстовий аналіз, у 10 разів вищі ліміти); Team — $15 на людину на місяць; Enterprise — за запитом.', 'Undermind is a research AI agent for scientific literature. It first asks clarifying questions to understand exactly what you are looking for, then systematically works through publications, reads them and returns a ranked list of the most relevant papers with explanations. In the company''s benchmarks it finds 85% of the 20 most relevant papers within 10 minutes, compared with about half for other AI search agents. It integrates with Claude, ChatGPT and other tools and is used by scientists at MIT, Harvard, Caltech and pharmaceutical companies. Plans: Free; Pro at $16 a month billed annually (full-text analysis, 10× higher limits); Team at $15 per person a month; Enterprise on request.', 'Уточнювальні запитання перед пошуком
Систематичний перебір і читання статей
Повнотекстовий аналіз (Pro)
Інтеграція з Claude, ChatGPT та іншими', 'Clarifying questions before the search
Systematic search and reading of papers
Full-text analysis (Pro)
Integration with Claude, ChatGPT and more', 'Науковці, інженери й R&D-команди, яким потрібен вичерпний пошук літератури.', 'Scientists, engineers and R&D teams who need an exhaustive literature search.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'undermind.ai' OR LOWER(`name`) = LOWER('Undermind')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' AND s.`slug` = 'research-search' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI agent for finding scientific papers: it clarifies your question, searches the literature thoroughly and finds the most relevant work, which you can then explore in depth.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Undermind is a research AI agent for scientific literature. It first asks clarifying questions to understand exactly what you are looking for, then systematically works through publications, reads them and returns a ranked list of the most relevant papers with explanations. In the company''s benchmarks it finds 85% of the 20 most relevant papers within 10 minutes, compared with about half for other AI search agents. It integrates with Claude, ChatGPT and other tools and is used by scientists at MIT, Harvard, Caltech and pharmaceutical companies. Plans: Free; Pro at $16 a month billed annually (full-text analysis, 10× higher limits); Team at $15 per person a month; Enterprise on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Clarifying questions before the search
Systematic search and reading of papers
Full-text analysis (Pro)
Integration with Claude, ChatGPT and more', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Scientists, engineers and R&D teams who need an exhaustive literature search.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Базові моделі, стандартні ліміти', 'Basic models, standard rate limits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Basic models, standard rate limits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 16.00, 'month', 'При річній оплаті: розширені моделі, повнотекстовий аналіз, у 10× вищі ліміти', 'Billed annually: advanced models, full-text analysis, 10× higher limits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Billed annually: advanced models, full-text analysis, 10× higher limits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Team', 'Team', 15.00, 'month', 'За людину на місяць при річній оплаті, керування командою', 'Per person a month billed annually, team management' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Team' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Team', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per person a month billed annually, team management', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Exa — Дослідження та пошук
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'exa.ai' OR LOWER(`name`) = LOWER('Exa'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Exa', NULL, 'https://exa.ai', NULL, NULL, 'Пошуковий API для AI-застосунків: швидкий пошук в інтернеті, вміст сторінок у зручному для моделей вигляді, готові відповіді та глибоке дослідження за запитом.', 'A search API for AI applications: fast web search, page contents in a model-friendly format, ready answers and in-depth research on demand.', 'Exa — пошукова система, створена для AI: замість сторінки з посиланнями розробники отримують через API релевантні результати та текст сторінок у компактному вигляді, зручному для мовних моделей. Є кілька режимів — миттєвий, швидкий і глибокий пошук, — а також Answer для готових відповідей з джерелами, Monitors для відстеження нових публікацій і Agent для багатокрокових досліджень. Оплата за використання: щомісяця $10 безкоштовних кредитів (≈2 500 швидких пошуків), далі — від $4 за 1 000 пошуків, $1 за 1 000 сторінок контенту, $5 за 1 000 відповідей. Для великих обсягів є Enterprise з власними індексами та нульовим зберіганням даних.', 'Exa is a search engine built for AI: instead of a page of links, developers get relevant results and page text through an API in a compact format suited to language models. There are several modes — instant, fast and deep search — plus Answer for ready answers with sources, Monitors for tracking new publications and Agent for multi-step research. Pricing is pay-as-you-go: $10 in free credits every month (≈2,500 instant searches), then from $4 per 1,000 searches, $1 per 1,000 pages of contents and $5 per 1,000 answers. Enterprise is available for high volumes, with custom indexes and zero data retention.', 'Пошуковий API з миттєвим, швидким і глибоким режимами
Текст сторінок у форматі для LLM
Answer, Monitors і Agent
$10 безкоштовних кредитів щомісяця', 'Search API with instant, fast and deep modes
Page contents in an LLM-friendly format
Answer, Monitors and Agent
$10 in free credits every month', 'Розробники AI-агентів, чат-ботів і RAG-систем, яким потрібен доступ до актуального інтернету.', 'Developers of AI agents, chatbots and RAG systems that need access to the live web.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'exa.ai' OR LOWER(`name`) = LOWER('Exa')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' AND s.`slug` = 'research-search' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A search API for AI applications: fast web search, page contents in a model-friendly format, ready answers and in-depth research on demand.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Exa is a search engine built for AI: instead of a page of links, developers get relevant results and page text through an API in a compact format suited to language models. There are several modes — instant, fast and deep search — plus Answer for ready answers with sources, Monitors for tracking new publications and Agent for multi-step research. Pricing is pay-as-you-go: $10 in free credits every month (≈2,500 instant searches), then from $4 per 1,000 searches, $1 per 1,000 pages of contents and $5 per 1,000 answers. Enterprise is available for high volumes, with custom indexes and zero data retention.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Search API with instant, fast and deep modes
Page contents in an LLM-friendly format
Answer, Monitors and Agent
$10 in free credits every month', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Developers of AI agents, chatbots and RAG systems that need access to the live web.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовні кредити', 'Free credits', 0.00, 'free', '$10 кредитів щомісяця (≈2 500 швидких пошуків)', '$10 in credits every month (≈2,500 instant searches)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Безкоштовні кредити' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '$10 in credits every month (≈2,500 instant searches)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Оплата за використання', 'Pay as you go', NULL, 'month', 'Від $4 за 1 000 пошуків, $1 за 1 000 сторінок, $5 за 1 000 відповідей', 'From $4 per 1,000 searches, $1 per 1,000 pages, $5 per 1,000 answers' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Оплата за використання' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pay as you go', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'From $4 per 1,000 searches, $1 per 1,000 pages, $5 per 1,000 answers', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- You.com — Дослідження та пошук
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'you.com' OR LOWER(`name`) = LOWER('You.com'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'You.com', NULL, 'https://you.com', NULL, NULL, 'API для пошуку й досліджень, створені для AI-систем і компаній: актуальна видача, витягування тексту зі сторінок і відповіді з посиланнями на джерела.', 'Search and research APIs built for AI systems and enterprises: real-time results, text extraction from pages and answers with citations.', 'You.com розвивається як платформа пошукових і дослідницьких API для AI-систем. Web Search API повертає актуальні результати (до 100 посилань за запит), Contents API витягує текст із кількох сторінок, Answer API дає узагальнені відповіді з посиланнями на джерела, Research API — розгорнуті дослідження, а Finance Research API — дані про компанії, звітність і ринки. Для компаній доступні нульове зберігання даних, сертифікація SOC 2 та індивідуальні ліміти. Безкоштовний рівень: 100 запитів на день і $100 кредиту; далі оплата за 1 000 викликів — $5 за пошук, $1 за контент, $5 за відповіді, $12 за дослідження.', 'You.com has evolved into a platform of search and research APIs for AI systems. The Web Search API returns real-time results (up to 100 URLs per call), the Contents API extracts text from multiple pages, the Answer API gives synthesised answers with citations, the Research API delivers in-depth research and the Finance Research API provides company data, filings and market research. Enterprises get zero data retention, SOC 2 certification and custom rate limits. The free tier offers 100 queries a day and $100 in credit; after that pricing per 1,000 calls is $5 for search, $1 for contents, $5 for answers and $12 for research.', 'Web Search API з актуальною видачею
Витягування тексту сторінок (Contents API)
Відповіді й дослідження з посиланнями
Нульове зберігання даних і SOC 2', 'Web Search API with real-time results
Page text extraction (Contents API)
Answers and research with citations
Zero data retention and SOC 2', 'Розробники та компанії, що будують AI-продукти з доступом до інтернету.', 'Developers and companies building AI products with web access.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'you.com' OR LOWER(`name`) = LOWER('You.com')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' AND s.`slug` = 'research-search' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Search and research APIs built for AI systems and enterprises: real-time results, text extraction from pages and answers with citations.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'You.com has evolved into a platform of search and research APIs for AI systems. The Web Search API returns real-time results (up to 100 URLs per call), the Contents API extracts text from multiple pages, the Answer API gives synthesised answers with citations, the Research API delivers in-depth research and the Finance Research API provides company data, filings and market research. Enterprises get zero data retention, SOC 2 certification and custom rate limits. The free tier offers 100 queries a day and $100 in credit; after that pricing per 1,000 calls is $5 for search, $1 for contents, $5 for answers and $12 for research.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Web Search API with real-time results
Page text extraction (Contents API)
Answers and research with citations
Zero data retention and SOC 2', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Developers and companies building AI products with web access.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free Tier', 'Free Tier', 0.00, 'free', '100 запитів на день і $100 кредиту', '100 queries a day and $100 in credit' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free Tier' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free Tier', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '100 queries a day and $100 in credit', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Оплата за використання', 'Pay as you go', NULL, 'month', 'За 1 000 викликів: пошук $5, контент $1, відповіді $5, дослідження $12', 'Per 1,000 calls: search $5, contents $1, answers $5, research $12' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Оплата за використання' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pay as you go', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per 1,000 calls: search $5, contents $1, answers $5, research $12', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Perplexity')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' AND s.`slug` = 'research-search' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Elicit')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' AND s.`slug` = 'research-search' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Consensus')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' AND s.`slug` = 'research-search' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('SciSpace')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' AND s.`slug` = 'research-search' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Semantic Scholar')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'education-knowledge' AND s.`slug` = 'research-search' LIMIT 1;
