SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Мультимедіа» → нові підкатегорії «AI-аватари» та «Видалення фону» — 6 нових продуктів, 6 прив'язок наявних
--   D-ID — AI-аватари
--   Hedra — AI-аватари
--   Captions — AI-аватари
--   Aragon AI — AI-аватари
--   remove.bg — Видалення фону
--   Pixelcut — Видалення фону
--   (наявний) HeyGen → AI-аватари
--   (наявний) Synthesia → AI-аватари
--   (наявний) Lensa → AI-аватари
--   (наявний) Photoroom → Видалення фону
--   (наявний) Clipdrop → Видалення фону
--   (наявний) Canva → Видалення фону
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'AI-аватари', 'AI Avatars', 'ai-avatars' FROM `categories` c WHERE c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Видалення фону', 'Background Removal', 'background-removal' FROM `categories` c WHERE c.`slug` = 'multimedia' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- D-ID — AI-аватари
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'd-id.com' OR LOWER(`name`) = LOWER('D-ID'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'D-ID', NULL, 'https://www.d-id.com', NULL, NULL, 'Платформа відео з фотореалістичними AI-аватарами, що говорять: ролики для маркетингу, продажів і навчання, переклад відео та API для розробників.', 'A video platform with photorealistic talking AI avatars: clips for marketing, sales and training, video translation and an API for developers.', 'D-ID створює відео, у яких фотореалістичний AI-аватар промовляє ваш текст. У D-ID Studio можна обрати готового аватара чи зробити власного, додати сценарій і озвучення та отримати ролик для маркетингу, продажів, підтримки клієнтів або корпоративного навчання. Є переклад відео іншими мовами, інтерактивні відеоагенти та API для інтеграції в продукти. Хвилини відео оновлюються щомісяця й не переносяться. Тарифи при річній оплаті: Trial — безкоштовно 3 хвилини з водяним знаком; Lite — $4,70 на місяць ($56 на рік, 10 хв); Pro — $16 на місяць ($191 на рік, 15 хв); Advanced — $108 на місяць ($1 293 на рік, 100 хв); Enterprise — за запитом.', 'D-ID creates videos in which a photorealistic AI avatar speaks your script. In D-ID Studio you can pick a ready-made avatar or make your own, add a script and voice, and get a clip for marketing, sales, customer support or corporate training. It also offers video translation, interactive video agents and an API for integrating into products. Video minutes renew monthly and do not roll over. Plans billed annually: Trial — 3 free minutes with a watermark; Lite — $4.70 a month ($56 a year, 10 min); Pro — $16 a month ($191 a year, 15 min); Advanced — $108 a month ($1,293 a year, 100 min); Enterprise on request.', 'Фотореалістичні аватари, що говорять
Власні аватари й озвучення
Переклад відео
Інтерактивні відеоагенти та API', 'Photorealistic talking avatars
Custom avatars and voices
Video translation
Interactive video agents and API', 'Маркетологи, тренери й команди продажів, яким потрібні відео з ведучим без зйомок.', 'Marketers, trainers and sales teams that need presenter-led videos without filming.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'd-id.com' OR LOWER(`name`) = LOWER('D-ID')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'ai-avatars' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A video platform with photorealistic talking AI avatars: clips for marketing, sales and training, video translation and an API for developers.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'D-ID creates videos in which a photorealistic AI avatar speaks your script. In D-ID Studio you can pick a ready-made avatar or make your own, add a script and voice, and get a clip for marketing, sales, customer support or corporate training. It also offers video translation, interactive video agents and an API for integrating into products. Video minutes renew monthly and do not roll over. Plans billed annually: Trial — 3 free minutes with a watermark; Lite — $4.70 a month ($56 a year, 10 min); Pro — $16 a month ($191 a year, 15 min); Advanced — $108 a month ($1,293 a year, 100 min); Enterprise on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Photorealistic talking avatars
Custom avatars and voices
Video translation
Interactive video agents and API', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Marketers, trainers and sales teams that need presenter-led videos without filming.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Trial', 'Trial', 0.00, 'free', '3 хвилини відео з водяним знаком', '3 minutes of video with a watermark' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Trial' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Trial', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '3 minutes of video with a watermark', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Lite', 'Lite', 56.00, 'year', '10 хв відео на місяць (≈$4,70/міс), з водяним знаком D-ID', '10 min of video a month (≈$4.70/mo), D-ID watermark' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Lite' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Lite', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '10 min of video a month (≈$4.70/mo), D-ID watermark', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 191.00, 'year', '15 хв відео на місяць (≈$16/міс)', '15 min of video a month (≈$16/mo)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '15 min of video a month (≈$16/mo)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Advanced', 'Advanced', 1293.00, 'year', '100 хв відео на місяць (≈$108/міс)', '100 min of video a month (≈$108/mo)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Advanced' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Advanced', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '100 min of video a month (≈$108/mo)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Hedra — AI-аватари
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'hedra.com' OR LOWER(`name`) = LOWER('Hedra'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Hedra', NULL, 'https://www.hedra.com', NULL, NULL, 'Студія AI-відео з персонажами: оживлює фото чи згенерованого героя, синхронізує губи з голосом і дає доступ до провідних відеомоделей та API.', 'An AI character video studio: it brings a photo or generated character to life, syncs lips to a voice and gives access to leading video models and an API.', 'Hedra — платформа для створення відео з персонажами, що говорять. Завантажте фото або згенеруйте героя, додайте аудіо чи текст — і Hedra створить виразне відео з синхронізацією губ, мімікою та рухами. У студії також доступні провідні моделі генерації відео й зображень через єдиний інтерфейс, а розробники можуть використовувати API. Усі платні тарифи дозволяють комерційне використання. Тарифи: безкоштовний старт; Basic — $20 на місяць (2 000 кредитів); Pro — $50 (7 200 кредитів); Ultra — $100 (18 000 кредитів, командний доступ); Teams — $75 на місяць (14 400 кредитів); Enterprise — за запитом.', 'Hedra is a platform for creating videos with talking characters. Upload a photo or generate a character, add audio or text, and Hedra creates an expressive video with lip sync, facial expressions and movement. The studio also gives access to leading video and image generation models through one interface, and developers can use the API. All paid plans include commercial use rights. Plans: free to start; Basic — $20 a month (2,000 credits); Pro — $50 (7,200 credits); Ultra — $100 (18,000 credits, team access); Teams — $75 a month (14,400 credits); Enterprise on request.', 'Відео з персонажами, що говорять
Синхронізація губ, міміка й рухи
Провідні відеомоделі в одній студії
API та комерційне використання', 'Talking character videos
Lip sync, expressions and movement
Leading video models in one studio
API and commercial use', 'Контент-мейкери, аніматори, маркетологи й розробники, які роблять відео з персонажами.', 'Content creators, animators, marketers and developers making character videos.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'hedra.com' OR LOWER(`name`) = LOWER('Hedra')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'ai-avatars' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI character video studio: it brings a photo or generated character to life, syncs lips to a voice and gives access to leading video models and an API.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Hedra is a platform for creating videos with talking characters. Upload a photo or generate a character, add audio or text, and Hedra creates an expressive video with lip sync, facial expressions and movement. The studio also gives access to leading video and image generation models through one interface, and developers can use the API. All paid plans include commercial use rights. Plans: free to start; Basic — $20 a month (2,000 credits); Pro — $50 (7,200 credits); Ultra — $100 (18,000 credits, team access); Teams — $75 a month (14,400 credits); Enterprise on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Talking character videos
Lip sync, expressions and movement
Leading video models in one studio
API and commercial use', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Content creators, animators, marketers and developers making character videos.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Basic', 'Basic', 20.00, 'month', '2 000 кредитів на місяць, комерційне використання', '2,000 credits a month, commercial use' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Basic' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Basic', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '2,000 credits a month, commercial use', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 50.00, 'month', '7 200 кредитів на місяць', '7,200 credits a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '7,200 credits a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ultra', 'Ultra', 100.00, 'month', '18 000 кредитів на місяць, командний доступ', '18,000 credits a month, team access' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ultra' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Ultra', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '18,000 credits a month, team access', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Captions — AI-аватари
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'captions.ai' OR LOWER(`name`) = LOWER('Captions'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Captions', NULL, 'https://www.captions.ai', NULL, NULL, 'AI-застосунок для коротких відео: автоматичні субтитри, монтаж, AI-аватари, які говорять ваш текст, і переклад відео для соцмереж.', 'An AI app for short-form video: automatic captions, editing, AI avatars that speak your script and video translation for social media.', 'Captions допомагає швидко створювати відео для соцмереж. Застосунок автоматично додає стильні субтитри, прибирає паузи й монтує ролик, а AI-аватари можуть промовляти ваш сценарій, тож відео можна зробити без зйомки себе. Доступні переклад і дубляж відео іншими мовами та інші AI-інструменти для монтажу. Працює у вебі та мобільному застосунку. Оплата — кредитами: платні тарифи коштують від $24,99 на місяць (500 кредитів) до $69,99 на місяць (1 400 кредитів); для компаній — Enterprise з індивідуальними обсягами.', 'Captions helps you make social media videos quickly. The app adds stylish captions automatically, removes pauses and edits the clip, and AI avatars can speak your script so you can make a video without filming yourself. It also offers video translation and dubbing and other AI editing tools. It works on the web and in a mobile app. Usage is credit-based: paid plans range from $24.99 a month (500 credits) to $69.99 a month (1,400 credits); companies can get Enterprise with custom volumes.', 'Автоматичні субтитри й монтаж
AI-аватари, що говорять ваш текст
Переклад і дубляж відео
Веб і мобільний застосунок', 'Automatic captions and editing
AI avatars that speak your script
Video translation and dubbing
Web and mobile app', 'Блогери, SMM-фахівці та малий бізнес, які регулярно публікують короткі відео.', 'Creators, social media managers and small businesses that post short videos regularly.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'captions.ai' OR LOWER(`name`) = LOWER('Captions')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'ai-avatars' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI app for short-form video: automatic captions, editing, AI avatars that speak your script and video translation for social media.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Captions helps you make social media videos quickly. The app adds stylish captions automatically, removes pauses and edits the clip, and AI avatars can speak your script so you can make a video without filming yourself. It also offers video translation and dubbing and other AI editing tools. It works on the web and in a mobile app. Usage is credit-based: paid plans range from $24.99 a month (500 credits) to $69.99 a month (1,400 credits); companies can get Enterprise with custom volumes.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Automatic captions and editing
AI avatars that speak your script
Video translation and dubbing
Web and mobile app', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Creators, social media managers and small businesses that post short videos regularly.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, '500 кредитів', '500 credits', 24.99, 'month', '500 AI-кредитів на місяць', '500 AI credits a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = '500 кредитів' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', '500 credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '500 AI credits a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, '1 400 кредитів', '1,400 credits', 69.99, 'month', '1 400 AI-кредитів на місяць', '1,400 AI credits a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = '1 400 кредитів' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', '1,400 credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '1,400 AI credits a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Aragon AI — AI-аватари
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'aragon.ai' OR LOWER(`name`) = LOWER('Aragon AI'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Aragon AI', NULL, 'https://www.aragon.ai', NULL, NULL, 'Професійні AI-портрети для резюме й LinkedIn за 15–45 хвилин: завантажуєте селфі й отримуєте до 100 бізнес-фото з різним одягом і фоном.', 'Professional AI headshots for resumes and LinkedIn in 15–45 minutes: upload selfies and get up to 100 business photos with different outfits and backgrounds.', 'Aragon AI замінює фотосесію для ділового портрета. Ви завантажуєте кілька звичайних селфі, обираєте стиль одягу й фон, і сервіс генерує набір професійних портретів для резюме, LinkedIn, сайту компанії чи профілю в соцмережах; усі права на зображення залишаються за вами. Сервіс створили дослідники з MIT, Meta і Google, і він уже згенерував понад 40 млн портретів. Оплата разова: Basic — $35 (40 портретів, 1 образ і фон, близько 45 хв); Standard — $45 (60 портретів, 2 образи й фони, близько 30 хв); Executive — $75 (100 портретів, усі образи й фони, вища роздільність, близько 15 хв). Часто діють знижки.', 'Aragon AI replaces a photo shoot for business headshots. You upload a few ordinary selfies, choose outfit styles and backgrounds, and the service generates a set of professional portraits for your resume, LinkedIn, company website or social profiles; you keep full ownership of the images. It was built by researchers from MIT, Meta and Google and has already generated more than 40 million headshots. Pricing is one-time: Basic — $35 (40 headshots, 1 outfit and background, about 45 min); Standard — $45 (60 headshots, 2 outfits and backgrounds, about 30 min); Executive — $75 (100 headshots, all outfits and backgrounds, higher resolution, about 15 min). Discounts are often available.', 'Бізнес-портрети з кількох селфі
Вибір одягу й фону
До 100 портретів за 15–45 хвилин
Повні права на зображення', 'Business headshots from a few selfies
Choice of outfits and backgrounds
Up to 100 headshots in 15–45 minutes
Full image ownership', 'Шукачі роботи, фрілансери й команди, яким потрібні ділові фото без фотографа.', 'Job seekers, freelancers and teams that need business photos without a photographer.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'aragon.ai' OR LOWER(`name`) = LOWER('Aragon AI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'ai-avatars' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Professional AI headshots for resumes and LinkedIn in 15–45 minutes: upload selfies and get up to 100 business photos with different outfits and backgrounds.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Aragon AI replaces a photo shoot for business headshots. You upload a few ordinary selfies, choose outfit styles and backgrounds, and the service generates a set of professional portraits for your resume, LinkedIn, company website or social profiles; you keep full ownership of the images. It was built by researchers from MIT, Meta and Google and has already generated more than 40 million headshots. Pricing is one-time: Basic — $35 (40 headshots, 1 outfit and background, about 45 min); Standard — $45 (60 headshots, 2 outfits and backgrounds, about 30 min); Executive — $75 (100 headshots, all outfits and backgrounds, higher resolution, about 15 min). Discounts are often available.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Business headshots from a few selfies
Choice of outfits and backgrounds
Up to 100 headshots in 15–45 minutes
Full image ownership', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Job seekers, freelancers and teams that need business photos without a photographer.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Basic', 'Basic', 35.00, 'one_time', '40 портретів, 1 образ і 1 фон', '40 headshots, 1 outfit and 1 background' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Basic' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Basic', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '40 headshots, 1 outfit and 1 background', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Standard', 'Standard', 45.00, 'one_time', '60 портретів, 2 образи й 2 фони', '60 headshots, 2 outfits and 2 backgrounds' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Standard' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Standard', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '60 headshots, 2 outfits and 2 backgrounds', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Executive', 'Executive', 75.00, 'one_time', '100 портретів, усі образи й фони, вища роздільність', '100 headshots, all outfits and backgrounds, higher resolution' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Executive' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Executive', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '100 headshots, all outfits and backgrounds, higher resolution', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- remove.bg — Видалення фону
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'remove.bg' OR LOWER(`name`) = LOWER('remove.bg'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'remove.bg', NULL, 'https://www.remove.bg', NULL, NULL, 'Автоматичне видалення фону з фото за кілька секунд: веб, застосунки для Windows, Mac, Linux і Android, розширення для Photoshop та API.', 'Automatic photo background removal in seconds: web, apps for Windows, Mac, Linux and Android, a Photoshop extension and an API.', 'remove.bg — один з найвідоміших сервісів для автоматичного видалення фону, зараз належить Canva. Досить завантажити зображення — AI виріже людину, товар, тварину чи автомобіль і поверне прозорий фон, який можна замінити. Сервісом користуються фотографи, маркетологи, інтернет-магазини, медіа й автодилери. Він доступний у вебі, як застосунок для Windows, Mac, Linux і Android, як розширення для Photoshop та через API для масової обробки. Оплата — кредитами: підписка від $9 на місяць за 40 кредитів або разові пакети (наприклад, 3 кредити за $3).', 'remove.bg is one of the best-known automatic background removal services and is now owned by Canva. Just upload an image and AI cuts out the person, product, animal or car and returns a transparent background that you can replace. Photographers, marketers, online stores, media and car dealers use it. It is available on the web, as an app for Windows, Mac, Linux and Android, as a Photoshop extension and through an API for bulk processing. Usage is credit-based: subscriptions start at $9 a month for 40 credits, or you can buy one-off packs (for example, 3 credits for $3).', 'Видалення фону за секунди
Люди, товари, тварини й авто
Застосунки для Windows, Mac, Linux, Android
Розширення Photoshop і API', 'Background removal in seconds
People, products, animals and cars
Apps for Windows, Mac, Linux and Android
Photoshop extension and API', 'Інтернет-магазини, маркетологи, дизайнери й фотографи.', 'Online stores, marketers, designers and photographers.', 'web,mobile,desktop', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'remove.bg' OR LOWER(`name`) = LOWER('remove.bg')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'background-removal' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Automatic photo background removal in seconds: web, apps for Windows, Mac, Linux and Android, a Photoshop extension and an API.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'remove.bg is one of the best-known automatic background removal services and is now owned by Canva. Just upload an image and AI cuts out the person, product, animal or car and returns a transparent background that you can replace. Photographers, marketers, online stores, media and car dealers use it. It is available on the web, as an app for Windows, Mac, Linux and Android, as a Photoshop extension and through an API for bulk processing. Usage is credit-based: subscriptions start at $9 a month for 40 credits, or you can buy one-off packs (for example, 3 credits for $3).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Background removal in seconds
People, products, animals and cars
Apps for Windows, Mac, Linux and Android
Photoshop extension and API', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Online stores, marketers, designers and photographers.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Підписка', 'Subscription', 9.00, 'month', '40 кредитів на місяць', '40 credits a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Підписка' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Subscription', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '40 credits a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pay as you go', 'Pay as you go', 3.00, 'one_time', 'Разовий пакет: 3 кредити', 'One-off pack: 3 credits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pay as you go' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pay as you go', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'One-off pack: 3 credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Pixelcut — Видалення фону
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'pixelcut.ai' OR LOWER(`name`) = LOWER('Pixelcut'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Pixelcut', NULL, 'https://www.pixelcut.ai', NULL, NULL, 'AI-фоторедактор для товарів і контенту: видалення фону, генерація фонів, покращення якості й пакетна обробка зображень для інтернет-магазинів.', 'An AI photo editor for products and content: background removal, background generation, upscaling and batch image processing for online stores.', 'Pixelcut допомагає швидко готувати зображення для інтернет-магазинів і соцмереж. Він видаляє фон, генерує нові фони й тіні для товарних фото, покращує якість і збільшує роздільність, прибирає зайві об''єкти та обробляє цілі партії зображень за раз. Працює у вебі та в мобільних застосунках. Тарифи: Free; Pro — $10 на місяць або $8 при річній оплаті (600 AI-кредитів, 1 000 пакетних експортів на місяць); Business — $30 на місяць або $24 при річній оплаті (3 600 кредитів, 2 000 пакетних експортів).', 'Pixelcut helps you prepare images for online stores and social media quickly. It removes backgrounds, generates new backgrounds and shadows for product photos, enhances quality and upscales, removes unwanted objects and processes whole batches of images at once. It works on the web and in mobile apps. Plans: Free; Pro — $10 a month or $8 billed yearly (600 AI credits, 1,000 batch exports a month); Business — $30 a month or $24 billed yearly (3,600 credits, 2,000 batch exports).', 'Видалення фону й генерація нових фонів
Покращення якості та збільшення роздільності
Пакетна обробка
Веб і мобільні застосунки', 'Background removal and generation
Enhancement and upscaling
Batch processing
Web and mobile apps', 'Продавці на маркетплейсах, інтернет-магазини й SMM-фахівці.', 'Marketplace sellers, online stores and social media managers.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'pixelcut.ai' OR LOWER(`name`) = LOWER('Pixelcut')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'background-removal' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI photo editor for products and content: background removal, background generation, upscaling and batch image processing for online stores.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Pixelcut helps you prepare images for online stores and social media quickly. It removes backgrounds, generates new backgrounds and shadows for product photos, enhances quality and upscales, removes unwanted objects and processes whole batches of images at once. It works on the web and in mobile apps. Plans: Free; Pro — $10 a month or $8 billed yearly (600 AI credits, 1,000 batch exports a month); Business — $30 a month or $24 billed yearly (3,600 credits, 2,000 batch exports).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Background removal and generation
Enhancement and upscaling
Batch processing
Web and mobile apps', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Marketplace sellers, online stores and social media managers.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Базові інструменти', 'Basic tools' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Basic tools', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 10.00, 'month', '600 AI-кредитів, 1 000 пакетних експортів; $8 при річній оплаті', '600 AI credits, 1,000 batch exports; $8 billed yearly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '600 AI credits, 1,000 batch exports; $8 billed yearly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Business', 'Business', 30.00, 'month', '3 600 AI-кредитів, 2 000 пакетних експортів; $24 при річній оплаті', '3,600 AI credits, 2,000 batch exports; $24 billed yearly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Business' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Business', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '3,600 AI credits, 2,000 batch exports; $24 billed yearly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('HeyGen')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'ai-avatars' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Synthesia')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'ai-avatars' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Lensa')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'ai-avatars' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Photoroom')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'background-removal' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Clipdrop')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'background-removal' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Canva')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'multimedia' AND s.`slug` = 'background-removal' LIMIT 1;
