SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Бізнес та маркетинг» → нова підкатегорія «Підтримка клієнтів» — 5 нових продуктів, 5 прив'язок наявних
--   Zendesk — Підтримка клієнтів
--   Freshdesk — Підтримка клієнтів
--   Gorgias — Підтримка клієнтів
--   Decagon — Підтримка клієнтів
--   Sierra — Підтримка клієнтів
--   (наявний) Intercom → Підтримка клієнтів
--   (наявний) Tidio → Підтримка клієнтів
--   (наявний) Chatbase → Підтримка клієнтів
--   (наявний) Crisp → Підтримка клієнтів
--   (наявний) Ada CX → Підтримка клієнтів
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Підтримка клієнтів', 'Customer Support', 'customer-support' FROM `categories` c WHERE c.`slug` = 'business-marketing' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Zendesk — Підтримка клієнтів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'zendesk.com' OR LOWER(`name`) = LOWER('Zendesk'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Zendesk', NULL, 'https://www.zendesk.com', NULL, NULL, 'Платформа служби підтримки з AI-агентами, що самі закривають звернення, і Copilot для операторів: тікети, чат, месенджери, телефонія та база знань в одному місці.', 'A customer service platform with AI agents that resolve requests on their own and a Copilot for human agents: tickets, chat, messaging, voice and a knowledge base in one place.', 'Zendesk — одна з найпоширеніших платформ клієнтської підтримки. Вона об''єднує тікети з email, чат, месенджери й телефонію, базу знань і маршрутизацію звернень. AI-агенти відповідають клієнтам і самостійно закривають типові звернення (кожен тариф включає кілька автоматичних вирішень на оператора, далі — $1,50–2 за вирішення), а Copilot підказує операторам відповіді, сортує звернення й допомагає адміністраторам. До Zendesk також приєдналася AI-платформа Forethought. Тарифи за оператора на місяць при річній оплаті: Support Team — $19; Suite Team — $55; Suite Professional — $115; Enterprise — за запитом; модуль Copilot — $50. Помісячна оплата дорожча.', 'Zendesk is one of the most widely used customer support platforms. It brings together email tickets, chat, messaging and voice, a knowledge base and request routing. AI agents answer customers and resolve common requests on their own (each plan includes a few automated resolutions per agent, then $1.50–2 per resolution), while Copilot suggests replies to human agents, triages requests and guides admins. The Forethought AI platform has joined Zendesk. Plans per agent a month billed annually: Support Team — $19; Suite Team — $55; Suite Professional — $115; Enterprise on request; the Copilot add-on is $50. Monthly billing costs more.', 'AI-агенти для автоматичного вирішення звернень
Copilot для операторів і адміністраторів
Тікети, чат, месенджери й телефонія
База знань і маршрутизація', 'AI agents that resolve requests automatically
Copilot for agents and admins
Tickets, chat, messaging and voice
Knowledge base and routing', 'Служби підтримки компаній будь-якого розміру — від стартапів до великих корпорацій.', 'Customer support teams at companies of any size — from startups to large enterprises.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'zendesk.com' OR LOWER(`name`) = LOWER('Zendesk')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'customer-support' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A customer service platform with AI agents that resolve requests on their own and a Copilot for human agents: tickets, chat, messaging, voice and a knowledge base in one place.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Zendesk is one of the most widely used customer support platforms. It brings together email tickets, chat, messaging and voice, a knowledge base and request routing. AI agents answer customers and resolve common requests on their own (each plan includes a few automated resolutions per agent, then $1.50–2 per resolution), while Copilot suggests replies to human agents, triages requests and guides admins. The Forethought AI platform has joined Zendesk. Plans per agent a month billed annually: Support Team — $19; Suite Team — $55; Suite Professional — $115; Enterprise on request; the Copilot add-on is $50. Monthly billing costs more.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI agents that resolve requests automatically
Copilot for agents and admins
Tickets, chat, messaging and voice
Knowledge base and routing', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Customer support teams at companies of any size — from startups to large enterprises.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Support Team', 'Support Team', 19.00, 'month', 'За оператора при річній оплаті: email, тікети, автоматизації ($25 помісячно)', 'Per agent billed annually: email, ticketing, automations ($25 monthly)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Support Team' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Support Team', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per agent billed annually: email, ticketing, automations ($25 monthly)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Suite Team', 'Suite Team', 55.00, 'month', 'За оператора: AI-агенти, база знань, месенджери, телефонія ($69 помісячно)', 'Per agent: AI agents, knowledge base, messaging, voice ($69 monthly)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Suite Team' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Suite Team', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per agent: AI agents, knowledge base, messaging, voice ($69 monthly)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Suite Professional', 'Suite Professional', 115.00, 'month', 'За оператора: Admin Copilot, маршрутизація за навичками, IVR ($149 помісячно)', 'Per agent: Admin Copilot, skills-based routing, IVR ($149 monthly)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Suite Professional' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Suite Professional', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per agent: Admin Copilot, skills-based routing, IVR ($149 monthly)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Freshdesk — Підтримка клієнтів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'freshworks.com/freshdesk' OR LOWER(`name`) = LOWER('Freshdesk'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Freshdesk', NULL, 'https://www.freshworks.com/freshdesk/', NULL, NULL, 'Хелпдеск від Freshworks з AI-агентом Freddy, що відповідає клієнтам, і Freddy Copilot для операторів: тікети, портал клієнтів, база знань і аналітика.', 'A helpdesk from Freshworks with the Freddy AI Agent that answers customers and Freddy Copilot for human agents: tickets, a customer portal, a knowledge base and analytics.', 'Freshdesk — система підтримки клієнтів від Freshworks. Вона збирає звернення в спільну скриньку тікетів, дає клієнтський портал і базу знань, налаштовувані звіти, SLA та маршрутизацію. AI-агент Freddy самостійно відповідає клієнтам (500 сесій включено в кожен тариф, далі $49 за 100 сесій), Freddy AI Copilot допомагає операторам з відповідями, аналізом настрою та живим перекладом, а Freddy AI Insights у тарифі Enterprise шукає першопричини проблем. Тарифи за оператора на місяць при річній оплаті: Growth — $19; Pro — $55; Enterprise — $89; Copilot — +$29. Є 14-денний пробний період.', 'Freshdesk is the customer support system from Freshworks. It gathers requests into a shared ticket inbox and provides a customer portal and knowledge base, custom reports, SLAs and routing. The Freddy AI Agent answers customers on its own (500 sessions included in every plan, then $49 per 100 sessions), Freddy AI Copilot helps agents with replies, sentiment analysis and live translation, and Freddy AI Insights on Enterprise finds root causes of issues. Plans per agent a month billed annually: Growth — $19; Pro — $55; Enterprise — $89; Copilot — +$29. There is a 14-day free trial.', 'AI-агент Freddy (500 сесій у кожному тарифі)
Freddy Copilot: підказки, настрій, переклад
Тікети, портал клієнтів, база знань
SLA, маршрутизація й дашборди', 'Freddy AI Agent (500 sessions on every plan)
Freddy Copilot: suggestions, sentiment, translation
Tickets, customer portal, knowledge base
SLAs, routing and dashboards', 'Служби підтримки малого й середнього бізнесу, яким потрібен простий хелпдеск з AI.', 'Support teams at small and mid-sized businesses that want a straightforward helpdesk with AI.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'freshworks.com/freshdesk' OR LOWER(`name`) = LOWER('Freshdesk')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'customer-support' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A helpdesk from Freshworks with the Freddy AI Agent that answers customers and Freddy Copilot for human agents: tickets, a customer portal, a knowledge base and analytics.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Freshdesk is the customer support system from Freshworks. It gathers requests into a shared ticket inbox and provides a customer portal and knowledge base, custom reports, SLAs and routing. The Freddy AI Agent answers customers on its own (500 sessions included in every plan, then $49 per 100 sessions), Freddy AI Copilot helps agents with replies, sentiment analysis and live translation, and Freddy AI Insights on Enterprise finds root causes of issues. Plans per agent a month billed annually: Growth — $19; Pro — $55; Enterprise — $89; Copilot — +$29. There is a 14-day free trial.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Freddy AI Agent (500 sessions on every plan)
Freddy Copilot: suggestions, sentiment, translation
Tickets, customer portal, knowledge base
SLAs, routing and dashboards', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Support teams at small and mid-sized businesses that want a straightforward helpdesk with AI.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Growth', 'Growth', 19.00, 'month', 'За оператора при річній оплаті; AI-агент Freddy (500 сесій), тікети, база знань', 'Per agent billed annually; Freddy AI Agent (500 sessions), ticketing, knowledge base' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Growth' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Growth', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per agent billed annually; Freddy AI Agent (500 sessions), ticketing, knowledge base', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 55.00, 'month', 'За оператора: багатомовність, дашборди, розумна маршрутизація', 'Per agent: multilingual support, dashboards, intelligent routing' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per agent: multilingual support, dashboards, intelligent routing', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Enterprise', 'Enterprise', 89.00, 'month', 'За оператора: Freddy AI Insights, маршрутизація за навичками, пісочниця', 'Per agent: Freddy AI Insights, skill-based routing, sandbox' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Enterprise' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Enterprise', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per agent: Freddy AI Insights, skill-based routing, sandbox', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Gorgias — Підтримка клієнтів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'gorgias.com' OR LOWER(`name`) = LOWER('Gorgias'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Gorgias', NULL, 'https://www.gorgias.com', NULL, NULL, 'Хелпдеск для інтернет-магазинів (особливо на Shopify) з AI-агентом, що сам відповідає покупцям у пошті, чаті, SMS, соцмережах і телефоні.', 'A helpdesk for online stores (especially on Shopify) with an AI Agent that answers shoppers on its own across email, chat, SMS, social media and phone.', 'Gorgias створено для e-commerce. Він збирає звернення покупців з пошти, чату, SMS, телефону й соцмереж в одну стрічку і орієнтований насамперед на магазини на Shopify. AI-агент доступний на всіх тарифах і самостійно вирішує типові запитання — про доставку, повернення, товари; платите лише тоді, коли він закрив розмову ($1 за автоматичну взаємодію при помісячній оплаті, $0,90 — при річній). Тарифи хелпдеску (помісячно): Starter — $10 (50 тікетів); Basic — $60 (300); Pro — $360 (2 000); Advanced — $900 (5 000); Enterprise — за запитом.', 'Gorgias is built for e-commerce. It gathers shopper requests from email, chat, SMS, phone and social media into one feed and is aimed primarily at Shopify stores. The AI Agent is available on every plan and resolves common questions — about shipping, returns and products — on its own; you pay only when it closes a conversation ($1 per automated interaction billed monthly, $0.90 billed annually). Helpdesk plans (monthly): Starter — $10 (50 tickets); Basic — $60 (300); Pro — $360 (2,000); Advanced — $900 (5,000); Enterprise on request.', 'AI-агент для типових запитань покупців
Пошта, чат, SMS, телефон і соцмережі в одній стрічці
Орієнтація на магазини Shopify
Оплата AI лише за вирішені розмови', 'AI Agent for common shopper questions
Email, chat, SMS, phone and social in one feed
Built for Shopify stores
Pay for AI only when it resolves a conversation', 'Інтернет-магазини та DTC-бренди, особливо на Shopify.', 'Online stores and DTC brands, especially on Shopify.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'gorgias.com' OR LOWER(`name`) = LOWER('Gorgias')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'customer-support' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A helpdesk for online stores (especially on Shopify) with an AI Agent that answers shoppers on its own across email, chat, SMS, social media and phone.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Gorgias is built for e-commerce. It gathers shopper requests from email, chat, SMS, phone and social media into one feed and is aimed primarily at Shopify stores. The AI Agent is available on every plan and resolves common questions — about shipping, returns and products — on its own; you pay only when it closes a conversation ($1 per automated interaction billed monthly, $0.90 billed annually). Helpdesk plans (monthly): Starter — $10 (50 tickets); Basic — $60 (300); Pro — $360 (2,000); Advanced — $900 (5,000); Enterprise on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI Agent for common shopper questions
Email, chat, SMS, phone and social in one feed
Built for Shopify stores
Pay for AI only when it resolves a conversation', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Online stores and DTC brands, especially on Shopify.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Starter', 'Starter', 10.00, 'month', '50 тікетів на місяць', '50 tickets a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Starter' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Starter', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '50 tickets a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Basic', 'Basic', 60.00, 'month', '300 тікетів на місяць', '300 tickets a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Basic' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Basic', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '300 tickets a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 360.00, 'month', '2 000 тікетів на місяць', '2,000 tickets a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '2,000 tickets a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Advanced', 'Advanced', 900.00, 'month', '5 000 тікетів на місяць', '5,000 tickets a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Advanced' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Advanced', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '5,000 tickets a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Decagon — Підтримка клієнтів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'decagon.ai' OR LOWER(`name`) = LOWER('Decagon'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Decagon', NULL, 'https://decagon.ai', NULL, NULL, 'Платформа AI-агентів для підтримки клієнтів у чаті, email і голосом: сценарії задаються звичайною мовою, є тестування, A/B-експерименти й аналітика.', 'An AI agent platform for customer support in chat, email and voice: workflows are defined in plain language, with testing, A/B experiments and analytics built in.', 'Decagon допомагає великим компаніям будувати й масштабувати AI-агентів для обслуговування клієнтів. Поведінку агента описують звичайною мовою у вигляді «процедур» (Agent Operating Procedures), без складного програмування, а єдиний шар інтелекту працює в чаті, email і голосових каналах. У платформу вбудовано тестування, A/B-експерименти, контроль якості та аналітику, що підказує, як покращити агента. Серед клієнтів — Deutsche Telekom, American Airlines, Delta, Duolingo, Chime та Ticketmaster. Ціни не опубліковано — їх обговорюють під час демонстрації.', 'Decagon helps large companies build and scale AI agents for customer service. Agent behaviour is described in plain language as ''Agent Operating Procedures'', without complex coding, and a single intelligence layer works across chat, email and voice. Testing, A/B experiments, quality assurance and analytics that show how to improve the agent are built in. Customers include Deutsche Telekom, American Airlines, Delta, Duolingo, Chime and Ticketmaster. Pricing is not published — it is discussed during a demo.', 'AI-агенти в чаті, email і голосом
Сценарії звичайною мовою (AOP)
Тестування й A/B-експерименти
Контроль якості та аналітика', 'AI agents in chat, email and voice
Workflows in plain language (AOPs)
Testing and A/B experiments
Quality assurance and analytics', 'Великі компанії з високим потоком звернень: фінанси, авіація, ритейл, технології.', 'Large companies with high request volumes: finance, travel, retail and technology.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'decagon.ai' OR LOWER(`name`) = LOWER('Decagon')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'customer-support' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI agent platform for customer support in chat, email and voice: workflows are defined in plain language, with testing, A/B experiments and analytics built in.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Decagon helps large companies build and scale AI agents for customer service. Agent behaviour is described in plain language as ''Agent Operating Procedures'', without complex coding, and a single intelligence layer works across chat, email and voice. Testing, A/B experiments, quality assurance and analytics that show how to improve the agent are built in. Customers include Deutsche Telekom, American Airlines, Delta, Duolingo, Chime and Ticketmaster. Pricing is not published — it is discussed during a demo.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI agents in chat, email and voice
Workflows in plain language (AOPs)
Testing and A/B experiments
Quality assurance and analytics', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Large companies with high request volumes: finance, travel, retail and technology.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Enterprise', 'Enterprise', NULL, 'month', 'Ціна за запитом після демонстрації', 'Price on request after a demo' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Enterprise' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Enterprise', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Price on request after a demo', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Sierra — Підтримка клієнтів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'sierra.ai' OR LOWER(`name`) = LOWER('Sierra'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Sierra', NULL, 'https://sierra.ai', NULL, NULL, 'Платформа розмовних AI-агентів для клієнтського сервісу великих брендів: чат, SMS, WhatsApp, email, голос і ChatGPT, з оплатою за досягнутий результат.', 'A conversational AI agent platform for the customer experience of large brands: chat, SMS, WhatsApp, email, voice and ChatGPT, with outcome-based pricing.', 'Sierra дає великим компаніям змогу створювати AI-агентів, які спілкуються з клієнтами від імені бренду й доводять запити до результату. Інструмент Ghostwriter будує готового агента з регламентів, записів розмов чи опису звичайною мовою, Agent Studio дає змогу керувати агентами й стежити за ними, а розділ Insights — аналізувати розмови, виявляти проблеми, проводити експерименти й відстежувати дії агента. Агенти працюють у чаті, SMS, WhatsApp, email, голосом і навіть у ChatGPT. Платформа має сертифікації SOC 2 Type II, ISO 27001, HIPAA, PCI DSS та інші. Серед клієнтів — Gap, Hyatt, Uber, SiriusXM, Vanguard і Santander. Оплата залежить від досягнутих результатів, а не від кількості розмов; ціни — за запитом.', 'Sierra lets large companies build AI agents that talk to customers on the brand''s behalf and carry requests through to an outcome. Ghostwriter builds a ready agent from SOPs, conversation transcripts or a plain-English description, Agent Studio lets you manage and monitor agents, and Insights lets you analyse conversations, spot issues, run experiments and track agent actions. Agents work in chat, SMS, WhatsApp, email, voice and even ChatGPT. The platform holds SOC 2 Type II, ISO 27001, HIPAA, PCI DSS and other certifications. Customers include Gap, Hyatt, Uber, SiriusXM, Vanguard and Santander. Pricing is outcome-based rather than per conversation and is available on request.', 'Ghostwriter: агент з регламентів чи опису
Чат, SMS, WhatsApp, email, голос і ChatGPT
Аналітика, моніторинг і експерименти
Оплата за результат', 'Ghostwriter: an agent from SOPs or a description
Chat, SMS, WhatsApp, email, voice and ChatGPT
Analytics, monitoring and experiments
Outcome-based pricing', 'Великі бренди й корпорації з масовим клієнтським сервісом.', 'Large brands and enterprises with high-volume customer service.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'sierra.ai' OR LOWER(`name`) = LOWER('Sierra')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'customer-support' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A conversational AI agent platform for the customer experience of large brands: chat, SMS, WhatsApp, email, voice and ChatGPT, with outcome-based pricing.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Sierra lets large companies build AI agents that talk to customers on the brand''s behalf and carry requests through to an outcome. Ghostwriter builds a ready agent from SOPs, conversation transcripts or a plain-English description, Agent Studio lets you manage and monitor agents, and Insights lets you analyse conversations, spot issues, run experiments and track agent actions. Agents work in chat, SMS, WhatsApp, email, voice and even ChatGPT. The platform holds SOC 2 Type II, ISO 27001, HIPAA, PCI DSS and other certifications. Customers include Gap, Hyatt, Uber, SiriusXM, Vanguard and Santander. Pricing is outcome-based rather than per conversation and is available on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Ghostwriter: an agent from SOPs or a description
Chat, SMS, WhatsApp, email, voice and ChatGPT
Analytics, monitoring and experiments
Outcome-based pricing', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Large brands and enterprises with high-volume customer service.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Enterprise', 'Enterprise', NULL, 'month', 'Ціна за запитом; оплата за досягнуті результати', 'Price on request; outcome-based pricing' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Enterprise' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Enterprise', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Price on request; outcome-based pricing', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Intercom')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'customer-support' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Tidio')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'customer-support' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Chatbase')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'customer-support' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Crisp')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'customer-support' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Ada CX')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'customer-support' LIMIT 1;
