SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Продуктивність» → нові підкатегорії «Презентації» і «Таблиці» — 7 нових продуктів, 5 прив'язок наявних
--   Gamma — Презентації
--   Beautiful.ai — Презентації
--   Pitch — Презентації
--   Plus AI — Презентації
--   GPTExcel — Таблиці
--   Numerous.ai — Таблиці
--   Equals — Таблиці
--   (наявний) Canva → Презентації
--   (наявний) Genspark → Презентації
--   (наявний) Rows → Таблиці
--   (наявний) Julius AI → Таблиці
--   (наявний) Microsoft Copilot → Таблиці
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Презентації', 'Presentations', 'presentations' FROM `categories` c WHERE c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Таблиці', 'Spreadsheets', 'spreadsheets' FROM `categories` c WHERE c.`slug` = 'productivity' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Gamma — Презентації
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'gamma.app' OR LOWER(`name`) = LOWER('Gamma'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Gamma', NULL, 'https://gamma.app', NULL, NULL, 'AI-конструктор презентацій, документів, сайтів і дописів для соцмереж: з одного запиту створює готові слайди з дизайном, текстом і зображеннями.', 'An AI builder for presentations, documents, websites and social posts: from a single prompt it creates ready slides with design, text and images.', 'Gamma перетворює ідею чи текст на готову презентацію, документ, простий сайт або допис для соцмереж. Досить описати тему чи вставити нотатки — AI складе структуру, напише текст, підбере макети й зображення, а далі все можна доопрацювати вручну чи командами AI. Є імпорт з PDF і PPTX та експорт у PDF, PPTX, PNG і Google Slides, публікація на власних доменах, аналітика переглядів, а в старших тарифах — API. Тарифи за місце на місяць при річній оплаті: Free — 400 кредитів при реєстрації; Plus — $9 (1 000 кредитів, без брендингу Gamma); Pro — $18 (4 000 кредитів, преміальні моделі зображень, власний брендинг, API); Ultra — $90 (20 000 кредитів, найпотужніші моделі для тексту, зображень і відео).', 'Gamma turns an idea or text into a ready presentation, document, simple website or social post. Just describe the topic or paste your notes — AI builds the structure, writes the text, picks layouts and images, and you can then refine everything by hand or with AI commands. It imports PDF and PPTX and exports to PDF, PPTX, PNG and Google Slides, publishes to custom domains, offers view analytics and, on higher plans, an API. Plans per seat a month billed annually: Free — 400 credits at signup; Plus — $9 (1,000 credits, no Gamma branding); Pro — $18 (4,000 credits, premium image models, custom branding, API); Ultra — $90 (20,000 credits, the most advanced text, image and video models).', 'Презентація, документ чи сайт з одного запиту
Імпорт PDF і PPTX
Експорт у PDF, PPTX, PNG і Google Slides
Власні домени й аналітика переглядів
API (Pro)', 'A deck, doc or site from one prompt
Import from PDF and PPTX
Export to PDF, PPTX, PNG and Google Slides
Custom domains and view analytics
API (Pro)', 'Студенти, викладачі, маркетологи, консультанти й усі, кому часто треба робити презентації.', 'Students, teachers, marketers, consultants and anyone who often needs to make presentations.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'gamma.app' OR LOWER(`name`) = LOWER('Gamma')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'presentations' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI builder for presentations, documents, websites and social posts: from a single prompt it creates ready slides with design, text and images.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Gamma turns an idea or text into a ready presentation, document, simple website or social post. Just describe the topic or paste your notes — AI builds the structure, writes the text, picks layouts and images, and you can then refine everything by hand or with AI commands. It imports PDF and PPTX and exports to PDF, PPTX, PNG and Google Slides, publishes to custom domains, offers view analytics and, on higher plans, an API. Plans per seat a month billed annually: Free — 400 credits at signup; Plus — $9 (1,000 credits, no Gamma branding); Pro — $18 (4,000 credits, premium image models, custom branding, API); Ultra — $90 (20,000 credits, the most advanced text, image and video models).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'A deck, doc or site from one prompt
Import from PDF and PPTX
Export to PDF, PPTX, PNG and Google Slides
Custom domains and view analytics
API (Pro)', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Students, teachers, marketers, consultants and anyone who often needs to make presentations.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '400 кредитів при реєстрації, до 10 слайдів за запит', '400 credits at signup, up to 10 slides per prompt' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '400 credits at signup, up to 10 slides per prompt', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Plus', 'Plus', 9.00, 'month', 'За місце при річній оплаті ($108 на рік): 1 000 кредитів, без брендингу', 'Per seat billed annually ($108 a year): 1,000 credits, no branding' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Plus' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Plus', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per seat billed annually ($108 a year): 1,000 credits, no branding', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 18.00, 'month', 'За місце при річній оплаті ($216 на рік): 4 000 кредитів, власний брендинг, API', 'Per seat billed annually ($216 a year): 4,000 credits, custom branding, API' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per seat billed annually ($216 a year): 4,000 credits, custom branding, API', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ultra', 'Ultra', 90.00, 'month', 'За місце при річній оплаті ($1 080 на рік): 20 000 кредитів, найпотужніші моделі', 'Per seat billed annually ($1,080 a year): 20,000 credits, most advanced models' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ultra' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Ultra', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per seat billed annually ($1,080 a year): 20,000 credits, most advanced models', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Beautiful.ai — Презентації
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'beautiful.ai' OR LOWER(`name`) = LOWER('Beautiful.ai'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Beautiful.ai', NULL, 'https://www.beautiful.ai', NULL, NULL, 'Сервіс презентацій з AI і «розумними» слайдами, які самі вирівнюють дизайн, коли ви додаєте контент; імпорт і експорт PowerPoint, брендинг для команд.', 'A presentation tool with AI and ''smart'' slides that keep the design aligned as you add content; PowerPoint import and export and team branding.', 'Beautiful.ai допомагає робити охайні презентації без ручного вирівнювання. Понад 300 макетів Smart Slides автоматично підлаштовують розташування елементів, коли ви додаєте чи прибираєте текст, зображення й діаграми, а AI генерує вміст і цілі слайди за запитом без обмежень. Підтримуються імпорт і експорт PowerPoint та власні шаблони з фірмовим стилем; командні тарифи додають спільне редагування, аналітику, SSO та відповідність GDPR. Тарифи: Pro — $14,50 на місяць при річній оплаті; Team — $40 за користувача на місяць при річній оплаті ($50 помісячно); Enterprise — за запитом. Для всіх тарифів є 14-денний пробний період.', 'Beautiful.ai helps you make clean presentations without manual alignment. More than 300 Smart Slide layouts automatically adjust the arrangement of elements as you add or remove text, images and charts, and AI generates content and whole slides on request without limits. PowerPoint import and export and custom branded templates are supported; team plans add collaborative editing, analytics, SSO and GDPR compliance. Plans: Pro — $14.50 a month billed annually; Team — $40 per user a month billed annually ($50 monthly); Enterprise on request. All plans have a 14-day free trial.', '300+ «розумних» макетів Smart Slides
Необмежена AI-генерація вмісту
Імпорт і експорт PowerPoint
Фірмові шаблони й командна робота', '300+ Smart Slide layouts
Unlimited AI content generation
PowerPoint import and export
Branded templates and teamwork', 'Фахівці з продажів, маркетингу та консалтингу, яким потрібні акуратні презентації швидко.', 'Sales, marketing and consulting professionals who need polished presentations fast.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'beautiful.ai' OR LOWER(`name`) = LOWER('Beautiful.ai')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'presentations' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A presentation tool with AI and ''smart'' slides that keep the design aligned as you add content; PowerPoint import and export and team branding.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Beautiful.ai helps you make clean presentations without manual alignment. More than 300 Smart Slide layouts automatically adjust the arrangement of elements as you add or remove text, images and charts, and AI generates content and whole slides on request without limits. PowerPoint import and export and custom branded templates are supported; team plans add collaborative editing, analytics, SSO and GDPR compliance. Plans: Pro — $14.50 a month billed annually; Team — $40 per user a month billed annually ($50 monthly); Enterprise on request. All plans have a 14-day free trial.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', '300+ Smart Slide layouts
Unlimited AI content generation
PowerPoint import and export
Branded templates and teamwork', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Sales, marketing and consulting professionals who need polished presentations fast.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 14.50, 'month', 'При річній оплаті; необмежений AI, 300+ макетів', 'Billed annually; unlimited AI, 300+ layouts' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Billed annually; unlimited AI, 300+ layouts', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Team', 'Team', 40.00, 'month', 'За користувача при річній оплаті ($50 помісячно), 2–20 користувачів', 'Per user billed annually ($50 monthly), 2–20 users' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Team' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Team', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per user billed annually ($50 monthly), 2–20 users', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Pitch — Презентації
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'pitch.com' OR LOWER(`name`) = LOWER('Pitch'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Pitch', NULL, 'https://pitch.com', NULL, NULL, 'Сервіс для командних презентацій з AI-генератором слайдів, спільним редагуванням у реальному часі, шаблонами й аналітикою переглядів.', 'A collaborative presentation tool with an AI slide generator, real-time co-editing, templates and view analytics.', 'Pitch створено для команд, які роблять презентації разом. AI-генератор швидко складає перші слайди за запитом, а далі колеги можуть одночасно редагувати, коментувати й призначати слайди, користуватися спільними шаблонами та фірмовим стилем. Презентацію можна показувати чи надсилати посиланням і бачити аналітику переглядів. Усі тарифи дають необмежену кількість презентацій. Ціни в євро: Free — 100 разових AI-кредитів; Plus — €10 на місяць (500 AI-кредитів); Team — €15 на місяць (до 25 учасників); Business — €20 на місяць (750 кредитів, до 200 учасників); при річній оплаті знижка 17%; Enterprise — за запитом.', 'Pitch is built for teams that create presentations together. The AI generator quickly drafts the first slides from a prompt, and then colleagues can edit at the same time, comment and assign slides, and use shared templates and brand styles. A presentation can be presented or shared by link, with view analytics. All plans include unlimited presentations. Prices in euros: Free — 100 one-time AI credits; Plus — €10 a month (500 AI credits); Team — €15 a month (up to 25 members); Business — €20 a month (750 credits, up to 200 members); 17% off with annual billing; Enterprise on request.', 'AI-генератор слайдів
Спільне редагування в реальному часі
Спільні шаблони й фірмовий стиль
Аналітика переглядів', 'AI slide generator
Real-time co-editing
Shared templates and brand styles
View analytics', 'Стартапи, маркетингові й продажні команди, які спільно готують презентації.', 'Startups, marketing and sales teams that prepare presentations together.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'pitch.com' OR LOWER(`name`) = LOWER('Pitch')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'presentations' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A collaborative presentation tool with an AI slide generator, real-time co-editing, templates and view analytics.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Pitch is built for teams that create presentations together. The AI generator quickly drafts the first slides from a prompt, and then colleagues can edit at the same time, comment and assign slides, and use shared templates and brand styles. A presentation can be presented or shared by link, with view analytics. All plans include unlimited presentations. Prices in euros: Free — 100 one-time AI credits; Plus — €10 a month (500 AI credits); Team — €15 a month (up to 25 members); Business — €20 a month (750 credits, up to 200 members); 17% off with annual billing; Enterprise on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI slide generator
Real-time co-editing
Shared templates and brand styles
View analytics', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Startups, marketing and sales teams that prepare presentations together.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Необмежені презентації, 100 разових AI-кредитів', 'Unlimited presentations, 100 one-time AI credits' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited presentations, 100 one-time AI credits', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Plus', 'Plus', NULL, 'month', '€10 на місяць, 500 AI-кредитів; знижка 17% при річній оплаті', '€10 a month, 500 AI credits; 17% off billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Plus' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Plus', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '€10 a month, 500 AI credits; 17% off billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Business', 'Business', NULL, 'month', '€20 на місяць, 750 AI-кредитів, до 200 учасників', '€20 a month, 750 AI credits, up to 200 members' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Business' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Business', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '€20 a month, 750 AI credits, up to 200 members', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Plus AI — Презентації
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'plusai.com' OR LOWER(`name`) = LOWER('Plus AI'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Plus AI', NULL, 'https://www.plusai.com', NULL, NULL, 'AI для презентацій прямо в Google Slides і PowerPoint: створює, редагує й форматує слайди, не змушуючи переходити в інший сервіс.', 'AI for presentations right inside Google Slides and PowerPoint: it creates, edits and formats slides without making you switch to another tool.', 'Plus AI вбудовується в Google Slides і PowerPoint, тож працювати можна у звичних програмах. Він генерує презентацію з запиту чи документа, переписує й форматує окремі слайди, підлаштовує дизайн під корпоративні шаблони та допомагає зберігати єдиний фірмовий стиль у команді. Тарифи (при річній оплаті / помісячно): Basic — $10 / $15; Pro — $20 / $25; Team — $30 / $40; Max — $200 / $240 на місяць. Кожен тариф має 7-денний пробний період з 1 000 AI-кредитів (потрібна картка); для організацій є Enterprise з SSO і бібліотекою матеріалів.', 'Plus AI plugs into Google Slides and PowerPoint, so you can work in the apps you already use. It generates a presentation from a prompt or document, rewrites and formats individual slides, adapts the design to company templates and helps teams keep a consistent brand. Plans (billed annually / monthly): Basic — $10 / $15; Pro — $20 / $25; Team — $30 / $40; Max — $200 / $240 a month. Every plan has a 7-day trial with 1,000 AI credits (card required); organisations can get Enterprise with SSO and an asset library.', 'Працює всередині Google Slides і PowerPoint
Презентація з запиту чи документа
Редагування й форматування слайдів
Корпоративні шаблони й фірмовий стиль', 'Works inside Google Slides and PowerPoint
A deck from a prompt or document
Slide editing and formatting
Company templates and brand consistency', 'Офісні працівники, консультанти й команди, які працюють у Google Slides чи PowerPoint.', 'Office workers, consultants and teams who work in Google Slides or PowerPoint.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'plusai.com' OR LOWER(`name`) = LOWER('Plus AI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'presentations' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'AI for presentations right inside Google Slides and PowerPoint: it creates, edits and formats slides without making you switch to another tool.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Plus AI plugs into Google Slides and PowerPoint, so you can work in the apps you already use. It generates a presentation from a prompt or document, rewrites and formats individual slides, adapts the design to company templates and helps teams keep a consistent brand. Plans (billed annually / monthly): Basic — $10 / $15; Pro — $20 / $25; Team — $30 / $40; Max — $200 / $240 a month. Every plan has a 7-day trial with 1,000 AI credits (card required); organisations can get Enterprise with SSO and an asset library.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Works inside Google Slides and PowerPoint
A deck from a prompt or document
Slide editing and formatting
Company templates and brand consistency', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Office workers, consultants and teams who work in Google Slides or PowerPoint.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Basic', 'Basic', 10.00, 'month', 'При річній оплаті ($15 помісячно)', 'Billed annually ($15 monthly)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Basic' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Basic', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Billed annually ($15 monthly)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 20.00, 'month', 'Розширені функції; $25 помісячно', 'Advanced features; $25 monthly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Advanced features; $25 monthly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Team', 'Team', 30.00, 'month', 'Для команд з фірмовим стилем; $40 помісячно', 'For teams with brand consistency; $40 monthly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Team' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Team', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'For teams with brand consistency; $40 monthly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- GPTExcel — Таблиці
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'gptexcel.uk' OR LOWER(`name`) = LOWER('GPTExcel'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'GPTExcel', NULL, 'https://gptexcel.uk', NULL, NULL, 'AI-помічник для таблиць: завантажте Excel чи CSV, поставте запитання звичайною мовою й отримайте формули, зведені таблиці, графіки та підсумки.', 'An AI spreadsheet assistant: upload Excel or CSV, ask in plain language and get formulas, pivot tables, charts and summaries.', 'GPTExcel допомагає працювати з таблицями без знання складних формул. Завантажте файл Excel чи CSV і запитайте, що потрібно, — сервіс підготує формулу, зведену таблицю, графік чи короткий підсумок даних. Окремо є генератори формул для Excel і Google Sheets, SQL-запитів, регулярних виразів і скриптів, а агент Pivot Builder будує зведені таблиці й діаграми. Тарифи: Free — 10 повідомлень на місяць і файли до 5 МБ; Pro — $9 на місяць (3 000 повідомлень, файли до 50 МБ); Pro Plus — $18 на місяць (10 000 повідомлень, файли до 100 МБ).', 'GPTExcel helps you work with spreadsheets without knowing complex formulas. Upload an Excel or CSV file and ask what you need — it prepares a formula, a pivot table, a chart or a short data summary. There are also generators for Excel and Google Sheets formulas, SQL queries, regular expressions and scripts, and the Pivot Builder agent creates pivot tables and charts. Plans: Free — 10 messages a month and files up to 5 MB; Pro — $9 a month (3,000 messages, files up to 50 MB); Pro Plus — $18 a month (10,000 messages, files up to 100 MB).', 'Аналіз Excel і CSV запитами звичайною мовою
Генератор формул Excel і Google Sheets
SQL, регулярні вирази й скрипти
Pivot Builder для зведених таблиць і графіків', 'Analyse Excel and CSV with plain-language questions
Excel and Google Sheets formula generator
SQL, regex and scripts
Pivot Builder for pivot tables and charts', 'Офісні працівники, аналітики-початківці й студенти, які працюють з таблицями.', 'Office workers, junior analysts and students who work with spreadsheets.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'gptexcel.uk' OR LOWER(`name`) = LOWER('GPTExcel')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'spreadsheets' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI spreadsheet assistant: upload Excel or CSV, ask in plain language and get formulas, pivot tables, charts and summaries.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'GPTExcel helps you work with spreadsheets without knowing complex formulas. Upload an Excel or CSV file and ask what you need — it prepares a formula, a pivot table, a chart or a short data summary. There are also generators for Excel and Google Sheets formulas, SQL queries, regular expressions and scripts, and the Pivot Builder agent creates pivot tables and charts. Plans: Free — 10 messages a month and files up to 5 MB; Pro — $9 a month (3,000 messages, files up to 50 MB); Pro Plus — $18 a month (10,000 messages, files up to 100 MB).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Analyse Excel and CSV with plain-language questions
Excel and Google Sheets formula generator
SQL, regex and scripts
Pivot Builder for pivot tables and charts', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Office workers, junior analysts and students who work with spreadsheets.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '10 повідомлень на місяць, файли до 5 МБ', '10 messages a month, files up to 5 MB' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '10 messages a month, files up to 5 MB', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 9.00, 'month', '3 000 повідомлень на місяць, файли до 50 МБ', '3,000 messages a month, files up to 50 MB' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '3,000 messages a month, files up to 50 MB', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro Plus', 'Pro Plus', 18.00, 'month', '10 000 повідомлень на місяць, файли до 100 МБ', '10,000 messages a month, files up to 100 MB' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro Plus' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro Plus', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '10,000 messages a month, files up to 100 MB', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Numerous.ai — Таблиці
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'numerous.ai' OR LOWER(`name`) = LOWER('Numerous.ai'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Numerous.ai', NULL, 'https://numerous.ai', NULL, NULL, 'Доповнення для Google Sheets і Excel, яке додає функцію =AI у клітинки: генерує тексти, класифікує й очищає дані прямо в таблиці, без API-ключів.', 'An add-on for Google Sheets and Excel that adds an =AI function to cells: it generates text and categorises and cleans data right in the sheet, with no API keys.', 'Numerous.ai приносить ChatGPT прямо в таблиці. Після встановлення доповнення для Google Sheets чи Excel у клітинках можна писати функцію =AI і масово обробляти рядки: генерувати рекламні тексти й ключові слова, підсумовувати, класифікувати й очищати текстові дані, швидко прототипувати AI-процеси. API-ключі не потрібні, повторні однакові запити не тарифікуються, а невикористані токени зберігаються. Тариф Personal коштує $10 на місяць при річній оплаті (500 000 символів, 500 генерацій формул); для команд до 8 людей — $10 на місяць за особу з пріоритетною підтримкою. Є 7-денний пробний період.', 'Numerous.ai brings ChatGPT straight into spreadsheets. Once you install the add-on for Google Sheets or Excel, you can type an =AI function in cells and process rows in bulk: generate ad copy and keywords, summarise, categorise and clean text data, and quickly prototype AI workflows. No API keys are needed, duplicate queries are not charged and unused tokens carry over. The Personal plan costs $10 a month billed annually (500,000 characters, 500 formula generations); for teams of up to 8 people it is $10 a month per person with priority support. There is a 7-day free trial.', 'Функція =AI у клітинках Google Sheets і Excel
Масова генерація й обробка тексту
Класифікація та очищення даних
Без API-ключів', '=AI function in Google Sheets and Excel cells
Bulk text generation and processing
Data categorisation and cleaning
No API keys', 'Маркетологи, SEO-фахівці та операційні команди, які обробляють дані в таблицях.', 'Marketers, SEO specialists and operations teams who process data in spreadsheets.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'numerous.ai' OR LOWER(`name`) = LOWER('Numerous.ai')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'spreadsheets' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An add-on for Google Sheets and Excel that adds an =AI function to cells: it generates text and categorises and cleans data right in the sheet, with no API keys.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Numerous.ai brings ChatGPT straight into spreadsheets. Once you install the add-on for Google Sheets or Excel, you can type an =AI function in cells and process rows in bulk: generate ad copy and keywords, summarise, categorise and clean text data, and quickly prototype AI workflows. No API keys are needed, duplicate queries are not charged and unused tokens carry over. The Personal plan costs $10 a month billed annually (500,000 characters, 500 formula generations); for teams of up to 8 people it is $10 a month per person with priority support. There is a 7-day free trial.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', '=AI function in Google Sheets and Excel cells
Bulk text generation and processing
Data categorisation and cleaning
No API keys', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Marketers, SEO specialists and operations teams who process data in spreadsheets.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Personal', 'Personal', 10.00, 'month', 'При річній оплаті: 500 000 символів, 500 генерацій формул; 7 днів безкоштовно', 'Billed annually: 500,000 characters, 500 formula generations; 7-day free trial' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Personal' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Personal', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Billed annually: 500,000 characters, 500 formula generations; 7-day free trial', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Equals — Таблиці
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'equals.com' OR LOWER(`name`) = LOWER('Equals'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Equals', NULL, 'https://equals.com', NULL, NULL, 'Таблиця, підключена напряму до даних компанії: BI, дашборди, автоматична звітність і AI-аналітика для команд без окремого аналітика.', 'A spreadsheet connected directly to company data: BI, dashboards, automated reporting and AI analytics for teams.', 'Equals поєднує звичну таблицю з бізнес-аналітикою. Дані з бази, сховища та бізнес-сервісів підтягуються в таблицю автоматично й оновлюються за розкладом, на їх основі будуються дашборди й регулярні звіти, які можна надсилати в Slack, а AI допомагає ставити запитання до даних і знаходити інсайти. Усі тарифи включають необмежену кількість переглядачів і редакторів та виділеного аналітика для впровадження. Серед клієнтів — Notion, Descript та Intercom. Тарифи на рік: Essential — $24 000 (3 конектори, синхронізація раз на 6 годин); Business — $36 000 (5 конекторів або сховище, щогодинна синхронізація); Enterprise — $60 000 (необмежені конектори, синхронізація кожні 15 хвилин, SSO).', 'Equals combines a familiar spreadsheet with business intelligence. Data from your database, warehouse and business tools flows into the sheet automatically and refreshes on a schedule; on top of it you build dashboards and recurring reports that can be sent to Slack, and AI helps you ask questions of the data and find insights. All plans include unlimited viewers and editors and a dedicated analyst for implementation. Customers include Notion, Descript and Intercom. Annual plans: Essential — $24,000 (3 connectors, 6-hour sync); Business — $36,000 (5 connectors or a warehouse, hourly sync); Enterprise — $60,000 (unlimited connectors, 15-minute sync, SSO).', 'Таблиця з прямим підключенням до даних
Дашборди й автоматична звітність
AI-аналітика
Інтеграція зі Slack', 'Spreadsheet connected directly to data
Dashboards and automated reporting
AI analytics
Slack integration', 'Фінансові, продуктові й операційні команди компаній, що ростуть.', 'Finance, product and operations teams at growing companies.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'equals.com' OR LOWER(`name`) = LOWER('Equals')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'spreadsheets' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A spreadsheet connected directly to company data: BI, dashboards, automated reporting and AI analytics for teams.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Equals combines a familiar spreadsheet with business intelligence. Data from your database, warehouse and business tools flows into the sheet automatically and refreshes on a schedule; on top of it you build dashboards and recurring reports that can be sent to Slack, and AI helps you ask questions of the data and find insights. All plans include unlimited viewers and editors and a dedicated analyst for implementation. Customers include Notion, Descript and Intercom. Annual plans: Essential — $24,000 (3 connectors, 6-hour sync); Business — $36,000 (5 connectors or a warehouse, hourly sync); Enterprise — $60,000 (unlimited connectors, 15-minute sync, SSO).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Spreadsheet connected directly to data
Dashboards and automated reporting
AI analytics
Slack integration', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Finance, product and operations teams at growing companies.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Essential', 'Essential', 24000.00, 'year', '3 конектори, синхронізація раз на 6 годин, необмежені користувачі', '3 connectors, 6-hour sync, unlimited users' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Essential' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Essential', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '3 connectors, 6-hour sync, unlimited users', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Business', 'Business', 36000.00, 'year', '5 конекторів або сховище, щогодинна синхронізація', '5 connectors or a warehouse, hourly sync' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Business' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Business', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '5 connectors or a warehouse, hourly sync', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Enterprise', 'Enterprise', 60000.00, 'year', 'Необмежені конектори, синхронізація кожні 15 хв, SSO', 'Unlimited connectors, 15-minute sync, SSO' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Enterprise' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Enterprise', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited connectors, 15-minute sync, SSO', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Canva')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'presentations' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Genspark')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'presentations' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Rows')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'spreadsheets' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Julius AI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'spreadsheets' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Microsoft Copilot')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'productivity' AND s.`slug` = 'spreadsheets' LIMIT 1;
