SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Текст та Чат-боти» → нові підкатегорії «Перефразування і граматика» та «Генератори промптів» — 6 нових продуктів, 3 прив'язок наявних
--   LanguageTool — Перефразування і граматика
--   ProWritingAid — Перефразування і граматика
--   Hemingway Editor — Перефразування і граматика
--   AIPRM — Генератори промптів
--   PromptLayer — Генератори промптів
--   PromptHub — Генератори промптів
--   (наявний) Grammarly → Перефразування і граматика
--   (наявний) Wordtune → Перефразування і граматика
--   (наявний) QuillBot → Перефразування і граматика
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Перефразування і граматика', 'Paraphrasing & Grammar', 'paraphrasing-grammar' FROM `categories` c WHERE c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Генератори промптів', 'Prompt Generators', 'prompt-generators' FROM `categories` c WHERE c.`slug` = 'text-chatbots' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- LanguageTool — Перефразування і граматика
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'languagetool.org' OR LOWER(`name`) = LOWER('LanguageTool'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'LanguageTool', NULL, 'https://languagetool.org', NULL, NULL, 'Перевірка граматики, пунктуації, стилю та орфографії понад 30 мовами, зокрема українською, з AI-перефразуванням; працює в браузері, Word, Google Docs і на комп''ютері.', 'Grammar, punctuation, style and spelling checks in 30+ languages, including Ukrainian, with AI rephrasing; works in the browser, Word, Google Docs and on desktop.', 'LanguageTool — помічник з письма, який перевіряє граматику, пунктуацію, стиль і орфографію понад 30 мовами, серед них українська. AI пропонує перефразувати речення, а Premium додає понад 20 000 додаткових правил, особистий стильовий посібник і довші тексти. Працює як розширення для Chrome, Edge, Firefox, Safari й Opera, як застосунок для Windows, macOS та iOS і як доповнення для Word, Google Docs і LibreOffice. Безкоштовна версія: до 2 000 символів у полі й 3 AI-перефразування на день. Premium (базові ціни, на сайті часто діють знижки, ціни можуть залежати від регіону): $24,90 на місяць, $49,90 на квартал, $69,90 на рік або $119,80 за два роки; 14-денна гарантія повернення коштів.', 'LanguageTool is a writing assistant that checks grammar, punctuation, style and spelling in more than 30 languages, including Ukrainian. AI suggests sentence rephrasing, and Premium adds 20,000+ extra rules, a personal style guide and longer texts. It works as an extension for Chrome, Edge, Firefox, Safari and Opera, as an app for Windows, macOS and iOS and as an add-in for Word, Google Docs and LibreOffice. The free version allows up to 2,000 characters per field and 3 AI rephrasings a day. Premium (list prices; the site often runs discounts and prices may vary by region): $24.90 a month, $49.90 a quarter, $69.90 a year or $119.80 for two years; a 14-day money-back guarantee.', 'Граматика, стиль і орфографія 30+ мовами, зокрема українською
AI-перефразування речень
Розширення браузерів, Word, Google Docs
Застосунки для Windows, macOS та iOS', 'Grammar, style and spelling in 30+ languages, including Ukrainian
AI sentence rephrasing
Browser extensions, Word, Google Docs
Apps for Windows, macOS and iOS', 'Усі, хто пише кількома мовами: студенти, перекладачі, офісні працівники, автори.', 'Anyone who writes in several languages: students, translators, office workers and writers.', 'web,mobile,desktop', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'languagetool.org' OR LOWER(`name`) = LOWER('LanguageTool')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'paraphrasing-grammar' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Grammar, punctuation, style and spelling checks in 30+ languages, including Ukrainian, with AI rephrasing; works in the browser, Word, Google Docs and on desktop.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'LanguageTool is a writing assistant that checks grammar, punctuation, style and spelling in more than 30 languages, including Ukrainian. AI suggests sentence rephrasing, and Premium adds 20,000+ extra rules, a personal style guide and longer texts. It works as an extension for Chrome, Edge, Firefox, Safari and Opera, as an app for Windows, macOS and iOS and as an add-in for Word, Google Docs and LibreOffice. The free version allows up to 2,000 characters per field and 3 AI rephrasings a day. Premium (list prices; the site often runs discounts and prices may vary by region): $24.90 a month, $49.90 a quarter, $69.90 a year or $119.80 for two years; a 14-day money-back guarantee.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Grammar, style and spelling in 30+ languages, including Ukrainian
AI sentence rephrasing
Browser extensions, Word, Google Docs
Apps for Windows, macOS and iOS', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Anyone who writes in several languages: students, translators, office workers and writers.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'До 2 000 символів, 3 AI-перефразування на день', 'Up to 2,000 characters, 3 AI rephrasings a day' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Up to 2,000 characters, 3 AI rephrasings a day', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premium (місяць)', 'Premium (monthly)', 24.90, 'month', 'Базова ціна; на сайті часто діють знижки', 'List price; the site often runs discounts' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Premium (місяць)' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Premium (monthly)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'List price; the site often runs discounts', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premium (рік)', 'Premium (yearly)', 69.90, 'year', 'Базова ціна; 150 000 символів, необмежене перефразування', 'List price; 150,000 characters, unlimited rephrasing' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Premium (рік)' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Premium (yearly)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'List price; 150,000 characters, unlimited rephrasing', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- ProWritingAid — Перефразування і граматика
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'prowritingaid.com' OR LOWER(`name`) = LOWER('ProWritingAid'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'ProWritingAid', NULL, 'https://prowritingaid.com', NULL, NULL, 'Помічник для авторів книжок і довгих текстів: перевірка граматики та стилю, понад 25 аналітичних звітів, AI-критика розділів і інструменти планування історії.', 'An assistant for book authors and long-form writers: grammar and style checks, 25+ analysis reports, AI chapter critiques and story-planning tools.', 'ProWritingAid орієнтований на тих, хто пише книжки та великі тексти. Окрім перевірки граматики й стилю, він дає понад 25 звітів про текст — повтори, темп, діалоги, читабельність тощо, — построкове редагування, AI-критику розділів з відгуком про сюжет і персонажів, власні стильові посібники та інструменти для планування історії. Старший тариф додає спільноту авторів, живі воркшопи й щоденні письменницькі спринти. Тарифи: Free — базова перевірка, 2 звіти на день (до 500 слів); Premium — $30 на місяць, $120 на рік або $399 довічно; Premium Pro — $36 на місяць, $144 на рік або $699 довічно.', 'ProWritingAid is aimed at people who write books and long texts. Besides grammar and style checks, it offers 25+ reports on your writing — repetition, pacing, dialogue, readability and more — line editing, AI chapter critiques with feedback on plot and characters, custom style guides and story-planning tools. The top plan adds a writers'' community, live workshops and daily writing sprints. Plans: Free — basic checks, 2 reports a day (up to 500 words); Premium — $30 a month, $120 a year or $399 lifetime; Premium Pro — $36 a month, $144 a year or $699 lifetime.', 'Граматика, стиль і построкове редагування
25+ аналітичних звітів про текст
AI-критика розділів
Планування історії та стильові посібники', 'Grammar, style and line editing
25+ analysis reports
AI chapter critiques
Story planning and style guides', 'Письменники, автори нон-фікшн і блогери, які працюють з довгими текстами англійською.', 'Novelists, non-fiction authors and bloggers working on long texts in English.', 'web,desktop', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'prowritingaid.com' OR LOWER(`name`) = LOWER('ProWritingAid')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'paraphrasing-grammar' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An assistant for book authors and long-form writers: grammar and style checks, 25+ analysis reports, AI chapter critiques and story-planning tools.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'ProWritingAid is aimed at people who write books and long texts. Besides grammar and style checks, it offers 25+ reports on your writing — repetition, pacing, dialogue, readability and more — line editing, AI chapter critiques with feedback on plot and characters, custom style guides and story-planning tools. The top plan adds a writers'' community, live workshops and daily writing sprints. Plans: Free — basic checks, 2 reports a day (up to 500 words); Premium — $30 a month, $120 a year or $399 lifetime; Premium Pro — $36 a month, $144 a year or $699 lifetime.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Grammar, style and line editing
25+ analysis reports
AI chapter critiques
Story planning and style guides', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Novelists, non-fiction authors and bloggers working on long texts in English.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Базова перевірка, 2 звіти на день до 500 слів', 'Basic checks, 2 reports a day up to 500 words' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Basic checks, 2 reports a day up to 500 words', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premium', 'Premium', 120.00, 'year', '$10/міс при річній оплаті ($30 помісячно, $399 довічно)', '$10/mo billed yearly ($30 monthly, $399 lifetime)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Premium' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Premium', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '$10/mo billed yearly ($30 monthly, $399 lifetime)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Premium Pro', 'Premium Pro', 144.00, 'year', '$12/міс при річній оплаті ($36 помісячно, $699 довічно), спільнота й воркшопи', '$12/mo billed yearly ($36 monthly, $699 lifetime), community and workshops' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Premium Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Premium Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '$12/mo billed yearly ($36 monthly, $699 lifetime), community and workshops', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Hemingway Editor — Перефразування і граматика
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'hemingwayapp.com' OR LOWER(`name`) = LOWER('Hemingway Editor'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Hemingway Editor', NULL, 'https://hemingwayapp.com', NULL, NULL, 'Редактор, що робить текст ясним і читабельним: підсвічує складні речення, пасивний стан і зайві слова, а версія Plus з AI виправляє граматику та переписує речення.', 'An editor that makes writing clear and readable: it highlights hard sentences, passive voice and unnecessary words, and the AI-powered Plus version fixes grammar and rewrites sentences.', 'Hemingway Editor допомагає писати просто й зрозуміло. Він оцінює рівень читабельності тексту й підсвічує надто довгі та складні речення, пасивний стан, зайві прислівники й слова, для яких є простіші заміни. Безкоштовні онлайн-інструменти включають перевірку граматики, перефразування, AI-коректуру та перевірку читабельності. Hemingway Editor Plus додає AI-функції — виправлення граматики й орфографії, переписування речень, підбір синонімів — з лімітом на кількість речень. Є 2-тижневий безкоштовний пробний період; при річній оплаті Plus коштує $100 на рік (5 000 AI-речень на місяць) або $150 на рік (10 000 речень), командний тариф — $150 на рік за користувача.', 'Hemingway Editor helps you write plainly and clearly. It grades the readability of your text and highlights overly long and complex sentences, passive voice, unnecessary adverbs and words with simpler alternatives. Free online tools include a grammar checker, paraphrasing, an AI proofreader and a readability checker. Hemingway Editor Plus adds AI features — grammar and spelling fixes, sentence rewrites and synonyms — with a monthly sentence limit. There is a 2-week free trial; billed annually, Plus costs $100 a year (5,000 AI sentences a month) or $150 a year (10,000 sentences), and the team plan is $150 a year per user.', 'Оцінка читабельності тексту
Підсвічування складних речень і пасиву
AI-виправлення граматики й переписування (Plus)
Безкоштовні онлайн-інструменти', 'Readability grading
Highlights hard sentences and passive voice
AI grammar fixes and rewrites (Plus)
Free online tools', 'Автори, маркетологи, журналісти й студенти, які хочуть писати коротко й ясно англійською.', 'Writers, marketers, journalists and students who want to write concisely and clearly in English.', 'web,desktop', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'hemingwayapp.com' OR LOWER(`name`) = LOWER('Hemingway Editor')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'paraphrasing-grammar' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An editor that makes writing clear and readable: it highlights hard sentences, passive voice and unnecessary words, and the AI-powered Plus version fixes grammar and rewrites sentences.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Hemingway Editor helps you write plainly and clearly. It grades the readability of your text and highlights overly long and complex sentences, passive voice, unnecessary adverbs and words with simpler alternatives. Free online tools include a grammar checker, paraphrasing, an AI proofreader and a readability checker. Hemingway Editor Plus adds AI features — grammar and spelling fixes, sentence rewrites and synonyms — with a monthly sentence limit. There is a 2-week free trial; billed annually, Plus costs $100 a year (5,000 AI sentences a month) or $150 a year (10,000 sentences), and the team plan is $150 a year per user.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Readability grading
Highlights hard sentences and passive voice
AI grammar fixes and rewrites (Plus)
Free online tools', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Writers, marketers, journalists and students who want to write concisely and clearly in English.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовно', 'Free', 0.00, 'free', 'Онлайн-редактор і безкоштовні інструменти; 2 тижні Plus безкоштовно', 'Online editor and free tools; 2-week free Plus trial' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Безкоштовно' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Online editor and free tools; 2-week free Plus trial', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Plus', 'Plus', 100.00, 'year', '≈$8,33/міс при річній оплаті, 5 000 AI-речень на місяць', '≈$8.33/mo billed annually, 5,000 AI sentences a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Plus' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Plus', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '≈$8.33/mo billed annually, 5,000 AI sentences a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Plus (10 000 речень)', 'Plus (10,000 sentences)', 150.00, 'year', '≈$12,50/міс при річній оплаті, 10 000 AI-речень на місяць', '≈$12.50/mo billed annually, 10,000 AI sentences a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Plus (10 000 речень)' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Plus (10,000 sentences)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '≈$12.50/mo billed annually, 10,000 AI sentences a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- AIPRM — Генератори промптів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'aiprm.com' OR LOWER(`name`) = LOWER('AIPRM'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'AIPRM', NULL, 'https://www.aiprm.com', NULL, NULL, 'Розширення браузера з бібліотекою понад 4 000 готових промптів для ChatGPT, Claude, Gemini та Midjourney, а також власними промптами й командною роботою.', 'A browser extension with a library of 4,000+ ready-made prompts for ChatGPT, Claude, Gemini and Midjourney, plus your own prompts and team sharing.', 'AIPRM — інструмент керування промптами та спільнотна бібліотека шаблонів. Розширення браузера додає в інтерфейс ChatGPT, Claude, Gemini, Midjourney та інших моделей понад 4 000 перевірених промптів для SEO, маркетингу, копірайтингу, програмування та інших задач. Можна створювати й зберігати власні приватні промпти, групувати їх у списки, ділитися з командою та підтягувати актуальний вміст сторінок з інтернету як контекст. Безкоштовна версія доступна без обмеження в часі; платні тарифи AIPRM Plus, Pro та командні збільшують квоти й відкривають додаткові функції (ціни в доларах на сайті, без повернення коштів).', 'AIPRM is a prompt management tool and community-driven prompt library. The browser extension adds 4,000+ curated prompts for SEO, marketing, copywriting, coding and other tasks to the interfaces of ChatGPT, Claude, Gemini, Midjourney and other models. You can create and store your own private prompts, organise them into lists, share them with your team and pull live web page content in as context. The free version can be used indefinitely; the paid AIPRM Plus, Pro and team plans raise quotas and unlock extra features (USD prices on the website, non-refundable).', '4 000+ готових промптів спільноти
Працює в ChatGPT, Claude, Gemini, Midjourney
Власні приватні промпти й списки
Командна робота', '4,000+ community prompts
Works in ChatGPT, Claude, Gemini, Midjourney
Your own private prompts and lists
Team collaboration', 'Маркетологи, SEO-фахівці, копірайтери й усі, хто щодня користується чат-ботами.', 'Marketers, SEO specialists, copywriters and anyone who uses chatbots daily.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'aiprm.com' OR LOWER(`name`) = LOWER('AIPRM')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'prompt-generators' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A browser extension with a library of 4,000+ ready-made prompts for ChatGPT, Claude, Gemini and Midjourney, plus your own prompts and team sharing.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'AIPRM is a prompt management tool and community-driven prompt library. The browser extension adds 4,000+ curated prompts for SEO, marketing, copywriting, coding and other tasks to the interfaces of ChatGPT, Claude, Gemini, Midjourney and other models. You can create and store your own private prompts, organise them into lists, share them with your team and pull live web page content in as context. The free version can be used indefinitely; the paid AIPRM Plus, Pro and team plans raise quotas and unlock extra features (USD prices on the website, non-refundable).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', '4,000+ community prompts
Works in ChatGPT, Claude, Gemini, Midjourney
Your own private prompts and lists
Team collaboration', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Marketers, SEO specialists, copywriters and anyone who uses chatbots daily.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', 'Безстрокова безкоштовна версія з бібліотекою промптів', 'Indefinite free version with the prompt library' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Indefinite free version with the prompt library', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- PromptLayer — Генератори промптів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'promptlayer.com' OR LOWER(`name`) = LOWER('PromptLayer'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'PromptLayer', NULL, 'https://www.promptlayer.com', NULL, NULL, 'Платформа для керування промптами в AI-продуктах: версії, тестування, оцінювання та моніторинг запитів до OpenAI, Anthropic, Gemini й інших моделей.', 'A prompt management platform for AI products: versioning, testing, evaluation and monitoring of requests to OpenAI, Anthropic, Gemini and other models.', 'PromptLayer допомагає командам, що будують AI-продукти, тримати промпти під контролем. Промпти зберігаються в реєстрі з версіями, їх можна редагувати без зміни коду, тестувати на наборах даних, оцінювати відповіді моделей і відстежувати використання й вартість запитів. Платформа працює з OpenAI, Anthropic, Google Gemini та фреймворками LangChain і LiteLLM. Тарифи: Free — 5 користувачів, 2 500 запитів на місяць; Pro — $49 на місяць; Team — $500 на місяць (25 користувачів, 100 000+ запитів); Enterprise — за запитом, з RBAC і HIPAA.', 'PromptLayer helps teams building AI products keep their prompts under control. Prompts live in a versioned registry, can be edited without code changes, tested against datasets, and model outputs can be evaluated while usage and request costs are tracked. The platform works with OpenAI, Anthropic, Google Gemini and the LangChain and LiteLLM frameworks. Plans: Free — 5 users, 2,500 requests a month; Pro — $49 a month; Team — $500 a month (25 users, 100,000+ requests); Enterprise on request, with RBAC and HIPAA.', 'Реєстр промптів з версіями
Тестування й оцінювання відповідей
Моніторинг використання та вартості
OpenAI, Anthropic, Gemini, LangChain', 'Versioned prompt registry
Testing and output evaluation
Usage and cost monitoring
OpenAI, Anthropic, Gemini, LangChain', 'Розробники та продуктові команди, які будують застосунки на мовних моделях.', 'Developers and product teams building applications on language models.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'promptlayer.com' OR LOWER(`name`) = LOWER('PromptLayer')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'prompt-generators' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A prompt management platform for AI products: versioning, testing, evaluation and monitoring of requests to OpenAI, Anthropic, Gemini and other models.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'PromptLayer helps teams building AI products keep their prompts under control. Prompts live in a versioned registry, can be edited without code changes, tested against datasets, and model outputs can be evaluated while usage and request costs are tracked. The platform works with OpenAI, Anthropic, Google Gemini and the LangChain and LiteLLM frameworks. Plans: Free — 5 users, 2,500 requests a month; Pro — $49 a month; Team — $500 a month (25 users, 100,000+ requests); Enterprise on request, with RBAC and HIPAA.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Versioned prompt registry
Testing and output evaluation
Usage and cost monitoring
OpenAI, Anthropic, Gemini, LangChain', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Developers and product teams building applications on language models.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '5 користувачів, 2 500 запитів на місяць', '5 users, 2,500 requests a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '5 users, 2,500 requests a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 49.00, 'month', 'Необмежені робочі простори, 150 МБ датасетів', 'Unlimited workspaces, 150 MB datasets' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited workspaces, 150 MB datasets', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Team', 'Team', 500.00, 'month', '25 користувачів, 100 000+ запитів, вебхуки', '25 users, 100,000+ requests, webhooks' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Team' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Team', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '25 users, 100,000+ requests, webhooks', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- PromptHub — Генератори промптів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'prompthub.us' OR LOWER(`name`) = LOWER('PromptHub'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'PromptHub', NULL, 'https://www.prompthub.us', NULL, NULL, 'Спільнотна платформа для керування промптами: версії, пакетне тестування, оцінювання, конвеєри та API, з безкоштовним стартом для всієї команди.', 'A community-first prompt management platform: versioning, batch testing, evaluations, pipelines and an API, free to start for the whole team.', 'PromptHub допомагає зберігати, тестувати й покращувати промпти. Промпти мають історію версій, їх можна запускати пакетами на різних моделях і порівнювати результати, налаштовувати оцінювання та конвеєри з кількох кроків і викликати через API. Є спільнота з публічними промптами. Тарифи: Free — 2 000 запитів на місяць, необмежені публічні промпти й учасники команди; Pro — $12 на місяць (10 000 запитів, приватні промпти, повний API); Team — $20 за користувача на місяць (50 000 запитів, оцінювання, конвеєри); при річній оплаті на 25% дешевше; Enterprise — за запитом, з SSO і SOC 2.', 'PromptHub helps you store, test and improve prompts. Prompts have version history, can be run in batches across models with results compared, and you can set up evaluations and multi-step pipelines and call them via API. There is a community with public prompts. Plans: Free — 2,000 requests a month, unlimited public prompts and team members; Pro — $12 a month (10,000 requests, private prompts, full API); Team — $20 per user a month (50,000 requests, evaluations, pipelines); 25% cheaper billed yearly; Enterprise on request, with SSO and SOC 2.', 'Версії промптів
Пакетне тестування на різних моделях
Оцінювання й конвеєри
API та спільнота', 'Prompt versioning
Batch testing across models
Evaluations and pipelines
API and community', 'Команди, які працюють з промптами в продуктах або щоденній роботі з AI.', 'Teams that work with prompts in products or in daily AI work.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'prompthub.us' OR LOWER(`name`) = LOWER('PromptHub')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'prompt-generators' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A community-first prompt management platform: versioning, batch testing, evaluations, pipelines and an API, free to start for the whole team.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'PromptHub helps you store, test and improve prompts. Prompts have version history, can be run in batches across models with results compared, and you can set up evaluations and multi-step pipelines and call them via API. There is a community with public prompts. Plans: Free — 2,000 requests a month, unlimited public prompts and team members; Pro — $12 a month (10,000 requests, private prompts, full API); Team — $20 per user a month (50,000 requests, evaluations, pipelines); 25% cheaper billed yearly; Enterprise on request, with SSO and SOC 2.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Prompt versioning
Batch testing across models
Evaluations and pipelines
API and community', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Teams that work with prompts in products or in daily AI work.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '2 000 запитів на місяць, необмежені учасники', '2,000 requests a month, unlimited team members' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '2,000 requests a month, unlimited team members', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pro', 'Pro', 12.00, 'month', '10 000 запитів, приватні промпти, повний API; $9 при річній оплаті', '10,000 requests, private prompts, full API; $9 billed yearly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pro' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pro', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '10,000 requests, private prompts, full API; $9 billed yearly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Team', 'Team', 20.00, 'month', 'За користувача: 50 000 запитів, оцінювання; $15 при річній оплаті', 'Per user: 50,000 requests, evaluations; $15 billed yearly' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Team' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Team', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per user: 50,000 requests, evaluations; $15 billed yearly', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Grammarly')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'paraphrasing-grammar' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Wordtune')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'paraphrasing-grammar' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('QuillBot')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'text-chatbots' AND s.`slug` = 'paraphrasing-grammar' LIMIT 1;
