SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Бізнес та маркетинг» → нова підкатегорія «Продажі» — 6 нових продуктів, 3 прив'язок наявних
--   Clay — Продажі
--   lemlist — Продажі
--   Gong — Продажі
--   Outreach — Продажі
--   Salesloft — Продажі
--   Lavender — Продажі
--   (наявний) Apollo.io → Продажі
--   (наявний) Instantly.ai → Продажі
--   (наявний) Attio → Продажі
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Продажі', 'Sales', 'sales' FROM `categories` c WHERE c.`slug` = 'business-marketing' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Clay — Продажі
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'clay.com' OR LOWER(`name`) = LOWER('Clay'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Clay', NULL, 'https://www.clay.com', NULL, NULL, 'Платформа для продажів і маркетингу, що збагачує дані про клієнтів із 150+ джерел і досліджує компанії за допомогою AI-агентів Claygent.', 'A sales and marketing platform that enriches prospect data from 150+ providers and researches companies with Claygent AI agents.', 'Clay допомагає командам продажів і маркетингу знаходити потенційних клієнтів, збагачувати дані про них і запускати кампанії. У таблицях Clay дані послідовно запитуються в понад 150 постачальників (каскадний пошук email і телефонів), а AI-агенти Claygent самостійно досліджують сайти компаній і знаходять потрібні факти. Далі можна відстежувати сигнали (зміну роботи, наміри на сайті), синхронізувати дані з CRM і запускати email-кампанії. Тарифи: Free — 100 кредитів даних і 500 дій на місяць; Launch — $185 на місяць (2 500 кредитів); Growth — $495 на місяць (6 000 кредитів, синхронізація з CRM, API); Enterprise — за запитом; річна оплата дешевша на 10%.', 'Clay helps sales and marketing teams find prospects, enrich their data and launch campaigns. In Clay tables, data is requested from more than 150 providers in sequence (waterfall email and phone lookup), and Claygent AI agents research company websites on their own to find the facts you need. You can then track signals (job changes, website intent), sync data to your CRM and launch email campaigns. Plans: Free — 100 data credits and 500 actions a month; Launch — $185 a month (2,500 credits); Growth — $495 a month (6,000 credits, CRM sync, API); Enterprise on request; annual billing is 10% cheaper.', 'Збагачення даних із 150+ постачальників
AI-агенти Claygent для дослідження компаній
Сигнали: зміна роботи, наміри на сайті
Синхронізація з CRM та email-кампанії', 'Data enrichment from 150+ providers
Claygent AI agents for company research
Signals: job changes, website intent
CRM sync and email campaigns', 'Команди продажів, growth-маркетологи та RevOps, які будують outbound на даних.', 'Sales teams, growth marketers and RevOps building data-driven outbound.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'clay.com' OR LOWER(`name`) = LOWER('Clay')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'sales' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A sales and marketing platform that enriches prospect data from 150+ providers and researches companies with Claygent AI agents.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Clay helps sales and marketing teams find prospects, enrich their data and launch campaigns. In Clay tables, data is requested from more than 150 providers in sequence (waterfall email and phone lookup), and Claygent AI agents research company websites on their own to find the facts you need. You can then track signals (job changes, website intent), sync data to your CRM and launch email campaigns. Plans: Free — 100 data credits and 500 actions a month; Launch — $185 a month (2,500 credits); Growth — $495 a month (6,000 credits, CRM sync, API); Enterprise on request; annual billing is 10% cheaper.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Data enrichment from 150+ providers
Claygent AI agents for company research
Signals: job changes, website intent
CRM sync and email campaigns', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Sales teams, growth marketers and RevOps building data-driven outbound.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Free', 'Free', 0.00, 'free', '100 кредитів даних і 500 дій на місяць', '100 data credits and 500 actions a month' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Free' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '100 data credits and 500 actions a month', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Launch', 'Launch', 185.00, 'month', '2 500 кредитів даних, 15 000 дій; $166,50 при річній оплаті', '2,500 data credits, 15,000 actions; $166.50 billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Launch' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Launch', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '2,500 data credits, 15,000 actions; $166.50 billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Growth', 'Growth', 495.00, 'month', '6 000 кредитів даних, 40 000 дій, CRM і API; $445,50 при річній оплаті', '6,000 data credits, 40,000 actions, CRM and API; $445.50 billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Growth' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Growth', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '6,000 data credits, 40,000 actions, CRM and API; $445.50 billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- lemlist — Продажі
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'lemlist.com' OR LOWER(`name`) = LOWER('lemlist'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'lemlist', NULL, 'https://www.lemlist.com', NULL, NULL, 'Платформа холодних розсилок і мультиканального outreach: база 650+ млн лідів, AI-персоналізація та послідовності в email, LinkedIn, дзвінках, SMS і WhatsApp.', 'A cold email and multichannel outreach platform: a 650M+ lead database, AI personalisation and sequences across email, LinkedIn, calls, SMS and WhatsApp.', 'lemlist поєднує пошук лідів, автоматизацію outreach і AI-персоналізацію в одному інструменті. У базі понад 650 млн контактів можна знайти людей із потрібними ознаками, а потім звертатися до них автоматичними послідовностями через email, LinkedIn, дзвінки, SMS і WhatsApp. AI-агент lemAgent допомагає складати кампанії й персоналізувати повідомлення, а прогрів пошти й інструменти доставлюваності підтримують листи поза спамом. Тарифи: Email — $69 на місяць ($55 при річній оплаті, 50 000 листів); Multichannel — $109 на місяць ($87 при річній оплаті, усі канали); Enterprise — за запитом.', 'lemlist combines lead search, outreach automation and AI personalisation in one tool. In a database of 650M+ contacts you can find people who match your criteria and then reach them with automated sequences over email, LinkedIn, calls, SMS and WhatsApp. The lemAgent AI agent helps build campaigns and personalise messages, while email warm-up and deliverability tools keep emails out of spam. Plans: Email — $69 a month ($55 billed annually, 50,000 emails); Multichannel — $109 a month ($87 billed annually, all channels); Enterprise on request.', 'База 650+ млн лідів
Послідовності в email, LinkedIn, дзвінках, SMS, WhatsApp
AI-агент lemAgent і персоналізація
Прогрів пошти та доставлюваність', '650M+ lead database
Sequences across email, LinkedIn, calls, SMS, WhatsApp
lemAgent AI agent and personalisation
Email warm-up and deliverability', 'Продавці, SDR, агенції та засновники, які шукають клієнтів через холодний outreach.', 'Salespeople, SDRs, agencies and founders who find customers through cold outreach.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'lemlist.com' OR LOWER(`name`) = LOWER('lemlist')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'sales' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A cold email and multichannel outreach platform: a 650M+ lead database, AI personalisation and sequences across email, LinkedIn, calls, SMS and WhatsApp.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'lemlist combines lead search, outreach automation and AI personalisation in one tool. In a database of 650M+ contacts you can find people who match your criteria and then reach them with automated sequences over email, LinkedIn, calls, SMS and WhatsApp. The lemAgent AI agent helps build campaigns and personalise messages, while email warm-up and deliverability tools keep emails out of spam. Plans: Email — $69 a month ($55 billed annually, 50,000 emails); Multichannel — $109 a month ($87 billed annually, all channels); Enterprise on request.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', '650M+ lead database
Sequences across email, LinkedIn, calls, SMS, WhatsApp
lemAgent AI agent and personalisation
Email warm-up and deliverability', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Salespeople, SDRs, agencies and founders who find customers through cold outreach.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Email', 'Email', 69.00, 'month', 'Необмежені користувачі, 50 000 листів на місяць; $55 при річній оплаті', 'Unlimited users, 50,000 emails a month; $55 billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Email' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Email', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Unlimited users, 50,000 emails a month; $55 billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Multichannel', 'Multichannel', 109.00, 'month', 'Усі канали: LinkedIn, SMS, WhatsApp, дзвінки; $87 при річній оплаті', 'All channels: LinkedIn, SMS, WhatsApp, calls; $87 billed annually' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Multichannel' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Multichannel', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'All channels: LinkedIn, SMS, WhatsApp, calls; $87 billed annually', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Gong — Продажі
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'gong.io' OR LOWER(`name`) = LOWER('Gong'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Gong', NULL, 'https://www.gong.io', NULL, NULL, 'Платформа revenue intelligence: записує й аналізує дзвінки та листи з клієнтами, прогнозує угоди й дає AI-агентів для команд продажів.', 'A revenue intelligence platform: it records and analyses customer calls and emails, forecasts deals and provides AI agents for sales teams.', 'Gong — «операційна система» для команд продажів на основі AI. Він автоматично записує дзвінки та зустрічі з клієнтами, транскрибує й аналізує їх, а також враховує листування, щоб показати, що відбувається в кожній угоді: ризики, наступні кроки, згадки конкурентів. На цих даних працюють прогнозування виручки, коучинг продавців, автоматизація outreach і AI-агенти, що виконують рутинні задачі. Gong інтегрується з CRM та іншими інструментами без доплати. Ціни не опубліковано: ліцензії рахуються за користувача плюс платформний збір залежно від розміру команди; пропозицію готують індивідуально.', 'Gong is an AI-powered ''operating system'' for revenue teams. It automatically records customer calls and meetings, transcribes and analyses them, and takes email into account to show what is happening in every deal: risks, next steps and competitor mentions. On top of this data it provides revenue forecasting, rep coaching, outreach automation and AI agents that handle routine tasks. Gong integrates with your CRM and other tools at no extra cost. Pricing is not published: licences are per user plus a platform fee based on team size, and proposals are tailored.', 'Запис і AI-аналіз дзвінків та зустрічей
Аналіз угод: ризики й наступні кроки
Прогнозування виручки
Коучинг продавців і AI-агенти', 'Call and meeting recording with AI analysis
Deal insights: risks and next steps
Revenue forecasting
Rep coaching and AI agents', 'Відділи продажів і керівники B2B-компаній середнього та великого розміру.', 'Sales teams and revenue leaders at mid-sized and large B2B companies.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'gong.io' OR LOWER(`name`) = LOWER('Gong')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'sales' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A revenue intelligence platform: it records and analyses customer calls and emails, forecasts deals and provides AI agents for sales teams.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Gong is an AI-powered ''operating system'' for revenue teams. It automatically records customer calls and meetings, transcribes and analyses them, and takes email into account to show what is happening in every deal: risks, next steps and competitor mentions. On top of this data it provides revenue forecasting, rep coaching, outreach automation and AI agents that handle routine tasks. Gong integrates with your CRM and other tools at no extra cost. Pricing is not published: licences are per user plus a platform fee based on team size, and proposals are tailored.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Call and meeting recording with AI analysis
Deal insights: risks and next steps
Revenue forecasting
Rep coaching and AI agents', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Sales teams and revenue leaders at mid-sized and large B2B companies.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ціна за запитом', 'Price on request', NULL, 'month', 'Ліцензія за користувача + платформний збір; індивідуальна пропозиція', 'Per-user licence + platform fee; tailored proposal' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ціна за запитом' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Price on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per-user licence + platform fee; tailored proposal', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Outreach — Продажі
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'outreach.ai' OR LOWER(`name`) = LOWER('Outreach'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Outreach', NULL, 'https://www.outreach.ai', NULL, NULL, 'AI-платформа для команд продажів: агенти для менеджерів, керівників і RevOps допомагають будувати воронку, закривати угоди й прогнозувати виручку.', 'An AI platform for revenue teams: agents for account executives, sales leaders and RevOps help build pipeline, close deals and forecast revenue.', 'Outreach позиціонує себе як платформу AI-агентів для команд продажів. Агенти, налаштовані під різні ролі, допомагають знаходити й опрацьовувати потенційних клієнтів, вести послідовності контактів, готуватися до зустрічей, оцінювати стан угод і складати прогнози. Платформа охоплює sales engagement, аналіз розмов, управління угодами та прогнозування. Модель оплати змішана: місця за користувачів (без платформного збору) плюс AI-кредити за використання; пакети Amplify Essentials, Core, Plus і Pro містять від 10 000 до 100 000 AI-кредитів. Конкретні ціни не опубліковано — пропозицію готують під команду.', 'Outreach presents itself as an AI agent platform for revenue teams. Agents tailored to different roles help find and work prospects, run contact sequences, prepare for meetings, assess deal health and build forecasts. The platform covers sales engagement, conversation intelligence, deal management and forecasting. Pricing is hybrid: per-user seats (no platform fee) plus AI credits for usage; the Amplify Essentials, Core, Plus and Pro packages include 10,000 to 100,000 AI credits. Exact prices are not published — proposals are tailored to the team.', 'AI-агенти під ролі в команді продажів
Послідовності контактів і sales engagement
Аналіз розмов і стану угод
Прогнозування виручки', 'Role-specific AI agents for revenue teams
Contact sequences and sales engagement
Conversation and deal insights
Revenue forecasting', 'B2B-команди продажів, керівники відділів і RevOps.', 'B2B sales teams, sales leaders and RevOps.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'outreach.ai' OR LOWER(`name`) = LOWER('Outreach')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'sales' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI platform for revenue teams: agents for account executives, sales leaders and RevOps help build pipeline, close deals and forecast revenue.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Outreach presents itself as an AI agent platform for revenue teams. Agents tailored to different roles help find and work prospects, run contact sequences, prepare for meetings, assess deal health and build forecasts. The platform covers sales engagement, conversation intelligence, deal management and forecasting. Pricing is hybrid: per-user seats (no platform fee) plus AI credits for usage; the Amplify Essentials, Core, Plus and Pro packages include 10,000 to 100,000 AI credits. Exact prices are not published — proposals are tailored to the team.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Role-specific AI agents for revenue teams
Contact sequences and sales engagement
Conversation and deal insights
Revenue forecasting', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'B2B sales teams, sales leaders and RevOps.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ціна за запитом', 'Price on request', NULL, 'month', 'Місця за користувача + AI-кредити (пакети Amplify від 10 000 до 100 000 кредитів)', 'Per-user seats + AI credits (Amplify packages from 10,000 to 100,000 credits)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ціна за запитом' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Price on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Per-user seats + AI credits (Amplify packages from 10,000 to 100,000 credits)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Salesloft — Продажі
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'salesloft.com' OR LOWER(`name`) = LOWER('Salesloft'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Salesloft', NULL, 'https://www.salesloft.com', NULL, NULL, 'Платформа для виконання продажів (тепер разом із Clari): послідовності контактів, аналіз розмов, керування угодами, прогнозування та AI-агенти.', 'A revenue execution platform (now merged with Clari): contact cadences, conversation intelligence, deal management, forecasting and AI agents.', 'Salesloft допомагає командам продажів організувати всю роботу з клієнтами: послідовності дзвінків і листів (Cadence), аналіз розмов, керування угодами, перевірку воронки (Inspect) і щоденні пріоритети для продавців (Rhythm). Після об''єднання з Clari до платформи додалося прогнозування Clari Forecast, а спільний шар даних пов''язує всі процеси. AI-агенти автоматизують рутину на кожному етапі — від першого контакту до закриття угоди. Компанія повідомляє про економію понад 12 годин на тиждень на одного продавця. Ціни не опубліковано — їх надає відділ продажів.', 'Salesloft helps sales teams organise all their customer work: call and email cadences (Cadence), conversation intelligence, deal management, pipeline inspection (Inspect) and daily priorities for reps (Rhythm). Following its merger with Clari, the platform now includes Clari Forecast, and a shared data layer connects every workflow. AI agents automate routine work at every stage — from first touch to closing the deal. The company reports more than 12 hours saved per rep each week. Pricing is not published — contact sales.', 'Послідовності дзвінків і листів (Cadence)
Аналіз розмов і керування угодами
Прогнозування Clari Forecast
AI-агенти для рутинних задач', 'Call and email cadences (Cadence)
Conversation intelligence and deal management
Clari Forecast forecasting
AI agents for routine tasks', 'B2B-команди продажів і керівники, яким потрібна єдина система для всього циклу угоди.', 'B2B sales teams and leaders who need one system for the whole deal cycle.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'salesloft.com' OR LOWER(`name`) = LOWER('Salesloft')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'sales' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A revenue execution platform (now merged with Clari): contact cadences, conversation intelligence, deal management, forecasting and AI agents.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Salesloft helps sales teams organise all their customer work: call and email cadences (Cadence), conversation intelligence, deal management, pipeline inspection (Inspect) and daily priorities for reps (Rhythm). Following its merger with Clari, the platform now includes Clari Forecast, and a shared data layer connects every workflow. AI agents automate routine work at every stage — from first touch to closing the deal. The company reports more than 12 hours saved per rep each week. Pricing is not published — contact sales.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Call and email cadences (Cadence)
Conversation intelligence and deal management
Clari Forecast forecasting
AI agents for routine tasks', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'B2B sales teams and leaders who need one system for the whole deal cycle.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Ціна за запитом', 'Price on request', NULL, 'month', 'Ціни надає відділ продажів', 'Contact sales for pricing' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Ціна за запитом' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Price on request', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Contact sales for pricing', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Lavender — Продажі
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'lavender.ai' OR LOWER(`name`) = LOWER('Lavender'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Lavender', NULL, 'https://www.lavender.ai', NULL, NULL, 'AI-коуч для холодних листів: у реальному часі оцінює текст листа, підказує, як підвищити шанс відповіді, і пише чернетки за допомогою агента Ora.', 'An AI coach for cold emails: it scores your email in real time, suggests how to improve the chance of a reply and writes drafts with the Ora agent.', 'Lavender допомагає продавцям писати холодні листи, на які відповідають. Сервіс навчено на мільярдах листів, тож він знає, що працює: прямо під час написання Email Coach оцінює лист, підказує, що скоротити чи змінити, перевіряє тон і читабельність, а AI-агент Ora готує персоналізовані чернетки на основі даних про отримувача. Lavender працює як розширення поверх поштових клієнтів, має сертифікацію SOC 2 і відповідає GDPR. Коуча можна встановити безкоштовно; ціни платних тарифів на головній сторінці не вказано.', 'Lavender helps salespeople write cold emails that get replies. It has been trained on billions of emails, so it knows what works: as you write, the Email Coach scores the email, suggests what to cut or change and checks tone and readability, while the Ora AI agent prepares personalised drafts based on data about the recipient. Lavender works as an extension on top of email clients, is SOC 2 certified and GDPR compliant. The Coach can be installed for free; paid plan prices are not shown on the home page.', 'Оцінка листа в реальному часі
Підказки щодо довжини, тону й читабельності
AI-агент Ora для персоналізованих чернеток
SOC 2 і GDPR', 'Real-time email scoring
Tips on length, tone and readability
Ora AI agent for personalised drafts
SOC 2 and GDPR', 'SDR, менеджери з продажів і засновники, які пишуть багато холодних листів.', 'SDRs, account executives and founders who write a lot of cold emails.', 'web', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'lavender.ai' OR LOWER(`name`) = LOWER('Lavender')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'sales' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'An AI coach for cold emails: it scores your email in real time, suggests how to improve the chance of a reply and writes drafts with the Ora agent.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Lavender helps salespeople write cold emails that get replies. It has been trained on billions of emails, so it knows what works: as you write, the Email Coach scores the email, suggests what to cut or change and checks tone and readability, while the Ora AI agent prepares personalised drafts based on data about the recipient. Lavender works as an extension on top of email clients, is SOC 2 certified and GDPR compliant. The Coach can be installed for free; paid plan prices are not shown on the home page.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Real-time email scoring
Tips on length, tone and readability
Ora AI agent for personalised drafts
SOC 2 and GDPR', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'SDRs, account executives and founders who write a lot of cold emails.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовно', 'Free', 0.00, 'free', 'Email Coach можна встановити безкоштовно', 'The Email Coach can be installed for free' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Безкоштовно' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'The Email Coach can be installed for free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Apollo.io')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'sales' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Instantly.ai')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'sales' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Attio')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'business-marketing' AND s.`slug` = 'sales' LIMIT 1;
