SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Здоров'я та краса» → нові підкатегорії «Сон» і «Харчування» — 6 нових продуктів, 14 прив'язок наявних
--   Oura — Сон
--   Eight Sleep — Сон
--   Rise — Сон
--   Sleep Cycle — Сон
--   Cal AI — Харчування
--   SnapCalorie — Харчування
--   (наявний) Calm → Сон
--   (наявний) Whoop → Сон
--   (наявний) Headspace → Сон
--   (наявний) MyFitnessPal → Харчування
--   (наявний) Noom → Харчування
--   (наявний) Carb Manager → Харчування
--   (наявний) Cronometer → Харчування
--   (наявний) MacroFactor → Харчування
--   (наявний) Lose It! → Харчування
--   (наявний) MyNetDiary → Харчування
--   (наявний) Intake → Харчування
--   (наявний) Nutrola → Харчування
--   (наявний) Eat This Much → Харчування
--   (наявний) Alma → Харчування
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Сон', 'Sleep', 'sleep' FROM `categories` c WHERE c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Харчування', 'Nutrition', 'nutrition' FROM `categories` c WHERE c.`slug` = 'health-beauty' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Oura — Сон
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'ouraring.com' OR LOWER(`name`) = LOWER('Oura'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Oura', NULL, 'https://ouraring.com', NULL, NULL, 'Смарт-кільце, що відстежує сон, відновлення, активність і стрес за 50+ показниками, з AI-помічником Oura Advisor, який пояснює ваші дані.', 'A smart ring that tracks sleep, readiness, activity and stress across 50+ health metrics, with the Oura Advisor AI companion that explains your data.', 'Oura Ring — розумне кільце, яке носять цілодобово. Воно відстежує понад 50 показників здоров''я — сон і його фази, пульс, серцево-судинні дані, активність і стрес — і щодня показує оцінки сну, готовності (Readiness) та активності. Oura Advisor, AI-помічник у застосунку, перетворює ці дані на персональні поради: чому ви погано спали, коли варто відпочити, як змінюється ваш стан. Саме кільце купується окремо; для повного доступу до щоденних інсайтів потрібне членство — $5,99 на місяць або $69,99 на рік (ціни можуть відрізнятися за регіоном), перший місяць безкоштовний. Без підписки кільце працює з обмеженими даними. Oura не є медичним виробом для діагностики.', 'Oura Ring is a smart ring worn day and night. It tracks more than 50 health metrics — sleep and sleep stages, heart rate, cardiovascular data, activity and stress — and shows daily Sleep, Readiness and Activity scores. Oura Advisor, the AI companion in the app, turns this data into personal guidance: why you slept badly, when to rest and how your condition is changing. The ring is bought separately; full access to daily insights requires a membership — $5.99 a month or $69.99 a year (prices may vary by region), with the first month free. Without a subscription the ring works with limited insights. Oura is not a diagnostic medical device.', 'Відстеження сну, пульсу, активності й стресу
Оцінки сну, готовності та активності
AI-помічник Oura Advisor
Носіння 24/7 у формі кільця', 'Tracks sleep, heart rate, activity and stress
Sleep, Readiness and Activity scores
Oura Advisor AI companion
Worn 24/7 as a ring', 'Люди, які хочуть краще спати й стежити за відновленням без годинника на руці.', 'People who want to sleep better and track recovery without wearing a watch.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'ouraring.com' OR LOWER(`name`) = LOWER('Oura')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'sleep' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A smart ring that tracks sleep, readiness, activity and stress across 50+ health metrics, with the Oura Advisor AI companion that explains your data.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Oura Ring is a smart ring worn day and night. It tracks more than 50 health metrics — sleep and sleep stages, heart rate, cardiovascular data, activity and stress — and shows daily Sleep, Readiness and Activity scores. Oura Advisor, the AI companion in the app, turns this data into personal guidance: why you slept badly, when to rest and how your condition is changing. The ring is bought separately; full access to daily insights requires a membership — $5.99 a month or $69.99 a year (prices may vary by region), with the first month free. Without a subscription the ring works with limited insights. Oura is not a diagnostic medical device.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Tracks sleep, heart rate, activity and stress
Sleep, Readiness and Activity scores
Oura Advisor AI companion
Worn 24/7 as a ring', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People who want to sleep better and track recovery without wearing a watch.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Членство (місяць)', 'Membership (monthly)', 5.99, 'month', 'Повний доступ до інсайтів; перший місяць безкоштовно; кільце купується окремо', 'Full access to insights; first month free; ring sold separately' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Членство (місяць)' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Membership (monthly)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Full access to insights; first month free; ring sold separately', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Членство (рік)', 'Membership (annual)', 69.99, 'year', 'Ціни можуть відрізнятися за регіоном', 'Prices may vary by region' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Членство (рік)' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Membership (annual)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Prices may vary by region', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Eight Sleep — Сон
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'eightsleep.com' OR LOWER(`name`) = LOWER('Eight Sleep'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Eight Sleep', NULL, 'https://www.eightsleep.com', NULL, NULL, 'Розумний чохол для матраца Pod: охолоджує й підігріває кожну половину ліжка окремо, відстежує сон біометричними датчиками й сам підлаштовує температуру вночі.', 'The Pod smart mattress cover: it cools and heats each side of the bed separately, tracks sleep with biometric sensors and adjusts the temperature automatically at night.', 'Eight Sleep Pod — система з чохла для матраца та блока Hub, що ставиться біля ліжка. Чохол з вбудованими біометричними датчиками охолоджує або підігріває кожну половину ліжка окремо в діапазоні приблизно від 13 до 43 °C, відстежує фази сну й показники здоров''я та протягом ночі сам змінює температуру, щоб подовжити глибокий сон і фазу REM. Налаштування й аналітика — у мобільному застосунку, є інтеграція з фітнес- і health-застосунками. Окремо можна додати основу з підйомом узголів''я, що допомагає при хропінні. Pod 6 коштує від $1 999.', 'Eight Sleep Pod is a system made of a mattress cover and a Hub unit placed beside the bed. The cover, with built-in biometric sensors, cools or heats each side of the bed separately within roughly 13–43 °C (55–110 °F), tracks sleep stages and health metrics and adjusts the temperature through the night to extend deep and REM sleep. Settings and analytics live in the mobile app, which integrates with fitness and health apps. An optional Base with head elevation helps with snoring. Pod 6 starts at $1,999.', 'Охолодження й підігрів кожної половини ліжка
Біометричні датчики в чохлі
Автоматичне підлаштування температури вночі
Основа з підйомом узголів''я (опція)', 'Cooling and heating for each side of the bed
Biometric sensors in the cover
Automatic overnight temperature adjustment
Optional Base with head elevation', 'Люди, яким заважає спати спека чи холод, і пари з різними вподобаннями щодо температури.', 'People whose sleep suffers from heat or cold, and couples with different temperature preferences.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'eightsleep.com' OR LOWER(`name`) = LOWER('Eight Sleep')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'sleep' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'The Pod smart mattress cover: it cools and heats each side of the bed separately, tracks sleep with biometric sensors and adjusts the temperature automatically at night.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Eight Sleep Pod is a system made of a mattress cover and a Hub unit placed beside the bed. The cover, with built-in biometric sensors, cools or heats each side of the bed separately within roughly 13–43 °C (55–110 °F), tracks sleep stages and health metrics and adjusts the temperature through the night to extend deep and REM sleep. Settings and analytics live in the mobile app, which integrates with fitness and health apps. An optional Base with head elevation helps with snoring. Pod 6 starts at $1,999.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Cooling and heating for each side of the bed
Biometric sensors in the cover
Automatic overnight temperature adjustment
Optional Base with head elevation', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People whose sleep suffers from heat or cold, and couples with different temperature preferences.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Pod 6', 'Pod 6', 1999.00, 'one_time', 'Від $1 999 залежно від розміру', 'From $1,999 depending on size' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Pod 6' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Pod 6', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'From $1,999 depending on size', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Rise — Сон
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'risescience.com' OR LOWER(`name`) = LOWER('Rise'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Rise', NULL, 'https://www.risescience.com', NULL, NULL, 'Застосунок для сну й енергії: рахує ваш «борг сну» та циркадний ритм і щодня підказує, коли буде пік енергії, спад і час готуватися до сну.', 'A sleep and energy app: it calculates your sleep debt and circadian rhythm and tells you each day when to expect peak energy, dips and wind-down time.', 'Rise допомагає краще спати й мати більше енергії вдень, спираючись на два показники — борг сну та циркадний ритм. Уже в перший день застосунок аналізує історію даних телефона, визначає вашу потребу в сні й поточний борг, а з Apple Health, Oura чи Fitbit отримує точніші дані. Щодня він підказує, скільки триватиме ранкова млявість, коли буде пік концентрації та коли починати готуватися до сну, і нагадує про 16 науково обґрунтованих звичок у потрібний час. Застосунок увійшов до найкращих застосунків Apple 2026 року. Є безкоштовний пробний період; вартість підписки вказано в застосунку.', 'Rise helps you sleep better and have more energy during the day, based on two metrics — sleep debt and circadian rhythm. On day one the app analyses your phone''s data history to estimate your sleep need and current debt, and it gets more accurate data from Apple Health, Oura or Fitbit. Each day it tells you how long morning grogginess will last, when your focus will peak and when to start winding down, and reminds you of 16 science-based habits at the right time. It was named one of Apple''s Best Apps of 2026. There is a free trial; the subscription price is shown in the app.', 'Борг сну та циркадний ритм
Прогноз енергії на день
16 науково обґрунтованих звичок
Інтеграція з Apple Health, Oura, Fitbit', 'Sleep debt and circadian rhythm
Daily energy forecast
16 science-based habits
Apple Health, Oura and Fitbit integration', 'Люди з нестабільним режимом сну, студенти й ті, хто хоче більше енергії вдень.', 'People with irregular sleep, students and anyone who wants more energy during the day.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'risescience.com' OR LOWER(`name`) = LOWER('Rise')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'sleep' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A sleep and energy app: it calculates your sleep debt and circadian rhythm and tells you each day when to expect peak energy, dips and wind-down time.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Rise helps you sleep better and have more energy during the day, based on two metrics — sleep debt and circadian rhythm. On day one the app analyses your phone''s data history to estimate your sleep need and current debt, and it gets more accurate data from Apple Health, Oura or Fitbit. Each day it tells you how long morning grogginess will last, when your focus will peak and when to start winding down, and reminds you of 16 science-based habits at the right time. It was named one of Apple''s Best Apps of 2026. There is a free trial; the subscription price is shown in the app.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Sleep debt and circadian rhythm
Daily energy forecast
16 science-based habits
Apple Health, Oura and Fitbit integration', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People with irregular sleep, students and anyone who wants more energy during the day.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Пробний період', 'Free trial', 0.00, 'free', 'Безкоштовна спроба; ціну підписки вказано в застосунку', 'Free trial; subscription price is shown in the app' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Пробний період' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free trial', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Free trial; subscription price is shown in the app', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Sleep Cycle — Сон
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'sleepcycle.com' OR LOWER(`name`) = LOWER('Sleep Cycle'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Sleep Cycle', NULL, 'https://www.sleepcycle.com', NULL, NULL, 'Трекер сну з розумним будильником, який будить у легкій фазі сну, аналізом нічних звуків і статистикою якості й тривалості сну.', 'A sleep tracker with a smart alarm that wakes you in a light sleep phase, night-time sound analysis and statistics on sleep quality and duration.', 'Sleep Cycle аналізує сон за допомогою мікрофона телефона чи годинника й будує статистику якості та тривалості сну. Розумний будильник спрацьовує в межах заданого вікна в момент легкого сну, тож прокидатися легше. Застосунок також розпізнає нічні звуки, зокрема хропіння й розмови уві сні, показує тенденції та допомагає виробити стабільний режим. Працює на iOS і Android. Базові функції безкоштовні; Premium відкриває розширену аналітику, є безкоштовний пробний період, а ціну підписки показано в застосунку.', 'Sleep Cycle analyses your sleep using your phone''s microphone or your watch and builds statistics on sleep quality and duration. The smart alarm goes off within a set window at a moment of light sleep, so waking up is easier. The app also recognises night-time sounds, including snoring and sleep talking, shows trends and helps you build a consistent routine. It works on iOS and Android. Basic features are free; Premium unlocks advanced analytics, with a free trial and the subscription price shown in the app.', 'Розумний будильник у фазі легкого сну
Статистика якості й тривалості сну
Розпізнавання хропіння й нічних звуків
iOS і Android', 'Smart alarm in a light sleep phase
Sleep quality and duration statistics
Snoring and night-sound detection
iOS and Android', 'Усі, кому важко прокидатися зранку чи хто хоче зрозуміти якість свого сну.', 'Anyone who struggles to wake up in the morning or wants to understand their sleep quality.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'sleepcycle.com' OR LOWER(`name`) = LOWER('Sleep Cycle')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'sleep' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A sleep tracker with a smart alarm that wakes you in a light sleep phase, night-time sound analysis and statistics on sleep quality and duration.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Sleep Cycle analyses your sleep using your phone''s microphone or your watch and builds statistics on sleep quality and duration. The smart alarm goes off within a set window at a moment of light sleep, so waking up is easier. The app also recognises night-time sounds, including snoring and sleep talking, shows trends and helps you build a consistent routine. It works on iOS and Android. Basic features are free; Premium unlocks advanced analytics, with a free trial and the subscription price shown in the app.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Smart alarm in a light sleep phase
Sleep quality and duration statistics
Snoring and night-sound detection
iOS and Android', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Anyone who struggles to wake up in the morning or wants to understand their sleep quality.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовно', 'Free', 0.00, 'free', 'Базові функції; Premium — пробний період, ціна в застосунку', 'Basic features; Premium has a free trial, price shown in the app' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Безкоштовно' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Basic features; Premium has a free trial, price shown in the app', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Cal AI — Харчування
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'calai.app' OR LOWER(`name`) = LOWER('Cal AI'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Cal AI', NULL, 'https://www.calai.app', NULL, NULL, 'Підрахунок калорій за фото їжі: сфотографуйте страву, відскануйте штрихкод чи опишіть її — і застосунок порахує калорії, білки, жири й вуглеводи.', 'Calorie counting from food photos: snap your meal, scan a barcode or describe it and the app calculates calories, protein, fat and carbs.', 'Cal AI робить облік харчування майже автоматичним. Досить сфотографувати страву — AI розпізнає продукти, а на сумісних телефонах використовує датчик глибини, щоб оцінити об''єм порції, — і показує калорії та макронутрієнти. Можна також сканувати штрихкоди, описувати їжу словами, зберігати власні страви й рецепти та підтягувати тренування з фітнес-пристроїв. Застосунком користуються близько 5 млн людей. Працює на iOS і Android; є 3-денний безкоштовний пробний період, підписка оформлюється через App Store чи Google Play. Застосунок не замінює консультацію лікаря чи дієтолога.', 'Cal AI makes food tracking almost automatic. Just take a photo of your meal — AI recognises the foods and, on compatible phones, uses the depth sensor to estimate portion volume — and it shows calories and macronutrients. You can also scan barcodes, describe food in words, save your own meals and recipes and pull in workouts from fitness devices. About 5 million people use the app. It works on iOS and Android; there is a 3-day free trial, and subscriptions are handled through the App Store or Google Play. The app does not replace advice from a doctor or dietitian.', 'Калорії й макроси за фото страви
Оцінка об''єму порції датчиком глибини
Сканування штрихкодів і опис словами
Власні рецепти та синхронізація тренувань', 'Calories and macros from a meal photo
Portion volume estimate with depth sensor
Barcode scanning and text descriptions
Custom recipes and workout sync', 'Люди, які стежать за вагою чи харчуванням і не хочуть вручну шукати продукти в базі.', 'People watching their weight or diet who do not want to search food databases by hand.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'calai.app' OR LOWER(`name`) = LOWER('Cal AI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'nutrition' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'Calorie counting from food photos: snap your meal, scan a barcode or describe it and the app calculates calories, protein, fat and carbs.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Cal AI makes food tracking almost automatic. Just take a photo of your meal — AI recognises the foods and, on compatible phones, uses the depth sensor to estimate portion volume — and it shows calories and macronutrients. You can also scan barcodes, describe food in words, save your own meals and recipes and pull in workouts from fitness devices. About 5 million people use the app. It works on iOS and Android; there is a 3-day free trial, and subscriptions are handled through the App Store or Google Play. The app does not replace advice from a doctor or dietitian.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Calories and macros from a meal photo
Portion volume estimate with depth sensor
Barcode scanning and text descriptions
Custom recipes and workout sync', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People watching their weight or diet who do not want to search food databases by hand.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Пробний період', 'Free trial', 0.00, 'free', '3 дні безкоштовно, далі підписка через App Store / Google Play', '3-day free trial, then a subscription via the App Store / Google Play' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Пробний період' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free trial', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '3-day free trial, then a subscription via the App Store / Google Play', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- SnapCalorie — Харчування
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'snapcalorie.com' OR LOWER(`name`) = LOWER('SnapCalorie'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'SnapCalorie', NULL, 'https://www.snapcalorie.com', NULL, NULL, 'AI-облік харчування за фото чи голосом з персональними планами під кето, веганство, середземноморську та інші дієти; основні функції безкоштовні.', 'AI food logging from photos or voice with personal plans for keto, vegan, Mediterranean and other diets; core features are free.', 'SnapCalorie розпізнає їжу на фото за допомогою комп''ютерного зору й автоматично рахує поживну цінність, а страву можна також надиктувати голосом. За даними розробників, такий облік у 5 разів швидший за пошук у базі продуктів, а оцінка калорій удвічі точніша, ніж у дієтологів. Застосунок складає персональні плани харчування — кето, веганський, середземноморський, палео, вегетаріанський або без обмежень, — показує тенденції та має базу продуктів, рецепти й навчальні матеріали. Дані шифруються. Основні функції безкоштовні, без картки; є API для розробників. Працює на iOS і Android.', 'SnapCalorie recognises food in photos with computer vision and calculates nutrition automatically, and you can also dictate a meal by voice. According to the developers, logging this way is 5 times faster than searching a food database, and its calorie estimates are twice as accurate as nutritionists''. The app builds personal meal plans — keto, vegan, Mediterranean, paleo, vegetarian or unrestricted — shows trends and includes a food database, recipes and educational content. Data is encrypted. Core features are free with no card required; there is an API for developers. It works on iOS and Android.', 'Облік їжі за фото та голосом
Персональні плани під різні дієти
Тенденції та аналітика харчування
Безкоштовні основні функції', 'Food logging from photos and voice
Personal plans for different diets
Nutrition trends and analytics
Free core features', 'Люди, які хочуть стежити за харчуванням без ручного введення даних.', 'People who want to track their diet without manual data entry.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'snapcalorie.com' OR LOWER(`name`) = LOWER('SnapCalorie')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'nutrition' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'AI food logging from photos or voice with personal plans for keto, vegan, Mediterranean and other diets; core features are free.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'SnapCalorie recognises food in photos with computer vision and calculates nutrition automatically, and you can also dictate a meal by voice. According to the developers, logging this way is 5 times faster than searching a food database, and its calorie estimates are twice as accurate as nutritionists''. The app builds personal meal plans — keto, vegan, Mediterranean, paleo, vegetarian or unrestricted — shows trends and includes a food database, recipes and educational content. Data is encrypted. Core features are free with no card required; there is an API for developers. It works on iOS and Android.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Food logging from photos and voice
Personal plans for different diets
Nutrition trends and analytics
Free core features', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People who want to track their diet without manual data entry.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовно', 'Free', 0.00, 'free', 'Основні функції безкоштовно, без картки', 'Core features free, no card required' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Безкоштовно' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Core features free, no card required', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Calm')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'sleep' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Whoop')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'sleep' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Headspace')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'sleep' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('MyFitnessPal')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'nutrition' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Noom')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'nutrition' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Carb Manager')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'nutrition' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Cronometer')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'nutrition' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('MacroFactor')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'nutrition' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Lose It!')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'nutrition' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('MyNetDiary')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'nutrition' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Intake')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'nutrition' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Nutrola')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'nutrition' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Eat This Much')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'nutrition' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Alma')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'nutrition' LIMIT 1;
