SET NAMES utf8mb4;

-- =====================================================================
-- AI LAB HUB — партія 2026-10-01: «Здоров'я та краса» → нові підкатегорії «Перевірка симптомів», «Догляд за шкірою» і «Жіноче здоров'я» — 6 нових продуктів, 6 прив'язок наявних
--   Symptomate — Перевірка симптомів
--   K Health — Перевірка симптомів
--   SkinVision — Догляд за шкірою
--   Flo — Жіноче здоров'я
--   Clue — Жіноче здоров'я
--   Natural Cycles — Жіноче здоров'я
--   (наявний) Ada Health → Перевірка симптомів
--   (наявний) WebMD Symptom Checker → Перевірка симптомів
--   (наявний) Isabel Healthcare → Перевірка симптомів
--   (наявний) Haut.AI → Догляд за шкірою
--   (наявний) Revieve → Догляд за шкірою
--   (наявний) Curology → Догляд за шкірою
--
-- Застосування (phpMyAdmin хостингу, БД gu621051_ailabhublive): «Импорт» → *.sql.zip → «Импорт» (або SQL → вставити → Вперёд).
-- Без фіксованих id і без DROP / DELETE. @new обчислюється ДО вставки продукту (без ROW_COUNT()); продукт додається
-- лише якщо немає продукту з тим самим нормалізованим URL АБО назвою, інакше наявному лише додаються категорія й
-- підкатегорія. Id тарифів — за product_id + plan_name. Повторний запуск безпечний.
-- Автор — whitevelvetelf@gmail.com (id за email). Статус published, партнерство «Знайдено».
-- =====================================================================

INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Перевірка симптомів', 'Symptom Checkers', 'symptom-checkers' FROM `categories` c WHERE c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Догляд за шкірою', 'Skin Care', 'skin-care' FROM `categories` c WHERE c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `subcategories` (`category_id`, `name`, `name_en`, `slug`) SELECT c.`id`, 'Жіноче здоров''я', 'Women''s Health', 'womens-health' FROM `categories` c WHERE c.`slug` = 'health-beauty' LIMIT 1;

SET @uid = (SELECT `id` FROM `users` WHERE `email` = 'whitevelvetelf@gmail.com' LIMIT 1);

-- Symptomate — Перевірка симптомів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'symptomate.com' OR LOWER(`name`) = LOWER('Symptomate'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Symptomate', NULL, 'https://symptomate.com', NULL, NULL, 'Безкоштовна перевірка симптомів від Infermedica: адаптивні запитання, ймовірні стани та рекомендація, до якого лікаря і як терміново звернутися; 13+ мов.', 'A free symptom checker by Infermedica: adaptive questions, possible conditions and a recommendation on which doctor to see and how urgently; 13+ languages.', 'Symptomate створили лікарі компанії Infermedica, щоб допомогти людям зрозуміти можливі причини симптомів і наступні кроки. Ви вказуєте симптоми (без обмеження кількості), відповідаєте на адаптивні запитання, а сервіс показує перелік імовірних станів і рекомендований рівень допомоги — від самодогляду до невідкладної. Є окремі режими для жінок, чоловіків, батьків і літніх людей, карти тіла та оцінка для дітей. Доступно понад 13 мовами. У ЄС Symptomate має статус медичного виробу класу IIb; проведено понад 27 млн опитувань. Для користувачів безкоштовний. Важливо: Symptomate не ставить діагноз і не замінює лікаря.', 'Symptomate was created by doctors at Infermedica to help people understand possible causes of their symptoms and the next steps. You enter symptoms (with no limit), answer adaptive questions, and it shows a list of probable conditions and a recommended level of care — from self-care to emergency. There are dedicated modes for women, men, parents and seniors, body maps and paediatric assessments. It is available in 13+ languages. In the EU Symptomate is a Class IIb medical device; more than 27 million interviews have been completed. It is free for users. Important: Symptomate does not provide a diagnosis and does not replace a doctor.', 'Адаптивні запитання про симптоми
Імовірні стани й рекомендований рівень допомоги
Режими для дітей, жінок, чоловіків і літніх
13+ мов, медичний виріб класу IIb у ЄС', 'Adaptive symptom questions
Probable conditions and recommended care level
Modes for children, women, men and seniors
13+ languages, Class IIb medical device in the EU', 'Люди, які хочуть зрозуміти свої симптоми й підготуватися до візиту до лікаря.', 'People who want to make sense of their symptoms and prepare for a doctor''s visit.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'symptomate.com' OR LOWER(`name`) = LOWER('Symptomate')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'symptom-checkers' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A free symptom checker by Infermedica: adaptive questions, possible conditions and a recommendation on which doctor to see and how urgently; 13+ languages.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Symptomate was created by doctors at Infermedica to help people understand possible causes of their symptoms and the next steps. You enter symptoms (with no limit), answer adaptive questions, and it shows a list of probable conditions and a recommended level of care — from self-care to emergency. There are dedicated modes for women, men, parents and seniors, body maps and paediatric assessments. It is available in 13+ languages. In the EU Symptomate is a Class IIb medical device; more than 27 million interviews have been completed. It is free for users. Important: Symptomate does not provide a diagnosis and does not replace a doctor.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Adaptive symptom questions
Probable conditions and recommended care level
Modes for children, women, men and seniors
13+ languages, Class IIb medical device in the EU', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People who want to make sense of their symptoms and prepare for a doctor''s visit.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовно', 'Free', 0.00, 'free', 'Веб і мобільні застосунки безкоштовні для користувачів', 'Web and mobile apps are free for users' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Безкоштовно' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Web and mobile apps are free for users', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- K Health — Перевірка симптомів
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'khealth.com' OR LOWER(`name`) = LOWER('K Health'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'K Health', NULL, 'https://khealth.com', NULL, NULL, 'Первинна медична допомога з AI у США: AI-асистент PatientGPT збирає симптоми, а сертифіковані лікарі консультують онлайн 24/7 у партнерстві з провідними клініками.', 'AI-enabled primary care in the US: the PatientGPT assistant collects symptoms, and board-certified doctors consult online 24/7 in partnership with leading health systems.', 'K Health поєднує AI і лікарів для первинної медичної допомоги. AI-асистент PatientGPT проводить первинне опитування про симптоми й готує інформацію для лікаря, а сертифіковані лікарі приймають онлайн цілодобово — при гострих станах, хронічних хворобах і для профілактики; додаються також ендокринологія й дерматологія. Платформа інтегрується з електронними медкартами й працює в партнерстві з великими системами охорони здоров''я США, зокрема Mass General Brigham, Mayo Clinic, Cedars-Sinai та Penn Medicine. Сервіс доступний у США; вартість залежить від партнерської клініки й страхування.', 'K Health combines AI and doctors for primary care. The PatientGPT AI assistant runs the initial symptom intake and prepares information for the clinician, and board-certified doctors see patients online 24/7 — for acute conditions, chronic care and prevention; endocrinology and dermatology are being added. The platform integrates with electronic health records and partners with major US health systems, including Mass General Brigham, Mayo Clinic, Cedars-Sinai and Penn Medicine. The service is available in the US; cost depends on the partner health system and insurance.', 'AI-опитування про симптоми (PatientGPT)
Онлайн-лікарі 24/7
Гострі, хронічні стани та профілактика
Інтеграція з медкартами клінік-партнерів', 'AI symptom intake (PatientGPT)
Online doctors 24/7
Acute, chronic and preventive care
EHR integration with partner health systems', 'Пацієнти в США, чиї клініки чи страховики співпрацюють з K Health.', 'Patients in the US whose health systems or insurers partner with K Health.', 'web,mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'khealth.com' OR LOWER(`name`) = LOWER('K Health')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'symptom-checkers' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'AI-enabled primary care in the US: the PatientGPT assistant collects symptoms, and board-certified doctors consult online 24/7 in partnership with leading health systems.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'K Health combines AI and doctors for primary care. The PatientGPT AI assistant runs the initial symptom intake and prepares information for the clinician, and board-certified doctors see patients online 24/7 — for acute conditions, chronic care and prevention; endocrinology and dermatology are being added. The platform integrates with electronic health records and partners with major US health systems, including Mass General Brigham, Mayo Clinic, Cedars-Sinai and Penn Medicine. The service is available in the US; cost depends on the partner health system and insurance.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI symptom intake (PatientGPT)
Online doctors 24/7
Acute, chronic and preventive care
EHR integration with partner health systems', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Patients in the US whose health systems or insurers partner with K Health.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Через клініку-партнера', 'Via partner health system', NULL, 'month', 'Вартість залежить від клініки й страхування (лише США)', 'Cost depends on the health system and insurance (US only)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Через клініку-партнера' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Via partner health system', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Cost depends on the health system and insurance (US only)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- SkinVision — Догляд за шкірою
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'skinvision.com' OR LOWER(`name`) = LOWER('SkinVision'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'SkinVision', NULL, 'https://www.skinvision.com', NULL, NULL, 'Застосунок для оцінки ризику раку шкіри: AI аналізує фото родимки чи плями, за потреби фото переглядають дерматологи; сертифікований медичний виріб з маркуванням CE.', 'A skin cancer risk check app: AI analyses a photo of a mole or spot, with dermatologist review when needed; a certified CE-marked medical device.', 'SkinVision допомагає вчасно помітити тривожні зміни на шкірі. Ви фотографуєте родимку чи пляму камерою телефона, AI оцінює ризик, а за потреби знімок переглядає команда кваліфікованих дерматологів. Застосунок веде карту тіла, щоб відстежувати плями з часом, враховує тип шкіри та фактори ризику й підказує, чи варто і коли звернутися до лікаря. SkinVision — сертифікований медичний виріб з маркуванням CE; ним користуються понад 3 млн людей, переважно в Нідерландах, Бельгії та Великій Британії. Ціни в євро: разова перевірка — €6,99, 3 місяці — €24,99, 12 місяців — €49,99. Застосунок не замінює огляд у дерматолога.', 'SkinVision helps you spot worrying skin changes early. You photograph a mole or spot with your phone camera, AI assesses the risk, and a team of qualified dermatologists reviews the image when needed. The app keeps a body map to track spots over time, takes your skin type and risk factors into account and advises whether and when to see a doctor. SkinVision is a certified CE-marked medical device used by more than 3 million people, mainly in the Netherlands, Belgium and the UK. Prices in euros: a single check — €6.99, 3 months — €24.99, 12 months — €49.99. The app does not replace an examination by a dermatologist.', 'AI-оцінка ризику за фото родимки
Перевірка дерматологами за потреби
Карта тіла й відстеження змін
Медичний виріб з маркуванням CE', 'AI risk assessment from a mole photo
Dermatologist review when needed
Body map and change tracking
CE-marked medical device', 'Люди з великою кількістю родимок або підвищеним ризиком раку шкіри.', 'People with many moles or an increased risk of skin cancer.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'skinvision.com' OR LOWER(`name`) = LOWER('SkinVision')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'skin-care' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A skin cancer risk check app: AI analyses a photo of a mole or spot, with dermatologist review when needed; a certified CE-marked medical device.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'SkinVision helps you spot worrying skin changes early. You photograph a mole or spot with your phone camera, AI assesses the risk, and a team of qualified dermatologists reviews the image when needed. The app keeps a body map to track spots over time, takes your skin type and risk factors into account and advises whether and when to see a doctor. SkinVision is a certified CE-marked medical device used by more than 3 million people, mainly in the Netherlands, Belgium and the UK. Prices in euros: a single check — €6.99, 3 months — €24.99, 12 months — €49.99. The app does not replace an examination by a dermatologist.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'AI risk assessment from a mole photo
Dermatologist review when needed
Body map and change tracking
CE-marked medical device', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'People with many moles or an increased risk of skin cancer.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Разова перевірка', 'Single check', NULL, 'one_time', '€6,99', '€6.99' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Разова перевірка' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Single check', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '€6.99', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, '12 місяців', '12 months', NULL, 'year', '€49,99 на рік (3 місяці — €24,99)', '€49.99 a year (3 months — €24.99)' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = '12 місяців' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', '12 months', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', '€49.99 a year (3 months — €24.99)', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Flo — Жіноче здоров'я
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'flo.health' OR LOWER(`name`) = LOWER('Flo'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Flo', NULL, 'https://flo.health', NULL, NULL, 'Трекер менструального циклу, овуляції, вагітності та перименопаузи, яким користуються понад 420 млн людей; режим анонімності та доступ для партнера.', 'A tracker for periods, ovulation, pregnancy and perimenopause used by more than 420 million people; Anonymous Mode and partner sharing.', 'Flo — один із найпопулярніших застосунків для жіночого здоров''я. Він відстежує менструальний цикл і симптоми, прогнозує місячні та фертильні дні, допомагає тим, хто планує вагітність, супроводжує вагітність тиждень за тижнем і підтримує в період перименопаузи. Застосунок дає персональні прогнози й поради та містить матеріали, перевірені медичними експертами. Для приватності є режим анонімності, а функція Flo for Partners дає змогу ділитися інформацією з партнером. Flo користуються понад 420 млн людей. Працює на iOS і Android; основні функції доступні безкоштовно, розширені — за платною підпискою, ціну показано в застосунку. Flo не є методом контрацепції й не замінює лікаря.', 'Flo is one of the most popular women''s health apps. It tracks your cycle and symptoms, predicts periods and fertile days, helps people trying to conceive, follows pregnancy week by week and supports you through perimenopause. The app gives personal predictions and tips and includes content reviewed by medical experts. For privacy there is Anonymous Mode, and Flo for Partners lets you share information with your partner. More than 420 million people use Flo. It works on iOS and Android; core features are free and advanced ones require a paid subscription, priced in the app. Flo is not a contraceptive method and does not replace a doctor.', 'Прогноз місячних і фертильних днів
Режими планування й вагітності
Підтримка в перименопаузі
Режим анонімності та Flo for Partners', 'Period and fertile-day predictions
Trying-to-conceive and pregnancy modes
Perimenopause support
Anonymous Mode and Flo for Partners', 'Жінки, які стежать за циклом, планують вагітність, вагітні або в перименопаузі.', 'Women who track their cycle, are trying to conceive, are pregnant or in perimenopause.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'flo.health' OR LOWER(`name`) = LOWER('Flo')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'womens-health' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A tracker for periods, ovulation, pregnancy and perimenopause used by more than 420 million people; Anonymous Mode and partner sharing.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Flo is one of the most popular women''s health apps. It tracks your cycle and symptoms, predicts periods and fertile days, helps people trying to conceive, follows pregnancy week by week and supports you through perimenopause. The app gives personal predictions and tips and includes content reviewed by medical experts. For privacy there is Anonymous Mode, and Flo for Partners lets you share information with your partner. More than 420 million people use Flo. It works on iOS and Android; core features are free and advanced ones require a paid subscription, priced in the app. Flo is not a contraceptive method and does not replace a doctor.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Period and fertile-day predictions
Trying-to-conceive and pregnancy modes
Perimenopause support
Anonymous Mode and Flo for Partners', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Women who track their cycle, are trying to conceive, are pregnant or in perimenopause.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовно', 'Free', 0.00, 'free', 'Основні функції; Premium — ціна в застосунку', 'Core features; Premium priced in the app' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Безкоштовно' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Core features; Premium priced in the app', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Clue — Жіноче здоров'я
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'helloclue.com' OR LOWER(`name`) = LOWER('Clue'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Clue', NULL, 'https://helloclue.com', NULL, NULL, 'Трекер циклу з європейським підходом до приватності (GDPR): прогнози місячних і фертильності, режими вагітності й перименопаузи, інтеграція з носимими пристроями.', 'A cycle tracker with a European approach to privacy (GDPR): period and fertility predictions, pregnancy and perimenopause modes and wearable integration.', 'Clue допомагає розуміти свій менструальний цикл і репродуктивне здоров''я. Застосунок відстежує місячні та симптоми, аналізує цикли й прогнозує фертильне вікно; режим Clue Conceive допомагає планувати вагітність, є режим вагітності та інструменти для перименопаузи. Можна створювати власні мітки, бачити дані в наочних графіках, налаштовувати нагадування, ділитися циклом через Clue Connect та підключати носимі пристрої. Компанія працює за європейськими правилами захисту даних (GDPR). Доступний на iOS і Android; базова версія безкоштовна, розширені функції — у підписці Clue Plus (ціну вказано при оформленні).', 'Clue helps you understand your menstrual cycle and reproductive health. The app tracks periods and symptoms, analyses cycles and predicts your fertile window; Clue Conceive helps you plan a pregnancy, and there is a pregnancy mode and perimenopause tools. You can create custom tags, see your data in clear charts, set reminders, share your cycle through Clue Connect and connect wearables. The company follows European data protection rules (GDPR). It is available on iOS and Android; the basic version is free, and advanced features come with a Clue Plus subscription (priced at checkout).', 'Аналіз циклу й прогноз фертильності
Clue Conceive, режими вагітності й перименопаузи
Власні мітки й нагадування
GDPR та інтеграція з носимими пристроями', 'Cycle analysis and fertility predictions
Clue Conceive, pregnancy and perimenopause modes
Custom tags and reminders
GDPR and wearable integration', 'Жінки, для яких важлива приватність даних про здоров''я.', 'Women for whom the privacy of health data matters.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'helloclue.com' OR LOWER(`name`) = LOWER('Clue')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'womens-health' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'A cycle tracker with a European approach to privacy (GDPR): period and fertility predictions, pregnancy and perimenopause modes and wearable integration.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Clue helps you understand your menstrual cycle and reproductive health. The app tracks periods and symptoms, analyses cycles and predicts your fertile window; Clue Conceive helps you plan a pregnancy, and there is a pregnancy mode and perimenopause tools. You can create custom tags, see your data in clear charts, set reminders, share your cycle through Clue Connect and connect wearables. The company follows European data protection rules (GDPR). It is available on iOS and Android; the basic version is free, and advanced features come with a Clue Plus subscription (priced at checkout).', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'Cycle analysis and fertility predictions
Clue Conceive, pregnancy and perimenopause modes
Custom tags and reminders
GDPR and wearable integration', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Women for whom the privacy of health data matters.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Безкоштовно', 'Free', 0.00, 'free', 'Базова версія; Clue Plus — ціна при оформленні', 'Basic version; Clue Plus priced at checkout' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Безкоштовно' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Free', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Basic version; Clue Plus priced at checkout', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Natural Cycles — Жіноче здоров'я
SET @new = IF(NOT EXISTS (SELECT 1 FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'naturalcycles.com' OR LOWER(`name`) = LOWER('Natural Cycles'))), 1, 0);
INSERT INTO `products` (`name`, `logo_url`, `official_url`, `internal_registration_url`, `affiliate_url`, `short_description`, `short_description_en`, `full_description`, `full_description_en`, `main_features`, `main_features_en`, `target_audience`, `target_audience_en`, `platform`, `skill_level`, `status`, `is_archived`, `partnership_status`, `created_by`, `created_at`) SELECT 'Natural Cycles', NULL, 'https://www.naturalcycles.com', NULL, NULL, 'Єдиний застосунок для контрацепції без гормонів, схвалений FDA: алгоритм визначає фертильні дні за температурою тіла й показує, коли потрібен захист.', 'The only FDA-cleared birth control app, hormone-free: its algorithm identifies fertile days from body temperature and shows when you need protection.', 'Natural Cycles (NC°) — застосунок, що допомагає запобігати вагітності без гормонів або планувати її. Алгоритм аналізує температуру тіла та інші дані циклу й щодня показує, чи є день фертильним і чи потрібен захист. Natural Cycles — єдиний застосунок для контрацепції, схвалений FDA (уже понад 8 років); його ефективність становить 98% при правильному використанні та 93% при типовому, що відповідає категорії ефективності таблеток. Застосунок також допомагає тим, хто планує вагітність. Ціну підписки вказано при оформленні й вона залежить від країни. Метод не захищає від інфекцій, що передаються статевим шляхом; перед вибором контрацепції варто порадитися з лікарем.', 'Natural Cycles (NC°) is an app that helps you prevent pregnancy without hormones or plan one. Its algorithm analyses body temperature and other cycle data and shows each day whether it is fertile and whether you need protection. Natural Cycles is the only FDA-cleared birth control app (for more than 8 years); it is 98% effective with perfect use and 93% with typical use, the same effectiveness category as the pill. The app also helps those trying to conceive. The subscription price is shown at checkout and depends on your country. The method does not protect against sexually transmitted infections; talk to a doctor before choosing contraception.', 'Контрацепція без гормонів, схвалена FDA
Визначення фертильних днів за температурою
Ефективність 93% при типовому використанні
Режим планування вагітності', 'FDA-cleared hormone-free birth control
Fertile-day detection from temperature
93% typical-use effectiveness
Pregnancy planning mode', 'Жінки, які шукають контрацепцію без гормонів або планують вагітність.', 'Women looking for hormone-free contraception or planning a pregnancy.', 'mobile', 'none', 'published', 0, 'found', @uid, '2026-10-01 00:00:00' FROM DUAL WHERE @new = 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(TRIM(TRAILING '/' FROM REPLACE(REPLACE(REPLACE(REPLACE(`official_url`, 'https://www.', ''), 'http://www.', ''), 'https://', ''), 'http://', ''))) = 'naturalcycles.com' OR LOWER(`name`) = LOWER('Natural Cycles')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'womens-health' LIMIT 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'short_description', 'en', 'The only FDA-cleared birth control app, hormone-free: its algorithm identifies fertile days from body temperature and shows when you need protection.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'full_description', 'en', 'Natural Cycles (NC°) is an app that helps you prevent pregnancy without hormones or plan one. Its algorithm analyses body temperature and other cycle data and shows each day whether it is fertile and whether you need protection. Natural Cycles is the only FDA-cleared birth control app (for more than 8 years); it is 98% effective with perfect use and 93% with typical use, the same effectiveness category as the pill. The app also helps those trying to conceive. The subscription price is shown at checkout and depends on your country. The method does not protect against sexually transmitted infections; talk to a doctor before choosing contraception.', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'main_features', 'en', 'FDA-cleared hormone-free birth control
Fertile-day detection from temperature
93% typical-use effectiveness
Pregnancy planning mode', 'manual' FROM DUAL WHERE @new = 1;
INSERT IGNORE INTO `product_translations` (`product_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @pid, 'target_audience', 'en', 'Women looking for hormone-free contraception or planning a pregnancy.', 'manual' FROM DUAL WHERE @new = 1;
INSERT INTO `pricing_plans` (`product_id`, `plan_name`, `plan_name_en`, `price`, `period`, `description`, `description_en`) SELECT @pid, 'Підписка', 'Subscription', NULL, 'year', 'Ціна залежить від країни й вказується при оформленні', 'Price depends on your country and is shown at checkout' FROM DUAL WHERE @new = 1;
SET @plan = IF(@new = 1, (SELECT `id` FROM `pricing_plans` WHERE `product_id` = @pid AND `plan_name` = 'Підписка' ORDER BY `id` DESC LIMIT 1), NULL);
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'plan_name', 'en', 'Subscription', 'manual' FROM DUAL WHERE @plan IS NOT NULL;
INSERT IGNORE INTO `pricing_plan_translations` (`plan_id`, `field_name`, `lang`, `translated_text`, `source`) SELECT @plan, 'description', 'en', 'Price depends on your country and is shown at checkout', 'manual' FROM DUAL WHERE @plan IS NOT NULL;

-- Прив'язка наявних продуктів (за точною назвою) до нових підкатегорій
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Ada Health')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'symptom-checkers' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('WebMD Symptom Checker')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'symptom-checkers' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Isabel Healthcare')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'symptom-checkers' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Haut.AI')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'skin-care' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Revieve')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'skin-care' LIMIT 1;
SET @pid = (SELECT `id` FROM `products` WHERE (LOWER(`name`) = LOWER('Curology')) ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `product_categories` (`product_id`, `category_id`) SELECT @pid, c.`id` FROM `categories` c WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' LIMIT 1;
INSERT IGNORE INTO `product_subcategories` (`product_id`, `subcategory_id`) SELECT @pid, s.`id` FROM `subcategories` s JOIN `categories` c ON c.`id` = s.`category_id` WHERE @pid IS NOT NULL AND c.`slug` = 'health-beauty' AND s.`slug` = 'skin-care' LIMIT 1;
